"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { useApp } from "@/context/AppContext";
import { PageHeader } from "@/components/ui/PageHeader";
import { DataTable, Column } from "@/components/ui/DataTable";
import { formatINR, formatDate } from "@/lib/utils";
import { filterPendingByAccess } from "@/lib/selectors";
import { PendingBillingItem } from "@/types";
import { NewInvoiceModal } from "@/components/billing/NewInvoiceModal";
import { PermissionGuard } from "@/components/billing/PermissionGuard";
import { ReceptionHandOffTab } from "@/components/billing/ReceptionHandOffTab";

const SOURCE_LABEL: Record<string, string> = {
  doctor_opd: "Doctor / OPD", diagnostics: "Diagnostics", pharmacy: "Pharmacy", ipd: "IPD", surgery: "Surgery", other: "Other Services",
};

export default function PendingBillingPage() {
  const { currentOrg, currentUser, pendingBillingItems, patients, encounters } = useApp();
  const [invoiceModal, setInvoiceModal] = useState<PendingBillingItem | null>(null);
  const [activeTab, setActiveTab] = useState<"pending" | "reception">("pending");

  const items = useMemo(
    () => filterPendingByAccess(pendingBillingItems, currentOrg.id, currentUser.scopes).filter((i) => i.status === "pending"),
    [pendingBillingItems, currentOrg.id, currentUser.scopes]
  );

  const columns: Column<PendingBillingItem>[] = [
    { header: "Patient", accessor: (r) => { const p = patients.find((x) => x.id === r.patientId); return <span>{p?.name}<span className="block text-xs text-ink-400">{p?.uhid}</span></span>; } },
    { header: "Encounter", accessor: (r) => { const e = encounters.find((x) => x.id === r.encounterId); return e ? `${e.type.toUpperCase()} · ${e.department}` : "—"; } },
    { header: "Source", accessor: (r) => SOURCE_LABEL[r.source] },
    { header: "Date", accessor: (r) => formatDate(r.date) },
    { header: "Amount", accessor: (r) => formatINR(r.amount) },
    {
      header: "Action",
      accessor: (r) => (
        <div className="flex gap-2">
          <button onClick={() => setInvoiceModal(r)} className="rounded-md bg-brand-600 px-2.5 py-1 text-xs font-medium text-white hover:bg-brand-700">Create Invoice</button>
          <Link href={`/patients/${r.patientId}`} className="rounded-md border border-ink-200 px-2.5 py-1 text-xs font-medium text-ink-600 hover:bg-ink-50">View Patient</Link>
        </div>
      ),
    },
  ];

  return (
    <div>
      <PageHeader
        title="Pending Billing &amp; Module Handoffs"
        description="Billable events generated by clinical/reception modules waiting to be invoiced. Billing Staff cannot modify underlying clinical records."
        actions={
          <div className="flex overflow-hidden rounded-lg border border-ink-200 bg-white">
            <button
              onClick={() => setActiveTab("pending")}
              className={`px-3 py-1.5 text-xs font-medium ${activeTab === "pending" ? "bg-brand-600 text-white" : "text-ink-600 hover:bg-ink-50"}`}
            >
              Pending Billable Items ({items.length})
            </button>
            <button
              onClick={() => setActiveTab("reception")}
              className={`px-3 py-1.5 text-xs font-medium ${activeTab === "reception" ? "bg-brand-600 text-white" : "text-ink-600 hover:bg-ink-50"}`}
            >
              Reception Hand-off Matrix (PRD Sec 19)
            </button>
          </div>
        }
      />
      <PermissionGuard permission="viewBills">
        {activeTab === "pending" ? (
          <>
            <div className="mb-3 rounded-lg border border-ink-200 bg-ink-50 p-2.5 text-xs text-ink-600">
              💡 <span className="font-semibold text-ink-800">PRD Section 21 &amp; 22 Rule:</span> External lab &amp; pharmacy services remain financially independent unless owned/integrated by the organization. External reports uploaded without a billing charge do not generate billable items.
            </div>
            <DataTable columns={columns} rows={items} rowKey={(r) => r.id} emptyTitle="Nothing pending" emptyDescription="All billable events for your scope have been invoiced." />
          </>
        ) : (
          <ReceptionHandOffTab />
        )}
      </PermissionGuard>
      <NewInvoiceModal open={!!invoiceModal} onClose={() => setInvoiceModal(null)} prefillPending={invoiceModal ?? undefined} />
    </div>
  );
}
