import { PrismaClient } from "../src/generated/prisma";
import argon2 from "argon2";
import { ROLE_PERMISSIONS, SYSTEM_ROLES, type SystemRole } from "../src/config/permissions";

const prisma = new PrismaClient();
const devPassword = "QlynoDemo!2026";
const pepper = process.env.PASSWORD_PEPPER ?? "local-development-pepper-change-me";

async function seedRole(tenantId: string, code: SystemRole) {
  const role = await prisma.role.upsert({ where: { id: `${tenantId}-role-${code}` }, create: { id: `${tenantId}-role-${code}`, tenantId, code, name: code.split("_").map((part) => `${part[0]?.toUpperCase()}${part.slice(1)}`).join(" "), system: true }, update: {} });
  for (const permissionCode of ROLE_PERMISSIONS[code]) { const permission = await prisma.permission.upsert({ where: { code: permissionCode }, create: { code: permissionCode, description: permissionCode }, update: {} }); await prisma.rolePermission.upsert({ where: { roleId_permissionId: { roleId: role.id, permissionId: permission.id } }, create: { roleId: role.id, permissionId: permission.id }, update: {} }); }
  return role;
}

async function seedUser(input: { id: string; email: string; name: string; tenantId: string; role: SystemRole; siteId: string; departmentId?: string; clientOrganizationId?: string; practitionerId?: string }) {
  const passwordHash = await argon2.hash(`${devPassword}${pepper}`, { type: argon2.argon2id, memoryCost: 19_456, timeCost: 2, parallelism: 1 });
  const user = await prisma.user.upsert({ where: { email: input.email }, create: { id: input.id, email: input.email, username: input.email.split("@")[0], name: input.name, passwordHash, status: "ACTIVE", passwordChangedAt: new Date("2026-09-01T00:00:00.000Z") }, update: { name: input.name, passwordHash, status: "ACTIVE" } });
  const membership = await prisma.tenantMembership.upsert({ where: { tenantId_userId: { tenantId: input.tenantId, userId: user.id } }, create: { tenantId: input.tenantId, userId: user.id, isDefault: true, clientOrganizationId: input.clientOrganizationId, practitionerId: input.practitionerId }, update: { clientOrganizationId: input.clientOrganizationId, practitionerId: input.practitionerId } });
  await prisma.userRole.upsert({ where: { membershipId_roleId: { membershipId: membership.id, roleId: `${input.tenantId}-role-${input.role}` } }, create: { tenantId: input.tenantId, membershipId: membership.id, roleId: `${input.tenantId}-role-${input.role}` }, update: {} });
  await prisma.userSiteScope.upsert({ where: { membershipId_siteId: { membershipId: membership.id, siteId: input.siteId } }, create: { tenantId: input.tenantId, membershipId: membership.id, siteId: input.siteId }, update: {} });
  if (input.departmentId) await prisma.userDepartmentScope.upsert({ where: { membershipId_departmentId: { membershipId: membership.id, departmentId: input.departmentId } }, create: { tenantId: input.tenantId, membershipId: membership.id, departmentId: input.departmentId }, update: {} });
}

async function main() {
  const sunrise = await prisma.tenant.upsert({ where: { slug: "sunrise-hospital" }, create: { id: "TEN-SUNRISE", slug: "sunrise-hospital", legalName: "Sunrise Hospital Private Limited", displayName: "Sunrise Hospital", mode: "HOSPITAL", billingEnabled: false, accreditation: ["NABL"], logoInitials: "SH" }, update: { mode: "HOSPITAL" } });
  const aarogya = await prisma.tenant.upsert({ where: { slug: "aarogya-diagnostics" }, create: { id: "TEN-AAROGYA", slug: "aarogya-diagnostics", legalName: "Aarogya Diagnostics Private Limited", displayName: "Aarogya Diagnostics", mode: "STANDALONE", billingEnabled: true, accreditation: ["NABL", "ISO 15189"], logoInitials: "AD" }, update: { mode: "STANDALONE" } });
  const sunriseSite = await prisma.site.upsert({ where: { tenantId_code: { tenantId: sunrise.id, code: "CENTRAL" } }, create: { id: "SITE-01", tenantId: sunrise.id, code: "CENTRAL", name: "Sunrise Hospital — Central Lab", type: "HOSPITAL_LAB", city: "Mumbai" }, update: {} });
  const aarogyaSite = await prisma.site.upsert({ where: { tenantId_code: { tenantId: aarogya.id, code: "ANDHERI" } }, create: { id: "SITE-A01", tenantId: aarogya.id, code: "ANDHERI", name: "Aarogya Diagnostics — Andheri", type: "PRIVATE_LAB", city: "Mumbai" }, update: {} });
  const hema = await prisma.department.upsert({ where: { tenantId_siteId_code: { tenantId: sunrise.id, siteId: sunriseSite.id, code: "HEMA" } }, create: { id: "DEPT-HEMA", tenantId: sunrise.id, siteId: sunriseSite.id, code: "HEMA", name: "Hematology" }, update: {} });
  const chem = await prisma.department.upsert({ where: { tenantId_siteId_code: { tenantId: sunrise.id, siteId: sunriseSite.id, code: "CHEM" } }, create: { id: "DEPT-CHEM", tenantId: sunrise.id, siteId: sunriseSite.id, code: "CHEM", name: "Clinical Chemistry" }, update: {} });
  const privateDept = await prisma.department.upsert({ where: { tenantId_siteId_code: { tenantId: aarogya.id, siteId: aarogyaSite.id, code: "LAB" } }, create: { id: "DEPT-A-LAB", tenantId: aarogya.id, siteId: aarogyaSite.id, code: "LAB", name: "Core Laboratory" }, update: {} });
  for (const tenant of [sunrise, aarogya]) for (const role of SYSTEM_ROLES) await seedRole(tenant.id, role);

  const client = await prisma.clientOrganization.upsert({ where: { id: "CLIENT-01" }, create: { id: "CLIENT-01", tenantId: sunrise.id, name: "CityCare Clinic", type: "clinic", contactPerson: "Meera Shah", contactEmail: "lab@citycare.example", creditLimit: 100000, creditTermsDays: 30 }, update: {} });
  const practitioner = await prisma.practitioner.upsert({ where: { id: "PRAC-01" }, create: { id: "PRAC-01", tenantId: sunrise.id, name: "Dr. Meera Shah", specialty: "Internal Medicine", clinicOrHospital: "CityCare Clinic", phone: "+91 98200 11001" }, update: {} });
  const users: Array<[string, string, string, SystemRole, string?]> = [
    ["USR-ADMIN", "admin@sunrise.example", "Sunrise Lab Admin", "tenant_admin"], ["USR-SANJEEV", "sanjeev@sunrise.example", "Dr. Sanjeev Kelkar", "lab_director"], ["USR-QUALITY", "anita@sunrise.example", "Anita Rane", "quality_manager"], ["USR-SUPERVISOR", "deepak@sunrise.example", "Deepak Shetty", "section_supervisor"], ["USR-TECH", "pooja@sunrise.example", "Pooja Iyer", "technologist"], ["USR-ACCESSION", "rahul@sunrise.example", "Rahul Salvi", "accessioning"], ["USR-PHLEB", "nikita@sunrise.example", "Nikita Bhosale", "phlebotomist"], ["USR-COURIER", "sandeep@sunrise.example", "Sandeep Yadav", "courier"], ["USR-RECEPTION", "farah@sunrise.example", "Farah Sheikh", "reception_cashier"], ["USR-INVENTORY", "inventory@sunrise.example", "Kiran Patil", "inventory_procurement"], ["USR-AUDITOR", "auditor@sunrise.example", "NABL Auditor", "auditor"], ["USR-DOCTOR", "doctor@citycare.example", "Dr. Meera Shah", "referring_clinician", "practitioner"], ["USR-CLIENT", "client@citycare.example", "CityCare Lab Desk", "client_lab_user", "client"]
  ];
  for (const [id, email, name, role, link] of users) await seedUser({ id, email, name, tenantId: sunrise.id, role, siteId: sunriseSite.id, departmentId: role === "technologist" || role === "section_supervisor" ? hema.id : undefined, practitionerId: link === "practitioner" ? practitioner.id : undefined, clientOrganizationId: link === "client" ? client.id : undefined });
  await seedUser({ id: "USR-AAROGYA-ADMIN", email: "admin@aarogya.example", name: "Aarogya Lab Admin", tenantId: aarogya.id, role: "tenant_admin", siteId: aarogyaSite.id, departmentId: privateDept.id });

  const patient = await prisma.patient.upsert({ where: { id: "PAT-1001" }, create: { id: "PAT-1001", tenantId: sunrise.id, mrn: "MRN-88213", name: "Ramesh Iyer", dateOfBirth: new Date("1968-03-12"), sex: "M", contact: "+91 98200 11223", source: "HOSPITAL_ENCOUNTER", branchOrWard: "Ward / bedside", identifiers: { create: { tenantId: sunrise.id, type: "MRN", value: "MRN-88213", issuer: "Sunrise HMS", isPrimary: true } } }, update: {} });
  const encounter = await prisma.encounter.upsert({ where: { id: "ENC-501" }, create: { id: "ENC-501", tenantId: sunrise.id, patientId: patient.id, encounterNo: "ENC-501", ward: "Ward 4B", bed: "12", admittingDoctor: "Dr. Ananya Rao", status: "ACTIVE" }, update: {} });
  const edta = await prisma.containerType.upsert({ where: { tenantId_code: { tenantId: sunrise.id, code: "EDTA" } }, create: { id: "CONT-EDTA", tenantId: sunrise.id, code: "EDTA", type: "EDTA (Lavender top)", color: "Lavender" }, update: {} });
  const sst = await prisma.containerType.upsert({ where: { tenantId_code: { tenantId: sunrise.id, code: "SST" } }, create: { id: "CONT-SST", tenantId: sunrise.id, code: "SST", type: "SST (Gold top)", color: "Gold" }, update: {} });
  const cbc = await prisma.testCatalogItem.upsert({ where: { tenantId_code_version: { tenantId: sunrise.id, code: "CBC", version: 1 } }, create: { id: "TEST-CBC", tenantId: sunrise.id, departmentId: hema.id, code: "CBC", name: "Complete Blood Count", method: "Impedance/optical", specimenType: "Whole Blood", containerName: "EDTA (Lavender top)", minVolume: "2 mL", stability: "24 h at 2–8°C", tatMinutes: 120, units: "various", referenceRange: "Age/sex specific", criticalRange: "Configured analyte-specific", version: 1, status: "ACTIVE", effectiveDate: new Date("2026-01-01") }, update: {} });
  const cmp = await prisma.testCatalogItem.upsert({ where: { tenantId_code_version: { tenantId: sunrise.id, code: "CMP", version: 1 } }, create: { id: "TEST-CMP", tenantId: sunrise.id, departmentId: chem.id, code: "CMP", name: "Comprehensive Metabolic Panel", method: "Photometric", specimenType: "Serum", containerName: "SST (Gold top)", minVolume: "3 mL", stability: "48 h at 2–8°C", tatMinutes: 180, units: "various", referenceRange: "Analyte-specific", version: 1, status: "ACTIVE", effectiveDate: new Date("2026-01-01") }, update: {} });
  await prisma.laboratoryOrder.upsert({ where: { id: "ORD-70011" }, create: { id: "ORD-70011", tenantId: sunrise.id, siteId: sunriseSite.id, patientId: patient.id, encounterId: encounter.id, source: "HOSPITAL_ENCOUNTER", billingAuthority: "HMS_CENTRAL", priority: "STAT", status: "PLACED", orderingDoctor: "Dr. Ananya Rao", placedAt: new Date("2026-09-02T03:42:00.000Z") }, update: {} });
  await prisma.laboratoryOrderItem.upsert({ where: { id: "OI-1" }, create: { id: "OI-1", tenantId: sunrise.id, orderId: "ORD-70011", testId: cbc.id, departmentId: hema.id, status: "ORDERED" }, update: {} });
  await prisma.laboratoryOrderItem.upsert({ where: { id: "OI-2" }, create: { id: "OI-2", tenantId: sunrise.id, orderId: "ORD-70011", testId: cmp.id, departmentId: chem.id, status: "ORDERED" }, update: {} });
  await prisma.specimen.upsert({ where: { id: "SPX-9001" }, create: { id: "SPX-9001", tenantId: sunrise.id, siteId: sunriseSite.id, orderId: "ORD-70011", patientId: patient.id, containerTypeId: sst.id, type: "Serum", status: "EXPECTED" }, update: {} });
  await prisma.specimen.upsert({ where: { id: "SPX-9002" }, create: { id: "SPX-9002", tenantId: sunrise.id, siteId: sunriseSite.id, orderId: "ORD-70011", patientId: patient.id, containerTypeId: edta.id, type: "Whole Blood", status: "EXPECTED" }, update: {} });
  await prisma.orderItemSpecimen.upsert({ where: { orderItemId_specimenId: { orderItemId: "OI-1", specimenId: "SPX-9002" } }, create: { tenantId: sunrise.id, orderItemId: "OI-1", specimenId: "SPX-9002" }, update: {} }); await prisma.orderItemSpecimen.upsert({ where: { orderItemId_specimenId: { orderItemId: "OI-2", specimenId: "SPX-9001" } }, create: { tenantId: sunrise.id, orderItemId: "OI-2", specimenId: "SPX-9001" }, update: {} });
  await prisma.collectionTask.upsert({ where: { id: "CT-ORD-70011" }, create: { id: "CT-ORD-70011", tenantId: sunrise.id, siteId: sunriseSite.id, orderId: "ORD-70011", encounterId: encounter.id, location: "Ward / bedside", priority: "STAT", scheduledAt: new Date("2026-09-02T03:45:00.000Z"), status: "PENDING" }, update: {} });
  for (const [specimenId, requiredContainer] of [["SPX-9001", "SST (Gold top)"], ["SPX-9002", "EDTA (Lavender top)"]] as const) await prisma.collectionTaskSpecimen.upsert({ where: { collectionTaskId_specimenId: { collectionTaskId: "CT-ORD-70011", specimenId } }, create: { tenantId: sunrise.id, collectionTaskId: "CT-ORD-70011", specimenId, requiredContainer }, update: {} });
  for (const charge of [{ id: "CHG-CBC", orderItemId: "OI-1", code: "CBC", description: "Complete Blood Count", amount: 450 }, { id: "CHG-CMP", orderItemId: "OI-2", code: "CMP", description: "Comprehensive Metabolic Panel", amount: 950 }]) await prisma.laboratoryChargeLine.upsert({ where: { id: charge.id }, create: { id: charge.id, tenantId: sunrise.id, orderId: "ORD-70011", orderItemId: charge.orderItemId, chargeType: "TEST", serviceCode: charge.code, description: charge.description, quantity: 1, unitPrice: charge.amount, grossAmount: charge.amount, discountAmount: 0, taxAmount: 0, netAmount: charge.amount, billingAuthority: "HMS_CENTRAL" }, update: {} });
  await prisma.hospitalBillingPosting.upsert({ where: { tenantId_orderId_postingVersion: { tenantId: sunrise.id, orderId: "ORD-70011", postingVersion: 1 } }, create: { tenantId: sunrise.id, orderId: "ORD-70011", postingVersion: 1, status: "READY_TO_POST" }, update: {} });
  await prisma.auditEvent.upsert({ where: { id: "EVT-ORDER-70011" }, create: { id: "EVT-ORDER-70011", tenantId: sunrise.id, entity: "LaboratoryLifecycle", entityId: "ORD-70011", action: "ORDER_PLACED", afterState: { orderId: "ORD-70011", specimenIds: ["SPX-9001", "SPX-9002"] }, timestamp: new Date("2026-09-02T03:42:00.000Z") }, update: {} });
  await prisma.qcRun.upsert({ where: { id: "QC-001" }, create: { id: "QC-001", tenantId: sunrise.id, analyte: "Glucose", departmentName: "Clinical Chemistry", controlLot: "GLU-26A", level: "L2", status: "IN_CONTROL", runAt: new Date("2026-09-03T02:30:00.000Z") }, update: {} });
  await prisma.inventoryItem.upsert({ where: { id: "INV-EDTA" }, create: { id: "INV-EDTA", tenantId: sunrise.id, name: "EDTA Vacutainer", category: "Collection supplies", unit: "tube", reorderLevel: 100, currentStock: 84 }, update: {} });
  await prisma.equipment.upsert({ where: { id: "EQ-COBAS" }, create: { id: "EQ-COBAS", tenantId: sunrise.id, name: "Cobas c311", departmentName: "Clinical Chemistry", status: "CONNECTED", lastServiceDate: new Date("2026-08-15"), nextCalibrationDate: new Date("2026-09-15") }, update: {} });
  await prisma.analyzer.upsert({ where: { id: "AN-COBAS" }, create: { id: "AN-COBAS", tenantId: sunrise.id, departmentId: chem.id, name: "Cobas c311", status: "CONNECTED", lastMessageAt: new Date(), queueDepth: 0, mappingVersion: "v1", errorCount: 0 }, update: {} });
  await prisma.integrationConnection.upsert({ where: { tenantId_system: { tenantId: sunrise.id, system: "Sunrise HMS" } }, create: { tenantId: sunrise.id, system: "Sunrise HMS", category: "HMS", status: "CONNECTED", lastSync: new Date(), errorCount: 0, mappingVersion: "v1" }, update: {} });

  // Seed every operational aggregate used by the frontend so no page needs a
  // disconnected page-local record after it is wired to the API.
  const aarogyaPatient = await prisma.patient.upsert({ where: { id: "PAT-A-2001" }, create: { id: "PAT-A-2001", tenantId: aarogya.id, name: "Arjun Mehta", dateOfBirth: new Date("1985-05-11"), sex: "M", contact: "+91 98111 22334", source: "WALK_IN", branchOrWard: "Andheri Branch" }, update: {} });
  const aarogyaTest = await prisma.testCatalogItem.upsert({ where: { tenantId_code_version: { tenantId: aarogya.id, code: "LFT", version: 1 } }, create: { id: "TEST-A-LFT", tenantId: aarogya.id, departmentId: privateDept.id, code: "LFT", name: "Liver Function Panel", method: "Photometry", specimenType: "Serum", containerName: "SST (Gold top)", minVolume: "3 mL", stability: "48 h at 2-8 C", tatMinutes: 240, units: "U/L, mg/dL", referenceRange: "Analyte-specific", version: 1, status: "ACTIVE", effectiveDate: new Date("2025-11-15") }, update: {} });
  const aarogyaOrder = await prisma.laboratoryOrder.upsert({ where: { id: "ORD-A-1001" }, create: { id: "ORD-A-1001", tenantId: aarogya.id, siteId: aarogyaSite.id, patientId: aarogyaPatient.id, source: "WALK_IN", billingAuthority: "LIS_INTERNAL", priority: "ROUTINE", status: "COMPLETED", orderingDoctor: "Dr. Farhan Ansari", placedAt: new Date("2026-08-23T02:35:00.000Z") }, update: {} });
  const aarogyaItem = await prisma.laboratoryOrderItem.upsert({ where: { id: "OI-A-1" }, create: { id: "OI-A-1", tenantId: aarogya.id, orderId: aarogyaOrder.id, testId: aarogyaTest.id, departmentId: privateDept.id, status: "RELEASED" }, update: {} });

  await prisma.workItem.upsert({ where: { id: "WORK-70011-1" }, create: { id: "WORK-70011-1", tenantId: sunrise.id, orderItemId: "OI-1", departmentId: hema.id, label: "Complete Blood Count", priority: "STAT", status: "READY" }, update: {} });
  const analyzer = await prisma.analyzer.upsert({ where: { id: "AN-01" }, create: { id: "AN-01", tenantId: sunrise.id, departmentId: chem.id, name: "Cobas c311", status: "CONNECTED", lastMessageAt: new Date("2026-08-23T04:28:00.000Z"), queueDepth: 6, mappingVersion: "map-v2.3", errorCount: 0 }, update: {} });
  await prisma.instrumentRun.upsert({ where: { id: "RUN-501" }, create: { id: "RUN-501", tenantId: sunrise.id, analyzerId: analyzer.id, runAt: new Date("2026-08-23T04:00:00.000Z"), status: "COMPLETED", items: { create: { tenantId: sunrise.id, workItemId: "WORK-70011-1", rawPayload: { source: "seed", itemCount: 1 } } } }, update: {} });
  const seededResult = await prisma.result.upsert({ where: { id: "RES-1" }, create: { id: "RES-1", tenantId: sunrise.id, orderItemId: "OI-2", testName: "Haemoglobin", currentValue: "10.2", units: "g/dL", referenceRange: "13.0-17.0", flag: "LOW", status: "RESULTED", enteredById: "USR-TECH", revisions: { create: { tenantId: sunrise.id, version: 1, value: "10.2", flag: "LOW", reason: "Initial analyzer result", actorUserId: "USR-TECH" } } }, update: {} });
  const report = await prisma.report.upsert({ where: { tenantId_orderId: { tenantId: aarogya.id, orderId: aarogyaOrder.id } }, create: { id: "RPT-A-1001", tenantId: aarogya.id, orderId: aarogyaOrder.id }, update: {} });
  await prisma.reportVersion.upsert({ where: { reportId_version: { reportId: report.id, version: 1 } }, create: { id: "RPT-A-1001-v1", tenantId: aarogya.id, reportId: report.id, version: 1, status: "FINAL", releasedAt: new Date("2026-08-23T07:40:00.000Z"), immutableAt: new Date("2026-08-23T07:40:00.000Z"), authorizedById: "USR-AAROGYA-ADMIN", payload: { patientName: aarogyaPatient.name, tests: [aarogyaTest.name] }, items: { create: { tenantId: aarogya.id, orderItemId: aarogyaItem.id } } }, update: {} });
  await prisma.criticalNotification.upsert({ where: { id: "CRIT-201" }, create: { id: "CRIT-201", tenantId: sunrise.id, resultId: seededResult.id, patientName: patient.name, testName: "Haemoglobin", value: "6.8 g/dL", notifiedTo: "Dr. Nikhil Wagh", acknowledged: false, timerSeconds: 240 }, update: {} });
  const nonconformance = await prisma.nonconformance.upsert({ where: { id: "NC-301" }, create: { id: "NC-301", tenantId: sunrise.id, title: "Glucose L2 QC out-of-control not actioned within SLA", category: "Analytical", severity: "MAJOR", status: "CAPA_LINKED", raisedAt: new Date("2026-08-23T00:50:00.000Z") }, update: {} });
  await prisma.correctivePreventiveAction.upsert({ where: { id: "CAPA-101" }, create: { id: "CAPA-101", tenantId: sunrise.id, nonconformanceId: nonconformance.id, title: "Retrain chemistry staff on Westgard rule escalation", stage: "ACTION_PLAN", owner: "Quality Manager", dueDate: new Date("2026-09-29") }, update: {} });
  await prisma.qualityDocument.upsert({ where: { id: "QDOC-001" }, create: { id: "QDOC-001", tenantId: sunrise.id, title: "Specimen acceptance and rejection SOP", version: 3, status: "ACTIVE", contentUrl: "https://example.invalid/qlyno/sop/specimen-acceptance" }, update: {} });
  await prisma.qualityAudit.upsert({ where: { id: "QAUD-001" }, create: { id: "QAUD-001", tenantId: sunrise.id, title: "Internal pre-analytical process audit", status: "SCHEDULED", scheduledAt: new Date("2026-09-20"), findings: {} }, update: {} });
  await prisma.competencyAssessment.upsert({ where: { id: "COMP-001" }, create: { id: "COMP-001", tenantId: sunrise.id, userId: "USR-TECH", competency: "Hematology analyzer operations", status: "COMPETENT", assessedAt: new Date("2026-08-15") }, update: {} });
  const lot = await prisma.stockLot.upsert({ where: { tenantId_itemId_lotNumber: { tenantId: sunrise.id, itemId: "INV-EDTA", lotNumber: "EDTA-7742" } }, create: { id: "LOT-03", tenantId: sunrise.id, itemId: "INV-EDTA", lotNumber: "EDTA-7742", expiryDate: new Date("2027-03-01"), quantity: 84, status: "AVAILABLE" }, update: {} });
  await prisma.stockMovement.upsert({ where: { id: "MOVE-001" }, create: { id: "MOVE-001", tenantId: sunrise.id, itemId: "INV-EDTA", type: "RECEIPT", quantity: lot.quantity, reason: "Opening seed balance", actorUserId: "USR-INVENTORY" }, update: {} });
  await prisma.purchaseOrder.upsert({ where: { id: "PO-001" }, create: { id: "PO-001", tenantId: sunrise.id, supplier: "MedSupply India", status: "DRAFT", total: 12500, items: { create: { tenantId: sunrise.id, description: "EDTA Vacutainer, box of 100", quantity: 10, unitPrice: 1250 } } }, update: {} });
  await prisma.equipmentMaintenance.upsert({ where: { id: "MAINT-001" }, create: { id: "MAINT-001", tenantId: sunrise.id, equipmentId: "EQ-COBAS", type: "CALIBRATION", status: "SCHEDULED", scheduledAt: new Date("2026-09-15"), notes: "Quarterly calibration" }, update: {} });
  const estimate = await prisma.estimate.upsert({ where: { id: "EST-A-001" }, create: { id: "EST-A-001", tenantId: aarogya.id, orderId: aarogyaOrder.id, patientName: aarogyaPatient.name, amount: 950, status: "ISSUED", issuedAt: new Date("2026-08-23T02:30:00.000Z"), lines: { create: { tenantId: aarogya.id, description: aarogyaTest.name, quantity: 1, unitPrice: 950 } } }, update: {} });
  const invoice = await prisma.invoice.upsert({ where: { id: "INV-A-3001" }, create: { id: "INV-A-3001", tenantId: aarogya.id, orderId: aarogyaOrder.id, patientName: aarogyaPatient.name, amount: estimate.amount, status: "PAID", issuedAt: new Date("2026-08-23T02:45:00.000Z"), lines: { create: { tenantId: aarogya.id, description: aarogyaTest.name, quantity: 1, unitPrice: 950 } } }, update: {} });
  await prisma.payment.upsert({ where: { id: "PAY-A-501" }, create: { id: "PAY-A-501", tenantId: aarogya.id, invoiceId: invoice.id, amount: 950, method: "UPI", receivedAt: new Date("2026-08-23T02:50:00.000Z") }, update: {} });
  const contract = await prisma.contract.upsert({ where: { id: "CTR-9001" }, create: { id: "CTR-9001", tenantId: sunrise.id, clientOrganizationId: client.id, rateCardVersion: "RC-2026-A", creditLimit: 100000, creditTermsDays: 30, status: "ACTIVE", rates: { create: { tenantId: sunrise.id, serviceCode: "CBC", amount: 450 } } }, update: {} });
  await prisma.refund.upsert({ where: { id: "REF-A-001" }, create: { id: "REF-A-001", tenantId: aarogya.id, invoiceId: invoice.id, amount: 100, reason: "Demonstration partial refund", status: "PENDING", actorUserId: "USR-AAROGYA-ADMIN" }, update: {} });
  const manifest = await prisma.manifest.upsert({ where: { id: "MAN-3301" }, create: { id: "MAN-3301", tenantId: sunrise.id, route: "Ward 4B to Central Lab", courierName: "Sandeep Yadav", status: "BUILDING", temperature: "Ambient", specimens: { create: { tenantId: sunrise.id, specimenId: "SPX-9001" } } }, update: {} });
  await prisma.aliquot.upsert({ where: { id: "ALQ-9001-A" }, create: { id: "ALQ-9001-A", tenantId: sunrise.id, parentSpecimenId: "SPX-9001", type: "Serum aliquot", volume: 1.5, unit: "mL", status: "ALIQUOTED" }, update: {} });
  const connection = await prisma.integrationConnection.findUniqueOrThrow({ where: { tenantId_system: { tenantId: sunrise.id, system: "Sunrise HMS" } } });
  await prisma.integrationEvent.upsert({ where: { id: "INT-EVT-001" }, create: { id: "INT-EVT-001", tenantId: sunrise.id, connectionId: connection.id, direction: "INBOUND", status: "PROCESSED", payload: { event: "ORDER_IMPORT", orderId: "ORD-70011" }, occurredAt: new Date("2026-09-02T03:42:00.000Z") }, update: {} });
  const template = await prisma.communicationTemplate.upsert({ where: { tenantId_name_channel: { tenantId: sunrise.id, name: "Critical result escalation", channel: "SMS" } }, create: { id: "COM-TPL-001", tenantId: sunrise.id, name: "Critical result escalation", channel: "SMS", body: "Critical laboratory result requires acknowledgement.", active: true }, update: {} });
  await prisma.communicationDelivery.upsert({ where: { id: "COM-DEL-001" }, create: { id: "COM-DEL-001", tenantId: sunrise.id, templateId: template.id, recipientMasked: "+91 ******0001", channel: "SMS", status: "DELIVERED", sentAt: new Date("2026-08-23T05:00:00.000Z") }, update: {} });
  await prisma.supportTicket.upsert({ where: { id: "SUP-001" }, create: { id: "SUP-001", tenantId: sunrise.id, requesterUserId: "USR-RECEPTION", subject: "Label printer calibration assistance", category: "PRINTER", severity: "MEDIUM", status: "OPEN", details: "Front desk label alignment requires support." }, update: {} });
  void contract; void manifest;
  console.info(`Seed complete. Tenant slugs: ${sunrise.slug}, ${aarogya.slug}. Shared demo password: ${devPassword}`);
}

main().catch((error: unknown) => { console.error(error); process.exitCode = 1; }).finally(async () => prisma.$disconnect());
