export type OrderLifecycleStage = "ORDER_RECEIVED" | "COLLECTION_READY" | "RECEIVING" | "ACCESSIONING" | "PROCESSING" | "TECHNICAL_REVIEW" | "MEDICAL_VALIDATION" | "REPORT_RELEASE" | "DELIVERY_CLOSURE" | "CLOSED";
export type LifecycleStageState = "NOT_STARTED" | "ACTIVE" | "PARTIAL" | "COMPLETED" | "BLOCKED" | "SKIPPED";
export type LaboratoryLifecycleEventType = "ORDER_IMPORTED" | "ORDER_PLACED" | "ORDER_VALIDATED" | "SPECIMEN_EXPECTED" | "COLLECTION_TASK_CREATED" | "LABEL_PRINTED" | "SPECIMEN_COLLECTED" | "SPECIMEN_DISPATCHED" | "SPECIMEN_RECEIVED" | "SPECIMEN_ACCEPTED" | "SPECIMEN_REJECTED" | "ACCESSION_CREATED" | "ALIQUOT_CREATED" | "WORK_ITEM_STARTED" | "ANALYZER_RESULT_RECEIVED" | "MANUAL_RESULT_ENTERED" | "RESULTS_COMPLETED" | "QC_PASSED" | "QC_FAILED" | "TECHNICAL_REVIEW_APPROVED" | "TECHNICAL_REVIEW_REJECTED" | "MEDICAL_VALIDATION_APPROVED" | "MEDICAL_VALIDATION_RETURNED" | "REPORT_VERSION_CREATED" | "REPORT_RELEASED" | "REPORT_DELIVERED" | "CRITICAL_RESULT_NOTIFIED" | "CRITICAL_RESULT_ACKNOWLEDGED" | "ORDER_CLOSED" | "ORDER_CANCELLED";

export interface LaboratoryLifecycleEvent { id: string; tenantId: string; siteId?: string; orderId: string; orderItemId?: string; specimenId?: string; reportGroupId?: string; reportVersionId?: string; type: LaboratoryLifecycleEventType; actorType: "USER" | "SYSTEM" | "HMS" | "ANALYZER"; actorId?: string; actorName: string; timestamp: string; reason?: string; metadata?: Record<string, string | number | boolean>; }
export interface LifecycleOrder { id: string; tenantId: string; cancelled?: boolean; validated: boolean; collectionTasksCreated: boolean; }
export interface LifecycleOrderItem { id: string; testId?: string; specimenIds: string[]; status: "ORDERED" | "READY" | "RUNNING" | "TECHNICAL_REVIEW" | "MEDICAL_VALIDATION" | "VERIFIED" | "RELEASED" | "BLOCKED" | "CANCELLED"; reportGroupId: string; }
export interface LifecycleSpecimen { id: string; tenantId: string; siteId: string; orderId: string; patientId: string; patientName: string; mrn: string; type: string; container: string; collectionLocation: string; priority: "routine" | "urgent" | "stat"; status: "EXPECTED" | "COLLECTED" | "IN_TRANSIT" | "RECEIVED" | "ACCEPTED" | "REJECTED"; collectedAt?: string; collectedBy?: string; collectionCondition?: string; sealStatus?: string; temperature?: string; receiptNotes?: string; blocker?: string; accessionId?: string; receivedAt?: string; receivedBy?: string; receivedSiteId?: string; rejectedAt?: string; rejectedBy?: string; recollectionSpecimenId?: string; }
export interface LifecycleWorkItem { id: string; orderItemId: string; started: boolean; qcPassed: boolean; resultsComplete: boolean; }
export interface LifecycleReview { orderItemId: string; technicalApproved: boolean; medicalApproved: boolean; }
export interface LifecycleReportGroup { id: string; orderItemIds: string[]; versionCreated: boolean; released: boolean; }
export interface LifecycleDelivery { reportGroupId: string; delivered: boolean; }
export interface LifecycleCriticalNotification { reportGroupId: string; required: boolean; acknowledged: boolean; }
export interface OrderLifecycleSnapshot { overallStage: OrderLifecycleStage; overallStatus: "PLACED" | "IN_PROGRESS" | "PARTIALLY_COMPLETED" | "COMPLETED" | "ON_HOLD" | "CANCELLED"; progressPercent: number; stages: Array<{ stage: OrderLifecycleStage; state: LifecycleStageState; completedCount: number; applicableCount: number; blockers: string[] }>; nextRequiredActions: Array<{ entityId: string; action: string; requiredPermission: string; route: string }>; }

const STAGES: OrderLifecycleStage[] = ["ORDER_RECEIVED", "COLLECTION_READY", "RECEIVING", "ACCESSIONING", "PROCESSING", "TECHNICAL_REVIEW", "MEDICAL_VALIDATION", "REPORT_RELEASE", "DELIVERY_CLOSURE", "CLOSED"];

export function deriveOrderLifecycle(input: { order: LifecycleOrder; orderItems: LifecycleOrderItem[]; specimens: LifecycleSpecimen[]; workItems: LifecycleWorkItem[]; results: unknown[]; reviews: LifecycleReview[]; reportGroups: LifecycleReportGroup[]; reportVersions: unknown[]; deliveries: LifecycleDelivery[]; criticalNotifications: LifecycleCriticalNotification[] }): OrderLifecycleSnapshot {
  const activeItems = input.orderItems.filter((item) => item.status !== "CANCELLED");
  const applicable = Math.max(activeItems.length, 1);
  const acceptedFor = (item: LifecycleOrderItem) => item.specimenIds.some((id) => input.specimens.find((s) => s.id === id)?.status === "ACCEPTED");
  const passed = (item: LifecycleOrderItem, stage: OrderLifecycleStage) => {
    const specimens = input.specimens.filter((s) => item.specimenIds.includes(s.id)); const work = input.workItems.find((w) => w.orderItemId === item.id); const review = input.reviews.find((r) => r.orderItemId === item.id); const report = input.reportGroups.find((r) => r.id === item.reportGroupId); const delivery = input.deliveries.find((d) => d.reportGroupId === item.reportGroupId); const critical = input.criticalNotifications.find((n) => n.reportGroupId === item.reportGroupId);
    if (stage === "ORDER_RECEIVED") return input.order.validated && input.order.collectionTasksCreated;
    if (stage === "COLLECTION_READY") return specimens.length > 0 && specimens.every((s) => s.status !== "EXPECTED");
    if (stage === "RECEIVING") return specimens.length > 0 && specimens.every((s) => ["RECEIVED", "ACCEPTED", "REJECTED"].includes(s.status));
    if (stage === "ACCESSIONING") return specimens.length > 0 && specimens.every((s) => ["ACCEPTED", "REJECTED"].includes(s.status));
    if (stage === "PROCESSING") return Boolean(work?.resultsComplete && work.qcPassed);
    if (stage === "TECHNICAL_REVIEW") return Boolean(review?.technicalApproved);
    if (stage === "MEDICAL_VALIDATION") return Boolean(review?.medicalApproved && report?.versionCreated);
    if (stage === "REPORT_RELEASE") return Boolean(report?.released);
    if (stage === "DELIVERY_CLOSURE") return Boolean(report?.released && delivery?.delivered && (!critical?.required || critical.acknowledged));
    return Boolean(report?.released && delivery?.delivered && (!critical?.required || critical.acknowledged));
  };
  const blockersFor = (stage: OrderLifecycleStage) => stage === "ACCESSIONING" || stage === "PROCESSING" ? input.specimens.filter((s) => s.status === "REJECTED").map((s) => s.blocker ?? `${s.id} rejected`) : [];
  const stages = STAGES.map((stage, index) => { const completedCount = activeItems.filter((item) => passed(item, stage)).length; const blockers = blockersFor(stage); const previousComplete = index === 0 || activeItems.some((item) => passed(item, STAGES[index - 1])); let state: LifecycleStageState = "NOT_STARTED"; if (completedCount === applicable) state = "COMPLETED"; else if (completedCount > 0) state = "PARTIAL"; else if (blockers.length && previousComplete) state = "BLOCKED"; else if (previousComplete) state = "ACTIVE"; return { stage, state, completedCount, applicableCount: applicable, blockers }; });
  const earliest = stages.find((stage) => stage.state !== "COMPLETED") ?? stages[stages.length - 1];
  const released = input.reportGroups.filter((group) => group.released).length; const allReleased = input.reportGroups.length > 0 && released === input.reportGroups.length; const closed = stages[9].state === "COMPLETED";
  const overallStatus = input.order.cancelled ? "CANCELLED" : closed ? "COMPLETED" : released > 0 && !allReleased ? "PARTIALLY_COMPLETED" : earliest.state === "BLOCKED" && activeItems.every((item) => item.status === "BLOCKED") ? "ON_HOLD" : input.order.validated ? "IN_PROGRESS" : "PLACED";
  const completedChecks = stages.slice(0, 9).reduce((sum, stage) => sum + stage.completedCount, 0); const progressPercent = closed ? 100 : Math.min(99, Math.round((completedChecks / (applicable * 9)) * 100));
  const actionMap: Record<OrderLifecycleStage, [string, string, string, string]> = { ORDER_RECEIVED: [input.order.id, "Validate order", "order.validate", `/orders/${input.order.id}`], COLLECTION_READY: [input.specimens.find((s) => s.status === "EXPECTED")?.id ?? input.order.id, "Confirm specimen collection", "collection.confirm", "/collection"], RECEIVING: [input.specimens.find((s) => ["COLLECTED", "IN_TRANSIT"].includes(s.status))?.id ?? input.order.id, "Receive specimen", "specimen.receive", "/collection/scan"], ACCESSIONING: [input.specimens.find((s) => s.status === "RECEIVED")?.id ?? input.order.id, "Accept and create accession", "specimen.accession", "/accessioning"], PROCESSING: [activeItems.find((i) => acceptedFor(i) && i.status !== "TECHNICAL_REVIEW")?.id ?? input.order.id, "Enter/import results", "result.enter", "/workbench"], TECHNICAL_REVIEW: [activeItems.find((i) => !input.reviews.find((r) => r.orderItemId === i.id)?.technicalApproved)?.id ?? input.order.id, "Approve technical review", "result.technical-review", "/validation"], MEDICAL_VALIDATION: [activeItems.find((i) => !input.reviews.find((r) => r.orderItemId === i.id)?.medicalApproved)?.id ?? input.order.id, "Medically validate", "result.medical-validate", "/validation"], REPORT_RELEASE: [input.reportGroups.find((r) => !r.released)?.id ?? input.order.id, "Release report", "report.release", "/reports"], DELIVERY_CLOSURE: [input.reportGroups.find((r) => r.released && !input.deliveries.find((d) => d.reportGroupId === r.id)?.delivered)?.id ?? input.order.id, "Confirm delivery", "report.deliver", "/communications"], CLOSED: [input.order.id, "No action required", "", `/orders/${input.order.id}`] };
  const [entityId, action, requiredPermission, route] = actionMap[earliest.stage];
  return { overallStage: earliest.stage, overallStatus, progressPercent, stages, nextRequiredActions: earliest.stage === "CLOSED" && closed ? [] : [{ entityId, action, requiredPermission, route }] };
}
