import { z } from "zod";
import { prisma } from "../../db/prisma";
import { protectedRouter } from "../../middleware/protected";
import { rejectAuditorWrites, requireAnyPermission, requirePermission } from "../../middleware/authorize";
import { validate } from "../../middleware/validate";
import { asyncHandler } from "../../utils/async-handler";
import { requireDepartment } from "../../services/scope";
import { notFound } from "../../utils/errors";

const run = z.object({ analyzerId: z.string().min(1), workItemIds: z.array(z.string().min(1)).min(1), rawPayload: z.record(z.unknown()).optional() }).strict();
const id = z.object({ id: z.string().min(1).max(100) }).strict();
export const workbenchRoutes = protectedRouter();
workbenchRoutes.get("/", requireAnyPermission("results.read", "workbench.write"), asyncHandler(async (req, res) => { const allDepartments = req.context!.roles.some((r) => ["tenant_admin", "auditor", "lab_director", "quality_manager"].includes(r)); res.json({ data: await prisma.workItem.findMany({ where: { tenantId: req.context!.tenantId, ...(allDepartments ? {} : { departmentId: { in: req.context!.departmentIds } }) }, include: { orderItem: { include: { test: true, order: { include: { patient: true } } } }, department: true }, orderBy: [{ priority: "desc" }, { createdAt: "asc" }] }) }); }));
workbenchRoutes.get("/analyzers", requireAnyPermission("results.read", "workbench.write", "equipment.read"), asyncHandler(async (req, res) => { const allDepartments = req.context!.roles.some((r) => ["tenant_admin", "auditor", "lab_director", "quality_manager", "inventory_procurement"].includes(r)); res.json({ data: await prisma.analyzer.findMany({ where: { tenantId: req.context!.tenantId, ...(allDepartments ? {} : { departmentId: { in: req.context!.departmentIds } }) }, orderBy: { name: "asc" } }) }); }));
workbenchRoutes.get("/analyzers/:id", requireAnyPermission("results.read", "workbench.write", "equipment.read"), validate({ params: id }), asyncHandler(async (req, res) => { const allDepartments = req.context!.roles.some((role) => ["tenant_admin", "auditor", "lab_director", "quality_manager", "inventory_procurement"].includes(role)); const data = await prisma.analyzer.findFirst({ where: { id: String(req.params.id), tenantId: req.context!.tenantId, ...(allDepartments ? {} : { departmentId: { in: req.context!.departmentIds } }) }, include: { department: true, runs: { orderBy: { runAt: "desc" }, take: 100, include: { items: true } } } }); if (!data) throw notFound("Analyzer"); res.json({ data }); }));
workbenchRoutes.get("/runs", requireAnyPermission("results.read", "workbench.write", "equipment.read"), asyncHandler(async (req, res) => { const allDepartments = req.context!.roles.some((role) => ["tenant_admin", "auditor", "lab_director", "quality_manager", "inventory_procurement"].includes(role)); res.json({ data: await prisma.instrumentRun.findMany({ where: { tenantId: req.context!.tenantId, analyzer: allDepartments ? undefined : { departmentId: { in: req.context!.departmentIds } } }, include: { analyzer: true, items: true }, orderBy: { runAt: "desc" }, take: 500 }) }); }));
workbenchRoutes.post("/runs", rejectAuditorWrites, requirePermission("workbench.write"), validate({ body: run }), asyncHandler(async (req, res) => { const analyzer = await prisma.analyzer.findFirst({ where: { id: req.body.analyzerId, tenantId: req.context!.tenantId } }); if (!analyzer) throw notFound("Analyzer"); if (analyzer.departmentId) requireDepartment(req.context!, analyzer.departmentId); const items = await prisma.workItem.findMany({ where: { id: { in: req.body.workItemIds }, tenantId: req.context!.tenantId } }); if (items.length !== new Set(req.body.workItemIds).size) throw notFound("Work item"); const data = await prisma.$transaction(async (tx) => { const created = await tx.instrumentRun.create({ data: { tenantId: req.context!.tenantId, analyzerId: analyzer.id, runAt: new Date(), status: "RUNNING", items: { create: items.map((item) => ({ tenantId: req.context!.tenantId, workItemId: item.id, rawPayload: req.body.rawPayload })) } } }); await tx.workItem.updateMany({ where: { id: { in: req.body.workItemIds }, tenantId: req.context!.tenantId }, data: { status: "RUNNING" } }); await tx.laboratoryOrderItem.updateMany({ where: { id: { in: items.map((item) => item.orderItemId) }, tenantId: req.context!.tenantId }, data: { status: "RUNNING" } }); return created; }); res.status(201).json({ data }); }));
