"use client";

import Link from "next/link";
import { ArrowRight, CheckCircle2, Circle, CircleAlert, LoaderCircle, RotateCcw } from "lucide-react";
import { Card } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import { StatusBadge } from "@/components/ui/Badge";
import { Timeline } from "@/components/ui/Timeline";
import { useToast } from "@/components/ui/Toast";
import { useHospitalWorkflow, type HospitalWorkflowStage } from "@/state/hospital-workflow-context";
import { cn } from "@/lib/utils/cn";

const STAGES: HospitalWorkflowStage[] = ["ORDER_RECEIVED", "COLLECTION_READY", "RECEIVING", "ACCESSIONING", "PROCESSING", "TECHNICAL_REVIEW", "MEDICAL_VALIDATION", "REPORT_RELEASE", "DELIVERY_CLOSURE", "CLOSED"];
const QUEUE: Record<HospitalWorkflowStage, { label: string; href: string }> = { ORDER_RECEIVED: { label: "Order intake", href: "/orders/ORD-70012" }, COLLECTION_READY: { label: "Collection Tasks", href: "/collection" }, RECEIVING: { label: "Receiving Scanner", href: "/collection/scan" }, ACCESSIONING: { label: "Accessioning", href: "/accessioning" }, PROCESSING: { label: "Coagulation Workbench", href: "/workbench/coagulation" }, TECHNICAL_REVIEW: { label: "Technical Review", href: "/validation" }, MEDICAL_VALIDATION: { label: "Medical Validation", href: "/validation" }, REPORT_RELEASE: { label: "Report Release", href: "/reports" }, DELIVERY_CLOSURE: { label: "Delivery & Closure", href: "/communications" }, CLOSED: { label: "Analytics & Archive", href: "/analytics" } };

export function HospitalWorkflowCard({ compact = false, orderId }: { compact?: boolean; orderId?: string }) {
  const { workflow, lifecycle, canAdvance, requiredRoles, actionLabel, advance, reset } = useHospitalWorkflow(); const { showToast } = useToast(); const baseQueue = QUEUE[workflow.stage]; const queue = workflow.stage === "ORDER_RECEIVED" ? { ...baseQueue, href: `/orders/${workflow.orderId}` } : baseQueue;
  const displayedOrderId = orderId ?? workflow.orderId; const isActiveWorkflow = displayedOrderId === workflow.orderId; const queueHandledStage = ["COLLECTION_READY", "RECEIVING", "ACCESSIONING"].includes(workflow.stage); const currentQueueHref = workflow.stage === "COLLECTION_READY" ? `/collection?orderId=${workflow.orderId}&specimenId=${workflow.specimenId}` : workflow.stage === "RECEIVING" ? `/collection/scan?orderId=${workflow.orderId}&specimenId=${workflow.specimenId}` : workflow.stage === "ACCESSIONING" ? `/accessioning?orderId=${workflow.orderId}&specimenId=${workflow.specimenId}` : queue.href;
  return <Card className="overflow-hidden"><div className="border-b border-app-border bg-[#F7FAF7] p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[0.13em] text-brand-blue">Order lifecycle</p><h3 className="mt-1 font-display text-xl font-semibold">{displayedOrderId} · {isActiveWorkflow ? queue.label : "Order progress"}</h3><p className="mt-1 text-xs text-text-muted">Overall lifecycle across tests, specimens, results and report groups. Child items may progress independently.</p></div><div className="text-right"><StatusBadge status={isActiveWorkflow ? lifecycle.overallStatus.toLowerCase() : "in_progress"} /><p className="mt-1 text-[10px] text-text-muted">{lifecycle.progressPercent}% from applicable checkpoints</p></div></div>
    <div className="mt-4 flex gap-1 overflow-x-auto pb-1">{lifecycle.stages.map(({ stage, state, completedCount, applicableCount, blockers }) => { const Icon = state === "COMPLETED" ? CheckCircle2 : state === "BLOCKED" ? CircleAlert : state === "ACTIVE" || state === "PARTIAL" ? LoaderCircle : Circle; return <div key={stage} className="min-w-[94px] flex-1" aria-label={`${stage.replaceAll("_", " ")}: ${state.replaceAll("_", " ")}; ${completedCount} of ${applicableCount} completed${blockers.length ? `; ${blockers.join(", ")}` : ""}`}><div className={cn("h-1.5 rounded-full", state === "COMPLETED" ? "bg-emerald-600" : state === "ACTIVE" ? "bg-brand-blue" : state === "PARTIAL" ? "bg-amber-400" : state === "BLOCKED" ? "bg-red-500" : "bg-app-border")} /><p className={cn("mt-1 flex items-start gap-1 text-[8px] uppercase", state === "ACTIVE" ? "font-bold text-brand-blue" : state === "BLOCKED" ? "font-bold text-status-critical" : "text-text-muted")}><Icon className="mt-px h-2.5 w-2.5 shrink-0" />{stage.replaceAll("_", " ")}</p><p className="mt-0.5 text-[8px] text-text-muted">{state === "PARTIAL" ? `${completedCount}/${applicableCount} complete` : state.replaceAll("_", " ")}</p></div>; })}</div></div>
    <div className="p-5"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Meta label="Patient / MRN" value={`${workflow.patientId} / ${workflow.mrn}`} /><Meta label="Encounter / Order item" value={`${workflow.encounterId} / ${workflow.orderItemId}`} /><Meta label="Specimen / Accession" value={`${workflow.specimenId} / ${workflow.accessionId ?? "Pending"}`} /><Meta label="Result / Report version" value={`${workflow.resultId ?? "Pending"} / ${workflow.reportVersionId ?? "Pending"}`} /></div>
    {isActiveWorkflow && <div className="mt-4 flex flex-wrap items-center gap-2 rounded-lg border border-app-border bg-app-bg p-3"><div className="mr-auto"><p className="text-xs font-semibold">Next required action: {actionLabel}</p><p className="text-[10px] text-text-muted">{requiredRoles.length ? `Responsible roles: ${requiredRoles.join(", ").replaceAll("_", " ")}` : "System or delegated laboratory administrator"}</p></div>{workflow.stage !== "CLOSED" && canAdvance && !queueHandledStage && <Button size="sm" onClick={() => { advance(); showToast({ title: `${actionLabel} completed`, description: "Child record, queues and immutable timeline updated; pipeline recalculated automatically.", tone: "success" }); }}>{actionLabel}<ArrowRight className="h-3.5 w-3.5" /></Button>}{workflow.stage !== "CLOSED" && !canAdvance && <span className="rounded-control border border-app-border bg-white px-3 py-2 text-xs text-text-muted">{workflow.stage === "COLLECTION_READY" ? "Awaiting authorized collector" : "Awaiting authorized role"}</span>}<Link href={currentQueueHref} className="rounded-control border border-app-border bg-white px-3 py-2 text-xs font-semibold text-brand-blue">Open current queue</Link>{workflow.stage === "CLOSED" && process.env.NODE_ENV !== "production" && <Button size="sm" variant="outline" onClick={reset}><RotateCcw className="h-3.5 w-3.5" /> Reset demo</Button>}</div>}
    {!compact && <div className="mt-5 grid gap-4 lg:grid-cols-2"><div className="rounded-lg border border-app-border p-4"><p className="text-xs font-semibold uppercase tracking-wide text-text-muted">Current records</p><div className="mt-3 grid grid-cols-2 gap-3"><Meta label="Specimen status" value={workflow.specimenStatus} /><Meta label="Test status" value={workflow.testStatus} /><Meta label="Report status" value={workflow.reportStatus} /><Meta label="HMS delivery" value={workflow.hmsDeliveryStatus} /></div></div><div className="rounded-lg border border-app-border p-4"><p className="mb-3 text-xs font-semibold uppercase tracking-wide text-text-muted">Immutable transition history</p><Timeline entries={workflow.events.slice().reverse().map((event) => ({ id: event.id, label: event.action, timestamp: event.timestamp, description: `${event.actor} · ${event.role} · ${event.reason}`, tone: "success" }))} /></div></div>}
    </div></Card>;
}
function Meta({ label, value }: { label: string; value: string }) { return <div><p className="text-[10px] uppercase tracking-wide text-text-muted">{label}</p><p className="mt-1 text-xs font-semibold text-text-main">{value}</p></div>; }
