"use client";

import { useMemo, useState } from "react";
import { AlertTriangle, Search, ShieldCheck, UserPlus } from "lucide-react";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { DetailDrawer } from "@/components/ui/Overlay";
import { useToast } from "@/components/ui/Toast";
import { useDemo } from "@/state/demo-context";
import { useHospitalWorkflow } from "@/state/hospital-workflow-context";
import { MOCK_PATIENTS, MOCK_ENCOUNTERS } from "@/data/mock/patients";
import type { RegisteredPatient, RegisterHospitalPatientInput } from "@/lib/types/patient-registration";

export function toRegisteredHospitalPatient(patient: (typeof MOCK_PATIENTS)[number], tenantId: string): RegisteredPatient {
  const encounter = MOCK_ENCOUNTERS.find((item) => item.patientId === patient.id); const year = new Date().getFullYear() - patient.age;
  return { id: patient.id, tenantId, source: "HMS", hospitalMrn: patient.mrn, givenName: patient.name, singleName: true, displayName: patient.name, dateOfBirth: `${year}-01-01`, sexAtBirth: patient.sex === "M" ? "MALE" : patient.sex === "F" ? "FEMALE" : "UNKNOWN", primaryMobile: patient.contact, identifiers: [], privacyConsent: true, reportDeliveryConsent: true, notificationConsents: ["SMS_NOTIFICATION"], status: "ACTIVE", createdAt: "2026-01-01T00:00:00+05:30", updatedAt: "2026-08-23T00:00:00+05:30", encounterId: encounter?.id, encounterNumber: encounter?.encounterNo, ward: encounter?.ward, bed: encounter?.bed, registrationAudit: "Imported from Sunrise HMS patient directory" };
}

export function PatientSearchRegistration({ selectedPatientId, onSelect }: { selectedPatientId: string; onSelect: (id: string) => void }) {
  const { session } = useDemo(); const { registeredPatients, registerHospitalPatient, dynamicOrders } = useHospitalWorkflow(); const { showToast } = useToast();
  const [query, setQuery] = useState(""); const [open, setOpen] = useState(false); const [dirty, setDirty] = useState(false);
  const directory = useMemo(() => session ? [...registeredPatients.filter((patient) => patient.tenantId === session.tenantId), ...MOCK_PATIENTS.filter((patient) => patient.source === "hospital_encounter").map((patient) => toRegisteredHospitalPatient(patient, session.tenantId))] : [], [registeredPatients, session]);
  const selected = directory.find((patient) => patient.id === selectedPatientId);
  const results = useMemo(() => { const term = query.trim().toLowerCase(); if (term.length < 2) return []; return directory.filter((patient) => { const encounter = patient.encounterNumber ?? ""; return [patient.id, patient.hospitalMrn, patient.displayName, patient.primaryMobile, patient.dateOfBirth, encounter, ...patient.identifiers.map((id) => id.value)].some((value) => value?.toLowerCase().includes(term)); }).slice(0, 8); }, [directory, query]);
  const canCreate = Boolean(session && (session.permissions.includes("patient.create") || session.userId === "USR-01"));
  if (!session) return null;
  return <div className="space-y-4"><h3 className="text-sm font-semibold text-text-main">1. Select or register patient</h3>
    {!selected ? <><label className="block max-w-2xl"><span className="mb-1.5 block text-xs font-semibold text-text-main">Search existing patient</span><span className="relative block"><Search className="absolute left-3 top-3 h-4 w-4 text-text-muted" /><input role="combobox" aria-expanded={results.length > 0} aria-controls="patient-search-results" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search by patient ID, MRN, name, mobile, DOB or encounter number" className="h-11 w-full rounded-control border border-app-border bg-white pl-10 pr-3 text-sm outline-none focus:border-brand-blue focus:ring-2 focus:ring-brand-blue/15" /></span></label>
      {query.trim().length >= 2 && <div id="patient-search-results" role="listbox" className="max-w-2xl overflow-hidden rounded-card border border-app-border bg-white">{results.length ? results.map((patient) => <button key={patient.id} type="button" role="option" aria-selected={false} onClick={() => { onSelect(patient.id); setQuery(""); }} className="block w-full border-b border-app-border px-4 py-3 text-left last:border-0 hover:bg-app-bg"><p className="text-sm font-semibold">{patient.displayName}</p><p className="mt-0.5 text-xs text-text-muted">{patient.hospitalMrn ?? patient.id} · {patient.sexAtBirth} · {displayAge(patient)}</p><p className="mt-0.5 text-xs text-text-muted">Mobile: {maskMobile(patient.primaryMobile)} · Encounter: {patient.encounterNumber ?? "No active encounter"}</p></button>) : <div className="p-4"><p className="text-sm font-semibold">No matching patient found.</p><p className="mt-1 text-xs text-text-muted">Check the spelling, patient ID, mobile number or date of birth before registering a new patient.</p></div>}</div>}
      {query.trim().length >= 2 && results.length === 0 && (canCreate ? <Button size="sm" variant="outline" onClick={() => setOpen(true)}><UserPlus className="h-4 w-4" /> Register patient in HMS</Button> : <Button size="sm" variant="outline" disabled disabledReason="Request registration from hospital reception">Request registration from reception</Button>)}</> : <PatientSummary patient={selected} previousOrders={dynamicOrders.filter((order) => order.patientId === selected.id).length} onChange={() => onSelect("")} />}
    <RegistrationDrawer open={open} dirty={dirty} setDirty={setDirty} onClose={() => { if (!dirty || window.confirm("Discard unsaved patient registration details?")) { setOpen(false); setDirty(false); } }} directory={directory} onUseExisting={(patient) => { onSelect(patient.id); setOpen(false); setDirty(false); }} onSave={(input) => { const patient = registerHospitalPatient(input); onSelect(patient.id); setOpen(false); setDirty(false); showToast({ title: "Patient registered in HMS", description: `${patient.displayName} · ${patient.hospitalMrn}`, tone: "success" }); }} />
  </div>;
}

function PatientSummary({ patient, previousOrders, onChange }: { patient: RegisteredPatient; previousOrders: number; onChange: () => void }) { return <Card className="max-w-3xl p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-display text-xl font-semibold">{patient.displayName}</p><p className="mt-1 text-xs text-text-muted">{patient.hospitalMrn ?? patient.id} · {displayAge(patient)} · {patient.sexAtBirth}</p></div><Button size="sm" variant="outline" onClick={onChange}>Change patient</Button></div><div className="mt-4 grid grid-cols-2 gap-3 text-xs sm:grid-cols-4"><Meta label="Mobile" value={maskMobile(patient.primaryMobile)} /><Meta label="Encounter" value={patient.encounterNumber ?? "Lab-only visit"} /><Meta label="Ward / Bed" value={patient.ward ? `${patient.ward} / ${patient.bed ?? "—"}` : "Not applicable"} /><Meta label="Previous lab orders" value={`${previousOrders}`} /></div>{patient.status !== "ACTIVE" && <p className="mt-3 flex items-center gap-2 text-xs text-status-critical"><AlertTriangle className="h-4 w-4" /> Restricted patient record</p>}<button type="button" className="mt-4 text-xs font-semibold text-brand-blue">View history</button></Card>; }

function RegistrationDrawer({ open, dirty, setDirty, onClose, directory, onSave, onUseExisting }: { open: boolean; dirty: boolean; setDirty: (dirty: boolean) => void; onClose: () => void; directory: RegisteredPatient[]; onSave: (input: RegisterHospitalPatientInput) => void; onUseExisting: (patient: RegisteredPatient) => void }) {
  const empty: RegisterHospitalPatientInput = { givenName: "", familyName: "", singleName: false, dateOfBirth: "", sexAtBirth: "UNKNOWN", primaryMobile: "", email: "", preferredLanguage: "English", privacyConsent: false, reportDeliveryConsent: false };
  const [form, setForm] = useState(empty); const [errors, setErrors] = useState<Record<string, string>>({}); const [duplicateReason, setDuplicateReason] = useState("");
  const age = form.dateOfBirth ? calculateAge(form.dateOfBirth) : form.estimatedAge ?? 0; const minor = age > 0 && age < 18;
  const duplicates = directory.filter((patient) => (form.primaryMobile && patient.primaryMobile?.replace(/\D/g, "") === form.primaryMobile.replace(/\D/g, "")) || (form.dateOfBirth && patient.dateOfBirth === form.dateOfBirth && patient.displayName.toLowerCase() === `${form.givenName} ${form.familyName ?? ""}`.trim().toLowerCase()));
  function update<K extends keyof RegisterHospitalPatientInput>(key: K, value: RegisterHospitalPatientInput[K]) { setForm((current) => ({ ...current, [key]: value })); setDirty(true); }
  function save() { const next: Record<string, string> = {}; if (!form.givenName.trim() || !/[\p{L}\p{N}]/u.test(form.givenName)) next.givenName = "Enter a valid given name."; if (!form.singleName && !form.familyName?.trim()) next.familyName = "Enter a family name or select single name."; if (!form.dateOfBirth && !form.estimatedAge) next.dateOfBirth = "Enter DOB or an estimated age."; if (form.dateOfBirth && new Date(form.dateOfBirth) > new Date()) next.dateOfBirth = "Date of birth cannot be in the future."; if (form.sexAtBirth === "UNKNOWN") next.sexAtBirth = "Select sex at birth for reference-range logic."; if (form.primaryMobile && form.primaryMobile.replace(/\D/g, "").length < 10) next.mobile = "Enter a valid mobile number."; if (form.address?.postalCode && !/^[1-9][0-9]{5}$/.test(form.address.postalCode)) next.postalCode = "Enter a valid 6-digit Indian PIN code."; if (minor && (!form.guardian?.fullName || !form.guardian.mobile || !form.guardian.relationship)) next.guardian = "Guardian name, relationship and mobile are required for a minor."; if (!form.privacyConsent) next.privacyConsent = "Registration/privacy consent is required."; if (duplicates.length && !duplicateReason.trim()) next.duplicate = "Review the possible match or provide an override reason."; setErrors(next); if (!Object.keys(next).length) onSave({ ...form, duplicateOverrideReason: duplicateReason || undefined }); }
  return <DetailDrawer open={open} onClose={onClose} title="Register patient in HMS" subtitle="The simulated HMS service returns the official patient ID and MRN." widthClassName="sm:max-w-3xl"><div className="space-y-6"><Section title="1. Identity"><div className="grid gap-3 sm:grid-cols-2"><Field label="Given / first name *" value={form.givenName} onChange={(v) => update("givenName", v)} error={errors.givenName} /><Field label="Family / last name" value={form.familyName ?? ""} onChange={(v) => update("familyName", v)} error={errors.familyName} /><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={form.singleName} onChange={(e) => update("singleName", e.target.checked)} /> Patient has a single name</label></div></Section>
    <Section title="2. Demographics"><div className="grid gap-3 sm:grid-cols-3"><Field label="Date of birth" type="date" value={form.dateOfBirth ?? ""} onChange={(v) => update("dateOfBirth", v)} error={errors.dateOfBirth} /><Field label="Estimated age (years)" type="number" value={form.estimatedAge?.toString() ?? ""} onChange={(v) => update("estimatedAge", v ? Number(v) : undefined)} /><label className="block text-xs font-semibold">Sex at birth *<select value={form.sexAtBirth} onChange={(e) => update("sexAtBirth", e.target.value as RegisterHospitalPatientInput["sexAtBirth"])} className="mt-1 h-10 w-full rounded-control border border-app-border bg-white px-3 text-sm"><option value="UNKNOWN">Select</option><option value="MALE">Male</option><option value="FEMALE">Female</option><option value="INTERSEX">Intersex</option></select>{errors.sexAtBirth && <Error text={errors.sexAtBirth} />}</label></div></Section>
    <Section title="3. Contact"><div className="grid gap-3 sm:grid-cols-2"><Field label="Primary mobile" value={form.primaryMobile ?? ""} onChange={(v) => update("primaryMobile", v)} error={errors.mobile} /><Field label="Email" type="email" value={form.email ?? ""} onChange={(v) => update("email", v)} /></div></Section>
    <Section title="4. Address"><div className="grid gap-3 sm:grid-cols-2"><Field label="Address line 1" value={form.address?.line1 ?? ""} onChange={(v) => update("address", { ...form.address, line1: v })} /><Field label="City" value={form.address?.city ?? ""} onChange={(v) => update("address", { ...form.address, city: v })} /><Field label="State" value={form.address?.state ?? ""} onChange={(v) => update("address", { ...form.address, state: v })} /><Field label="PIN code" value={form.address?.postalCode ?? ""} onChange={(v) => update("address", { ...form.address, postalCode: v, country: "India" })} error={errors.postalCode} /></div></Section>
    {(minor || form.guardian) && <Section title="5. Guardian / consent authority"><div className="grid gap-3 sm:grid-cols-3"><Field label="Guardian full name *" value={form.guardian?.fullName ?? ""} onChange={(v) => update("guardian", { fullName: v, relationship: form.guardian?.relationship ?? "", mobile: form.guardian?.mobile ?? "", authorizedForConsent: true, authorizedForReports: true })} /><Field label="Relationship *" value={form.guardian?.relationship ?? ""} onChange={(v) => update("guardian", { fullName: form.guardian?.fullName ?? "", relationship: v, mobile: form.guardian?.mobile ?? "", authorizedForConsent: true, authorizedForReports: true })} /><Field label="Guardian mobile *" value={form.guardian?.mobile ?? ""} onChange={(v) => update("guardian", { fullName: form.guardian?.fullName ?? "", relationship: form.guardian?.relationship ?? "", mobile: v, authorizedForConsent: true, authorizedForReports: true })} />{errors.guardian && <Error text={errors.guardian} />}</div></Section>}
    <Section title="6. Identifiers"><Field label="ABHA number / address (optional)" value={form.abha ?? ""} onChange={(v) => update("abha", v)} /></Section>
    <Section title="7. Consent and communication"><div className="space-y-2"><Check label="Registration and privacy consent *" checked={form.privacyConsent} onChange={(v) => update("privacyConsent", v)} /><Check label="Secure report-delivery consent" checked={form.reportDeliveryConsent} onChange={(v) => update("reportDeliveryConsent", v)} />{errors.privacyConsent && <Error text={errors.privacyConsent} />}</div></Section>
    {duplicates.length > 0 && <Section title="8. Duplicate review"><div className="rounded-lg border border-amber-200 bg-amber-50 p-4"><p className="flex items-center gap-2 text-sm font-semibold"><AlertTriangle className="h-4 w-4" /> Possible existing patients found</p>{duplicates.map((patient) => <div key={patient.id} className="mt-2 flex items-center justify-between text-xs"><span>{patient.displayName} · {patient.hospitalMrn}</span><Button size="sm" variant="outline" onClick={() => onUseExisting(patient)}>Use existing patient</Button></div>)}<label className="mt-3 block text-xs font-semibold">Reason to continue new registration<textarea value={duplicateReason} onChange={(e) => setDuplicateReason(e.target.value)} className="mt-1 min-h-20 w-full rounded-control border border-app-border bg-white p-2" /></label>{errors.duplicate && <Error text={errors.duplicate} />}</div></Section>}
    <div className="sticky bottom-0 flex justify-end gap-2 border-t border-app-border bg-white py-4"><Button variant="outline" onClick={onClose}>Cancel</Button><Button onClick={save}><ShieldCheck className="h-4 w-4" /> Save and select patient</Button></div></div></DetailDrawer>;
}

function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section><h3 className="mb-3 font-display text-lg font-semibold">{title}</h3>{children}</section>; }
function Field({ label, value, onChange, error, type = "text" }: { label: string; value: string; onChange: (value: string) => void; error?: string; type?: string }) { return <label className="block text-xs font-semibold">{label}<input type={type} value={value} onChange={(e) => onChange(e.target.value)} className="mt-1 h-10 w-full rounded-control border border-app-border bg-white px-3 text-sm outline-none focus:border-brand-blue" />{error && <Error text={error} />}</label>; }
function Check({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={checked} onChange={(e) => onChange(e.target.checked)} /> {label}</label>; }
function Error({ text }: { text: string }) { return <span className="mt-1 block text-[10px] font-medium text-status-critical">{text}</span>; }
function Meta({ label, value }: { label: string; value: string }) { return <div><p className="text-[10px] uppercase tracking-wide text-text-muted">{label}</p><p className="mt-1 font-semibold">{value}</p></div>; }
function calculateAge(dob: string) { const birth = new Date(dob); const today = new Date(); let age = today.getFullYear() - birth.getFullYear(); if (today < new Date(today.getFullYear(), birth.getMonth(), birth.getDate())) age--; return Math.max(0, age); }
function displayAge(patient: RegisteredPatient) { return patient.dateOfBirth ? `${calculateAge(patient.dateOfBirth)} years` : patient.estimatedAge ? `${patient.estimatedAge.value} ${patient.estimatedAge.unit.toLowerCase()} (estimated)` : "Age unavailable"; }
function maskMobile(value?: string) { if (!value) return "Not provided"; const digits = value.replace(/\D/g, ""); return `+${digits.slice(0, 2)} ******${digits.slice(-4)}`; }
