import { prisma } from "../../db/prisma";
import { protectedRouter } from "../../middleware/protected";
import { requireAnyPermission, requirePermission } from "../../middleware/authorize";
import { asyncHandler } from "../../utils/async-handler";
import { orderReadScope, specimenReadScope } from "../../services/scope";

export const dashboardRoutes = protectedRouter();
dashboardRoutes.get("/", requirePermission("dashboard.read"), asyncHandler(async (req, res) => { const tenantId = req.context!.tenantId; const orderScope = orderReadScope(req.context!); const specimenScope = specimenReadScope(req.context!); const [orders, uncollected, receiving, accessioning, processing, technical, medical, reports, critical, qc, stock, analyzers] = await Promise.all([prisma.laboratoryOrder.count({ where: orderScope }), prisma.specimen.count({ where: { ...specimenScope, status: { in: ["EXPECTED", "LABEL_PRINTED"] } } }), prisma.specimen.count({ where: { ...specimenScope, status: { in: ["COLLECTED", "IN_TRANSIT"] } } }), prisma.specimen.count({ where: { ...specimenScope, status: "RECEIVED", accessionId: null } }), prisma.laboratoryOrderItem.count({ where: { tenantId, status: { in: ["READY", "RUNNING", "RESULTED"] }, order: orderScope } }), prisma.result.count({ where: { tenantId, status: "RESULTED", orderItem: { order: orderScope } } }), prisma.result.count({ where: { tenantId, status: "TECHNICAL_REVIEW", orderItem: { order: orderScope } } }), prisma.reportVersion.count({ where: { tenantId, status: { in: ["FINAL", "CORRECTED", "AMENDED"] } } }), prisma.criticalNotification.count({ where: { tenantId, acknowledged: false } }), prisma.qcRun.count({ where: { tenantId, status: "OUT_OF_CONTROL" } }), prisma.inventoryItem.count({ where: { tenantId, currentStock: { lte: 5 } } }), prisma.analyzer.count({ where: { tenantId, status: { not: "CONNECTED" } } })]); res.json({ data: { orders, uncollected, receiving, accessioning, processing, pendingTechnicalReview: technical, pendingMedicalValidation: medical, releasedReports: reports, unacknowledgedCritical: critical, qcBlocks: qc, lowStockItems: stock, analyzerDowntime: analyzers } }); }));

export const analyticsRoutes = protectedRouter();
analyticsRoutes.get("/summary", requireAnyPermission("analytics.read", "dashboard.read"), asyncHandler(async (req, res) => { const tenantId = req.context!.tenantId; const [orderStatuses, specimenStatuses, billingStatuses] = await Promise.all([prisma.laboratoryOrder.groupBy({ by: ["status"], where: orderReadScope(req.context!), _count: { _all: true } }), prisma.specimen.groupBy({ by: ["status"], where: specimenReadScope(req.context!), _count: { _all: true } }), prisma.invoice.groupBy({ by: ["status"], where: { tenantId }, _count: { _all: true }, _sum: { amount: true } })]); res.json({ data: { orderStatuses, specimenStatuses, billingStatuses } }); }));
