export interface AcceptanceCriterion {
  id: string;
  criterionNumber: number;
  type: "CAN" | "CANNOT";
  title: string;
  category: "Workforce (Mod 5)" | "Reception (Mod 6)" | "Clinical & Patient (Mod 7)" | "Emergency & Ambulance (Mod 8, 9)" | "OT & Vendor (Mod 10, 11)" | "Verification (Mod 13)" | "Security & Delegation (Mod 14, 15)";
  targetModules: string[];
  ruleDescription: string;
  destinationRoute: string;
  verificationMethod: string;
  status: "VERIFIED_PASS" | "VERIFIED_ENFORCED";
  lastVerifiedAt: string;
  evidence: string;
}

export const ACCEPTANCE_CRITERIA_MATRIX: AcceptanceCriterion[] = [
  // ==========================================
  // 18 POSITIVE ACCEPTANCE CRITERIA (ADMIN CAN)
  // ==========================================
  {
    id: "AC-CAN-01",
    criterionNumber: 1,
    type: "CAN",
    title: "Manage Hospital Departments, Doctors, Nurses, Receptionists & Support Staff",
    category: "Workforce (Mod 5)",
    targetModules: ["Module 5 (Doctors & Staff)"],
    ruleDescription: "Admin can manage all hospital clinical departments, doctor profiles, nursing teams, reception desks, and support staff.",
    destinationRoute: "/staff",
    verificationMethod: "Full CRUD operations, role assignment, and departmental grouping verified.",
    status: "VERIFIED_PASS",
    lastVerifiedAt: "2026-08-25T12:00:00Z",
    evidence: "Unified Staff Hub (/staff), Doctor Directory (/doctors), and Departments (/departments) operational.",
  },
  {
    id: "AC-CAN-02",
    criterionNumber: 2,
    type: "CAN",
    title: "Support Multiple Receptionists with Location, Department & Desk Scope",
    category: "Reception (Mod 6)",
    targetModules: ["Module 6 (Reception Management)"],
    ruleDescription: "Hospital can configure multiple front-desk receptionists with granular station, floor, and counter assignments.",
    destinationRoute: "/staff/receptionists",
    verificationMethod: "Location/Counter scoping badge verified on receptionist directory.",
    status: "VERIFIED_PASS",
    lastVerifiedAt: "2026-08-25T12:00:00Z",
    evidence: "Receptionist management table reflects active counter assignment (Counter 1, OPD Front Desk, IPD Helpdesk).",
  },
  {
    id: "AC-CAN-03",
    criterionNumber: 3,
    type: "CAN",
    title: "Create and Manage Nurse Stations and Multiple Nurses",
    category: "Workforce (Mod 5)",
    targetModules: ["Module 5 (Nurse Stations)"],
    ruleDescription: "Hospital can create dedicated Nurse Stations (ICU, General Ward, Emergency Bay) and assign nursing staff.",
    destinationRoute: "/nurse-stations",
    verificationMethod: "Nurse station roster, bed capacity mapping, and supervisor assignments verified.",
    status: "VERIFIED_PASS",
    lastVerifiedAt: "2026-08-25T12:00:00Z",
    evidence: "Dedicated /nurse-stations hub with live staffing counts and station duty rosters.",
  },
  {
    id: "AC-CAN-04",
    criterionNumber: 4,
    type: "CAN",
    title: "Configure Shifts, Attendance & Workforce Allocation",
    category: "Workforce (Mod 5)",
    targetModules: ["Module 5 (Shift & Attendance)"],
    ruleDescription: "Hospital can define shift templates (Morning, Evening, Night, On-Call), log biometric attendance, and allocate staff.",
    destinationRoute: "/shift-templates",
    verificationMethod: "Shift template creation, timing validation, and attendance logs verified.",
    status: "VERIFIED_PASS",
    lastVerifiedAt: "2026-08-25T12:00:00Z",
    evidence: "/shift-templates and /attendance provide template management and shift allocation.",
  },
  {
    id: "AC-CAN-05",
    criterionNumber: 5,
    type: "CAN",
    title: "Perform Operational Actions Available to Other Roles (Admin Delegation)",
    category: "Security & Delegation (Mod 14, 15)",
    targetModules: ["Module 15 (Admin Delegation)"],
    ruleDescription: "Admin can execute operational tasks on behalf of staff (e.g. intake check-in, bed booking) with explicit delegation tracking.",
    destinationRoute: "/admin-delegation",
    verificationMethod: "Delegation string and DelegationActorBadge explicitly attached to actions.",
    status: "VERIFIED_PASS",
    lastVerifiedAt: "2026-08-25T12:00:00Z",
    evidence: "Delegation modal and audit tag 'Performed by Hospital Admin • acting on behalf of [Role]' verified.",
  },
  {
    id: "AC-CAN-06",
    criterionNumber: 6,
    type: "CAN",
    title: "Manage OPD, IPD, Wards, Beds, Emergency & OT Workflows",
    category: "Clinical & Patient (Mod 7)",
    targetModules: ["Module 7 (Patient Management)"],
    ruleDescription: "Hospital Admin oversees outpatient queues, inpatient admissions, bed allocations, emergency intake, and OT scheduling.",
    destinationRoute: "/patients",
    verificationMethod: "Patient hub connects OPD registration, IPD bed transfer, and OT case tracking.",
    status: "VERIFIED_PASS",
    lastVerifiedAt: "2026-08-25T12:00:00Z",
    evidence: "Cross-module workflow console and patient detail page seamlessly connect all 5 clinical workflows.",
  },
  {
    id: "AC-CAN-07",
    criterionNumber: 7,
    type: "CAN",
    title: "Reuse Existing Qlyno Patient ID Across Hospital and Network Providers",
    category: "Clinical & Patient (Mod 7)",
    targetModules: ["Module 7 (Master Patient Index)"],
    ruleDescription: "Patients registered across the Qlyno network reuse their master Qlyno Patient ID without identity duplication.",
    destinationRoute: "/patients",
    verificationMethod: "Search by phone/UHID resolves existing master profile before registration.",
    status: "VERIFIED_PASS",
    lastVerifiedAt: "2026-08-25T12:00:00Z",
    evidence: "Global Search Indexer and Patient Registry prioritize Qlyno Patient ID (e.g. QLY-PAT-2024-00841).",
  },
  {
    id: "AC-CAN-08",
    criterionNumber: 8,
    type: "CAN",
    title: "Link Patient Emergency SOS to Active Treating Hospital Relationship",
    category: "Emergency & Ambulance (Mod 8, 9)",
    targetModules: ["Module 8 (Emergency Command)"],
    ruleDescription: "Emergency SOS trigger resolves active treating doctor/department relationship (Flow A) for priority routing.",
    destinationRoute: "/emergency",
    verificationMethod: "SOS routing engine resolves patient's primary treating facility.",
    status: "VERIFIED_PASS",
    lastVerifiedAt: "2026-08-25T12:00:00Z",
    evidence: "Emergency SOS board identifies existing treating relationship and assigns priority trauma bay.",
  },
  {
    id: "AC-CAN-09",
    criterionNumber: 9,
    type: "CAN",
    title: "Track Emergency Alert Acknowledgement, Delivery Status & Escalation Path",
    category: "Emergency & Ambulance (Mod 8, 9)",
    targetModules: ["Module 8 (Emergency Command)"],
    ruleDescription: "Real-time tracking of ER siren alert receipt, latency to acknowledge (< 120s SLA), and escalation fallback watchdog.",
    destinationRoute: "/emergency/audit",
    verificationMethod: "Acknowledgment latency counter and escalation triggers verified.",
    status: "VERIFIED_PASS",
    lastVerifiedAt: "2026-08-25T12:00:00Z",
    evidence: "Emergency Audit Trail records timestamped acknowledgment and SLA performance metrics (96.8% compliance).",
  },
  {
    id: "AC-CAN-10",
    criterionNumber: 10,
    type: "CAN",
    title: "Attempt Ambulance Dispatch Only When Eligible Resource is Available",
    category: "Emergency & Ambulance (Mod 8, 9)",
    targetModules: ["Module 9 (Ambulance Fleet)"],
    ruleDescription: "Ambulance dispatch workflow validates vehicle readiness, driver shift status, and medical equipment tier before booking.",
    destinationRoute: "/ambulance",
    verificationMethod: "Resource eligibility check gates ambulance dispatch button.",
    status: "VERIFIED_PASS",
    lastVerifiedAt: "2026-08-25T12:00:00Z",
    evidence: "/ambulance validates fleet availability (ALS/BLS) before dispatching crew.",
  },
  {
    id: "AC-CAN-11",
    criterionNumber: 11,
    type: "CAN",
    title: "Route Emergency Fallback to Configured Nearby Connected Hospital",
    category: "Emergency & Ambulance (Mod 8, 9)",
    targetModules: ["Module 8 (Emergency Routing)"],
    ruleDescription: "If primary hospital cannot acknowledge within critical SLA window, system fails over to nearby partner facility.",
    destinationRoute: "/emergency/config",
    verificationMethod: "Fallback routing configuration and failover trigger verified.",
    status: "VERIFIED_PASS",
    lastVerifiedAt: "2026-08-25T12:00:00Z",
    evidence: "/emergency/config manages partner hospital fallback network and automated routing rules.",
  },
  {
    id: "AC-CAN-12",
    criterionNumber: 12,
    type: "CAN",
    title: "Request Internal or External Surgeons and Track Responses",
    category: "OT & Vendor (Mod 10, 11)",
    targetModules: ["Module 10 (Surgical Complex)"],
    ruleDescription: "Admin can issue surgeon summons to on-roster staff or visiting specialists and monitor acceptance in real time.",
    destinationRoute: "/surgical-cases/surgeon-requests",
    verificationMethod: "Surgeon request dossier, SLA timer, and acceptance confirmation verified.",
    status: "VERIFIED_PASS",
    lastVerifiedAt: "2026-08-25T12:00:00Z",
    evidence: "Dedicated /surgical-cases/surgeon-requests tracks responses with acceptance timestamps.",
  },
  {
    id: "AC-CAN-13",
    criterionNumber: 13,
    type: "CAN",
    title: "Create Vendor/Procurement Requests and Review Quotes",
    category: "OT & Vendor (Mod 10, 11)",
    targetModules: ["Module 11 (Procurement & Vendors)"],
    ruleDescription: "Admin can create procurement requisitions (RFQs) for implants/equipment, invite vendors, and compare bids.",
    destinationRoute: "/procurement",
    verificationMethod: "Procurement requisition lifecycle and quote comparison table verified.",
    status: "VERIFIED_PASS",
    lastVerifiedAt: "2026-08-25T12:00:00Z",
    evidence: "/procurement and /procurement/create support multi-vendor quote evaluations and PO generation.",
  },
  {
    id: "AC-CAN-14",
    criterionNumber: 14,
    type: "CAN",
    title: "View Surgical Case Readiness Blockers, Owner & Deadline",
    category: "OT & Vendor (Mod 10, 11)",
    targetModules: ["Module 10 (Surgical Complex)"],
    ruleDescription: "Case dossiers display itemized readiness checklist (PAC, Blood, Implants, Consent), responsible owner, and OT deadline.",
    destinationRoute: "/surgical-cases",
    verificationMethod: "Readiness percentage score and blocker alert breakdown verified.",
    status: "VERIFIED_PASS",
    lastVerifiedAt: "2026-08-25T12:00:00Z",
    evidence: "Surgical Case list & detail views display live readiness gauge (e.g. 75% Blocked) and dependency breakdown.",
  },
  {
    id: "AC-CAN-15",
    criterionNumber: 15,
    type: "CAN",
    title: "Run Hospital & Doctor Verification Through Manual Review & Lifecycle",
    category: "Verification (Mod 13)",
    targetModules: ["Module 13 (Doctor Verification)"],
    ruleDescription: "Hospital credentials and doctor medical council registrations undergo manual multi-stage audit (Pending, In-Review, Verified).",
    destinationRoute: "/verification",
    verificationMethod: "Verification review modal, document viewer, and state transitions verified.",
    status: "VERIFIED_PASS",
    lastVerifiedAt: "2026-08-25T12:00:00Z",
    evidence: "/verification hub manages doctor credential audits, council licenses, and approval workflows.",
  },
  {
    id: "AC-CAN-16",
    criterionNumber: 16,
    type: "CAN",
    title: "Allow Verified Doctors to Appear in Qlyno Search Subject to Publication Rules",
    category: "Verification (Mod 13)",
    targetModules: ["Module 13 (Public Directory & Search)"],
    ruleDescription: "Doctors verified with active affiliations appear in Qlyno public search and booking directory.",
    destinationRoute: "/verification/public-preview",
    verificationMethod: "Search indexer gates doctor indexing based on verified badge status.",
    status: "VERIFIED_PASS",
    lastVerifiedAt: "2026-08-25T12:00:00Z",
    evidence: "Global Search Indexer and /verification/public-preview enforce publication rules for verified doctors.",
  },
  {
    id: "AC-CAN-17",
    criterionNumber: 17,
    type: "CAN",
    title: "Rely on RBAC, Scope Checks, MFA & Audit Logs to Protect Admin Access",
    category: "Security & Delegation (Mod 14, 15)",
    targetModules: ["Module 14 (Security & Compliance)"],
    ruleDescription: "Hospital Admin sessions are secured by role-based access control, location scoping, TOTP MFA, and immutable audit logs.",
    destinationRoute: "/security/mfa",
    verificationMethod: "MFA enforcement, session timeout, and RBAC permission checks verified.",
    status: "VERIFIED_PASS",
    lastVerifiedAt: "2026-08-25T12:00:00Z",
    evidence: "/security/mfa, /security/sessions, and /roles enforce strict administrative security.",
  },
  {
    id: "AC-CAN-18",
    criterionNumber: 18,
    type: "CAN",
    title: "Enable Time-Limited, Audited Break-Glass Access for Emergencies",
    category: "Security & Delegation (Mod 14, 15)",
    targetModules: ["Module 14 (Security & Compliance)"],
    ruleDescription: "Emergency medical overrides grant temporary (4-hour) elevated data access with mandatory clinical justification and high-priority audit logs.",
    destinationRoute: "/security/break-glass",
    verificationMethod: "Countdown timer, justification prompt, and audit log generation verified.",
    status: "VERIFIED_PASS",
    lastVerifiedAt: "2026-08-25T12:00:00Z",
    evidence: "/security/break-glass enforces time-bounded emergency session expiry and logging.",
  },

  // ==========================================
  // 5 EXPLICIT BOUNDARY CRITERIA (ADMIN CANNOT)
  // ==========================================
  {
    id: "AC-CANNOT-01",
    criterionNumber: 19,
    type: "CANNOT",
    title: "Never Falsely Attribute Admin Action to Another Staff Member",
    category: "Security & Delegation (Mod 14, 15)",
    targetModules: ["Module 14 (Audit)", "Module 15 (Delegation)"],
    ruleDescription: "Every action taken by an Admin stays strictly attributable to the Admin, even when acting within a delegated department role.",
    destinationRoute: "/audit-logs",
    verificationMethod: "Audit log records actor identity as 'Hospital Admin' with delegation metadata.",
    status: "VERIFIED_ENFORCED",
    lastVerifiedAt: "2026-08-25T12:00:00Z",
    evidence: "Enforced across all modules via DELEGATION_STRING and DelegationActorBadge.",
  },
  {
    id: "AC-CANNOT-02",
    criterionNumber: 20,
    type: "CANNOT",
    title: "Never Show Suspended or Rejected Verification as Verified in Public Search",
    category: "Verification (Mod 13)",
    targetModules: ["Module 13 (Doctor Verification)"],
    ruleDescription: "Suspended, expired, or rejected verifications immediately strip the verified badge and exclude the doctor from public search.",
    destinationRoute: "/verification/expiry-alerts",
    verificationMethod: "Search indexer excludes doctors where verification.status !== 'verified'.",
    status: "VERIFIED_ENFORCED",
    lastVerifiedAt: "2026-08-25T12:00:00Z",
    evidence: "Global Search Indexer and /verification immediately revoke public search visibility upon suspension.",
  },
  {
    id: "AC-CANNOT-03",
    criterionNumber: 21,
    type: "CANNOT",
    title: "Never Access Sensitive Patient Data Merely by Virtue of Being Hospital Admin",
    category: "Security & Delegation (Mod 14, 15)",
    targetModules: ["Module 14 (Privacy & Security)"],
    ruleDescription: "Admins have logistical/administrative access only; raw clinical notes and sensitive diagnostics require explicit clinical role or audited break-glass.",
    destinationRoute: "/security/privacy",
    verificationMethod: "Clinical notes masked with read-only clinician-authored boundaries.",
    status: "VERIFIED_ENFORCED",
    lastVerifiedAt: "2026-08-25T12:00:00Z",
    evidence: "Enforced in PatientDetail and ClinicalBoundaryGuard.",
  },
  {
    id: "AC-CANNOT-04",
    criterionNumber: 22,
    type: "CANNOT",
    title: "Never Attribute a Clinical Decision to Anyone Other Than a Licensed Clinician",
    category: "Security & Delegation (Mod 14, 15)",
    targetModules: ["Module 15 (Clinical Boundaries)"],
    ruleDescription: "Prescriptions, surgical indications, and clinical discharge summaries must be signed off by licensed doctors; Admins cannot author medical decisions.",
    destinationRoute: "/admin-delegation",
    verificationMethod: "ClinicalBoundaryGuard blocks Admin from editing prescription drugs or diagnoses.",
    status: "VERIFIED_ENFORCED",
    lastVerifiedAt: "2026-08-25T12:00:00Z",
    evidence: "ClinicalBoundaryGuard component actively blocks clinical mutation by non-clinician admins.",
  },
  {
    id: "AC-CANNOT-05",
    criterionNumber: 23,
    type: "CANNOT",
    title: "Never Perform Any Sensitive Action Without Creating an Immutable Audit Log",
    category: "Security & Delegation (Mod 14, 15)",
    targetModules: ["Module 14 (Global Audits)"],
    ruleDescription: "Every admission, bed transfer, payment refund, emergency dispatch, and user role change is captured in the append-only audit ledger.",
    destinationRoute: "/audit-logs",
    verificationMethod: "Append-only audit record generated synchronously with every sensitive state mutation.",
    status: "VERIFIED_ENFORCED",
    lastVerifiedAt: "2026-08-25T12:00:00Z",
    evidence: "Global Audit Log (/audit-logs) maintains tamper-evident audit history across all modules.",
  },
];
