import { z } from "zod";
import { prisma } from "../../db/prisma";
import { protectedRouter } from "../../middleware/protected";
import { rejectAuditorWrites, requirePermission } from "../../middleware/authorize";
import { validate } from "../../middleware/validate";
import { asyncHandler } from "../../utils/async-handler";
import { AppError, notFound } from "../../utils/errors";
import { specimenReadScope } from "../../services/scope";

const create = z.object({ route: z.string().min(2).max(200), courierName: z.string().min(2).max(120), temperature: z.string().min(1).max(80), specimenIds: z.array(z.string().min(1)).min(1).max(500) }).strict();
const id = z.object({ id: z.string().min(1).max(100) }).strict();
export const logisticsRoutes = protectedRouter();
logisticsRoutes.get("/manifests", requirePermission("logistics.read"), asyncHandler(async (req, res) => { res.json({ data: await prisma.manifest.findMany({ where: { tenantId: req.context!.tenantId }, include: { specimens: { include: { specimen: { include: { patient: true, order: true } } } } }, orderBy: { createdAt: "desc" } }) }); }));
logisticsRoutes.get("/routes", requirePermission("logistics.read"), asyncHandler(async (req, res) => { const rows = await prisma.manifest.groupBy({ by: ["route", "status"], where: { tenantId: req.context!.tenantId }, _count: { _all: true }, _max: { createdAt: true } }); const byRoute = new Map<string, { route: string; manifests: number; statuses: Record<string, number>; lastActivityAt: Date | null }>(); for (const row of rows) { const current = byRoute.get(row.route) ?? { route: row.route, manifests: 0, statuses: {}, lastActivityAt: null }; current.manifests += row._count._all; current.statuses[row.status] = row._count._all; if (!current.lastActivityAt || (row._max.createdAt && row._max.createdAt > current.lastActivityAt)) current.lastActivityAt = row._max.createdAt; byRoute.set(row.route, current); } res.json({ data: [...byRoute.values()] }); }));
logisticsRoutes.get("/send-outs", requirePermission("logistics.read"), asyncHandler(async (req, res) => { res.json({ data: await prisma.manifest.findMany({ where: { tenantId: req.context!.tenantId, route: { contains: "reference", mode: "insensitive" } }, include: { specimens: { include: { specimen: { include: { patient: true, order: true } } } } }, orderBy: { createdAt: "desc" } }) }); }));
logisticsRoutes.get("/reference-labs", requirePermission("logistics.read"), asyncHandler(async (req, res) => { res.json({ data: await prisma.clientOrganization.findMany({ where: { tenantId: req.context!.tenantId, type: { in: ["reference_lab", "client_lab"] } }, orderBy: { name: "asc" } }) }); }));
logisticsRoutes.get("/manifests/:id", requirePermission("logistics.read"), validate({ params: id }), asyncHandler(async (req, res) => { const data = await prisma.manifest.findFirst({ where: { id: String(req.params.id), tenantId: req.context!.tenantId }, include: { specimens: { include: { specimen: { include: { patient: true, order: true, containerType: true } } } } } }); if (!data) throw notFound("Manifest"); res.json({ data }); }));
logisticsRoutes.post("/manifests", rejectAuditorWrites, requirePermission("logistics.write"), validate({ body: create }), asyncHandler(async (req, res) => { const specimens = await prisma.specimen.findMany({ where: { ...specimenReadScope(req.context!), id: { in: req.body.specimenIds }, status: "COLLECTED" } }); if (specimens.length !== new Set(req.body.specimenIds).size) throw new AppError(400, "Every specimen must be collected and within scope", "INVALID_SPECIMEN"); const data = await prisma.$transaction(async (tx) => { const manifest = await tx.manifest.create({ data: { tenantId: req.context!.tenantId, route: req.body.route, courierName: req.body.courierName, temperature: req.body.temperature, status: "IN_TRANSIT", specimens: { create: specimens.map((item) => ({ tenantId: req.context!.tenantId, specimenId: item.id })) } } }); await tx.specimen.updateMany({ where: { id: { in: specimens.map((item) => item.id) }, tenantId: req.context!.tenantId }, data: { status: "IN_TRANSIT" } }); return manifest; }); res.status(201).json({ data }); }));
logisticsRoutes.post("/manifests/:id/status", rejectAuditorWrites, requirePermission("logistics.write"), validate({ params: id, body: z.object({ status: z.enum(["SEALED", "IN_TRANSIT", "DELIVERED", "DELAYED", "LOST", "DAMAGED"]) }).strict() }), asyncHandler(async (req, res) => { const row = await prisma.manifest.findFirst({ where: { id: String(req.params.id), tenantId: req.context!.tenantId } }); if (!row) throw notFound("Manifest"); const data = await prisma.manifest.update({ where: { id: row.id }, data: { status: req.body.status } }); res.json({ data }); }));
