import { z } from "zod";
import { prisma } from "../../db/prisma";
import { protectedRouter } from "../../middleware/protected";
import { rejectAuditorWrites, requireAnyPermission, requirePermission } from "../../middleware/authorize";
import { validate } from "../../middleware/validate";
import { asyncHandler } from "../../utils/async-handler";
import { AppError, notFound } from "../../utils/errors";
import { requireSite, specimenReadScope } from "../../services/scope";
import { appendLifecycleEvent, getOrderLifecycle } from "../../services/lifecycle";
import { audit } from "../../services/audit";

const idParams = z.object({ id: z.string().min(1).max(100) }).strict();
const targetQuery = z.object({ orderId: z.string().optional(), specimenId: z.string().optional(), status: z.enum(["EXPECTED", "LABEL_PRINTED", "COLLECTED", "IN_TRANSIT", "RECEIVED", "ACCESSIONED", "ACCEPTED", "REJECTED", "ALIQUOTED", "STORED", "DISPOSED"]).optional() }).strict();
const collectionBody = z.object({ specimenIds: z.array(z.string().min(1)).min(1), identification: z.object({ patientAndMrn: z.literal(true), dateOfBirthOrMrn: z.literal(true), requisition: z.literal(true), containersAndLabels: z.literal(true) }).strict(), notes: z.string().max(2000).optional(), containers: z.array(z.object({ specimenId: z.string(), quantity: z.number().positive(), unit: z.string().min(1).max(30) }).strict()).min(1) }).strict();
const receiptBody = z.object({ specimenId: z.string().min(1), condition: z.string().min(1).max(100), sealStatus: z.string().min(1).max(100), temperature: z.string().min(1).max(100), notes: z.string().max(2000).optional(), verification: z.object({ patientAndMrn: z.literal(true), orderAndRequisition: z.literal(true), containerAndLabel: z.literal(true), sealIntact: z.literal(true), collectionTimeAcceptable: z.literal(true) }).strict() }).strict();
const accessionBody = z.object({ specimenId: z.string().min(1), action: z.enum(["ACCEPT", "PARTIAL_ACCEPT", "REJECT"]), reason: z.string().max(1000).optional() }).strict().superRefine((value, ctx) => { if (value.action === "REJECT" && !value.reason?.trim()) ctx.addIssue({ code: "custom", path: ["reason"], message: "Rejection reason is required" }); });

export const collectionRoutes = protectedRouter();
collectionRoutes.get("/tasks", requireAnyPermission("specimens.read", "collection.confirm"), validate({ query: targetQuery }), asyncHandler(async (req, res) => {
  const query = targetQuery.parse(req.query); const context = req.context!;
  const data = await prisma.collectionTask.findMany({ where: { tenantId: context.tenantId, siteId: { in: context.roles.some((r) => ["tenant_admin", "auditor", "lab_director", "quality_manager"].includes(r)) ? undefined : context.siteIds }, status: { in: ["PENDING", "PARTIAL"] }, ...(query.orderId ? { orderId: query.orderId } : {}), ...(query.specimenId ? { specimens: { some: { specimenId: query.specimenId } } } : {}) }, include: { order: { include: { patient: true, items: { include: { test: true } } } }, specimens: { include: { specimen: { include: { containerType: true } } } } }, orderBy: [{ priority: "desc" }, { scheduledAt: "asc" }] });
  if (query.orderId && query.specimenId && data.length === 0) throw new AppError(409, `Collection task missing for ${query.orderId} / ${query.specimenId}`, "COLLECTION_TASK_MISSING"); res.json({ data });
}));
collectionRoutes.post("/tasks/:id/confirm", rejectAuditorWrites, requirePermission("collection.confirm"), validate({ params: idParams, body: collectionBody }), asyncHandler(async (req, res) => {
  const context = req.context!; const task = await prisma.collectionTask.findFirst({ where: { id: String(req.params.id), tenantId: context.tenantId, siteId: { in: context.siteIds } }, include: { specimens: { include: { specimen: true } } } }); if (!task) throw notFound("Collection task");
  const allowed = new Set(task.specimens.filter((link) => ["EXPECTED", "LABEL_PRINTED"].includes(link.specimen.status)).map((link) => link.specimenId)); if (req.body.specimenIds.some((id: string) => !allowed.has(id))) throw new AppError(400, "A selected specimen is not pending on this collection task", "INVALID_SPECIMEN");
  const containerMap = new Map<string, { specimenId: string; quantity: number; unit: string }>(req.body.containers.map((item: { specimenId: string; quantity: number; unit: string }) => [item.specimenId, item])); if (req.body.specimenIds.some((id: string) => !containerMap.has(id))) throw new AppError(400, "Every selected container requires a positive quantity", "CONTAINER_VALIDATION_FAILED");
  const now = new Date(); await prisma.$transaction(async (tx) => { for (const specimenId of req.body.specimenIds as string[]) { const container = containerMap.get(specimenId)!; await tx.specimen.update({ where: { id: specimenId }, data: { status: "COLLECTED", collectedAt: now, collectedById: context.userId, collectionCondition: req.body.notes } }); await tx.collectionTaskSpecimen.update({ where: { collectionTaskId_specimenId: { collectionTaskId: task.id, specimenId } }, data: { quantity: container.quantity } }); await appendLifecycleEvent(tx, { tenantId: context.tenantId, orderId: task.orderId, specimenId, type: "SPECIMEN_COLLECTED", actorUserId: context.userId, actorName: "Authorized collector", metadata: { quantity: container.quantity, unit: container.unit, notes: req.body.notes ?? null } }); } const outstanding = task.specimens.filter((link) => !req.body.specimenIds.includes(link.specimenId) && ["EXPECTED", "LABEL_PRINTED"].includes(link.specimen.status)).length; await tx.collectionTask.update({ where: { id: task.id }, data: { status: outstanding === 0 ? "COMPLETED" : "PARTIAL", collectedAt: outstanding === 0 ? now : undefined, assignedUserId: context.userId } }); });
  await audit(req, "CollectionTask", task.id, "COLLECTION_CONFIRMED", { status: task.status }, { specimenIds: req.body.specimenIds }); res.json({ data: { taskId: task.id }, lifecycle: await getOrderLifecycle(prisma, context.tenantId, task.orderId), next: `/api/collection/receiving?orderId=${encodeURIComponent(task.orderId)}&specimenId=${encodeURIComponent(req.body.specimenIds[0])}` });
}));
collectionRoutes.get("/receiving", requireAnyPermission("specimens.read", "specimen.receive"), validate({ query: targetQuery }), asyncHandler(async (req, res) => { const query = targetQuery.parse(req.query); const where = specimenReadScope(req.context!); const data = await prisma.specimen.findMany({ where: { ...where, status: { in: ["COLLECTED", "IN_TRANSIT"] }, ...(query.orderId ? { orderId: query.orderId } : {}), ...(query.specimenId ? { id: query.specimenId } : {}) }, include: { patient: true, order: true, containerType: true }, orderBy: { collectedAt: "asc" } }); if (query.orderId && query.specimenId && data.length === 0) throw new AppError(409, `Receiving specimen missing for ${query.orderId} / ${query.specimenId}`, "RECEIVING_SPECIMEN_MISSING"); res.json({ data }); }));
collectionRoutes.post("/receiving/confirm", rejectAuditorWrites, requirePermission("specimen.receive"), validate({ body: receiptBody }), asyncHandler(async (req, res) => { const context = req.context!; const specimen = await prisma.specimen.findFirst({ where: { id: req.body.specimenId, ...specimenReadScope(context), status: { in: ["COLLECTED", "IN_TRANSIT"] } } }); if (!specimen) throw notFound("Pending receiving specimen"); requireSite(context, specimen.siteId); const now = new Date(); await prisma.$transaction(async (tx) => { await tx.specimen.update({ where: { id: specimen.id }, data: { status: "RECEIVED", receivedAt: now, receivedById: context.userId, receivedSiteId: specimen.siteId, collectionCondition: req.body.condition, sealStatus: req.body.sealStatus, temperature: req.body.temperature, receiptNotes: req.body.notes } }); await appendLifecycleEvent(tx, { tenantId: context.tenantId, orderId: specimen.orderId, specimenId: specimen.id, type: "SPECIMEN_RECEIVED", actorUserId: context.userId, actorName: "Authorized receiver", metadata: { siteId: specimen.siteId, condition: req.body.condition, sealStatus: req.body.sealStatus, temperature: req.body.temperature } }); }); await audit(req, "Specimen", specimen.id, "SPECIMEN_RECEIVED", { status: specimen.status }, { status: "RECEIVED" }); res.json({ data: { specimenId: specimen.id, status: "RECEIVED" }, lifecycle: await getOrderLifecycle(prisma, context.tenantId, specimen.orderId), next: `/api/accessioning?orderId=${encodeURIComponent(specimen.orderId)}&specimenId=${encodeURIComponent(specimen.id)}` }); }));

export const accessioningRoutes = protectedRouter();
accessioningRoutes.get("/", requireAnyPermission("specimens.read", "specimen.accession"), validate({ query: targetQuery }), asyncHandler(async (req, res) => { const query = targetQuery.parse(req.query); const data = await prisma.specimen.findMany({ where: { ...specimenReadScope(req.context!), status: "RECEIVED", accessionId: null, ...(query.orderId ? { orderId: query.orderId } : {}), ...(query.specimenId ? { id: query.specimenId } : {}) }, include: { patient: true, order: true, containerType: true, orderItemLinks: { include: { orderItem: { include: { test: true } } } } }, orderBy: { receivedAt: "asc" } }); if (query.orderId && query.specimenId && data.length === 0) throw new AppError(409, `Accessioning target missing for ${query.orderId} / ${query.specimenId}`, "ACCESSION_TARGET_MISSING"); res.json({ data }); }));
accessioningRoutes.post("/resolve", rejectAuditorWrites, requirePermission("specimen.accession"), validate({ body: accessionBody }), asyncHandler(async (req, res) => {
  const context = req.context!; const specimen = await prisma.specimen.findFirst({ where: { id: req.body.specimenId, ...specimenReadScope(context), status: "RECEIVED", accessionId: null }, include: { orderItemLinks: { include: { orderItem: { include: { test: true } } } }, containerType: true, order: true } }); if (!specimen) throw notFound("Accessioning specimen"); requireSite(context, specimen.siteId); const action = req.body.action as "ACCEPT" | "PARTIAL_ACCEPT" | "REJECT";
  const output = await prisma.$transaction(async (tx) => { if (action === "REJECT") { await tx.specimen.update({ where: { id: specimen.id }, data: { status: "REJECTED", rejectedReason: req.body.reason, rejectedAt: new Date(), rejectedById: context.userId } }); const replacement = await tx.specimen.create({ data: { tenantId: context.tenantId, siteId: specimen.siteId, orderId: specimen.orderId, patientId: specimen.patientId, containerTypeId: specimen.containerTypeId, type: specimen.type, status: "EXPECTED", recollectionOfId: specimen.id } }); const task = await tx.collectionTask.create({ data: { tenantId: context.tenantId, siteId: specimen.siteId, orderId: specimen.orderId, encounterId: specimen.order.encounterId, location: "Recollection", priority: specimen.order.priority, scheduledAt: new Date(), status: "PENDING", specimens: { create: { tenantId: context.tenantId, specimenId: replacement.id, requiredContainer: specimen.containerType?.type ?? specimen.type } } } }); for (const link of specimen.orderItemLinks) await tx.orderItemSpecimen.create({ data: { tenantId: context.tenantId, orderItemId: link.orderItemId, specimenId: replacement.id } }); await appendLifecycleEvent(tx, { tenantId: context.tenantId, orderId: specimen.orderId, specimenId: specimen.id, type: "SPECIMEN_REJECTED", actorUserId: context.userId, actorName: "Accessioning user", reason: req.body.reason, metadata: { recollectionSpecimenId: replacement.id, collectionTaskId: task.id } }); return { specimenId: specimen.id, status: "REJECTED", recollectionSpecimenId: replacement.id }; }
    const accessionId = `ACC-${new Date().getUTCFullYear()}-${specimen.id.slice(-8).toUpperCase()}`; await tx.specimen.update({ where: { id: specimen.id }, data: { status: action === "PARTIAL_ACCEPT" ? "ACCESSIONED" : "ACCEPTED", accessionId } }); await appendLifecycleEvent(tx, { tenantId: context.tenantId, orderId: specimen.orderId, specimenId: specimen.id, type: "ACCESSION_CREATED", actorUserId: context.userId, actorName: "Accessioning user", metadata: { accessionId, disposition: action } }); await appendLifecycleEvent(tx, { tenantId: context.tenantId, orderId: specimen.orderId, specimenId: specimen.id, type: action === "PARTIAL_ACCEPT" ? "SPECIMEN_PARTIALLY_ACCEPTED" : "SPECIMEN_ACCEPTED", actorUserId: context.userId, actorName: "Accessioning user" }); for (const link of specimen.orderItemLinks) await tx.workItem.upsert({ where: { id: `WI-${link.orderItemId}` }, create: { id: `WI-${link.orderItemId}`, tenantId: context.tenantId, orderItemId: link.orderItemId, departmentId: link.orderItem.departmentId, label: link.orderItem.test.name, priority: specimen.order.priority, status: "READY" }, update: { status: "READY" } }); return { specimenId: specimen.id, status: action === "PARTIAL_ACCEPT" ? "ACCESSIONED" : "ACCEPTED", accessionId }; });
  await audit(req, "Specimen", specimen.id, action === "REJECT" ? "SPECIMEN_REJECTED" : "SPECIMEN_ACCEPTED", { status: specimen.status }, output); res.json({ data: output, lifecycle: await getOrderLifecycle(prisma, context.tenantId, specimen.orderId), next: action === "REJECT" ? "/api/collection/tasks" : "/api/workbench" });
}));

export const specimenRoutes = protectedRouter();
specimenRoutes.get("/", requireAnyPermission("specimens.read", "orders.read.own", "orders.read.client"), validate({ query: targetQuery }), asyncHandler(async (req, res) => { const query = targetQuery.parse(req.query); res.json({ data: await prisma.specimen.findMany({ where: { ...specimenReadScope(req.context!), ...(query.status ? { status: query.status } : {}), ...(query.orderId ? { orderId: query.orderId } : {}), ...(query.specimenId ? { id: query.specimenId } : {}) }, include: { patient: true, order: true, containerType: true }, orderBy: { createdAt: "desc" } }) }); }));
specimenRoutes.post("/:id/aliquots", rejectAuditorWrites, requirePermission("specimen.accession"), validate({ params: idParams, body: z.object({ type: z.string().min(1), volume: z.number().positive().optional(), unit: z.string().max(30).optional() }).strict() }), asyncHandler(async (req, res) => { const parent = await prisma.specimen.findFirst({ where: { id: String(req.params.id), ...specimenReadScope(req.context!), status: { in: ["ACCESSIONED", "ACCEPTED", "ALIQUOTED"] } } }); if (!parent) throw notFound("Accessioned specimen"); const data = await prisma.$transaction(async (tx) => { const aliquot = await tx.aliquot.create({ data: { tenantId: req.context!.tenantId, parentSpecimenId: parent.id, type: req.body.type, volume: req.body.volume, unit: req.body.unit, status: "ALIQUOTED" } }); await tx.specimen.update({ where: { id: parent.id }, data: { status: "ALIQUOTED" } }); await appendLifecycleEvent(tx, { tenantId: req.context!.tenantId, orderId: parent.orderId, specimenId: parent.id, type: "ALIQUOT_CREATED", actorUserId: req.context!.userId, actorName: "Accessioning user", metadata: { aliquotId: aliquot.id, volume: req.body.volume ?? null, unit: req.body.unit ?? null } }); return aliquot; }); res.status(201).json({ data }); }));
specimenRoutes.get("/:id", requireAnyPermission("specimens.read", "orders.read.own", "orders.read.client"), validate({ params: idParams }), asyncHandler(async (req, res) => { const data = await prisma.specimen.findFirst({ where: { id: String(req.params.id), ...specimenReadScope(req.context!) }, include: { patient: true, order: true, containerType: true, aliquots: true, collectionTaskLinks: { include: { collectionTask: true } }, orderItemLinks: { include: { orderItem: { include: { test: true, results: true } } } } } }); if (!data) throw notFound("Specimen"); const events = await prisma.auditEvent.findMany({ where: { tenantId: req.context!.tenantId, entity: "LaboratoryLifecycle", entityId: data.orderId }, orderBy: { timestamp: "asc" } }); res.json({ data, lifecycle: await getOrderLifecycle(prisma, req.context!.tenantId, data.orderId), events }); }));
