"use client";

import { useMemo, useState } from "react";
import clsx from "clsx";
import { CheckCircle2, ClipboardCheck, Clock3, Siren } from "lucide-react";
import { DoctorTaskCard, WorkplaceBadge } from "@/components/doctor-workflow";
import { Card, EmptyState, Pill, SectionHeading, CardGridSkeleton, SectionSkeleton, Skeleton } from "@/components/ui";
import { useDoctorWorkflow } from "@/lib/doctor-workflow-context";

const tabs = ["all", "urgent", "today", "upcoming", "completed"] as const;
type TaskTab = (typeof tabs)[number];

export default function DoctorTasksPage() {
  const { completeTask, doctorTasks, getWorkplace, isLoadingWorkflow, startTask, workplaces } = useDoctorWorkflow();
  const [tab, setTab] = useState<TaskTab>("all");
  const [workplaceId, setWorkplaceId] = useState("all");

  const visibleTasks = useMemo(
    () =>
      doctorTasks
        .filter((task) => tab === "all" || task.status === tab)
        .filter((task) => workplaceId === "all" || task.workplaceId === workplaceId),
    [doctorTasks, tab, workplaceId]
  );
  const urgentCount = doctorTasks.filter((task) => task.status === "urgent").length;
  const todayCount = doctorTasks.filter((task) => task.status === "today").length;
  const activeWorkplace = workplaceId === "all" ? undefined : getWorkplace(workplaceId);

  if (isLoadingWorkflow) {
    return (
      <div className="space-y-6">
        <SectionSkeleton />
        <div className="grid grid-cols-1 gap-3 md:grid-cols-4">
          {Array.from({ length: 4 }).map((_, index) => (
            <Card key={index} className="!p-4">
              <Skeleton className="h-5 w-5" />
              <Skeleton className="mt-3 h-4 w-24" />
              <Skeleton className="mt-2 h-8 w-12" />
            </Card>
          ))}
        </div>
        <CardGridSkeleton cards={4} />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <SectionHeading
        eyebrow="14 - Tasks"
        title="Tasks"
        description="Track doctor work generated by lab reports, follow-ups, hospital duty, discharge review and online consultations."
        action={
          <select value={workplaceId} onChange={(event) => setWorkplaceId(event.target.value)} className="input-field h-10 w-64">
            <option value="all">All workplaces</option>
            {workplaces.map((workplace) => (
              <option key={workplace.id} value={workplace.id}>
                {workplace.name} {workplace.location ? `- ${workplace.location}` : ""}
              </option>
            ))}
          </select>
        }
      />

      {activeWorkplace && <WorkplaceBadge workplace={activeWorkplace} />}

      <div className="grid grid-cols-1 gap-3 md:grid-cols-4">
        <Card className="!p-4 border-alert-100 bg-alert-50">
          <Siren size={18} className="text-alert-500" />
          <p className="mt-3 text-sm font-semibold text-ink">Urgent</p>
          <p className="mt-1 font-mono text-2xl text-alert-500">{urgentCount}</p>
        </Card>
        <Card className="!p-4">
          <Clock3 size={18} className="text-clay-600" />
          <p className="mt-3 text-sm font-semibold text-ink">Today</p>
          <p className="mt-1 font-mono text-2xl text-ink">{todayCount}</p>
        </Card>
        <Card className="!p-4">
          <ClipboardCheck size={18} className="text-brand-700" />
          <p className="mt-3 text-sm font-semibold text-ink">Open work</p>
          <p className="mt-1 font-mono text-2xl text-ink">{doctorTasks.filter((task) => task.status !== "completed").length}</p>
        </Card>
        <Card className="!p-4">
          <CheckCircle2 size={18} className="text-sage-500" />
          <p className="mt-3 text-sm font-semibold text-ink">Completed</p>
          <p className="mt-1 font-mono text-2xl text-ink">{doctorTasks.filter((task) => task.status === "completed").length}</p>
        </Card>
      </div>

      <Card padded={false}>
        <div className="flex flex-col gap-3 border-b border-line px-5 py-4 lg:flex-row lg:items-center lg:justify-between">
          <div>
            <p className="eyebrow">Work board</p>
            <h2 className="font-display text-xl text-ink">My Doctor Tasks</h2>
          </div>
          <div className="flex flex-wrap gap-2">
            {tabs.map((item) => (
              <button
                key={item}
                type="button"
                onClick={() => setTab(item)}
                className={clsx("rounded-md px-3 py-2 text-xs font-semibold capitalize", tab === item ? "bg-brand-500 text-white" : "bg-paper text-ink-soft")}
              >
                {item}
              </button>
            ))}
          </div>
        </div>
        {visibleTasks.length > 0 ? (
          <div className="grid grid-cols-1 gap-4 p-5 xl:grid-cols-2">
            {visibleTasks.map((task) => (
              <DoctorTaskCard
                key={task.id}
                task={task}
                workplace={getWorkplace(task.workplaceId)}
                onStart={() => startTask(task.id)}
                onComplete={() => completeTask(task.id)}
              />
            ))}
          </div>
        ) : (
          <EmptyState title="No tasks here" description="Try another status or workplace filter." action={<Pill tone="sage">Caught up</Pill>} />
        )}
      </Card>
    </div>
  );
}
