import { z } from "zod";
import { prisma } from "../../db/prisma";
import { protectedRouter } from "../../middleware/protected";
import { rejectAuditorWrites, requireAnyPermission } from "../../middleware/authorize";
import { validate } from "../../middleware/validate";
import { asyncHandler } from "../../utils/async-handler";
import { AppError, notFound } from "../../utils/errors";
import { orderReadScope, requireSite } from "../../services/scope";
import { resolveBillingAuthority } from "../../utils/billing-authority";
import { appendLifecycleEvent, getOrderLifecycle } from "../../services/lifecycle";
import { audit } from "../../services/audit";

const idParams = z.object({ id: z.string().min(1).max(100) }).strict();
const listQuery = z.object({ search: z.string().max(120).optional(), status: z.enum(["DRAFT", "PLACED", "ACCEPTED", "COLLECTED", "IN_PROGRESS", "PARTIALLY_COMPLETED", "COMPLETED", "ON_HOLD", "CANCELLED"]).optional(), take: z.coerce.number().int().min(1).max(100).default(25) }).strict();
const createOrder = z.object({ siteId: z.string().min(1), patientId: z.string().min(1), encounterId: z.string().optional(), clientOrganizationId: z.string().optional(), practitionerId: z.string().optional(), source: z.enum(["HOSPITAL_ENCOUNTER", "WALK_IN", "HOME_COLLECTION", "B2B_CLIENT", "INTERNAL_NO_CHARGE"]), priority: z.enum(["ROUTINE", "URGENT", "STAT"]), orderingDoctor: z.string().min(2).max(180), collectionLocation: z.string().min(2).max(180), scheduledAt: z.coerce.date().optional(), testIds: z.array(z.string().min(1)).min(1).max(100) }).strict();
const updateOrder = z.object({ priority: z.enum(["ROUTINE", "URGENT", "STAT"]).optional(), status: z.enum(["ON_HOLD", "CANCELLED"]).optional() }).strict().refine((value) => Object.keys(value).length > 0);

export const orderRoutes = protectedRouter();
orderRoutes.get("/", requireAnyPermission("orders.read", "orders.read.own", "orders.read.client"), validate({ query: listQuery }), asyncHandler(async (req, res) => { const query = listQuery.parse(req.query); const data = await prisma.laboratoryOrder.findMany({ where: { ...orderReadScope(req.context!), ...(query.status ? { status: query.status } : {}), ...(query.search ? { OR: [{ id: { contains: query.search, mode: "insensitive" } }, { patient: { name: { contains: query.search, mode: "insensitive" } } }] } : {}) }, include: { patient: true, site: true, items: { include: { test: true } }, specimens: true }, orderBy: { placedAt: "desc" }, take: query.take }); res.json({ data }); }));
orderRoutes.get("/:id", requireAnyPermission("orders.read", "orders.read.own", "orders.read.client"), validate({ params: idParams }), asyncHandler(async (req, res) => { const orderId = String(req.params.id); const data = await prisma.laboratoryOrder.findFirst({ where: { id: orderId, ...orderReadScope(req.context!) }, include: { patient: true, encounter: true, site: true, practitioner: true, clientOrganization: true, items: { include: { test: true, results: { include: { revisions: true } }, specimenLinks: { include: { specimen: true } } } }, specimens: { include: { containerType: true } }, collectionTasks: { include: { specimens: { include: { specimen: true } } } }, chargeLines: true, hmsPostings: true, invoices: { include: { lines: true, payments: true } }, reports: { include: { versions: { orderBy: { version: "desc" } } } } } }); if (!data) throw notFound("Order"); res.json({ data, lifecycle: await getOrderLifecycle(prisma, req.context!.tenantId, orderId) }); }));

orderRoutes.post("/", rejectAuditorWrites, requireAnyPermission("orders.write", "orders.write.client"), validate({ body: createOrder }), asyncHandler(async (req, res) => {
  const context = req.context!; requireSite(context, req.body.siteId);
  if (context.roles.includes("client_lab_user") && req.body.clientOrganizationId !== context.clientOrganizationId) throw new AppError(403, "Insufficient permissions", "FORBIDDEN");
  const [tenant, patient, site, tests, encounter, client, practitioner] = await Promise.all([prisma.tenant.findUnique({ where: { id: context.tenantId } }), prisma.patient.findFirst({ where: { id: req.body.patientId, tenantId: context.tenantId } }), prisma.site.findFirst({ where: { id: req.body.siteId, tenantId: context.tenantId } }), prisma.testCatalogItem.findMany({ where: { id: { in: req.body.testIds }, tenantId: context.tenantId, status: "ACTIVE" } }), req.body.encounterId ? prisma.encounter.findFirst({ where: { id: req.body.encounterId, tenantId: context.tenantId, patientId: req.body.patientId } }) : null, req.body.clientOrganizationId ? prisma.clientOrganization.findFirst({ where: { id: req.body.clientOrganizationId, tenantId: context.tenantId } }) : null, (req.body.practitionerId ?? context.practitionerId) ? prisma.practitioner.findFirst({ where: { id: req.body.practitionerId ?? context.practitionerId, tenantId: context.tenantId } }) : null]);
  if (!tenant || !patient || !site || tests.length !== new Set(req.body.testIds).size || (req.body.encounterId && !encounter) || (req.body.clientOrganizationId && !client) || ((req.body.practitionerId ?? context.practitionerId) && !practitioner)) throw new AppError(400, "Patient, site, encounter, client, practitioner or tests are outside the active tenant", "INVALID_REFERENCE");
  if (req.body.source === "HOSPITAL_ENCOUNTER" && !encounter) throw new AppError(400, "Hospital encounter orders require a matching encounter", "INVALID_REFERENCE");
  if (req.body.source === "B2B_CLIENT" && !client) throw new AppError(400, "B2B orders require a client organization", "INVALID_REFERENCE");
  const authority = resolveBillingAuthority(tenant.mode, req.body.source);
  const result = await prisma.$transaction(async (tx) => {
    const order = await tx.laboratoryOrder.create({ data: { tenantId: context.tenantId, siteId: req.body.siteId, patientId: req.body.patientId, encounterId: req.body.encounterId, clientOrganizationId: req.body.clientOrganizationId, practitionerId: req.body.practitionerId ?? context.practitionerId, source: req.body.source, billingAuthority: authority, priority: req.body.priority, status: "PLACED", orderingDoctor: req.body.orderingDoctor } });
    const containerGroups = new Map<string, typeof tests>(); for (const test of tests) containerGroups.set(`${test.specimenType}|${test.containerName}`, [...(containerGroups.get(`${test.specimenType}|${test.containerName}`) ?? []), test]);
    const task = await tx.collectionTask.create({ data: { tenantId: context.tenantId, siteId: req.body.siteId, orderId: order.id, encounterId: req.body.encounterId, location: req.body.collectionLocation, priority: req.body.priority, scheduledAt: req.body.scheduledAt ?? new Date(), status: "PENDING" } });
    for (const groupedTests of containerGroups.values()) { const first = groupedTests[0]!; const container = await tx.containerType.upsert({ where: { tenantId_code: { tenantId: context.tenantId, code: first.containerName.toUpperCase().replace(/[^A-Z0-9]+/g, "_") } }, create: { tenantId: context.tenantId, code: first.containerName.toUpperCase().replace(/[^A-Z0-9]+/g, "_"), type: first.containerName, color: "Mapped" }, update: {} }); const specimen = await tx.specimen.create({ data: { tenantId: context.tenantId, siteId: req.body.siteId, orderId: order.id, patientId: patient.id, containerTypeId: container.id, type: first.specimenType, status: "EXPECTED", collectionTaskLinks: { create: { tenantId: context.tenantId, collectionTaskId: task.id, requiredContainer: first.containerName } } } }); for (const test of groupedTests) { const item = await tx.laboratoryOrderItem.create({ data: { tenantId: context.tenantId, orderId: order.id, testId: test.id, departmentId: test.departmentId, status: "ORDERED", specimenLinks: { create: { tenantId: context.tenantId, specimenId: specimen.id } } } }); await tx.laboratoryChargeLine.create({ data: { tenantId: context.tenantId, orderId: order.id, orderItemId: item.id, chargeType: "TEST", serviceCode: test.code, description: test.name, quantity: 1, unitPrice: 0, grossAmount: 0, discountAmount: 0, taxAmount: 0, netAmount: 0, billingAuthority: authority } }); } }
    if (authority === "HMS_CENTRAL") await tx.hospitalBillingPosting.create({ data: { tenantId: context.tenantId, orderId: order.id, postingVersion: 1, status: "READY_TO_POST" } });
    await appendLifecycleEvent(tx, { tenantId: context.tenantId, orderId: order.id, type: "ORDER_PLACED", actorUserId: context.userId, actorName: "Authenticated user", metadata: { billingAuthority: authority, collectionTaskId: task.id } });
    return order;
  });
  await audit(req, "LaboratoryOrder", result.id, "ORDER_PLACED", undefined, { billingAuthority: authority, source: req.body.source }); res.status(201).json({ data: result, lifecycle: await getOrderLifecycle(prisma, context.tenantId, result.id) });
}));

orderRoutes.patch("/:id", rejectAuditorWrites, requireAnyPermission("orders.write", "orders.write.client"), validate({ params: idParams, body: updateOrder }), asyncHandler(async (req, res) => { const current = await prisma.laboratoryOrder.findFirst({ where: { id: String(req.params.id), ...orderReadScope(req.context!) } }); if (!current) throw notFound("Order"); if (["COMPLETED", "CANCELLED"].includes(current.status)) throw new AppError(409, "Closed orders cannot be changed", "ORDER_IMMUTABLE"); const data = await prisma.laboratoryOrder.update({ where: { id: current.id }, data: req.body }); await audit(req, "LaboratoryOrder", data.id, "ORDER_UPDATED", current, data); res.json({ data }); }));
orderRoutes.get("/:id/charges", requireAnyPermission("billing.read", "billing.read.client", "orders.read"), validate({ params: idParams }), asyncHandler(async (req, res) => { const order = await prisma.laboratoryOrder.findFirst({ where: { id: String(req.params.id), ...orderReadScope(req.context!) }, include: { chargeLines: true, hmsPostings: true, invoices: { include: { lines: true, payments: true } } } }); if (!order) throw notFound("Order"); res.json({ data: { billingAuthority: order.billingAuthority, readOnly: order.billingAuthority === "HMS_CENTRAL", chargeLines: order.chargeLines, hmsPostings: order.hmsPostings, invoices: order.invoices } }); }));
