import {
  BiomedicalAsset,
  AssetAllocationRecord,
  RepairTicket,
  AssetHistoryEvent,
} from "@/hospital-admin/lib/types";

// ==========================================
// 1. MASTER ASSETS DATASET (Clinical & Facility)
// ==========================================
export const mockBiomedicalAssetsExtended: BiomedicalAsset[] = [
  // --- MEDICAL EQUIPMENT: Diagnostic & Imaging ---
  {
    id: "ast_01",
    assetCode: "BIO-CT-128",
    name: "Somatom Definition AS 128-Slice CT Scanner",
    category: "Diagnostic & Imaging",
    model: "Siemens Healthineers AS 128",
    serialNo: "SN-SIEM-994102",
    department: "Radiology & Imaging",
    floor: "Ground Floor - Radiology Block",
    installedRoom: "CT Scan Suite 1",
    purchaseDate: "2024-03-15",
    purchaseCost: 28500000,
    warrantyExpiry: "2027-03-15",
    amcCmcContract: "Active",
    vendorName: "Siemens Healthcare Pvt Ltd",
    nextPPMDate: "2026-09-15",
    maintenanceStatus: "Operational",
    lastCalibrationDate: "2026-06-15",
    isLoaned: false,
  },
  {
    id: "ast_02",
    assetCode: "BIO-MRI-3T",
    name: "Magnetom Lumina 3.0 Tesla MRI System",
    category: "Diagnostic & Imaging",
    model: "Siemens Magnetom Lumina 3T",
    serialNo: "SN-SIEM-330192",
    department: "Radiology & Imaging",
    floor: "Ground Floor - MRI Pavilion",
    installedRoom: "MRI Shielded Bay A",
    purchaseDate: "2023-09-10",
    purchaseCost: 55000000,
    warrantyExpiry: "2026-09-10",
    amcCmcContract: "Active",
    vendorName: "Siemens Healthcare Pvt Ltd",
    nextPPMDate: "2026-10-05",
    maintenanceStatus: "Operational",
    lastCalibrationDate: "2026-05-10",
    isLoaned: false,
  },
  {
    id: "ast_03",
    assetCode: "BIO-US-03",
    name: "Affiniti 70 Ultrasound Cardiovascular System",
    category: "Diagnostic & Imaging",
    model: "Philips Affiniti 70",
    serialNo: "SN-PHIL-881920",
    department: "Cardiology OPD",
    floor: "1st Floor - Cardiology Wing",
    installedRoom: "Echocardiography Lab 2",
    purchaseDate: "2024-01-18",
    purchaseCost: 3200000,
    warrantyExpiry: "2027-01-18",
    amcCmcContract: "Active",
    vendorName: "Philips Healthcare India",
    nextPPMDate: "2026-11-20",
    maintenanceStatus: "Operational",
    lastCalibrationDate: "2026-05-20",
    isLoaned: false,
  },

  // --- MEDICAL EQUIPMENT: Life Support ---
  {
    id: "ast_04",
    assetCode: "BIO-VENT-04",
    name: "Hamilton C6 Intensive Care Ventilator",
    category: "Life Support",
    model: "Hamilton Medical C6",
    serialNo: "SN-HAM-881902",
    department: "Intensive Care Unit (ICU)",
    floor: "3rd Floor - Critical Care Block",
    installedRoom: "ICU Bed 04",
    purchaseDate: "2023-08-20",
    purchaseCost: 2400000,
    warrantyExpiry: "2026-08-20",
    amcCmcContract: "Under Renewal",
    vendorName: "Hamilton Medical India",
    nextPPMDate: "2026-08-28",
    maintenanceStatus: "Calibration Due",
    lastCalibrationDate: "2026-02-20",
    isLoaned: false,
  },
  {
    id: "ast_05",
    assetCode: "BIO-VENT-PORT",
    name: "Hamilton T1 Transport Ventilator",
    category: "Life Support",
    model: "Hamilton T1 Mobile",
    serialNo: "SN-HAM-992381",
    department: "Intensive Care Unit (ICU)",
    floor: "Ground Floor - Emergency Block",
    installedRoom: "Trauma Resuscitation Bay 1",
    purchaseDate: "2024-04-12",
    purchaseCost: 1850000,
    warrantyExpiry: "2027-04-12",
    amcCmcContract: "Active",
    vendorName: "Hamilton Medical India",
    nextPPMDate: "2026-10-15",
    maintenanceStatus: "Operational",
    lastCalibrationDate: "2026-04-15",
    isLoaned: true,
    currentLoanDepartment: "Emergency & Trauma",
    expectedReturnDate: "2026-08-30",
  },
  {
    id: "ast_06",
    assetCode: "BIO-DEFIB-01",
    name: "Zoll R Series Biphasic Defibrillator",
    category: "Life Support",
    model: "Zoll R Series Plus",
    serialNo: "SN-ZOLL-441092",
    department: "Emergency & Trauma",
    floor: "Ground Floor - Emergency Bay",
    installedRoom: "Crash Cart Zone 1",
    purchaseDate: "2023-11-05",
    purchaseCost: 950000,
    warrantyExpiry: "2026-11-05",
    amcCmcContract: "Active",
    vendorName: "Zoll Medical India",
    nextPPMDate: "2026-09-01",
    maintenanceStatus: "Operational",
    lastCalibrationDate: "2026-03-01",
    isLoaned: false,
  },

  // --- MEDICAL EQUIPMENT: OT Equipment ---
  {
    id: "ast_07",
    assetCode: "BIO-ANESTH-02",
    name: "Dräger Perseus A500 Anesthesia Workstation",
    category: "OT Equipment",
    model: "Dräger Perseus A500",
    serialNo: "SN-DRAG-449102",
    department: "Operation Theatre (OT)",
    floor: "3rd Floor - Surgical Suite",
    installedRoom: "OT 2 (Cardiothoracic)",
    purchaseDate: "2024-01-10",
    purchaseCost: 3800000,
    warrantyExpiry: "2027-01-10",
    amcCmcContract: "Active",
    vendorName: "Dräger India Pvt Ltd",
    nextPPMDate: "2026-10-10",
    maintenanceStatus: "Operational",
    lastCalibrationDate: "2026-04-10",
    isLoaned: false,
  },
  {
    id: "ast_08",
    assetCode: "BIO-CARM-01",
    name: "Ziehm Vision RFD 3D Mobile C-Arm",
    category: "OT Equipment",
    model: "Ziehm Vision RFD 3D",
    serialNo: "SN-ZIEHM-102938",
    department: "Operation Theatre (OT)",
    floor: "3rd Floor - Surgical Suite",
    installedRoom: "OT 4 (Orthopedic & Spine)",
    purchaseDate: "2023-06-15",
    purchaseCost: 9200000,
    warrantyExpiry: "2026-06-15",
    amcCmcContract: "Under Renewal",
    vendorName: "Ziehm Imaging India",
    nextPPMDate: "2026-09-20",
    maintenanceStatus: "Under Maintenance",
    lastCalibrationDate: "2026-03-20",
    isLoaned: false,
  },

  // --- MEDICAL EQUIPMENT: Monitoring ---
  {
    id: "ast_09",
    assetCode: "BIO-MON-12",
    name: "Mindray BeneVision N17 Multi-Parameter Patient Monitor",
    category: "Monitoring",
    model: "Mindray BeneVision N17",
    serialNo: "SN-MIND-100293",
    department: "Emergency & Trauma",
    floor: "Ground Floor - Emergency Block",
    installedRoom: "Triage Bed 03",
    purchaseDate: "2023-11-05",
    purchaseCost: 650000,
    warrantyExpiry: "2025-11-05",
    amcCmcContract: "Active",
    vendorName: "Mindray Medical India",
    nextPPMDate: "2026-09-05",
    maintenanceStatus: "Operational",
    lastCalibrationDate: "2026-05-05",
    isLoaned: false,
  },
  {
    id: "ast_10",
    assetCode: "BIO-DIAL-03",
    name: "Fresenius 5008S CorDiax Hemodialysis System",
    category: "Monitoring",
    model: "Fresenius 5008S",
    serialNo: "SN-FRES-772910",
    department: "Nephrology & Dialysis",
    floor: "2nd Floor - Dialysis Unit",
    installedRoom: "Dialysis Bay 03",
    purchaseDate: "2023-12-01",
    purchaseCost: 1950000,
    warrantyExpiry: "2026-12-01",
    amcCmcContract: "Active",
    vendorName: "Fresenius Medical Care",
    nextPPMDate: "2026-11-01",
    maintenanceStatus: "Operational",
    lastCalibrationDate: "2026-05-01",
    isLoaned: false,
  },

  // --- HOSPITAL EQUIPMENT: Facility Infrastructure ---
  {
    id: "ast_11",
    assetCode: "FAC-PSA-O2",
    name: "Central PSA Medical Oxygen Generation Plant (500 LPM)",
    category: "Facility Infrastructure",
    model: "Oxair PSA-500",
    serialNo: "SN-OX-991029",
    department: "Biomedical & Engineering",
    floor: "Basement 1 - Plant Room",
    installedRoom: "Central Gas Manifold Room",
    purchaseDate: "2022-05-10",
    purchaseCost: 14500000,
    warrantyExpiry: "2025-05-10",
    amcCmcContract: "Active",
    vendorName: "Linde India Limited",
    nextPPMDate: "2026-09-10",
    maintenanceStatus: "Operational",
    lastCalibrationDate: "2026-06-10",
    isLoaned: false,
  },
  {
    id: "ast_12",
    assetCode: "FAC-GEN-500",
    name: "Cummins 500 kVA Emergency Diesel Generator",
    category: "Facility Infrastructure",
    model: "Cummins C500D5P",
    serialNo: "SN-CUMM-882901",
    department: "Biomedical & Engineering",
    floor: "Substation Yard",
    installedRoom: "Power Substation 1",
    purchaseDate: "2021-08-15",
    purchaseCost: 4800000,
    warrantyExpiry: "2024-08-15",
    amcCmcContract: "Active",
    vendorName: "Cummins India Limited",
    nextPPMDate: "2026-09-30",
    maintenanceStatus: "Operational",
    lastCalibrationDate: "2026-06-30",
    isLoaned: false,
  },
  {
    id: "ast_13",
    assetCode: "FAC-AUTO-01",
    name: "Tuttnauer 5596 Horizontal Steam Autoclave Sterilizer (430L)",
    category: "Facility Infrastructure",
    model: "Tuttnauer 5596-1V",
    serialNo: "SN-TUTT-440192",
    department: "CSSD (Central Sterile)",
    floor: "Basement 1 - Sterilization Wing",
    installedRoom: "Autoclave Chamber 1",
    purchaseDate: "2023-04-20",
    purchaseCost: 3600000,
    warrantyExpiry: "2026-04-20",
    amcCmcContract: "Active",
    vendorName: "Tuttnauer Medical",
    nextPPMDate: "2026-10-20",
    maintenanceStatus: "Operational",
    lastCalibrationDate: "2026-04-20",
    isLoaned: false,
  },
  {
    id: "ast_14",
    assetCode: "FAC-HVAC-01",
    name: "Daikin Water-Cooled Centrifugal Chiller (300 TR)",
    category: "Facility Infrastructure",
    model: "Daikin WMC-300",
    serialNo: "SN-DAIK-229102",
    department: "Biomedical & Engineering",
    floor: "Rooftop Plant Room",
    installedRoom: "HVAC Plant Bay",
    purchaseDate: "2022-10-15",
    purchaseCost: 8800000,
    warrantyExpiry: "2025-10-15",
    amcCmcContract: "Active",
    vendorName: "Daikin Airconditioning India",
    nextPPMDate: "2026-09-25",
    maintenanceStatus: "Operational",
    lastCalibrationDate: "2026-06-25",
    isLoaned: false,
  },
  {
    id: "ast_15",
    assetCode: "FAC-ELEV-BED",
    name: "Schindler 5500 Stretcher & Bed Elevator (2000 kg)",
    category: "Facility Infrastructure",
    model: "Schindler 5500 Hospital",
    serialNo: "SN-SCH-771920",
    department: "Biomedical & Engineering",
    floor: "Block A - Central Core",
    installedRoom: "Elevator Shaft Lift 2",
    purchaseDate: "2022-02-10",
    purchaseCost: 5200000,
    warrantyExpiry: "2025-02-10",
    amcCmcContract: "Active",
    vendorName: "Schindler India Pvt Ltd",
    nextPPMDate: "2026-09-08",
    maintenanceStatus: "Operational",
    lastCalibrationDate: "2026-06-08",
    isLoaned: false,
  },
];

// ==========================================
// 2. ASSET ALLOCATIONS & TEMPORARY LOANS
// ==========================================
export const mockAssetAllocations: AssetAllocationRecord[] = [
  {
    id: "alc_01",
    allocationNo: "ALC-2026-0089",
    assetId: "ast_05",
    assetCode: "BIO-VENT-PORT",
    assetName: "Hamilton T1 Transport Ventilator",
    fromDepartment: "Intensive Care Unit (ICU)",
    toDepartment: "Emergency & Trauma",
    fromFloor: "3rd Floor - ICU Core",
    toFloor: "Ground Floor - Emergency Block",
    fromRoom: "ICU Equipment Room",
    toRoom: "Trauma Resuscitation Bay 1",
    allocatedBy: "Dr. Vikram Sethi (Medical Superintendent)",
    allocatedAt: "2026-08-22T08:30:00Z",
    allocationType: "Temporary Loan",
    expectedReturnDate: "2026-08-30",
    status: "Active",
    purposeNotes: "Surge emergency capacity: loaned for high-volume polytrauma triage resuscitation shift.",
  },
  {
    id: "alc_02",
    allocationNo: "ALC-2026-0072",
    assetId: "ast_03",
    assetCode: "BIO-US-03",
    assetName: "Affiniti 70 Ultrasound Cardiovascular System",
    fromDepartment: "Radiology & Imaging",
    toDepartment: "Cardiology OPD",
    fromFloor: "Ground Floor - Imaging Block",
    toFloor: "1st Floor - Cardiology Wing",
    fromRoom: "USG Room 3",
    toRoom: "Echocardiography Lab 2",
    allocatedBy: "Hospital Admin (Delegated)",
    allocatedAt: "2026-07-15T10:00:00Z",
    allocationType: "Permanent Transfer",
    status: "Active",
    purposeNotes: "Permanent department transfer to establish dedicated Echo laboratory in Cardiology OPD.",
  },
  {
    id: "alc_03",
    allocationNo: "ALC-2026-0045",
    assetId: "ast_06",
    assetCode: "BIO-DEFIB-01",
    assetName: "Zoll R Series Biphasic Defibrillator",
    fromDepartment: "Emergency & Trauma",
    toDepartment: "Day Care / Cath Lab",
    fromFloor: "Ground Floor",
    toFloor: "2nd Floor - Cath Suite",
    fromRoom: "Crash Cart Zone 1",
    toRoom: "Holding Area",
    allocatedBy: "Biomedical In-Charge",
    allocatedAt: "2026-06-10T09:00:00Z",
    allocationType: "Temporary Loan",
    expectedReturnDate: "2026-06-12",
    returnedAt: "2026-06-12T17:30:00Z",
    returnedBy: "Nurse Station Lead (Cath Lab)",
    status: "Returned",
    purposeNotes: "Temporary loan during scheduled Cath Lab holding bay drill and equipment maintenance.",
  },
];

// ==========================================
// 3. CORRECTIVE REPAIR TICKETS
// ==========================================
export const mockRepairTickets: RepairTicket[] = [
  {
    id: "rep_01",
    ticketNo: "REP-2026-0104",
    assetId: "ast_08",
    assetCode: "BIO-CARM-01",
    assetName: "Ziehm Vision RFD 3D Mobile C-Arm",
    department: "Operation Theatre (OT)",
    reportedBy: "Dr. Sandeep Nair (Chief Orthopedic Surgeon)",
    reportedAt: "2026-08-25T14:15:00Z",
    faultDescription: "3D Image reconstruction workstation freezes during high-resolution fluoroscopy spin. Artifact streak error on display panel.",
    priority: "Critical",
    assignedTechnicianOrVendor: "Ziehm Imaging India (Service Engineer: Rajesh Kumar)",
    repairCost: 45000,
    partsUsed: "High-Speed Reconstruction GPU Card Re-seating",
    downtimeStart: "2026-08-25T14:15:00Z",
    status: "In Progress",
    requiresStepUpAuth: false,
  },
  {
    id: "rep_02",
    ticketNo: "REP-2026-0098",
    assetId: "ast_04",
    assetCode: "BIO-VENT-04",
    assetName: "Hamilton C6 Intensive Care Ventilator",
    department: "Intensive Care Unit (ICU)",
    reportedBy: "Staff Nurse Priya Pillai (ICU In-Charge)",
    reportedAt: "2026-08-26T09:00:00Z",
    faultDescription: "Expiratory valve flow sensor intermittent error warning during pre-operational check.",
    priority: "High",
    assignedTechnicianOrVendor: "Sunil Verma (Biomedical Senior Engineer)",
    downtimeStart: "2026-08-26T09:00:00Z",
    status: "Reported",
    requiresStepUpAuth: false,
  },
  {
    id: "rep_03",
    ticketNo: "REP-2026-0082",
    assetId: "ast_10",
    assetCode: "BIO-DIAL-03",
    assetName: "Fresenius 5008S CorDiax Hemodialysis System",
    department: "Nephrology & Dialysis",
    reportedBy: "Dr. Ananya Roy (Nephrology Head)",
    reportedAt: "2026-08-18T11:00:00Z",
    faultDescription: "Heparin infusion pump drive motor error code E-441.",
    priority: "Medium",
    assignedTechnicianOrVendor: "Fresenius Medical Care (OEM Support)",
    repairCost: 28500,
    partsUsed: "Heparin Stepper Motor Assembly (OEM Part #F-4401)",
    downtimeStart: "2026-08-18T11:00:00Z",
    downtimeEnd: "2026-08-19T16:00:00Z",
    resolutionNotes: "Replaced stepper motor assembly, recalibrated infusion flow rate, ran 3 clean diagnostic test cycles. Device verified operational.",
    status: "Resolved",
    resolvedBy: "Amitabh Sen (Biomedical Lead)",
    resolvedAt: "2026-08-19T16:00:00Z",
    requiresStepUpAuth: false,
  },
  {
    id: "rep_04",
    ticketNo: "REP-2026-0051",
    assetId: "ast_14",
    assetCode: "FAC-HVAC-01",
    assetName: "Daikin Water-Cooled Centrifugal Chiller (300 TR)",
    department: "Biomedical & Engineering",
    reportedBy: "Engineering Maintenance Desk",
    reportedAt: "2026-07-20T08:00:00Z",
    faultDescription: "Compressor refrigerant pressure sensor trip and oil filter high differential pressure alert.",
    priority: "High",
    assignedTechnicianOrVendor: "Daikin Airconditioning India (Service Partner)",
    repairCost: 82000,
    partsUsed: "Compressor Oil Filter Core, Pressure Transducer PT-300",
    downtimeStart: "2026-07-20T08:00:00Z",
    downtimeEnd: "2026-07-21T18:30:00Z",
    resolutionNotes: "Replaced oil filter core and transducer. Recharged R-134a refrigerant. Operating at full 300 TR capacity with normal pressure benchmarks.",
    status: "Resolved",
    resolvedBy: "Ramesh Sharma (Chief Facility Engineer)",
    resolvedAt: "2026-07-21T18:30:00Z",
    requiresStepUpAuth: true,
  },
];

// ==========================================
// 4. UNIFIED ASSET HISTORY EVENTS
// ==========================================
export const mockAssetHistoryEvents: AssetHistoryEvent[] = [
  {
    id: "evt_01",
    assetId: "ast_04",
    assetCode: "BIO-VENT-04",
    assetName: "Hamilton C6 Intensive Care Ventilator",
    eventType: "Breakdown Reported",
    timestamp: "2026-08-26T09:00:00Z",
    actor: "Staff Nurse Priya Pillai (ICU)",
    title: "Fault Ticket Created (REP-2026-0098)",
    details: "Flow sensor intermittent error warning reported. Asset flagged for calibration and technical inspection.",
    referenceId: "REP-2026-0098",
  },
  {
    id: "evt_02",
    assetId: "ast_08",
    assetCode: "BIO-CARM-01",
    assetName: "Ziehm Vision RFD 3D Mobile C-Arm",
    eventType: "Breakdown Reported",
    timestamp: "2026-08-25T14:15:00Z",
    actor: "Dr. Sandeep Nair (Orthopedic Surgery)",
    title: "Critical Breakdown Logged (REP-2026-0104)",
    details: "Workstation frozen during 3D acquisition. Escalated to OEM engineer Rajesh Kumar (Ziehm Imaging India).",
    referenceId: "REP-2026-0104",
  },
  {
    id: "evt_03",
    assetId: "ast_05",
    assetCode: "BIO-VENT-PORT",
    assetName: "Hamilton T1 Transport Ventilator",
    eventType: "Allocation / Transfer",
    timestamp: "2026-08-22T08:30:00Z",
    actor: "Dr. Vikram Sethi (Medical Superintendent)",
    title: "Temporary Loan Dispatched to Emergency",
    details: "Loaned from ICU Core to Emergency Trauma Resuscitation Bay 1. Expected return: 2026-08-30.",
    referenceId: "ALC-2026-0089",
  },
  {
    id: "evt_04",
    assetId: "ast_10",
    assetCode: "BIO-DIAL-03",
    assetName: "Fresenius 5008S CorDiax Hemodialysis System",
    eventType: "Repair Completed",
    timestamp: "2026-08-19T16:00:00Z",
    actor: "Amitabh Sen (Biomedical Lead)",
    title: "Repair Ticket Resolved & Certified (REP-2026-0082)",
    details: "Replaced Heparin Stepper Motor Assembly (₹28,500). 3 diagnostic test cycles passed. Asset operational.",
    referenceId: "REP-2026-0082",
  },
  {
    id: "evt_05",
    assetId: "ast_01",
    assetCode: "BIO-CT-128",
    assetName: "Somatom Definition AS 128-Slice CT Scanner",
    eventType: "PPM Certified",
    timestamp: "2026-06-15T11:00:00Z",
    actor: "Kavita Rao (Lead Biomedical Engineer)",
    title: "Bi-Annual Planned Preventive Maintenance (PPM)",
    details: "Tube voltage calibration, laser alignment, and gantry safety interlock testing completed. Next PPM: 2026-09-15.",
    referenceId: "PPM-2026-0041",
  },
  {
    id: "evt_06",
    assetId: "ast_01",
    assetCode: "BIO-CT-128",
    assetName: "Somatom Definition AS 128-Slice CT Scanner",
    eventType: "Registration",
    timestamp: "2024-03-15T10:00:00Z",
    actor: "Hospital Procurement & Asset Commissioning Board",
    title: "Capital Asset Commissioned & Tagged",
    details: "Commissioned under Siemens Healthineers warranty (₹2.85 Cr). Asset Code BIO-CT-128 assigned.",
    referenceId: "PO-2024-0012",
  },
];
