import {
  MessageTemplate,
  WhatsAppGatewayMetrics,
  WhatsAppMessageLog,
  PatientChatThread,
  AppointmentMessageRecord,
  ClinicalNote,
  BroadcastRecord,
  UnifiedDeliveryLogItem,
  ReportNotificationRecord,
  FollowUpReminderRecord,
  MedicationReminderItem,
} from "@/hospital-admin/lib/types";

// ==========================================
// 1. SHARED MESSAGE TEMPLATES LIBRARY
// ==========================================
export const mockMessageTemplates: MessageTemplate[] = [
  {
    id: "tpl-001",
    templateId: "TPL-APT-CONFIRM",
    name: "OPD Appointment Confirmation",
    category: "Appointment",
    channel: "WhatsApp",
    content: "Dear {{patient_name}}, your appointment with {{doctor_name}} ({{department}}) is confirmed for {{appointment_date}} at {{appointment_time}}. Please arrive 15 minutes prior at Desk 3. Hospital Helpline: 080-49112200.",
    variables: ["patient_name", "doctor_name", "department", "appointment_date", "appointment_time"],
    status: "Active",
    createdBy: "Care Coordination Lead",
    createdAt: "2026-08-01 10:00",
    usageCount: 1420,
  },
  {
    id: "tpl-002",
    templateId: "TPL-APT-REM-24H",
    name: "Pre-Visit 24-Hour Reminder",
    category: "Appointment",
    channel: "WhatsApp",
    content: "Reminder: {{patient_name}}, you have a scheduled consultation with {{doctor_name}} tomorrow, {{appointment_date}} at {{appointment_time}}. Fasting required: {{fasting_required}}. Reply 1 to Confirm or 2 to Reschedule.",
    variables: ["patient_name", "doctor_name", "appointment_date", "appointment_time", "fasting_required"],
    status: "Active",
    createdBy: "Front Desk Admin",
    createdAt: "2026-08-01 11:30",
    usageCount: 2310,
  },
  {
    id: "tpl-003",
    templateId: "TPL-REP-SIGN-OFF",
    name: "Diagnostic Report Ready Notice",
    category: "Report",
    channel: "WhatsApp",
    content: "Hello {{patient_name}}, your diagnostic report for {{test_name}} has been signed off by {{doctor_name}}. View your verified report securely on the Patient Portal: {{portal_link}}",
    variables: ["patient_name", "test_name", "doctor_name", "portal_link"],
    status: "Active",
    createdBy: "Chief Pathologist",
    createdAt: "2026-08-05 09:15",
    usageCount: 980,
  },
  {
    id: "tpl-004",
    templateId: "TPL-FOL-DUE-7D",
    name: "Post-Op 7-Day Follow-up Recall",
    category: "Follow-up",
    channel: "WhatsApp",
    content: "Dear {{patient_name}}, your 7-day post-procedure clinical follow-up with {{doctor_name}} is due on {{due_date}}. Book your preferred slot online: {{portal_link}} or call 080-49112200.",
    variables: ["patient_name", "doctor_name", "due_date", "portal_link"],
    status: "Active",
    createdBy: "Surgical Coordinator",
    createdAt: "2026-08-10 14:00",
    usageCount: 460,
  },
  {
    id: "tpl-005",
    templateId: "TPL-EMG-CODE-BLUE",
    name: "Emergency Code Blue Alert Staging",
    category: "Broadcast",
    channel: "Broadcast",
    content: "EMERGENCY: CODE BLUE activated at {{location_room}}, Floor {{floor_no}}. Resuscitation crash team report immediately with AED kit. Lead: {{team_lead}}.",
    variables: ["location_room", "floor_no", "team_lead"],
    status: "Active",
    createdBy: "Emergency Medical Officer",
    createdAt: "2026-08-02 08:00",
    usageCount: 14,
  },
  {
    id: "tpl-006",
    templateId: "TPL-CLN-PANIC-VAL",
    name: "NABH Critical Panic Value Urgent Notice",
    category: "Clinical",
    channel: "SMS",
    content: "CRITICAL ALERT: Patient {{patient_name}} (UHID: {{patient_uhid}}) has panic lab value: {{panic_result}} (Ref: {{ref_range}}). Attending Dr. {{doctor_name}} please perform verbal read-back.",
    variables: ["patient_name", "patient_uhid", "panic_result", "ref_range", "doctor_name"],
    status: "Active",
    createdBy: "Quality & Compliance Head",
    createdAt: "2026-08-04 16:30",
    usageCount: 125,
  },
  {
    id: "tpl-007",
    templateId: "TPL-OPS-MAINT-NOTICE",
    name: "Department Scheduled Maintenance",
    category: "Broadcast",
    channel: "Broadcast",
    content: "Notice to Staff: Scheduled facility maintenance in {{department}} from {{start_time}} to {{end_time}}. Diagnostic services rerouted to Block B Annex.",
    variables: ["department", "start_time", "end_time"],
    status: "Active",
    createdBy: "Facility Operations Manager",
    createdAt: "2026-08-12 11:00",
    usageCount: 38,
  },
];

// ==========================================
// 2. WHATSAPP GATEWAY TELEMETRY & LOGS
// ==========================================
export const mockWhatsAppGatewayMetrics: WhatsAppGatewayMetrics = {
  deliveryRate: 99.4,
  readRate: 88.2,
  apiHealth: "Operational",
  status: "Operational",
  latencyMs: 340,
  averageLatencyMs: 340,
  activeSessions: 64,
  totalSentToday: 1845,
  dailySentCount: 1845,
  dailyLimit: 100000,
  totalFailedToday: 11,
  phoneNumber: "+91 80 4911 2200 (Verified Business)",
  webhookStatus: "Connected",
  lastPing: "Just now (42ms)",
};

export const mockWhatsAppMessageLogs: WhatsAppMessageLog[] = [
  {
    id: "walog-001",
    recipientName: "Aarav Sharma",
    recipientPhone: "+91 98450 12345",
    moduleSource: "F1 Appointments",
    templateUsed: "TPL-APT-CONFIRM",
    contentSnippet: "Dear Aarav Sharma, your appointment with Dr. Arvind Kumar...",
    status: "Read",
    timestamp: "2026-08-28 10:15",
    cost: 0.48,
  },
  {
    id: "walog-002",
    recipientName: "Sunita Reddy",
    recipientPhone: "+91 97411 98765",
    moduleSource: "F22 Reports Review",
    templateUsed: "TPL-REP-SIGN-OFF",
    contentSnippet: "Hello Sunita Reddy, your diagnostic report for Lipid Profile...",
    status: "Read",
    timestamp: "2026-08-28 10:08",
    cost: 0.48,
  },
  {
    id: "walog-003",
    recipientName: "Vikram Patel",
    recipientPhone: "+91 99800 45678",
    moduleSource: "F5 Follow-ups",
    templateUsed: "TPL-FOL-DUE-7D",
    contentSnippet: "Dear Vikram Patel, your 7-day post-procedure clinical follow-up...",
    status: "Delivered",
    timestamp: "2026-08-28 09:55",
    cost: 0.48,
  },
  {
    id: "walog-004",
    recipientName: "Meenakshi Iyer",
    recipientPhone: "+91 98860 33445",
    moduleSource: "F1 Appointments",
    templateUsed: "TPL-APT-REM-24H",
    contentSnippet: "Reminder: Meenakshi Iyer, you have a scheduled consultation...",
    status: "Delivered",
    timestamp: "2026-08-28 09:40",
    cost: 0.48,
  },
  {
    id: "walog-005",
    recipientName: "Rajesh Rao",
    recipientPhone: "+91 99450 00112",
    moduleSource: "Reception (PDF 6)",
    templateUsed: "TPL-APT-CONFIRM",
    contentSnippet: "Dear Rajesh Rao, your walk-in token #42 is ready...",
    status: "Failed",
    timestamp: "2026-08-28 09:20",
    errorMessage: "Recipient phone inactive / network timeout",
    cost: 0.0,
  },
  {
    id: "walog-006",
    recipientName: "Priya Nair",
    recipientPhone: "+91 98455 77889",
    moduleSource: "F22 Reports Review",
    templateUsed: "TPL-REP-SIGN-OFF",
    contentSnippet: "Hello Priya Nair, your diagnostic report for Thyroid Profile...",
    status: "Read",
    timestamp: "2026-08-28 09:05",
    cost: 0.48,
  },
];

// ==========================================
// 3. PATIENT PORTAL CHAT THREADS
// ==========================================
export const mockPatientChatThreads: PatientChatThread[] = [
  {
    id: "thread-001",
    threadId: "PCT-2026-0891",
    patientId: "pat-101",
    patientName: "Aarav Sharma",
    patientUhid: "UHID-2026-8801",
    patientPhone: "+91 98450 12345",
    avatarUrl: "",
    lastMessage: "Thank you for confirming the fasting hours. I will bring my previous ECG.",
    lastMessageTime: "10:18 AM",
    unreadCount: 1,
    channel: "Portal",
    department: "Cardiology",
    attendingDoctor: "Dr. Arvind Kumar",
    messages: [
      {
        id: "msg-101",
        senderType: "patient",
        senderName: "Aarav Sharma",
        text: "Hello, do I need to fast for 12 hours before tomorrow's Lipid test?",
        timestamp: "09:50 AM",
        readAt: "09:52 AM",
      },
      {
        id: "msg-102",
        senderType: "care_coordinator",
        senderName: "Nurse Kavitha (Care Lead)",
        text: "Yes Mr. Sharma, complete fasting for 10-12 hours is required. You may drink plain water.",
        timestamp: "09:55 AM",
        readAt: "10:00 AM",
      },
      {
        id: "msg-103",
        senderType: "patient",
        senderName: "Aarav Sharma",
        text: "Thank you for confirming the fasting hours. I will bring my previous ECG.",
        timestamp: "10:18 AM",
      },
    ],
  },
  {
    id: "thread-002",
    threadId: "PCT-2026-0892",
    patientId: "pat-102",
    patientName: "Sunita Reddy",
    patientUhid: "UHID-2026-8802",
    patientPhone: "+91 97411 98765",
    avatarUrl: "",
    lastMessage: "I uploaded the post-operative wound photo for Dr. Shweta's review.",
    lastMessageTime: "09:30 AM",
    unreadCount: 2,
    channel: "Portal",
    department: "Orthopaedics",
    attendingDoctor: "Dr. Shweta Rao",
    messages: [
      {
        id: "msg-201",
        senderType: "patient",
        senderName: "Sunita Reddy",
        text: "Good morning, the knee swelling has reduced significantly compared to Day 3.",
        timestamp: "09:10 AM",
        readAt: "09:15 AM",
      },
      {
        id: "msg-202",
        senderType: "patient",
        senderName: "Sunita Reddy",
        text: "I uploaded the post-operative wound photo for Dr. Shweta's review.",
        timestamp: "09:30 AM",
        isAttachment: true,
        attachmentName: "knee_incision_day5.jpg",
        attachmentType: "image/jpeg",
      },
    ],
  },
  {
    id: "thread-003",
    threadId: "PCT-2026-0893",
    patientId: "pat-103",
    patientName: "Vikram Patel",
    patientUhid: "UHID-2026-8803",
    patientPhone: "+91 99800 45678",
    avatarUrl: "",
    lastMessage: "Can we shift my follow-up consultation to Saturday morning?",
    lastMessageTime: "Yesterday",
    unreadCount: 0,
    channel: "Portal",
    department: "Neurology",
    attendingDoctor: "Dr. Arvind Kumar",
    messages: [
      {
        id: "msg-301",
        senderType: "patient",
        senderName: "Vikram Patel",
        text: "Can we shift my follow-up consultation to Saturday morning?",
        timestamp: "Yesterday 04:30 PM",
        readAt: "Yesterday 04:45 PM",
      },
      {
        id: "msg-302",
        senderType: "care_coordinator",
        senderName: "Coordinator Rahul",
        text: "Slot updated to Saturday 10:30 AM with Dr. Kumar. Confirmation sent via WhatsApp.",
        timestamp: "Yesterday 04:50 PM",
        readAt: "Yesterday 05:00 PM",
      },
    ],
  },
  {
    id: "thread-004",
    threadId: "PCT-2026-0894",
    patientId: "pat-104",
    patientName: "Meenakshi Iyer",
    patientUhid: "UHID-2026-8804",
    patientPhone: "+91 98860 33445",
    avatarUrl: "",
    lastMessage: "Please verify if my cashless insurance authorization is approved.",
    lastMessageTime: "Aug 26",
    unreadCount: 0,
    channel: "Portal",
    department: "General Medicine",
    attendingDoctor: "Dr. Arvind Kumar",
    messages: [
      {
        id: "msg-401",
        senderType: "patient",
        senderName: "Meenakshi Iyer",
        text: "Please verify if my cashless insurance authorization is approved.",
        timestamp: "Aug 26 11:15 AM",
        readAt: "Aug 26 11:20 AM",
      },
      {
        id: "msg-402",
        senderType: "care_coordinator",
        senderName: "TPA Desk Pooja",
        text: "Pre-authorization approved for ₹75,000 by Star Health. You are clear for admission.",
        timestamp: "Aug 26 11:40 AM",
        readAt: "Aug 26 12:00 PM",
      },
    ],
  },
];

// ==========================================
// 4. APPOINTMENT MESSAGES (SOURCED FROM F1)
// ==========================================
export const mockAppointmentMessages: AppointmentMessageRecord[] = [
  {
    id: "aptmsg-001",
    appointmentId: "apt-8901",
    patientName: "Aarav Sharma",
    patientUhid: "UHID-2026-8801",
    patientPhone: "+91 98450 12345",
    doctorName: "Dr. Arvind Kumar",
    department: "Cardiology",
    appointmentDate: "2026-08-29",
    appointmentTime: "10:30 AM",
    triggerType: "reminder_24h",
    templateId: "TPL-APT-REM-24H",
    templateName: "Pre-Visit 24-Hour Reminder",
    channel: "WhatsApp",
    status: "Delivered",
    dispatchedAt: "2026-08-28 10:15",
  },
  {
    id: "aptmsg-002",
    appointmentId: "apt-8902",
    patientName: "Sunita Reddy",
    patientUhid: "UHID-2026-8802",
    patientPhone: "+91 97411 98765",
    doctorName: "Dr. Shweta Rao",
    department: "Orthopaedics",
    appointmentDate: "2026-08-29",
    appointmentTime: "11:00 AM",
    triggerType: "reminder_24h",
    templateId: "TPL-APT-REM-24H",
    templateName: "Pre-Visit 24-Hour Reminder",
    channel: "WhatsApp",
    status: "Delivered",
    dispatchedAt: "2026-08-28 10:15",
  },
  {
    id: "aptmsg-003",
    appointmentId: "apt-8903",
    patientName: "Karan Malhotra",
    patientUhid: "UHID-2026-8805",
    patientPhone: "+91 98452 33211",
    doctorName: "Dr. Rajesh Gupta",
    department: "General Medicine",
    appointmentDate: "2026-08-28",
    appointmentTime: "02:00 PM",
    triggerType: "reminder_2h",
    templateId: "TPL-APT-REM-24H",
    templateName: "Pre-Visit 2-Hour Notice",
    channel: "WhatsApp",
    status: "Scheduled",
    scheduledFor: "2026-08-28 12:00",
  },
  {
    id: "aptmsg-004",
    appointmentId: "apt-8904",
    patientName: "Ananya Deshmukh",
    patientUhid: "UHID-2026-8806",
    patientPhone: "+91 98453 99887",
    doctorName: "Dr. Priya Nair",
    department: "Gynaecology",
    appointmentDate: "2026-08-29",
    appointmentTime: "03:30 PM",
    triggerType: "booking_confirmation",
    templateId: "TPL-APT-CONFIRM",
    templateName: "OPD Appointment Confirmation",
    channel: "WhatsApp",
    status: "Delivered",
    dispatchedAt: "2026-08-28 09:30",
  },
  {
    id: "aptmsg-005",
    appointmentId: "apt-8905",
    patientName: "Rohan Verma",
    patientUhid: "UHID-2026-8807",
    patientPhone: "+91 98454 44556",
    doctorName: "Dr. Arvind Kumar",
    department: "Cardiology",
    appointmentDate: "2026-08-28",
    appointmentTime: "11:30 AM",
    triggerType: "reschedule",
    templateId: "TPL-APT-CONFIRM",
    templateName: "OPD Reschedule Confirmation",
    channel: "WhatsApp",
    status: "Delivered",
    dispatchedAt: "2026-08-28 08:45",
  },
];

// ==========================================
// 5. DOCTOR CLINICAL NOTES (CARE TEAM COLLAB)
// ==========================================
export const mockClinicalNotes: ClinicalNote[] = [
  {
    id: "cnote-001",
    noteId: "NOTE-2026-041",
    patientId: "pat-101",
    patientName: "Aarav Sharma",
    patientUhid: "UHID-2026-8801",
    authorDoctorId: "doc-101",
    authorDoctorName: "Dr. Arvind Kumar",
    doctorSpecialty: "Cardiology",
    noteText: "Patient presented with mild exertional dyspnea. Echocardiogram shows LVEF 55%. Advised starting low-dose Beta-blocker post-renal panel clearance. Nursing: monitor supine vs standing BP Q4H.",
    visibility: "Care Team",
    priority: "Urgent",
    createdAt: "2026-08-28 09:30",
    readBy: [
      { staffId: "stf-201", staffName: "Nurse Kavitha", staffRole: "ICU Staff Nurse", readAt: "2026-08-28 09:35" },
      { staffId: "stf-202", staffName: "Dr. Rajesh Gupta", staffRole: "Resident Medical Officer", readAt: "2026-08-28 09:42" },
      { staffId: "stf-203", staffName: "Pharmacist Meera", staffRole: "Clinical Pharmacist", readAt: "2026-08-28 10:00" },
    ],
  },
  {
    id: "cnote-002",
    noteId: "NOTE-2026-042",
    patientId: "pat-102",
    patientName: "Sunita Reddy",
    patientUhid: "UHID-2026-8802",
    authorDoctorId: "doc-102",
    authorDoctorName: "Dr. Shweta Rao",
    doctorSpecialty: "Orthopaedics",
    noteText: "Day 5 post TKR right knee. Incision clean, minimal serosanguinous discharge. Cryotherapy continued 20 mins TID. Physiotherapy team may initiate active-assisted flexion up to 75 degrees.",
    visibility: "Care Team",
    priority: "Routine",
    createdAt: "2026-08-28 08:45",
    readBy: [
      { staffId: "stf-204", staffName: "Physio Anand", staffRole: "Chief Physiotherapist", readAt: "2026-08-28 09:00" },
      { staffId: "stf-205", staffName: "Nurse Suman", staffRole: "Ward Nurse (Floor 3)", readAt: "2026-08-28 09:12" },
    ],
  },
  {
    id: "cnote-003",
    noteId: "NOTE-2026-043",
    patientId: "pat-103",
    patientName: "Vikram Patel",
    patientUhid: "UHID-2026-8803",
    authorDoctorId: "doc-101",
    authorDoctorName: "Dr. Arvind Kumar",
    doctorSpecialty: "Cardiology",
    noteText: "Telemetry review showed intermittent sinus bradycardia (HR 48-52 bpm) during sleep. No pauses > 2.5s. Withholding nighttime diltiazem dose pending 24h Holter completion.",
    visibility: "Specific Recipients",
    recipientRoles: ["Duty Medical Officer", "Cardiac Telemetry Nurse"],
    priority: "Routine",
    createdAt: "2026-08-27 18:30",
    readBy: [
      { staffId: "stf-206", staffName: "Dr. Vinay", staffRole: "Duty Medical Officer", readAt: "2026-08-27 19:00" },
    ],
  },
];

// ==========================================
// 6. BROADCASTS & CODE BLUE DELIVERY
// ==========================================
export const mockBroadcastRecords: BroadcastRecord[] = [
  {
    id: "bcast-001",
    broadcastId: "BC-2026-018",
    type: "Code Blue",
    title: "CODE BLUE ACTIVATED: ICU Bay 4 (Floor 2)",
    message: "EMERGENCY: Code Blue activated at ICU Bay 4, Floor 2. Crash Team Alpha report immediately. AED & airway cart dispatched.",
    channels: ["PA Screens", "App Push", "SMS"],
    targetScope: "Hospital-wide",
    triggeredBy: "Dr. Arvind Kumar",
    triggeredByRole: "Emergency Medical Officer",
    triggeredAt: "2026-08-28 08:14",
    status: "Delivered",
    acknowledgedCount: 28,
    targetAudienceSize: 32,
  },
  {
    id: "bcast-002",
    broadcastId: "BC-2026-017",
    type: "Operational",
    title: "Central Oxygen Line Pressure Calibration",
    message: "Plant Engineering conducting 15-minute pressure sensor calibration on Block A secondary oxygen manifold. Backup cylinder banks primed.",
    channels: ["App Push", "PA Screens"],
    targetScope: "Department",
    targetDetail: "ICU, OT Complex, Emergency",
    triggeredBy: "Eng. Ramesh",
    triggeredByRole: "Biomedical Plant Supervisor",
    triggeredAt: "2026-08-27 14:00",
    status: "Delivered",
    acknowledgedCount: 45,
    targetAudienceSize: 48,
  },
  {
    id: "bcast-003",
    broadcastId: "BC-2026-016",
    type: "Clinical Alert",
    title: "Seasonal H1N1 Screening Protocol Mandatory",
    message: "In accordance with state health advisory, all OPD registration counters must conduct temperature checks and issue N95 masks for respiratory complaints.",
    channels: ["WhatsApp", "App Push"],
    targetScope: "Hospital-wide",
    triggeredBy: "Dr. Suresh (MS)",
    triggeredByRole: "Medical Superintendent",
    triggeredAt: "2026-08-25 09:00",
    status: "Active",
    acknowledgedCount: 112,
    targetAudienceSize: 120,
  },
];

// ==========================================
// 7. UNIFIED CROSS-MODULE DELIVERY AUDIT LOG
// ==========================================
export const mockUnifiedDeliveryLogs: UnifiedDeliveryLogItem[] = [
  {
    id: "udl-001",
    sourceModule: "F3 Emergency",
    recipientName: "Resuscitation Crash Team (32 Staff)",
    recipientContact: "Broadcast PA & Staff Push",
    channel: "Broadcast",
    templateUsed: "TPL-EMG-CODE-BLUE",
    messageSummary: "CODE BLUE ACTIVATED at ICU Bay 4 (Floor 2)",
    deliveryStatus: "Delivered",
    timestamp: "2026-08-28 08:14",
  },
  {
    id: "udl-002",
    sourceModule: "F1 Appointments",
    recipientName: "Aarav Sharma",
    recipientUhid: "UHID-2026-8801",
    recipientContact: "+91 98450 12345",
    channel: "WhatsApp",
    templateUsed: "TPL-APT-REM-24H",
    messageSummary: "24-Hour Pre-visit reminder for Cardiology OPD consultation",
    deliveryStatus: "Read",
    timestamp: "2026-08-28 10:15",
  },
  {
    id: "udl-003",
    sourceModule: "F22 Reports Review",
    recipientName: "Sunita Reddy",
    recipientUhid: "UHID-2026-8802",
    recipientContact: "+91 97411 98765",
    channel: "WhatsApp",
    templateUsed: "TPL-REP-SIGN-OFF",
    messageSummary: "Lipid Profile verified report signed off by Dr. Arvind Kumar",
    deliveryStatus: "Read",
    timestamp: "2026-08-28 10:08",
  },
  {
    id: "udl-004",
    sourceModule: "F5 Follow-ups",
    recipientName: "Vikram Patel",
    recipientUhid: "UHID-2026-8803",
    recipientContact: "+91 99800 45678",
    channel: "WhatsApp",
    templateUsed: "TPL-FOL-DUE-7D",
    messageSummary: "7-Day post-op clinical follow-up recall reminder",
    deliveryStatus: "Delivered",
    timestamp: "2026-08-28 09:55",
  },
  {
    id: "udl-005",
    sourceModule: "F13 Lab",
    recipientName: "Attending Dr. Arvind Kumar",
    recipientContact: "+91 98450 99001",
    channel: "SMS",
    templateUsed: "TPL-CLN-PANIC-VAL",
    messageSummary: "CRITICAL PANIC: Serum Potassium 6.8 mEq/L (Ref: 3.5-5.0)",
    deliveryStatus: "Delivered",
    timestamp: "2026-08-28 09:15",
  },
  {
    id: "udl-006",
    sourceModule: "F14 Radiology",
    recipientName: "On-Call Neurosurgeon Dr. Verma",
    recipientContact: "+91 98450 77112",
    channel: "Phone Call",
    templateUsed: "TPL-CLN-PANIC-VAL",
    messageSummary: "RED FLAG ESCALATION: Acute Subdural Hematoma (Midline shift 6mm)",
    deliveryStatus: "Delivered",
    timestamp: "2026-08-28 08:50",
  },
  {
    id: "udl-007",
    sourceModule: "Reception",
    recipientName: "Rajesh Rao",
    recipientContact: "+91 99450 00112",
    channel: "SMS",
    templateUsed: "TPL-APT-CONFIRM",
    messageSummary: "Walk-in registration token #42 counter ready notice",
    deliveryStatus: "Failed",
    timestamp: "2026-08-28 09:20",
  },
];

// ==========================================
// 8. REPORT SIGN-OFF NOTIFICATIONS (F22 / F13 / F14)
// ==========================================
export const mockReportNotifications: ReportNotificationRecord[] = [
  {
    id: "repnotif-001",
    reportId: "LAB-REP-8790",
    patientName: "Sunita Reddy",
    patientUhid: "UHID-2026-8802",
    patientPhone: "+91 97411 98765",
    testName: "Lipid Profile",
    sourceModule: "F22 Reports Review",
    signedOffBy: "Dr. Arvind Kumar",
    kind: "sign_off",
    isCritical: false,
    channel: "WhatsApp",
    templateId: "TPL-REP-SIGN-OFF",
    status: "Read",
    dispatchedAt: "2026-08-28 10:08",
  },
  {
    id: "repnotif-002",
    reportId: "LAB-REP-8821",
    patientName: "Priya Nair",
    patientUhid: "UHID-2026-8810",
    patientPhone: "+91 98455 77889",
    testName: "Thyroid Profile",
    sourceModule: "F22 Reports Review",
    signedOffBy: "Dr. Rajesh Gupta",
    kind: "portal_ready",
    isCritical: false,
    channel: "Portal",
    templateId: "TPL-REP-SIGN-OFF",
    status: "Delivered",
    dispatchedAt: "2026-08-28 09:05",
  },
  {
    id: "repnotif-003",
    reportId: "LAB-CRIT-4412",
    patientName: "Aarav Sharma",
    patientUhid: "UHID-2026-8801",
    patientPhone: "+91 98450 12345",
    testName: "Serum Potassium",
    sourceModule: "F13 Lab",
    signedOffBy: "Chief Pathologist",
    kind: "panic_value",
    isCritical: true,
    channel: "SMS",
    templateId: "TPL-CLN-PANIC-VAL",
    status: "Delivered",
    dispatchedAt: "2026-08-28 09:15",
  },
  {
    id: "repnotif-004",
    reportId: "RAD-CT-3301",
    patientName: "Vikram Patel",
    patientUhid: "UHID-2026-8803",
    patientPhone: "+91 99800 45678",
    testName: "CT Brain (Non-contrast)",
    sourceModule: "F14 Radiology",
    signedOffBy: "Dr. Verma",
    kind: "panic_value",
    isCritical: true,
    channel: "Phone Call",
    templateId: "TPL-CLN-PANIC-VAL",
    status: "Delivered",
    dispatchedAt: "2026-08-28 08:50",
  },
  {
    id: "repnotif-005",
    reportId: "LAB-REP-8805",
    patientName: "Deepak Choudhury",
    patientUhid: "UHID-2026-8812",
    patientPhone: "+91 98770 99017",
    testName: "Pre-Operative Viral Serology",
    sourceModule: "F13 Lab",
    signedOffBy: "Dr. Arvind Joshi",
    kind: "sign_off",
    isCritical: false,
    channel: "WhatsApp",
    templateId: "TPL-REP-SIGN-OFF",
    status: "Scheduled",
    dispatchedAt: "2026-08-29 08:00",
  },
];

// ==========================================
// 9. FOLLOW-UP RECALLS (SOURCED FROM F5)
// ==========================================
export const mockFollowUpReminders: FollowUpReminderRecord[] = [
  {
    id: "furem-001",
    patientName: "Vikram Patel",
    patientUhid: "UHID-2026-8803",
    patientPhone: "+91 99800 45678",
    doctorName: "Dr. Arvind Kumar",
    department: "Neurology",
    dueDate: "2026-09-04",
    recallType: "PostOp",
    procedureOrCondition: "7-day post-procedure clinical review",
    channel: "WhatsApp",
    status: "Sent",
    scheduledFor: "2026-08-28 09:55",
  },
  {
    id: "furem-002",
    patientName: "Sunita Reddy",
    patientUhid: "UHID-2026-8802",
    patientPhone: "+91 97411 98765",
    doctorName: "Dr. Shweta Rao",
    department: "Orthopaedics",
    dueDate: "2026-09-02",
    recallType: "PostOp",
    procedureOrCondition: "Day-14 TKR wound & physiotherapy review",
    channel: "WhatsApp",
    status: "Pending",
    scheduledFor: "2026-08-29 09:00",
  },
  {
    id: "furem-003",
    patientName: "Meenakshi Iyer",
    patientUhid: "UHID-2026-8804",
    patientPhone: "+91 98860 33445",
    doctorName: "Dr. Arvind Kumar",
    department: "General Medicine",
    dueDate: "2026-08-27",
    recallType: "ChronicReview",
    procedureOrCondition: "Hypertension / diabetes quarterly clinic",
    channel: "SMS",
    status: "Overdue",
    scheduledFor: "2026-08-26 10:00",
  },
  {
    id: "furem-004",
    patientName: "Aarav Sharma",
    patientUhid: "UHID-2026-8801",
    patientPhone: "+91 98450 12345",
    doctorName: "Dr. Arvind Kumar",
    department: "Cardiology",
    dueDate: "2026-09-10",
    recallType: "DiagnosticRepeat",
    procedureOrCondition: "Repeat Lipid Profile after statin initiation",
    channel: "WhatsApp",
    status: "Confirmed",
    scheduledFor: "2026-08-27 16:20",
  },
  {
    id: "furem-005",
    patientName: "Ananya Deshmukh",
    patientUhid: "UHID-2026-8806",
    patientPhone: "+91 98453 99887",
    doctorName: "Dr. Priya Nair",
    department: "Gynaecology",
    dueDate: "2026-09-05",
    recallType: "PostOp",
    procedureOrCondition: "Post-LSCS wound and BP review",
    channel: "WhatsApp",
    status: "Pending",
    scheduledFor: "2026-08-29 11:30",
  },
];

export const mockMedicationReminders: MedicationReminderItem[] = [
  {
    id: "medrem-001",
    patientName: "Aarav Sharma",
    patientUhid: "UHID-2026-8801",
    patientPhone: "+91 98450 12345",
    doctorName: "Dr. Arvind Kumar",
    type: "Medication",
    medicationOrService: "Metoprolol 25 mg — after renal panel clearance",
    frequency: "Once daily (AM)",
    scheduledTime: "Today 08:00",
    channel: "WhatsApp",
    status: "Sent",
  },
  {
    id: "medrem-002",
    patientName: "Sunita Reddy",
    patientUhid: "UHID-2026-8802",
    patientPhone: "+91 97411 98765",
    doctorName: "Dr. Shweta Rao",
    type: "FollowUp",
    medicationOrService: "Orthopaedics OPD — Day 14 TKR review",
    frequency: "One-time recall",
    scheduledTime: "Tomorrow 09:00",
    channel: "WhatsApp",
    status: "Pending",
  },
  {
    id: "medrem-003",
    patientName: "Meenakshi Iyer",
    patientUhid: "UHID-2026-8804",
    patientPhone: "+91 98860 33445",
    doctorName: "Dr. Arvind Kumar",
    type: "LabTest",
    medicationOrService: "HbA1c & fasting lipid panel repeat",
    frequency: "Quarterly",
    scheduledTime: "Today 10:00",
    channel: "SMS",
    status: "Pending",
  },
  {
    id: "medrem-004",
    patientName: "Vikram Patel",
    patientUhid: "UHID-2026-8803",
    patientPhone: "+91 99800 45678",
    doctorName: "Dr. Arvind Kumar",
    type: "FollowUp",
    medicationOrService: "Neurology post-procedure 7-day recall",
    frequency: "One-time recall",
    scheduledTime: "Dispatched 2026-08-28 09:55",
    channel: "WhatsApp",
    status: "Sent",
  },
];
