import {
  ArticleItem,
  VideoAssetItem,
  PatientEducationItem,
  DoctorContentItem,
  DepartmentContentItem,
} from "@/hospital-admin/lib/types";

// ==========================================
// 1. ARTICLES MOCK DATA
// ==========================================
export const mockArticles: ArticleItem[] = [
  {
    id: "art-101",
    title: "Recognizing Early Signs of Coronary Artery Disease: When to Seek Emergency Care",
    slug: "recognizing-early-signs-coronary-artery-disease",
    category: "Preventive Care",
    summary:
      "A comprehensive clinical guide explaining chest discomfort vs angina, atypical presentation in diabetics, and when to activate emergency Code STEMI protocols.",
    body: `Coronary Artery Disease (CAD) remains one of the leading causes of acute myocardial infarction worldwide. While classic retrosternal chest pain is the most recognized symptom, atypical presentations—such as unexplained fatigue, jaw radiation, or epigastric discomfort—frequently occur in female patients and individuals with diabetes mellitus.\n\n### Clinical Red Flags\n1. Substernal pressure lasting > 15 minutes\n2. Pain radiating to the left arm, neck, or interscapular region\n3. Diaphoresis, syncope, or profound dyspnea upon mild exertion\n\n### Hospital Emergency Protocols\nImmediate 12-lead ECG within 10 minutes of arrival at the Emergency Department ensures door-to-balloon intervals remain below the NABH standard of 90 minutes.`,
    authorId: "doc-101",
    authorName: "Dr. Arvind Kumar",
    authorRole: "Chief Cardiologist & Interventional Director",
    coverImage: "/images/blog/cardiology-hero.jpg",
    readTimeMinutes: 5,
    tags: ["Cardiology", "Heart Health", "Emergency Care", "NABH Guidelines"],
    status: "Published",
    version: 1,
    clinicalReview: {
      id: "rev-art-101",
      contentId: "art-101",
      contentType: "Articles",
      reviewerDoctorId: "doc-102",
      reviewerDoctorName: "Dr. Sunita Rao",
      reviewerSpecialty: "Cardiovascular Surgery",
      status: "Approved",
      nabhChecklist: {
        medicalAccuracy: true,
        referenceCitations: true,
        clearDisclaimer: true,
        noExaggeratedClaims: true,
      },
      reviewNotes: "Clinically precise. Door-to-balloon benchmark verified according to ACC/AHA guidelines.",
      reviewedAt: "2026-08-20 14:30",
    },
    publishedToPublic: true,
    hospitalProfileSynced: true,
    createdAt: "2026-08-18 10:00",
    updatedAt: "2026-08-20 15:00",
  },
  {
    id: "art-102",
    title: "Post-Operative Recovery and Wound Care Following Robotic Total Knee Replacement",
    slug: "post-op-recovery-robotic-knee-replacement",
    category: "Clinical Outcomes",
    summary:
      "Essential milestone rehabilitation protocols, surgical incision surveillance, and cryotherapy guidelines for patients post-robotic arthroplasty.",
    body: `Robotic-assisted total knee arthroplasty provides sub-millimeter precision in implant placement, resulting in reduced soft-tissue disruption and accelerated ambulation.\n\n### Phase 1: Days 1 to 7\n- Early weight-bearing with walker support within 6 hours post-op.\n- Continuous passive motion and quadriceps strengthening sets.\n- Waterproof dressing inspection; report any localized erythema or purulent drainage immediately.\n\n### Phase 2: Weeks 2 to 6\nTransition to single-point cane and outpatient physical therapy regimens.`,
    authorId: "doc-103",
    authorName: "Dr. Rajeshwar Singh",
    authorRole: "Senior Joint Replacement Surgeon",
    readTimeMinutes: 6,
    tags: ["Orthopaedics", "Joint Replacement", "Rehabilitation", "Post-Op"],
    status: "Published",
    version: 1,
    clinicalReview: {
      id: "rev-art-102",
      contentId: "art-102",
      contentType: "Articles",
      reviewerDoctorId: "doc-104",
      reviewerDoctorName: "Dr. Arvind Kumar",
      reviewerSpecialty: "Cardiology",
      status: "Approved",
      nabhChecklist: {
        medicalAccuracy: true,
        referenceCitations: true,
        clearDisclaimer: true,
        noExaggeratedClaims: true,
      },
      reviewNotes: "Rehab phases align with hospital joint pathway protocols.",
      reviewedAt: "2026-08-22 11:15",
    },
    publishedToPublic: true,
    hospitalProfileSynced: true,
    createdAt: "2026-08-21 09:30",
    updatedAt: "2026-08-22 11:30",
  },
  {
    id: "art-103",
    title: "Understanding Glioblastoma Multiforme: Advancements in Intraoperative MRI Navigation",
    slug: "understanding-glioblastoma-intraoperative-mri",
    category: "Clinical Outcomes",
    summary:
      "A clinical review of surgical resection boundaries assisted by 3T Intraoperative MRI and 5-ALA fluorescence-guided neurosurgery.",
    body: `Maximizing the extent of resection (EOR) while preserving eloquent neurological function is the cornerstone of malignant glioma management. Real-time intraoperative MRI allows the surgical team to scan for residual margins before dural closure.`,
    authorId: "doc-105",
    authorName: "Dr. Meenakshi Sundaram",
    authorRole: "Director of Neurosurgery",
    readTimeMinutes: 8,
    tags: ["Neurosurgery", "Brain Tumor", "iMRI", "Oncology"],
    status: "In Review",
    version: 1,
    publishedToPublic: false,
    hospitalProfileSynced: false,
    createdAt: "2026-08-28 16:45",
    updatedAt: "2026-08-28 16:45",
  },
  {
    id: "art-104",
    title: "Glycemic Control & Diabetic Foot Ulcer Prevention: Evidence-Based Guidelines",
    slug: "glycemic-control-diabetic-foot-ulcer-prevention",
    category: "Disease Awareness",
    summary:
      "Preventive foot hygiene, monofilament neuropathy screening, and early vascular consult triggers for chronic diabetes management.",
    body: `Peripheral neuropathy and microvascular compromise significantly elevate the risk of silent ulceration. Daily self-examination and specialized podiatric footwear are critical non-pharmacological interventions.`,
    authorId: "doc-106",
    authorName: "Dr. Priya Deshmukh",
    authorRole: "Consultant Endocrinologist",
    readTimeMinutes: 4,
    tags: ["Endocrinology", "Diabetes", "Preventive Health"],
    status: "Draft",
    version: 1,
    publishedToPublic: false,
    hospitalProfileSynced: false,
    createdAt: "2026-08-29 08:30",
    updatedAt: "2026-08-29 08:30",
  },
];

// ==========================================
// 2. VIDEOS MOCK DATA (EXTENDS MediaAsset)
// ==========================================
export const mockVideos: VideoAssetItem[] = [
  {
    id: "vid-201",
    title: "Pre-Operative Fasting Guidelines: What You Must Know Before General Anesthesia",
    description:
      "Dr. Arvind Kumar explains the American Society of Anesthesiologists (ASA) 6-2 fasting rules (clear fluids vs solid meals) to ensure safe surgical induction.",
    category: "Patient Education",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    thumbnailUrl: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=800&q=80",
    durationSeconds: 245,
    quality: "1080p",
    departmentId: "dept-anaesthesia",
    departmentName: "Anesthesiology & OT",
    doctorId: "doc-101",
    doctorName: "Dr. Arvind Kumar",
    hasCaptions: true,
    status: "Published",
    requiresClinicalReview: true,
    clinicalReview: {
      id: "rev-vid-201",
      contentId: "vid-201",
      contentType: "Videos",
      reviewerDoctorId: "doc-107",
      reviewerDoctorName: "Dr. Farooq Abdullah",
      reviewerSpecialty: "Anesthesiology",
      status: "Approved",
      nabhChecklist: {
        medicalAccuracy: true,
        referenceCitations: true,
        clearDisclaimer: true,
        noExaggeratedClaims: true,
      },
      reviewNotes: "Adheres strictly to ASA fasting protocols.",
      reviewedAt: "2026-08-15 10:00",
    },
    publishedToPublic: true,
    createdAt: "2026-08-14 11:00",
  },
  {
    id: "vid-202",
    title: "Virtual Walkthrough: Level 1 Trauma Care Center & Resuscitation Bay",
    description:
      "360-degree interactive tour of our 24/7 Emergency Triage, Trauma Bays, and dedicated CT Suite.",
    category: "Facility Tour",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    thumbnailUrl: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&q=80",
    durationSeconds: 380,
    quality: "4K",
    departmentId: "dept-emg",
    departmentName: "Emergency & Trauma",
    hasCaptions: true,
    status: "Published",
    requiresClinicalReview: false,
    publishedToPublic: true,
    createdAt: "2026-08-10 14:20",
  },
  {
    id: "vid-203",
    title: "Understanding Minimally Invasive Coronary Angiography (Radial Approach)",
    description:
      "Animated procedure explanation showing catheter navigation via the wrist artery with same-day discharge criteria.",
    category: "Procedure Explainer",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    thumbnailUrl: "https://images.unsplash.com/photo-1628348068343-c6a848d2b6dd?w=800&q=80",
    durationSeconds: 310,
    quality: "1080p",
    departmentId: "dept-cardio",
    departmentName: "Cardiology",
    doctorId: "doc-101",
    doctorName: "Dr. Arvind Kumar",
    hasCaptions: true,
    status: "In Review",
    requiresClinicalReview: true,
    publishedToPublic: false,
    createdAt: "2026-08-27 16:00",
  },
  {
    id: "vid-204",
    title: "Meet Dr. Sunita Rao: Lead Cardiothoracic & Heart Transplant Surgeon",
    description:
      "Personal introduction, surgical philosophy, complex mitral valve repair experience, and patient consultation approach.",
    category: "Doctor Introduction",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    thumbnailUrl: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=800&q=80",
    durationSeconds: 190,
    quality: "1080p",
    departmentId: "dept-cardio",
    departmentName: "Cardiovascular Surgery",
    doctorId: "doc-102",
    doctorName: "Dr. Sunita Rao",
    hasCaptions: true,
    status: "Published",
    requiresClinicalReview: false,
    publishedToPublic: true,
    createdAt: "2026-08-05 09:00",
  },
];

// ==========================================
// 3. PATIENT EDUCATION MOCK DATA (PRE/POST-OP & LEAFLETS)
// ==========================================
export const mockPatientEducation: PatientEducationItem[] = [
  {
    id: "edu-301",
    title: "Pre-Operative Fasting & Medication Checklist (Cardiac Catheterization)",
    code: "GUIDE-CARD-001",
    type: "Pre-Op Guide",
    departmentId: "dept-cardio",
    departmentName: "Cardiology",
    procedureName: "Coronary Angiogram / Angioplasty",
    languages: ["English", "Hindi", "Kannada", "Tamil"],
    summary:
      "Mandatory 6-hour fasting instructions, anti-platelet / blood-thinner hold checklist, and admission desk reporting protocol.",
    contentSections: [
      {
        heading: "Fasting & Fluid Intake Rules",
        body: "No solid food or milk for 6 hours prior to your reporting time. You may sip up to 100ml of plain water up to 2 hours before admission.",
      },
      {
        heading: "Medication Directives",
        body: "Follow these specific instructions on the morning of procedure:",
        items: [
          "Take regular blood pressure medications with a small sip of water.",
          "Hold morning dose of oral diabetic medications / Metformin.",
          "If on Blood Thinners (Warfarin/Acitrom), verify your target INR has been checked within 48 hours.",
        ],
      },
      {
        heading: "What to Bring to the Hospital",
        body: "Government Photo ID (Aadhaar / Passport), insurance card, and all recent original diagnostic test reports.",
      },
    ],
    downloadUrl: "/downloads/guides/preop-cardiac-cath.pdf",
    destination: "Both",
    triggeredByTrigger: "F6 Surgery Scheduled",
    status: "Published",
    version: 1,
    clinicalReview: {
      id: "rev-edu-301",
      contentId: "edu-301",
      contentType: "Patient Education",
      reviewerDoctorId: "doc-101",
      reviewerDoctorName: "Dr. Arvind Kumar",
      reviewerSpecialty: "Cardiology",
      status: "Approved",
      nabhChecklist: {
        medicalAccuracy: true,
        referenceCitations: true,
        clearDisclaimer: true,
        noExaggeratedClaims: true,
      },
      reviewNotes: "Approved for automated WhatsApp dispatch via Communication Hub.",
      reviewedAt: "2026-08-10 16:00",
    },
    dispatchCount: 142,
    createdAt: "2026-08-08 12:00",
    updatedAt: "2026-08-10 16:00",
  },
  {
    id: "edu-302",
    title: "Post-Discharge Wound Care & Warning Signs (Total Hip Replacement)",
    code: "GUIDE-ORTH-002",
    type: "Post-Op Guide",
    departmentId: "dept-ortho",
    departmentName: "Orthopaedics",
    procedureName: "Total Hip Arthroplasty",
    languages: ["English", "Hindi", "Telugu"],
    summary:
      "Incision dressing care, anti-thromboembolic exercises, deep vein thrombosis (DVT) warning signs, and follow-up appointment timeline.",
    contentSections: [
      {
        heading: "Incision & Showering Protocol",
        body: "Keep the waterproof silver-impregnated dressing intact for 10 days. Do not soak in bathtubs or apply unprescribed topical ointments.",
      },
      {
        heading: "Immediate Escalation Red Flags",
        body: "Contact Emergency Care (080-49112200) immediately if you experience:",
        items: [
          "Sudden calf tenderness, swelling, or unilateral leg heat (possible DVT).",
          "Persistent oral temperature > 100.4°F (38°C).",
          "Sudden onset shortness of breath or pleuritic chest pain.",
        ],
      },
      {
        heading: "Mobility Precautions",
        body: "Maintain 90-degree hip flexion limits and use an elevated toilet seat for the first 6 weeks.",
      },
    ],
    downloadUrl: "/downloads/guides/postop-hip-care.pdf",
    destination: "Targeted Patient Dispatch",
    triggeredByTrigger: "F5 Discharge",
    status: "Published",
    version: 1,
    clinicalReview: {
      id: "rev-edu-302",
      contentId: "edu-302",
      contentType: "Patient Education",
      reviewerDoctorId: "doc-103",
      reviewerDoctorName: "Dr. Rajeshwar Singh",
      reviewerSpecialty: "Orthopaedics",
      status: "Approved",
      nabhChecklist: {
        medicalAccuracy: true,
        referenceCitations: true,
        clearDisclaimer: true,
        noExaggeratedClaims: true,
      },
      reviewNotes: "NABH compliant discharge education material.",
      reviewedAt: "2026-08-12 11:30",
    },
    dispatchCount: 88,
    createdAt: "2026-08-11 14:00",
    updatedAt: "2026-08-12 11:30",
  },
  {
    id: "edu-303",
    title: "Low Sodium DASH Diet for Hypertension Management",
    code: "LEAF-DIET-003",
    type: "Leaflet",
    departmentId: "dept-med",
    departmentName: "General Medicine & Clinical Nutrition",
    languages: ["English", "Hindi", "Kannada", "Marathi", "Tamil"],
    summary:
      "A colorful clinical infographic outlining daily sodium limits (< 2,000 mg), potassium-rich alternatives, and hidden salt sources in packaged foods.",
    contentSections: [
      {
        heading: "Target Daily Intake",
        body: "Cap total dietary sodium at under 2,000 mg (approx 1 teaspoon of table salt). Use lemon juice, herbs, and garlic for flavor enhancement.",
      },
      {
        heading: "Recommended Foods",
        body: "Fresh leafy greens, whole grains, steamed legumes, skimmed dairy, and unsalted nuts.",
      },
    ],
    downloadUrl: "/downloads/leaflets/dash-diet-infographic.pdf",
    destination: "Both",
    status: "Published",
    version: 1,
    clinicalReview: {
      id: "rev-edu-303",
      contentId: "edu-303",
      contentType: "Patient Education",
      reviewerDoctorId: "doc-106",
      reviewerDoctorName: "Dr. Priya Deshmukh",
      reviewerSpecialty: "Endocrinology",
      status: "Approved",
      nabhChecklist: {
        medicalAccuracy: true,
        referenceCitations: true,
        clearDisclaimer: true,
        noExaggeratedClaims: true,
      },
      reviewNotes: "Nutrition guidelines match Indian Council of Medical Research (ICMR) norms.",
      reviewedAt: "2026-08-16 09:00",
    },
    dispatchCount: 310,
    createdAt: "2026-08-15 10:00",
    updatedAt: "2026-08-16 09:00",
  },
  {
    id: "edu-304",
    title: "Pre-Procedural Instructions: Contrast Enhanced MRI & CT Scans",
    code: "GUIDE-RAD-004",
    type: "Pre-Op Guide",
    departmentId: "dept-rad",
    departmentName: "Radiology & Imaging",
    procedureName: "Contrast CT / MRI Scan",
    languages: ["English", "Hindi"],
    summary:
      "Serum creatinine threshold check (< 1.5 mg/dL), 4-hour fasting before IV contrast, and metallic implant screening questionnaire.",
    contentSections: [
      {
        heading: "Renal Function Safety Check",
        body: "A valid Serum Creatinine / eGFR lab report within 30 days is mandatory prior to IV Gadolinium or Iodinated contrast administration.",
      },
      {
        heading: "MRI Safety Screening",
        body: "Notify radiology staff immediately if you have a cardiac pacemaker, cochlear implant, aneurysm clips, or metallic fragments in your eyes.",
      },
    ],
    downloadUrl: "/downloads/guides/radiology-contrast-prep.pdf",
    destination: "Both",
    triggeredByTrigger: "General",
    status: "In Review",
    version: 1,
    dispatchCount: 0,
    createdAt: "2026-08-28 14:00",
    updatedAt: "2026-08-28 14:00",
  },
];

// ==========================================
// 4. DOCTOR CONTENT MOCK DATA
// ==========================================
export const mockDoctorContent: DoctorContentItem[] = [
  {
    id: "doc-cnt-401",
    title: "Clinical Pearl: Distinguishing Musculoskeletal Chest Pain from Ischemic Angina",
    doctorId: "doc-101",
    doctorName: "Dr. Arvind Kumar",
    doctorSpecialty: "Cardiology",
    doctorUhid: "DOC-2026-CARD-01",
    isDoctorVerified: true,
    contentType: "Health Tip",
    summary:
      "A quick diagnostic aid on palpation tenderness (costochondritis) vs positional pleuritic friction rubs vs pressure-type angina.",
    content: `Point tenderness over the costochondral junctions reproducing the patient's exact symptoms strongly suggests Tietze syndrome or costochondritis. However, in elderly or diabetic cohorts, never defer a baseline 12-lead ECG and Troponin panel solely based on tenderness.`,
    tags: ["Clinical Pearl", "Cardiology", "Triage"],
    status: "Published",
    syncedWithDoctorBio: true,
    clinicalReview: {
      id: "rev-doc-401",
      contentId: "doc-cnt-401",
      contentType: "Doctor Content",
      reviewerDoctorId: "doc-102",
      reviewerDoctorName: "Dr. Sunita Rao",
      reviewerSpecialty: "Cardiovascular Surgery",
      status: "Approved",
      nabhChecklist: {
        medicalAccuracy: true,
        referenceCitations: true,
        clearDisclaimer: true,
        noExaggeratedClaims: true,
      },
      reviewNotes: "Clinical reasoning is sound.",
      reviewedAt: "2026-08-19 14:00",
    },
    createdAt: "2026-08-18 17:00",
  },
  {
    id: "doc-cnt-402",
    title: "Case Study: Successful Hybrid Revascularization in Multivessel CAD with Low EF",
    doctorId: "doc-102",
    doctorName: "Dr. Sunita Rao",
    doctorSpecialty: "Cardiovascular Surgery",
    doctorUhid: "DOC-2026-CTVS-02",
    isDoctorVerified: true,
    contentType: "Case Study",
    summary:
      "Minimally invasive LIMA-to-LAD off-pump bypass combined with staged PCI to the circumflex artery in a 64-year-old with EF 28%.",
    content: `Hybrid Coronary Revascularization (HCR) leverages the longevity of internal mammary grafting with the minimal morbidity of catheter-based stenting. The patient was extubated within 3 hours and discharged on Day 4 with marked functional class improvement.`,
    tags: ["Case Study", "Hybrid CTVS", "Complex CAD"],
    status: "Published",
    syncedWithDoctorBio: true,
    clinicalReview: {
      id: "rev-doc-402",
      contentId: "doc-cnt-402",
      contentType: "Doctor Content",
      reviewerDoctorId: "doc-101",
      reviewerDoctorName: "Dr. Arvind Kumar",
      reviewerSpecialty: "Cardiology",
      status: "Approved",
      nabhChecklist: {
        medicalAccuracy: true,
        referenceCitations: true,
        clearDisclaimer: true,
        noExaggeratedClaims: true,
      },
      reviewNotes: "Excellent surgical case documentation with de-identified patient data.",
      reviewedAt: "2026-08-21 16:30",
    },
    createdAt: "2026-08-20 11:00",
  },
  {
    id: "doc-cnt-403",
    title: "Joint Preservation Techniques: When is Cartilage Restoration Viable?",
    doctorId: "doc-103",
    doctorName: "Dr. Rajeshwar Singh",
    doctorSpecialty: "Orthopaedics",
    doctorUhid: "DOC-2026-ORTH-03",
    isDoctorVerified: true,
    contentType: "Specialty Guide",
    summary:
      "Evaluating Autologous Chondrocyte Implantation (ACI) and OATS mosaicplasty in active young adults under 45.",
    content: `Focal Outerbridge Grade III/IV cartilage lesions in high-demand young athletes present unique dilemmas. Where mechanical alignment is preserved, cellular chondrocyte restoration yields superior longevity over early unicompartmental arthroplasty.`,
    tags: ["Cartilage Restoration", "Sports Orthopaedics"],
    status: "In Review",
    syncedWithDoctorBio: false,
    createdAt: "2026-08-28 10:00",
  },
];

// ==========================================
// 5. DEPARTMENT CONTENT MOCK DATA
// ==========================================
export const mockDepartmentContent: DepartmentContentItem[] = [
  {
    id: "dept-cnt-501",
    title: "Cardiology Care Pathway: Comprehensive Chest Pain Triage & Rapid Cath Protocol",
    departmentId: "dept-cardio",
    departmentName: "Cardiology & Interventional Sciences",
    contentType: "Care Pathway",
    summary:
      "Standardized 24/7 Primary Angioplasty pathway detailing emergency ECG capture, high-sensitivity troponin timelines, and radial access recovery.",
    content: `Our accredited Chest Pain Unit maintains an unbroken record of under-45-minute door-to-balloon time. With state-of-the-art dual flat-panel digital Cath Labs and intravascular ultrasound (IVUS), patients receive tertiary-grade cardiovascular care.`,
    status: "Published",
    syncedWithDepartmentCuration: true,
    clinicalReview: {
      id: "rev-dept-501",
      contentId: "dept-cnt-501",
      contentType: "Department Content",
      reviewerDoctorId: "doc-101",
      reviewerDoctorName: "Dr. Arvind Kumar",
      reviewerSpecialty: "Cardiology",
      status: "Approved",
      nabhChecklist: {
        medicalAccuracy: true,
        referenceCitations: true,
        clearDisclaimer: true,
        noExaggeratedClaims: true,
      },
      reviewNotes: "Clinical pathway aligned with hospital SOPs.",
      reviewedAt: "2026-08-14 18:00",
    },
    createdAt: "2026-08-12 10:00",
  },
  {
    id: "dept-cnt-502",
    title: "Orthopaedic Department Milestone: 1,000 Robotic Joint Replacements Completed",
    departmentId: "dept-ortho",
    departmentName: "Orthopaedics & Joint Reconstruction",
    contentType: "Clinical Milestone",
    summary:
      "Celebrating 1,000 successful Mako robotic-arm assisted knee and hip surgeries with zero deep surgical site infections.",
    content: `Our orthopaedic surgical team reached a landmark milestone of 1,000 robotic joint procedures. Post-operative telemetry confirms an average hospital stay of just 2.1 days, with 98.4% patient satisfaction at 90-day follow-up.`,
    status: "Published",
    syncedWithDepartmentCuration: true,
    clinicalReview: {
      id: "rev-dept-502",
      contentId: "dept-cnt-502",
      contentType: "Department Content",
      reviewerDoctorId: "doc-103",
      reviewerDoctorName: "Dr. Rajeshwar Singh",
      reviewerSpecialty: "Orthopaedics",
      status: "Approved",
      nabhChecklist: {
        medicalAccuracy: true,
        referenceCitations: true,
        clearDisclaimer: true,
        noExaggeratedClaims: true,
      },
      reviewNotes: "Audited figures verified by Quality & Compliance committee.",
      reviewedAt: "2026-08-18 12:00",
    },
    createdAt: "2026-08-17 15:00",
  },
  {
    id: "dept-cnt-503",
    title: "Neuroscience Technology Guide: 3T Intraoperative MRI & StealthStation Neuronavigation",
    departmentId: "dept-neuro",
    departmentName: "Neurosurgery & Spine Institute",
    contentType: "Technology Guide",
    summary:
      "How optical neuronavigation and real-time intraoperative MRI enable sub-millimeter surgical precision in deep brain lesions.",
    content: `Sub-millimeter cranial stereotaxy allows our neurosurgical faculty to map vital motor and speech tracts during tumor resection, dramatically minimizing post-operative functional deficits.`,
    status: "In Review",
    syncedWithDepartmentCuration: false,
    createdAt: "2026-08-28 11:30",
  },
];
