export interface DepartmentData {
  id: string;
  name: string;
  type: string;
  categoryId?: string;
  categoryName?: string;
  description?: string;
  location: string;
  floor: string;
  headName: string;
  headTitle: string;
  activePatients: number;
  bedCapacity?: number;
  occupiedBeds?: number;
  status: "active" | "warning" | "critical";
  operatingHours: string;
  shiftModel: string;
  nurseStations: string[];
  scope: {
    clinicalProcedures: string[];
    bedAllocationRights: string;
    equipmentReady: string[];
    supervisionLevel: string;
    delegationLimits: string;
  };
  activePatientsList: Array<{
    id: string;
    name: string;
    qlynoId: string;
    age: number;
    gender: string;
    bedNumber: string;
    admittingDoctor: string;
    admissionDate: string;
    condition: string;
    status: "Stable" | "Critical" | "Under Observation" | "Pre-Op";
  }>;
  activeDoctorsList: Array<{
    id: string;
    name: string;
    specialty: string;
    qualification: string;
    experience: string;
    availability: "On-Duty" | "In-Surgery" | "On-Call" | "Consulting";
    rating: number;
  }>;
  activeNursesList: Array<{
    id: string;
    name: string;
    station: string;
    role: string;
    shift: string;
    status: "On-Duty" | "Break" | "Standby";
  }>;
  supportStaffList: Array<{
    id: string;
    name: string;
    role: string;
    taskScope: string;
    shift: string;
    status: "Active" | "On-Task";
  }>;
}

export interface DepartmentCategory {
  id: string;
  name: string;
  shortName: string;
  description: string;
  iconName: "Stethoscope" | "Scissors" | "Baby" | "Eye" | "Brain" | "ShieldCheck" | "HeartPulse" | "Building2" | "Activity" | string;
  themeColor: string;
  gradient: string;
  departmentCount: number;
  departments: DepartmentData[];
  keySpecialties?: string[];
}

export const detailedDepartments: DepartmentData[] = [
  // -------------------------------------------------------------
  // Category 1: Medicine & Specialised Medical Clinics (9 Depts)
  // -------------------------------------------------------------
  {
    id: "dep_med_01",
    name: "General Medicine / Internal Medicine",
    type: "Medicine",
    categoryId: "cat_medicine",
    categoryName: "Medicine & Specialised Medical Clinics",
    description: "First point of contact for adult illnesses, chronic diseases, and general wellness.",
    location: "Qlyno Multispecialty Hospital - Main Campus",
    floor: "1st Floor · Wing A",
    headName: "Dr. Simran Kaur",
    headTitle: "Chief of Internal Medicine",
    activePatients: 42,
    bedCapacity: 24,
    occupiedBeds: 18,
    status: "active",
    operatingHours: "08:00 AM – 08:00 PM (Daily)",
    shiftModel: "3-Shift Rotational",
    nurseStations: ["Station M1 (General Triage)"],
    scope: {
      clinicalProcedures: ["Adult primary evaluations", "Hypertension & metabolic management", "Infectious disease review"],
      bedAllocationRights: "General Ward Medicine Beds (M01-M24)",
      equipmentReady: ["Vital Signs Multipara", "Digital ECG", "Nebulization Station"],
      supervisionLevel: "Attending Consultant Level",
      delegationLimits: "Hospital Admin coordinates triage queues and bed assignment.",
    },
    activePatientsList: [
      { id: "pat_m01", name: "Aarav Shah", qlynoId: "QLY-PAT-2024-00841", age: 42, gender: "Male", bedNumber: "M-04", admittingDoctor: "Dr. Simran Kaur", admissionDate: "2026-08-14", condition: "Hypertension & Fever Workup", status: "Stable" },
      { id: "pat_m02", name: "Ibrahim Sheikh", qlynoId: "QLY-PAT-2022-00187", age: 58, gender: "Male", bedNumber: "M-08", admittingDoctor: "Dr. Simran Kaur", admissionDate: "2026-08-13", condition: "Type 2 Diabetes Review", status: "Stable" },
    ],
    activeDoctorsList: [
      { id: "doc_007", name: "Dr. Simran Kaur", specialty: "General Medicine", qualification: "MBBS, MD (Medicine)", experience: "12 yrs", availability: "Consulting", rating: 4.9 },
      { id: "doc_008", name: "Dr. Aditya Verma", specialty: "Internal Medicine", qualification: "MBBS, MD", experience: "8 yrs", availability: "On-Duty", rating: 4.7 },
    ],
    activeNursesList: [{ id: "nur_m01", name: "Pooja Hegde", station: "Station M1", role: "Senior Staff Nurse", shift: "Morning", status: "On-Duty" }],
    supportStaffList: [{ id: "sup_m01", name: "Ramesh Pawar", role: "Ward Attendant", taskScope: "General support", shift: "Morning", status: "Active" }],
  },
  {
    id: "dep_med_02",
    name: "Cardiology",
    type: "Cardiology",
    categoryId: "cat_medicine",
    categoryName: "Medicine & Specialised Medical Clinics",
    description: "Management of heart conditions, hypertension, chest pain, and routine ECG/Echocardiogram follow-ups.",
    location: "Qlyno Multispecialty Hospital - Main Campus",
    floor: "2nd Floor · Cardiac Wing",
    headName: "Dr. Ananya Rao",
    headTitle: "Director of Interventional Cardiology",
    activePatients: 28,
    bedCapacity: 16,
    occupiedBeds: 14,
    status: "active",
    operatingHours: "08:00 AM – 08:00 PM (24x7 Cath Lab On-Call)",
    shiftModel: "3-Shift Cardiac Critical Care",
    nurseStations: ["Station CCU-1", "Station Cardiac OPD"],
    scope: {
      clinicalProcedures: ["2D Echocardiography", "Stress ECG (TMT)", "Holter telemetry", "Post-angioplasty reviews"],
      bedAllocationRights: "Cardiac Care Unit (CCU) and Post-Cath Beds",
      equipmentReady: ["GE Vivid E95 Echo", "Philips 12-lead ECG", "Defibrillator Crash Cart"],
      supervisionLevel: "Senior Interventional Cardiologist",
      delegationLimits: "Emergency alert dispatch managed by ER/IPD admin console.",
    },
    activePatientsList: [
      { id: "pat_c01", name: "Rohan Verma", qlynoId: "QLY-PAT-2024-00128", age: 52, gender: "Male", bedNumber: "CCU-02", admittingDoctor: "Dr. Ananya Rao", admissionDate: "2026-08-12", condition: "Post-PCI Day 3 Review", status: "Stable" },
    ],
    activeDoctorsList: [
      { id: "doc_001", name: "Dr. Ananya Rao", specialty: "Cardiology", qualification: "MBBS, MD, DM (Cardiology)", experience: "14 yrs", availability: "Consulting", rating: 4.9 },
      { id: "doc_card_2", name: "Dr. Vikram Seth", specialty: "Interventional Cardiology", qualification: "MBBS, DM", experience: "11 yrs", availability: "On-Call", rating: 4.8 },
    ],
    activeNursesList: [{ id: "nur_c01", name: "Zoya Ansari", station: "Station CCU-1", role: "Cardiac Nurse Specialist", shift: "Morning", status: "On-Duty" }],
    supportStaffList: [{ id: "sup_c01", name: "Kiran Shinde", role: "ECG Technician", taskScope: "Cardiac diagnostics", shift: "Morning", status: "Active" }],
  },
  {
    id: "dep_med_03",
    name: "Neurology",
    type: "Neurology",
    categoryId: "cat_medicine",
    categoryName: "Medicine & Specialised Medical Clinics",
    description: "Consultations for headaches, epilepsy, stroke follow-ups, and neuromuscular disorders.",
    location: "Qlyno Multispecialty Hospital - Main Campus",
    floor: "3rd Floor · Neurosciences Block",
    headName: "Dr. Kavya Iyer",
    headTitle: "Chief Neurologist",
    activePatients: 22,
    bedCapacity: 14,
    occupiedBeds: 10,
    status: "active",
    operatingHours: "09:00 AM – 06:00 PM (Daily)",
    shiftModel: "2-Shift Neuro OPD",
    nurseStations: ["Station Neuro-1"],
    scope: {
      clinicalProcedures: ["Electroencephalography (EEG)", "Nerve Conduction Studies (NCS/EMG)", "Stroke follow-up clinic"],
      bedAllocationRights: "Stroke Unit and Neuro-Stepdown Beds",
      equipmentReady: ["Digital 32-Channel EEG", "Nihon Kohden EMG", "Carotid Doppler"],
      supervisionLevel: "Attending Consultant Neurologist",
      delegationLimits: "Admin coordinates EEG slot appointments and token queue.",
    },
    activePatientsList: [
      { id: "pat_n01", name: "Suresh Kulkarni", qlynoId: "QLY-PAT-2022-00341", age: 48, gender: "Male", bedNumber: "NEU-04", admittingDoctor: "Dr. Kavya Iyer", admissionDate: "2026-08-11", condition: "Intractable Migraine", status: "Stable" },
    ],
    activeDoctorsList: [
      { id: "doc_003", name: "Dr. Kavya Iyer", specialty: "Neurology", qualification: "MBBS, DM (Neurology)", experience: "10 yrs", availability: "Consulting", rating: 4.8 },
    ],
    activeNursesList: [{ id: "nur_n01", name: "Suman Rao", station: "Station Neuro-1", role: "Staff Nurse", shift: "Morning", status: "On-Duty" }],
    supportStaffList: [{ id: "sup_n01", name: "Girish Mane", role: "EEG Tech", taskScope: "Diagnostic support", shift: "Morning", status: "Active" }],
  },
  {
    id: "dep_med_04",
    name: "Gastroenterology",
    type: "Gastroenterology",
    categoryId: "cat_medicine",
    categoryName: "Medicine & Specialised Medical Clinics",
    description: "Diagnosis of digestive tract issues, liver conditions, and scheduling of outpatient endoscopies.",
    location: "Qlyno Multispecialty Hospital - Main Campus",
    floor: "2nd Floor · Wing B",
    headName: "Dr. Rajiv Singhal",
    headTitle: "Senior Consultant Gastroenterologist",
    activePatients: 19,
    bedCapacity: 12,
    occupiedBeds: 8,
    status: "active",
    operatingHours: "08:30 AM – 05:30 PM (Mon–Sat)",
    shiftModel: "2-Shift Day-Care Endoscopy",
    nurseStations: ["Station GI-Daycare"],
    scope: {
      clinicalProcedures: ["Upper GI Endoscopy", "Colonoscopy", "FibroScan Liver Elastography", "IBD Management"],
      bedAllocationRights: "Endoscopy Day-Care Recovery Suites",
      equipmentReady: ["Olympus EVIS X1 Endoscopy System", "FibroScan 530 Compact", "Cautery Unit"],
      supervisionLevel: "Consultant Medical Gastroenterologist",
      delegationLimits: "Pre-procedure sedation clearance governed by clinical team.",
    },
    activePatientsList: [],
    activeDoctorsList: [
      { id: "doc_g01", name: "Dr. Rajiv Singhal", specialty: "Gastroenterology", qualification: "MBBS, MD, DM", experience: "16 yrs", availability: "Consulting", rating: 4.9 },
    ],
    activeNursesList: [{ id: "nur_g01", name: "Sunita G.", station: "Station GI-Daycare", role: "Endoscopy Nurse", shift: "Morning", status: "On-Duty" }],
    supportStaffList: [{ id: "sup_g01", name: "Vinod T.", role: "Scope Technician", taskScope: "Disinfection & prep", shift: "Morning", status: "Active" }],
  },
  {
    id: "dep_med_05",
    name: "Endocrinology",
    type: "Endocrinology",
    categoryId: "cat_medicine",
    categoryName: "Medicine & Specialised Medical Clinics",
    description: "Management of diabetes, thyroid disorders, and hormonal imbalances.",
    location: "Qlyno Multispecialty Hospital - Main Campus",
    floor: "1st Floor · Wing C",
    headName: "Dr. Priya Sharma",
    headTitle: "Lead Endocrinologist",
    activePatients: 31,
    status: "active",
    operatingHours: "09:00 AM – 06:00 PM (Mon–Sat)",
    shiftModel: "General OPD",
    nurseStations: ["Station Endo-1"],
    scope: {
      clinicalProcedures: ["Continuous Glucose Monitoring (CGM)", "Insulin Pump Optimization", "Thyroid Biopsy / FNAC Follow-up"],
      bedAllocationRights: "Outpatient consult and day-care monitoring only",
      equipmentReady: ["HbA1c Point-of-Care Analyzer", "Continuous Glucose Monitors", "Bio-Thesiometer"],
      supervisionLevel: "Attending Consultant Endocrinologist",
      delegationLimits: "Diabetes educator counselling workflows.",
    },
    activePatientsList: [],
    activeDoctorsList: [
      { id: "doc_e01", name: "Dr. Priya Sharma", specialty: "Endocrinology", qualification: "MBBS, MD, DM (Endocrinology)", experience: "11 yrs", availability: "Consulting", rating: 4.8 },
    ],
    activeNursesList: [{ id: "nur_e01", name: "Radha K.", station: "Station Endo-1", role: "Diabetes Educator", shift: "Morning", status: "On-Duty" }],
    supportStaffList: [{ id: "sup_e01", name: "Pankaj D.", role: "Clinic Assistant", taskScope: "Log maintenance", shift: "Morning", status: "Active" }],
  },
  {
    id: "dep_med_06",
    name: "Nephrology",
    type: "Nephrology",
    categoryId: "cat_medicine",
    categoryName: "Medicine & Specialised Medical Clinics",
    description: "Care for chronic kidney diseases and managing outpatient dialysis protocols.",
    location: "Qlyno Multispecialty Hospital - Main Campus",
    floor: "Ground Floor · Dialysis Center",
    headName: "Dr. Harish Madhav",
    headTitle: "Chief of Nephrology & Dialysis",
    activePatients: 36,
    bedCapacity: 20,
    occupiedBeds: 18,
    status: "active",
    operatingHours: "06:00 AM – 10:00 PM (Mon–Sat, 3 Dialysis Shifts)",
    shiftModel: "3-Shift Dialysis Unit",
    nurseStations: ["Station Dialysis-1", "Station Dialysis-2"],
    scope: {
      clinicalProcedures: ["Hemodialysis", "Peritoneal Dialysis Catheter Review", "Kidney Transplant Follow-up", "Hypertensive Nephropathy Care"],
      bedAllocationRights: "20 Hemodialysis Stations (Dialysis Beds D01-D20)",
      equipmentReady: ["Fresenius 4008S Dialysis Machines", "RO Water Treatment Plant", "BIA Body Composition Analyzer"],
      supervisionLevel: "Senior Consultant Nephrologist",
      delegationLimits: "Dialysis slot scheduling and machine assignment overseen by Admin.",
    },
    activePatientsList: [
      { id: "pat_np01", name: "Mohan Das", qlynoId: "QLY-PAT-2023-00712", age: 62, gender: "Male", bedNumber: "D-03", admittingDoctor: "Dr. Harish Madhav", admissionDate: "2026-08-14", condition: "Maintenance Hemodialysis", status: "Stable" },
    ],
    activeDoctorsList: [
      { id: "doc_np01", name: "Dr. Harish Madhav", specialty: "Nephrology", qualification: "MBBS, MD, DNB (Nephrology)", experience: "15 yrs", availability: "Consulting", rating: 4.9 },
    ],
    activeNursesList: [{ id: "nur_np01", name: "Deepa Nair", station: "Station Dialysis-1", role: "Dialysis In-Charge", shift: "Morning", status: "On-Duty" }],
    supportStaffList: [{ id: "sup_np01", name: "Anil More", role: "Dialysis Technician", taskScope: "Dialyzer reprocessing", shift: "Morning", status: "Active" }],
  },
  {
    id: "dep_med_07",
    name: "Pulmonology / Respiratory Medicine",
    type: "Pulmonology",
    categoryId: "cat_medicine",
    categoryName: "Medicine & Specialised Medical Clinics",
    description: "Treatment for asthma, COPD, chronic coughs, and sleep disorders.",
    location: "Qlyno Multispecialty Hospital - Main Campus",
    floor: "3rd Floor · Respiratory Care Wing",
    headName: "Dr. Arvind Joshi",
    headTitle: "Consultant Pulmonologist & Sleep Specialist",
    activePatients: 24,
    status: "active",
    operatingHours: "08:30 AM – 06:30 PM (Daily)",
    shiftModel: "2-Shift Pulmonary Clinic",
    nurseStations: ["Station Resp-1"],
    scope: {
      clinicalProcedures: ["Spirometry & PFT", "Fiberoptic Bronchoscopy", "Overnight Polysomnography (Sleep Study)", "Allergy Testing"],
      bedAllocationRights: "Respiratory High-Dependency & Sleep Lab Beds",
      equipmentReady: ["Jaeger MasterScreen PFT", "Flexible Video Bronchoscope", "Philips Alice 6 Sleep Diagnostic"],
      supervisionLevel: "Attending Pulmonologist",
      delegationLimits: "Diagnostic test reporting validated by clinician.",
    },
    activePatientsList: [],
    activeDoctorsList: [
      { id: "doc_p01", name: "Dr. Arvind Joshi", specialty: "Pulmonology", qualification: "MBBS, MD (Pulmonary Medicine)", experience: "13 yrs", availability: "Consulting", rating: 4.8 },
    ],
    activeNursesList: [{ id: "nur_p01", name: "Kalyani T.", station: "Station Resp-1", role: "PFT Technician / Nurse", shift: "Morning", status: "On-Duty" }],
    supportStaffList: [{ id: "sup_p01", name: "Santosh K.", role: "Respiratory Tech", taskScope: "Equipment calibration", shift: "Morning", status: "Active" }],
  },
  {
    id: "dep_med_08",
    name: "Oncology",
    type: "Oncology",
    categoryId: "cat_medicine",
    categoryName: "Medicine & Specialised Medical Clinics",
    description: "Outpatient cancer consultations, treatment planning, and dedicated day-care chemotherapy units.",
    location: "Qlyno Multispecialty Hospital - Main Campus",
    floor: "4th Floor · Oncology Pavilion",
    headName: "Dr. Meenakshi Sundaram",
    headTitle: "Chief Medical Oncologist",
    activePatients: 26,
    bedCapacity: 15,
    occupiedBeds: 12,
    status: "active",
    operatingHours: "08:00 AM – 07:00 PM (Mon–Sat)",
    shiftModel: "Day-Care Chemotherapy Shifts",
    nurseStations: ["Station Chemo-Daycare"],
    scope: {
      clinicalProcedures: ["Chemotherapy Administration", "Targeted Immunotherapy Infusions", "Tumor Board Planning", "Post-Op Cancer Reviews"],
      bedAllocationRights: "15 Day-Care Infusion Chairs & Recliners",
      equipmentReady: ["Laminar Flow Cytotoxic Hood", "Infusion Pumps Multipara", "Port-a-Cath Flushing Kits"],
      supervisionLevel: "Senior Medical Oncologist",
      delegationLimits: "Cytotoxic dosage verification strictly dual-checked by clinical oncologists.",
    },
    activePatientsList: [
      { id: "pat_on01", name: "Geeta Sen", qlynoId: "QLY-PAT-2024-00451", age: 56, gender: "Female", bedNumber: "CH-04", admittingDoctor: "Dr. Meenakshi Sundaram", admissionDate: "2026-08-14", condition: "Cycle 3 Adjuvant Chemotherapy", status: "Stable" },
    ],
    activeDoctorsList: [
      { id: "doc_on01", name: "Dr. Meenakshi Sundaram", specialty: "Medical Oncology", qualification: "MBBS, MD, DM (Medical Oncology)", experience: "18 yrs", availability: "Consulting", rating: 4.9 },
    ],
    activeNursesList: [{ id: "nur_on01", name: "Sarita J.", station: "Station Chemo-Daycare", role: "Chemotherapy Certified Nurse", shift: "Morning", status: "On-Duty" }],
    supportStaffList: [{ id: "sup_on01", name: "Dinesh B.", role: "Pharmacy Runner", taskScope: "Cytotoxic delivery", shift: "Morning", status: "Active" }],
  },
  {
    id: "dep_med_09",
    name: "Rheumatology",
    type: "Rheumatology",
    categoryId: "cat_medicine",
    categoryName: "Medicine & Specialised Medical Clinics",
    description: "Management of autoimmune diseases, arthritis, and chronic joint pain.",
    location: "Qlyno Multispecialty Hospital - Main Campus",
    floor: "1st Floor · Wing D",
    headName: "Dr. Alok Verma",
    headTitle: "Consultant Rheumatologist",
    activePatients: 16,
    status: "active",
    operatingHours: "09:00 AM – 05:00 PM (Mon–Fri)",
    shiftModel: "Outpatient Speciality",
    nurseStations: ["Station Rheum-1"],
    scope: {
      clinicalProcedures: ["Intra-articular Joint Injections", "Biologic Infusions (Infliximab/Rituximab)", "Nailfold Capillaroscopy"],
      bedAllocationRights: "Infusion suite for biologics",
      equipmentReady: ["Musculoskeletal Ultrasound", "Nailfold Capillaroscope", "Centrifuge Unit"],
      supervisionLevel: "Consultant Rheumatologist",
      delegationLimits: "Biologic prior authorizations and protocol tracking.",
    },
    activePatientsList: [],
    activeDoctorsList: [
      { id: "doc_rh01", name: "Dr. Alok Verma", specialty: "Rheumatology", qualification: "MBBS, MD, DM", experience: "9 yrs", availability: "Consulting", rating: 4.7 },
    ],
    activeNursesList: [{ id: "nur_rh01", name: "Fatima K.", station: "Station Rheum-1", role: "Infusion Nurse", shift: "Morning", status: "On-Duty" }],
    supportStaffList: [{ id: "sup_rh01", name: "Mohan S.", role: "Clinic Coordinator", taskScope: "Patient recall", shift: "Morning", status: "Active" }],
  },

  // ---------------------------------------------------------------------------------
  // Category 2: Surgical Specialties (Pre- & Post-Operative OPD) (6 Depts)
  // ---------------------------------------------------------------------------------
  {
    id: "dep_surg_01",
    name: "General Surgery",
    type: "General Surgery",
    categoryId: "cat_surgical",
    categoryName: "Surgical Specialties (Pre- & Post-Operative OPD)",
    description: "Consultations for hernias, gallstones, appendicitis, and minor outpatient wound dressings.",
    location: "Qlyno Multispecialty Hospital - Main Campus",
    floor: "3rd Floor · Surgical Suite A",
    headName: "Dr. Rohan Mehta",
    headTitle: "Head of General & Laparoscopic Surgery",
    activePatients: 34,
    bedCapacity: 20,
    occupiedBeds: 16,
    status: "active",
    operatingHours: "08:00 AM – 08:00 PM (24x7 Emergency OT Cover)",
    shiftModel: "Rotational OT & Surgical Ward",
    nurseStations: ["Station Surg-1"],
    scope: {
      clinicalProcedures: ["Pre-operative surgical workups", "Laparoscopic consultation", "Minor surgical dressings & sutures", "Abscess drainages"],
      bedAllocationRights: "Surgical Inpatient Ward (Beds S01-S20)",
      equipmentReady: ["Surgical Dressing Trolley", "Cautery Pencil & Generator", "Sterile Minor OT Kit"],
      supervisionLevel: "Senior General Surgeon",
      delegationLimits: "OT slot bookings prioritized based on surgeon authorization.",
    },
    activePatientsList: [
      { id: "pat_sg01", name: "Kishore Kumar", qlynoId: "QLY-PAT-2024-00912", age: 46, gender: "Male", bedNumber: "S-05", admittingDoctor: "Dr. Rohan Mehta", admissionDate: "2026-08-13", condition: "Laparoscopic Cholecystectomy Post-Op Day 1", status: "Stable" },
    ],
    activeDoctorsList: [
      { id: "doc_002", name: "Dr. Rohan Mehta", specialty: "General & Laparoscopic Surgery", qualification: "MBBS, MS (Surgery)", experience: "15 yrs", availability: "Consulting", rating: 4.9 },
    ],
    activeNursesList: [{ id: "nur_sg01", name: "Anjali Bhosale", station: "Station Surg-1", role: "Surgical Ward Sister", shift: "Morning", status: "On-Duty" }],
    supportStaffList: [{ id: "sup_sg01", name: "Shankar L.", role: "OT Attendant", taskScope: "Sterilization transport", shift: "Morning", status: "Active" }],
  },
  {
    id: "dep_surg_02",
    name: "Orthopaedics",
    type: "Orthopedics",
    categoryId: "cat_surgical",
    categoryName: "Surgical Specialties (Pre- & Post-Operative OPD)",
    description: "Treatment for bone fractures, joint pain, sports injuries, and applying or removing plaster casts.",
    location: "Qlyno Multispecialty Hospital - Main Campus",
    floor: "Ground Floor · Orthopedic Trauma Pavilion",
    headName: "Dr. Arvind Joshi",
    headTitle: "Chief of Joint Replacement & Orthopedics",
    activePatients: 38,
    bedCapacity: 22,
    occupiedBeds: 19,
    status: "active",
    operatingHours: "08:00 AM – 08:00 PM (Daily)",
    shiftModel: "2-Shift Ortho OPD & Plaster Room",
    nurseStations: ["Station Ortho-Plaster"],
    scope: {
      clinicalProcedures: ["Plaster of Paris (POP) Casting & Removal", "Joint Aspiration & Injections", "Knee & Hip Arthroplasty Follow-up", "Fracture Reduction"],
      bedAllocationRights: "Orthopedic Inpatient Ward & Traction Beds",
      equipmentReady: ["Electric Cast Saw with Vacuum", "C-Arm Mobile Radiography Unit", "Traction Frames"],
      supervisionLevel: "Consultant Orthopedic Surgeon",
      delegationLimits: "Plaster technician operations supervised by attending surgeon.",
    },
    activePatientsList: [
      { id: "pat_or01", name: "Kabir Malhotra", qlynoId: "QLY-PAT-2024-01190", age: 51, gender: "Male", bedNumber: "DLX-201", admittingDoctor: "Dr. Arvind Joshi", admissionDate: "2026-08-08", condition: "Right Total Knee Replacement", status: "Stable" },
    ],
    activeDoctorsList: [
      { id: "doc_or01", name: "Dr. Arvind Joshi", specialty: "Orthopaedics", qualification: "MBBS, MS (Ortho), MCh", experience: "17 yrs", availability: "Consulting", rating: 4.9 },
    ],
    activeNursesList: [{ id: "nur_or01", name: "Kavita Patil", station: "Station Ortho-Plaster", role: "Ortho Ward Nurse", shift: "Morning", status: "On-Duty" }],
    supportStaffList: [{ id: "sup_or01", name: "Ganesh M.", role: "Plaster Technician", taskScope: "Casting & splinting", shift: "Morning", status: "Active" }],
  },
  {
    id: "dep_surg_03",
    name: "Neurosurgery",
    type: "Neurosurgery",
    categoryId: "cat_surgical",
    categoryName: "Surgical Specialties (Pre- & Post-Operative OPD)",
    description: "Brain and spine surgical consultations and post-operative healing reviews.",
    location: "Qlyno Multispecialty Hospital - Main Campus",
    floor: "4th Floor · Neuro-Surgical Tower",
    headName: "Dr. Vikram Seth",
    headTitle: "Chief Neurosurgeon",
    activePatients: 18,
    bedCapacity: 12,
    occupiedBeds: 10,
    status: "active",
    operatingHours: "09:00 AM – 06:00 PM (24x7 Neurotrauma Cover)",
    shiftModel: "Neuro ICU & Surgical Roster",
    nurseStations: ["Station NeuroSurg-1"],
    scope: {
      clinicalProcedures: ["Craniotomy follow-up", "Spinal fusion & disc decompression reviews", "Shunt checkups", "Neuro-oncology planning"],
      bedAllocationRights: "Neuro-ICU & Spine Care Beds",
      equipmentReady: ["Neuro-Navigation System", "Carl Zeiss OPMI Pentero Microscope", "High-Speed Drill Unit"],
      supervisionLevel: "Senior Consultant Neurosurgeon",
      delegationLimits: "Critical post-craniotomy reviews signed off exclusively by consultant neurosurgeon.",
    },
    activePatientsList: [],
    activeDoctorsList: [
      { id: "doc_ns01", name: "Dr. Vikram Seth", specialty: "Neurosurgery", qualification: "MBBS, MS, MCh (Neurosurgery)", experience: "16 yrs", availability: "Consulting", rating: 4.9 },
    ],
    activeNursesList: [{ id: "nur_ns01", name: "Sheetal R.", station: "Station NeuroSurg-1", role: "Neuro ICU Sister", shift: "Morning", status: "On-Duty" }],
    supportStaffList: [{ id: "sup_ns01", name: "Prashant T.", role: "OT Technician", taskScope: "Navigation setup", shift: "Morning", status: "Active" }],
  },
  {
    id: "dep_surg_04",
    name: "Urology",
    type: "Urology",
    categoryId: "cat_surgical",
    categoryName: "Surgical Specialties (Pre- & Post-Operative OPD)",
    description: "Care for kidney stones, prostate issues, and urinary tract disorders.",
    location: "Qlyno Multispecialty Hospital - Main Campus",
    floor: "2nd Floor · Wing D",
    headName: "Dr. Nilesh Jain",
    headTitle: "Consultant Urologist & Andrologist",
    activePatients: 25,
    status: "active",
    operatingHours: "08:30 AM – 06:00 PM (Mon–Sat)",
    shiftModel: "2-Shift Urology Clinic",
    nurseStations: ["Station Uro-1"],
    scope: {
      clinicalProcedures: ["Uroflowmetry", "Flexible Diagnostic Cystoscopy", "Catheter Changes & Stent Removals", "Prostate (BPH) Evaluations"],
      bedAllocationRights: "Day-care urology recovery suites",
      equipmentReady: ["Digital Uroflowmeter", "Flexible Video Cystoscope", "Holmium Laser Generator"],
      supervisionLevel: "Consultant Urologist",
      delegationLimits: "Diagnostic flow reports validated by urology lead.",
    },
    activePatientsList: [],
    activeDoctorsList: [
      { id: "doc_u01", name: "Dr. Nilesh Jain", specialty: "Urology", qualification: "MBBS, MS, MCh (Urology)", experience: "12 yrs", availability: "Consulting", rating: 4.8 },
    ],
    activeNursesList: [{ id: "nur_u01", name: "Sunil D.", station: "Station Uro-1", role: "Urology Staff Nurse", shift: "Morning", status: "On-Duty" }],
    supportStaffList: [{ id: "sup_u01", name: "Kishor B.", role: "Laser Assistant", taskScope: "Laser maintenance", shift: "Morning", status: "Active" }],
  },
  {
    id: "dep_surg_05",
    name: "Cardiothoracic Surgery",
    type: "Cardiothoracic Surgery",
    categoryId: "cat_surgical",
    categoryName: "Surgical Specialties (Pre- & Post-Operative OPD)",
    description: "Pre-surgical evaluations and follow-ups for open-heart or lung operations.",
    location: "Qlyno Multispecialty Hospital - Main Campus",
    floor: "2nd Floor · Cardiac Tower",
    headName: "Dr. K. N. Rao",
    headTitle: "Chief Cardiothoracic & Vascular Surgeon (CTVS)",
    activePatients: 15,
    bedCapacity: 10,
    occupiedBeds: 8,
    status: "active",
    operatingHours: "09:00 AM – 06:00 PM (24x7 Heart-Lung Cover)",
    shiftModel: "CTVS ICU Roster",
    nurseStations: ["Station CTVS-ICU"],
    scope: {
      clinicalProcedures: ["CABG (Bypass) surgical planning", "Heart Valve Replacement Review", "Sternal wound assessments", "Thoracic drainage care"],
      bedAllocationRights: "Cardiothoracic Post-Op Intensive Care Units",
      equipmentReady: ["Heart-Lung Machine (CPB)", "Intra-Aortic Balloon Pump (IABP)", "ECMO Console"],
      supervisionLevel: "Chief CTVS Surgeon",
      delegationLimits: "Critical post-sternotomy clearance signed by surgeon.",
    },
    activePatientsList: [],
    activeDoctorsList: [
      { id: "doc_ct01", name: "Dr. K. N. Rao", specialty: "CTVS", qualification: "MBBS, MS, MCh (CTVS)", experience: "22 yrs", availability: "Consulting", rating: 4.9 },
    ],
    activeNursesList: [{ id: "nur_ct01", name: "Mariam V.", station: "Station CTVS-ICU", role: "CTVS Specialist Nurse", shift: "Morning", status: "On-Duty" }],
    supportStaffList: [{ id: "sup_ct01", name: "Satish M.", role: "Perfusionist", taskScope: "Perfusion maintenance", shift: "Morning", status: "Active" }],
  },
  {
    id: "dep_surg_06",
    name: "Plastic & Reconstructive Surgery",
    type: "Plastic Surgery",
    categoryId: "cat_surgical",
    categoryName: "Surgical Specialties (Pre- & Post-Operative OPD)",
    description: "Consultation for cosmetic enhancements, scar revisions, or burn reconstruction.",
    location: "Qlyno Multispecialty Hospital - Main Campus",
    floor: "3rd Floor · Aesthetic Suite",
    headName: "Dr. Shalini Mukerji",
    headTitle: "Consultant Plastic & Aesthetic Surgeon",
    activePatients: 14,
    status: "active",
    operatingHours: "09:30 AM – 05:30 PM (Mon–Sat)",
    shiftModel: "Specialty Day Surgery",
    nurseStations: ["Station Plastic-1"],
    scope: {
      clinicalProcedures: ["Microvascular flap follow-ups", "Burn scar revision & pressure therapy", "Cosmetic consultations", "Diabetic foot reconstructive surgery"],
      bedAllocationRights: "Cosmetic & Plastic surgery day-care rooms",
      equipmentReady: ["Surgical Loupes & Microscope", "Electro-cautery Micro-tip", "Dermatome Skin Grafting Tool"],
      supervisionLevel: "Consultant Plastic Surgeon",
      delegationLimits: "Wound photograph audits compliant with privacy guidelines.",
    },
    activePatientsList: [],
    activeDoctorsList: [
      { id: "doc_ps01", name: "Dr. Shalini Mukerji", specialty: "Plastic Surgery", qualification: "MBBS, MS, MCh (Plastic Surgery)", experience: "14 yrs", availability: "Consulting", rating: 4.8 },
    ],
    activeNursesList: [{ id: "nur_ps01", name: "Tanuja K.", station: "Station Plastic-1", role: "Aesthetic Nurse", shift: "Morning", status: "On-Duty" }],
    supportStaffList: [{ id: "sup_ps01", name: "Ashok L.", role: "Clinic Attendant", taskScope: "Supplies handling", shift: "Morning", status: "Active" }],
  },

  // ---------------------------------------------------------------------------------
  // Category 3: Women & Children's Health (3 Depts)
  // ---------------------------------------------------------------------------------
  {
    id: "dep_wc_01",
    name: "Obstetrics & Gynaecology (OB-GYN)",
    type: "Gynecology",
    categoryId: "cat_women_children",
    categoryName: "Women & Children's Health",
    description: "Routine pregnancy check-ups, prenatal care, and treatment of female reproductive system issues.",
    location: "Qlyno Multispecialty Hospital - Main Campus",
    floor: "2nd Floor · Mother & Child Pavilion",
    headName: "Dr. Neha Kulkarni",
    headTitle: "Head of Obstetrics & Gynaecology",
    activePatients: 45,
    bedCapacity: 25,
    occupiedBeds: 21,
    status: "active",
    operatingHours: "08:00 AM – 08:00 PM (24x7 Labour Ward Cover)",
    shiftModel: "3-Shift Labour & Gynae Ward",
    nurseStations: ["Station Maternity-1", "Station Antenatal OPD"],
    scope: {
      clinicalProcedures: ["Antenatal Care (ANC) & High-Risk Pregnancy Clinics", "Pap Smear & Colposcopy", "Infertility Workups", "Postnatal LSCS follow-ups"],
      bedAllocationRights: "Maternity Ward, Deluxe LDR Suites (Labour-Delivery-Recovery)",
      equipmentReady: ["Fetal Doppler & Cardiotocography (CTG)", "Voluson E8 4D Ultrasound", "Colposcope HD"],
      supervisionLevel: "Senior Consultant Obstetrician & Gynaecologist",
      delegationLimits: "Delivery registration and birth notifications recorded via admin desk.",
    },
    activePatientsList: [
      { id: "pat_ob01", name: "Meera Nambiar", qlynoId: "QLY-PAT-2023-00412", age: 29, gender: "Female", bedNumber: "MAT-08", admittingDoctor: "Dr. Neha Kulkarni", admissionDate: "2026-08-12", condition: "Elective LSCS Post-Op Day 2", status: "Stable" },
    ],
    activeDoctorsList: [
      { id: "doc_005", name: "Dr. Neha Kulkarni", specialty: "Obstetrics & Gynaecology", qualification: "MBBS, MD, DGO", experience: "15 yrs", availability: "Consulting", rating: 4.9 },
    ],
    activeNursesList: [{ id: "nur_ob01", name: "Fatima Ansari", station: "Station Maternity-1", role: "Midwife In-Charge", shift: "Morning", status: "On-Duty" }],
    supportStaffList: [{ id: "sup_ob01", name: "Lata Shinde", role: "Maternity Ayah", taskScope: "Patient comfort", shift: "Morning", status: "Active" }],
  },
  {
    id: "dep_wc_02",
    name: "Paediatrics",
    type: "Pediatrics",
    categoryId: "cat_women_children",
    categoryName: "Women & Children's Health",
    description: "General medical check-ups for children, newborn growth tracking, and developmental assessments.",
    location: "Qlyno Multispecialty Hospital - Main Campus",
    floor: "2nd Floor · Child Health Center",
    headName: "Dr. Sneha Roy",
    headTitle: "Chief Paediatrician",
    activePatients: 38,
    bedCapacity: 18,
    occupiedBeds: 12,
    status: "active",
    operatingHours: "08:30 AM – 08:00 PM (Daily)",
    shiftModel: "2-Shift Paediatric OPD & Ward",
    nurseStations: ["Station Paed-1"],
    scope: {
      clinicalProcedures: ["Well-Baby Growth & Milestone Tracking", "Childhood Immunization Schedules", "Paediatric Asthma & Allergy Care", "Infectious Disease Triage"],
      bedAllocationRights: "Paediatric Inpatient Ward & Play-Zone Beds",
      equipmentReady: ["Paediatric Vital Sign Monitors", "Infant Radiant Warmers", "Broselow Paediatric Emergency Tape"],
      supervisionLevel: "Attending Consultant Paediatrician",
      delegationLimits: "Vaccine cold-chain tracking monitored by dispensary and nursing lead.",
    },
    activePatientsList: [],
    activeDoctorsList: [
      { id: "doc_004", name: "Dr. Sneha Roy", specialty: "Paediatrics", qualification: "MBBS, MD (Paediatrics)", experience: "11 yrs", availability: "Consulting", rating: 4.9 },
    ],
    activeNursesList: [{ id: "nur_p01", name: "Zeenat B.", station: "Station Paed-1", role: "Paediatric Staff Nurse", shift: "Morning", status: "On-Duty" }],
    supportStaffList: [{ id: "sup_p01", name: "Manoj P.", role: "Child Life Assistant", taskScope: "Play area coordination", shift: "Morning", status: "Active" }],
  },
  {
    id: "dep_wc_03",
    name: "Neonatology",
    type: "Neonatology",
    categoryId: "cat_women_children",
    categoryName: "Women & Children's Health",
    description: "Specialized outpatient follow-ups for premature or high-risk babies after NICU discharge.",
    location: "Qlyno Multispecialty Hospital - Main Campus",
    floor: "2nd Floor · Neonatal Intensive Unit",
    headName: "Dr. Tanvi Parekh",
    headTitle: "Lead Neonatologist & NICU In-Charge",
    activePatients: 14,
    bedCapacity: 12,
    occupiedBeds: 10,
    status: "active",
    operatingHours: "08:00 AM – 06:00 PM (24x7 Level III NICU)",
    shiftModel: "3-Shift NICU Critical Roster",
    nurseStations: ["Station NICU-Level3"],
    scope: {
      clinicalProcedures: ["High-Risk Neonate Neuro-developmental Assessment", "Kangaroo Mother Care (KMC) Training", "Retinopathy of Prematurity (ROP) Follow-up", "Neonatal Growth & Nutrition Tuning"],
      bedAllocationRights: "NICU Incubators & Step-Down Warmers",
      equipmentReady: ["Dräger Isolette Incubators", "SLE 6000 Neonatal Ventilator", "LED Phototherapy Units"],
      supervisionLevel: "Senior Neonatologist (DM Neonatology)",
      delegationLimits: "NICU bed admissions validated through pediatric-neonatal chief.",
    },
    activePatientsList: [],
    activeDoctorsList: [
      { id: "doc_neo01", name: "Dr. Tanvi Parekh", specialty: "Neonatology", qualification: "MBBS, MD, DM (Neonatology)", experience: "13 yrs", availability: "Consulting", rating: 4.9 },
    ],
    activeNursesList: [{ id: "nur_neo01", name: "Geeta Verma", station: "Station NICU-Level3", role: "NICU Lead Specialist", shift: "Morning", status: "On-Duty" }],
    supportStaffList: [{ id: "sup_neo01", name: "Rahul S.", role: "Incubator Sterilizer", taskScope: "Infection control", shift: "Morning", status: "Active" }],
  },

  // ---------------------------------------------------------------------------------
  // Category 4: Head, Neck & Sensory Organs (3 Depts)
  // ---------------------------------------------------------------------------------
  {
    id: "dep_hn_01",
    name: "Ophthalmology",
    type: "Ophthalmology",
    categoryId: "cat_head_neck",
    categoryName: "Head, Neck & Sensory Organs",
    description: "Eye examinations, vision testing, glaucoma screening, and minor outpatient laser procedures.",
    location: "Qlyno Multispecialty Hospital - Main Campus",
    floor: "1st Floor · Vision Care Center",
    headName: "Dr. Sandeep Chawla",
    headTitle: "Chief Ophthalmic Surgeon",
    activePatients: 32,
    status: "active",
    operatingHours: "08:30 AM – 06:30 PM (Mon–Sat)",
    shiftModel: "Eye OPD & Refraction Suite",
    nurseStations: ["Station Eye-1"],
    scope: {
      clinicalProcedures: ["Comprehensive Slit Lamp Biomicroscopy", "Visual Acuity & Refraction", "Optical Coherence Tomography (OCT)", "YAG Capsulotomy Laser", "Glaucoma Tonometry"],
      bedAllocationRights: "Day-care cataract recovery lounge",
      equipmentReady: ["Zeiss Slit Lamp with Applanation Tonometer", "Heidelberg Spectralis OCT", "Topcon Auto-Refractometer"],
      supervisionLevel: "Consultant Ophthalmologist",
      delegationLimits: "Optometry technician vision measurements reviewed by ophthalmologist.",
    },
    activePatientsList: [],
    activeDoctorsList: [
      { id: "doc_op01", name: "Dr. Sandeep Chawla", specialty: "Ophthalmology", qualification: "MBBS, MS, FICO (Eye)", experience: "16 yrs", availability: "Consulting", rating: 4.8 },
    ],
    activeNursesList: [{ id: "nur_op01", name: "Pooja V.", station: "Station Eye-1", role: "Ophthalmic Nurse", shift: "Morning", status: "On-Duty" }],
    supportStaffList: [{ id: "sup_op01", name: "Hitesh N.", role: "Optometrist", taskScope: "Vision testing", shift: "Morning", status: "Active" }],
  },
  {
    id: "dep_hn_02",
    name: "ENT (Ear, Nose, & Throat / Otolaryngology)",
    type: "ENT",
    categoryId: "cat_head_neck",
    categoryName: "Head, Neck & Sensory Organs",
    description: "Care for hearing issues, sinusitis, tonsillitis, and basic endoscopic throat checks.",
    location: "Qlyno Multispecialty Hospital - Main Campus",
    floor: "1st Floor · ENT & Audiology Wing",
    headName: "Dr. Aniruddh Dixit",
    headTitle: "Senior ENT & Head-Neck Surgeon",
    activePatients: 29,
    status: "active",
    operatingHours: "09:00 AM – 06:00 PM (Daily)",
    shiftModel: "2-Shift ENT OPD & Audiology",
    nurseStations: ["Station ENT-1"],
    scope: {
      clinicalProcedures: ["Diagnostic Nasal Endoscopy (DNE)", "Flexible Video Laryngoscopy (FVL)", "Pure Tone Audiometry (PTA) & Tympanometry", "Foreign Body Ear/Nose Extraction"],
      bedAllocationRights: "Outpatient ENT procedure suites",
      equipmentReady: ["Karl Storz Rigid Nasal Endoscope", "Interacoustics Digital Audiometer", "ENT Treatment Workstation"],
      supervisionLevel: "Senior ENT Surgeon",
      delegationLimits: "Audiometric reporting co-signed by Audiology Specialist.",
    },
    activePatientsList: [],
    activeDoctorsList: [
      { id: "doc_ent01", name: "Dr. Aniruddh Dixit", specialty: "ENT", qualification: "MBBS, MS (ENT)", experience: "14 yrs", availability: "Consulting", rating: 4.8 },
    ],
    activeNursesList: [{ id: "nur_ent01", name: "Snehal S.", station: "Station ENT-1", role: "ENT Nurse", shift: "Morning", status: "On-Duty" }],
    supportStaffList: [{ id: "sup_ent01", name: "Rajat G.", role: "Audiologist", taskScope: "Hearing evaluation", shift: "Morning", status: "Active" }],
  },
  {
    id: "dep_hn_03",
    name: "Dermatology & Venereology",
    type: "Dermatology",
    categoryId: "cat_head_neck",
    categoryName: "Head, Neck & Sensory Organs",
    description: "Diagnosis of skin conditions, acne, allergies, hair loss, and minor skin biopsies.",
    location: "Qlyno Multispecialty Hospital - Main Campus",
    floor: "1st Floor · Skin & Laser Center",
    headName: "Dr. Sunita Deshmukh",
    headTitle: "Lead Dermatologist & Dermatosurgeon",
    activePatients: 36,
    status: "active",
    operatingHours: "09:00 AM – 07:00 PM (Mon–Sat)",
    shiftModel: "Dermatology OPD & Minor Procedures",
    nurseStations: ["Station Derma-1"],
    scope: {
      clinicalProcedures: ["Dermoscopy Examination", "Punch & Excision Skin Biopsies", "Cryotherapy for Warts/Lesions", "Chemical Peels & Scar Laser"],
      bedAllocationRights: "Minor dermatosurgery procedure suites",
      equipmentReady: ["Heine Delta 30 Dermatoscope", "Cryo-gun Liquid Nitrogen System", "Fractional CO2 Laser"],
      supervisionLevel: "Attending Dermatologist",
      delegationLimits: "Laser parameter selection authorized exclusively by doctor.",
    },
    activePatientsList: [],
    activeDoctorsList: [
      { id: "doc_006", name: "Dr. Sunita Deshmukh", specialty: "Dermatology", qualification: "MBBS, MD (DVL)", experience: "12 yrs", availability: "Consulting", rating: 4.9 },
    ],
    activeNursesList: [{ id: "nur_d01", name: "Pooja Hegde", station: "Station Derma-1", role: "Derma Procedure Nurse", shift: "Morning", status: "On-Duty" }],
    supportStaffList: [{ id: "sup_d01", name: "Sagar P.", role: "Laser Technician", taskScope: "Machine sanitation", shift: "Morning", status: "Active" }],
  },

  // ---------------------------------------------------------------------------------
  // Category 5: Mental Health & Rehabilitation (3 Depts)
  // ---------------------------------------------------------------------------------
  {
    id: "dep_mh_01",
    name: "Psychiatry",
    type: "Psychiatry",
    categoryId: "cat_mental_health",
    categoryName: "Mental Health & Rehabilitation",
    description: "Outpatient mental health evaluations, counselling, and psychiatric medication management.",
    location: "Qlyno Multispecialty Hospital - Main Campus",
    floor: "5th Floor · Mind Wellness Block",
    headName: "Dr. Devendra Sanyal",
    headTitle: "Chief Consultant Psychiatrist",
    activePatients: 21,
    status: "active",
    operatingHours: "09:00 AM – 06:00 PM (Mon–Sat)",
    shiftModel: "Private Consultation Suites",
    nurseStations: ["Station Psych-1"],
    scope: {
      clinicalProcedures: ["Diagnostic Psychiatric Evaluation", "Psychopharmacology Review", "Mood & Anxiety Disorders Clinic", "Substance De-addiction Guidance"],
      bedAllocationRights: "Dedicated Quiet Observation Suite",
      equipmentReady: ["Psychometric Testing Kiosks", "Sound-insulated Consult Rooms", "Emergency Sedation Trolley"],
      supervisionLevel: "Senior Consultant Psychiatrist",
      delegationLimits: "Psychiatric medication prescriptions strictly clinician-gated.",
    },
    activePatientsList: [],
    activeDoctorsList: [
      { id: "doc_psy01", name: "Dr. Devendra Sanyal", specialty: "Psychiatry", qualification: "MBBS, MD (Psychiatry), DPM", experience: "19 yrs", availability: "Consulting", rating: 4.9 },
    ],
    activeNursesList: [{ id: "nur_psy01", name: "Nirmala K.", station: "Station Psych-1", role: "Psychiatric Nurse", shift: "Morning", status: "On-Duty" }],
    supportStaffList: [{ id: "sup_psy01", name: "Arun V.", role: "Coordinator", taskScope: "Appointment confidential filing", shift: "Morning", status: "Active" }],
  },
  {
    id: "dep_mh_02",
    name: "Clinical Psychology",
    type: "Clinical Psychology",
    categoryId: "cat_mental_health",
    categoryName: "Mental Health & Rehabilitation",
    description: "Therapy sessions, cognitive behavioral therapy (CBT), and mental health assessments.",
    location: "Qlyno Multispecialty Hospital - Main Campus",
    floor: "5th Floor · Counselling Suites",
    headName: "Dr. Ananya Sen",
    headTitle: "Head Clinical Psychologist (RCI Registered)",
    activePatients: 18,
    status: "active",
    operatingHours: "09:30 AM – 05:30 PM (Mon–Sat)",
    shiftModel: "Individual Therapy Appointments",
    nurseStations: ["Station Psych-1"],
    scope: {
      clinicalProcedures: ["Cognitive Behavioral Therapy (CBT)", "Neuropsychological Battery Testing", "Childhood Behavioral Therapy", "Stress & Trauma Counselling"],
      bedAllocationRights: "Outpatient counselling therapy rooms",
      equipmentReady: ["WISC-V Intelligence Scale", "BDI-II & HAM-A Scoring Software", "Biofeedback Station"],
      supervisionLevel: "Lead Clinical Psychologist",
      delegationLimits: "Therapy notes encrypted under strict medical confidentiality.",
    },
    activePatientsList: [],
    activeDoctorsList: [
      { id: "doc_cp01", name: "Dr. Ananya Sen", specialty: "Clinical Psychology", qualification: "M.Phil, Ph.D. (Clinical Psychology)", experience: "11 yrs", availability: "Consulting", rating: 4.9 },
    ],
    activeNursesList: [{ id: "nur_cp01", name: "Nirmala K.", station: "Station Psych-1", role: "Wellness Nurse", shift: "Morning", status: "On-Duty" }],
    supportStaffList: [{ id: "sup_cp01", name: "Meena R.", role: "Therapy Scheduler", taskScope: "Confidential booking", shift: "Morning", status: "Active" }],
  },
  {
    id: "dep_mh_03",
    name: "Physiotherapy & Rehabilitation",
    type: "Physiotherapy",
    categoryId: "cat_mental_health",
    categoryName: "Mental Health & Rehabilitation",
    description: "Outpatient physical therapy sessions for injury recovery, stroke rehab, and pain management.",
    location: "Qlyno Multispecialty Hospital - Main Campus",
    floor: "Ground Floor · Physiotherapy Gymnasium",
    headName: "Dr. Rajesh Iyer (PT)",
    headTitle: "Head of Physical Therapy & Rehabilitation",
    activePatients: 44,
    status: "active",
    operatingHours: "07:30 AM – 07:30 PM (Mon–Sat)",
    shiftModel: "Continuous Therapy Gym Slots",
    nurseStations: ["Station Physio-Gym"],
    scope: {
      clinicalProcedures: ["Post-Op Arthroplasty Gait Training", "Stroke Neuro-Rehabilitation", "Spinal Decompression Therapy", "Sports Injury Kinetic Conditioning"],
      bedAllocationRights: "12 Therapy Treatment Couches & Traction Beds",
      equipmentReady: ["Shortwave Diathermy (SWD)", "Class IV Therapeutic Laser", "Cervical & Lumbar Traction Unit", "Balance Master Proprioception Platform"],
      supervisionLevel: "Lead Physiotherapist & Rehabilitation Specialist",
      delegationLimits: "Exercise prescriptions formulated based on physician referral.",
    },
    activePatientsList: [],
    activeDoctorsList: [
      { id: "doc_pt01", name: "Dr. Rajesh Iyer (PT)", specialty: "Physiotherapy", qualification: "BPT, MPT (Neuro-Rehab)", experience: "13 yrs", availability: "Consulting", rating: 4.8 },
    ],
    activeNursesList: [{ id: "nur_pt01", name: "Kiran Patil", station: "Station Physio-Gym", role: "Rehab Nurse", shift: "Morning", status: "On-Duty" }],
    supportStaffList: [{ id: "sup_pt01", name: "Sanjay D.", role: "Gym Assistant", taskScope: "Patient mobility aid", shift: "Morning", status: "Active" }],
  },

  // ---------------------------------------------------------------------------------
  // Category 6: Ancillary & Preventive Services (3 Depts)
  // ---------------------------------------------------------------------------------
  {
    id: "dep_anc_01",
    name: "Preventive Medicine / Health Check-up Lounge",
    type: "Preventive Medicine",
    categoryId: "cat_ancillary",
    categoryName: "Ancillary & Preventive Services",
    description: "Master health checks, routine corporate screenings, and wellness packages.",
    location: "Qlyno Multispecialty Hospital - Main Campus",
    floor: "Ground Floor · Executive Wellness Lounge",
    headName: "Dr. Manisha Kulkarni",
    headTitle: "Chief Wellness Officer & Preventive Care Lead",
    activePatients: 52,
    status: "active",
    operatingHours: "07:00 AM – 04:00 PM (Daily)",
    shiftModel: "Executive Screening Protocol",
    nurseStations: ["Station Wellness-1"],
    scope: {
      clinicalProcedures: ["Comprehensive Executive Health Screenings", "Corporate Annual Health Checkups", "Cancer Risk Biomarker Panels", "Cardiac & Metabolic Wellness Packages"],
      bedAllocationRights: "Executive Day Lounge Recliners",
      equipmentReady: ["Point-of-Care Blood Biomarker Analyzers", "Dual-Energy X-ray Absorptiometry (DEXA Bone Scan)", "Treadmill Test Suite"],
      supervisionLevel: "Consultant Physician in Preventive Care",
      delegationLimits: "Diagnostic routing and consolidated summary compiled by wellness team.",
    },
    activePatientsList: [],
    activeDoctorsList: [
      { id: "doc_pv01", name: "Dr. Manisha Kulkarni", specialty: "Preventive Medicine", qualification: "MBBS, MD (Community Medicine)", experience: "15 yrs", availability: "Consulting", rating: 4.9 },
    ],
    activeNursesList: [{ id: "nur_pv01", name: "Bhavna S.", station: "Station Wellness-1", role: "Wellness Coordinator Nurse", shift: "Morning", status: "On-Duty" }],
    supportStaffList: [{ id: "sup_pv01", name: "Tejas M.", role: "Executive Host", taskScope: "Screening itinerary routing", shift: "Morning", status: "Active" }],
  },
  {
    id: "dep_anc_02",
    name: "Vaccination / Immunization Clinic",
    type: "Vaccination",
    categoryId: "cat_ancillary",
    categoryName: "Ancillary & Preventive Services",
    description: "Scheduled childhood vaccines, adult booster shots, and travel vaccinations.",
    location: "Qlyno Multispecialty Hospital - Main Campus",
    floor: "Ground Floor · Wing E",
    headName: "Dr. Sneha Roy",
    headTitle: "Immunization Program Director",
    activePatients: 28,
    status: "active",
    operatingHours: "08:30 AM – 05:30 PM (Daily)",
    shiftModel: "Cold-Chain Immunization Unit",
    nurseStations: ["Station Vaccine-1"],
    scope: {
      clinicalProcedures: ["Universal Childhood Immunizations (WHO / IAP Schedule)", "Adult Vaccines (HPV, Pneumococcal, Flu, Shingles)", "International Travel Immunizations & Yellow Fever Certificates"],
      bedAllocationRights: "Post-vaccination 30-min observation area",
      equipmentReady: ["WHO-Pre-qualified Ice-Lined Vaccine Refrigerators", "Digital Cold Chain Data Loggers", "Anaphylaxis Emergency Response Kit"],
      supervisionLevel: "Attending Paediatrician & Preventive Physician",
      delegationLimits: "Cold chain telemetry and lot numbering tracked with zero error tolerance.",
    },
    activePatientsList: [],
    activeDoctorsList: [
      { id: "doc_vc01", name: "Dr. Sneha Roy", specialty: "Immunization & Paediatrics", qualification: "MBBS, MD", experience: "11 yrs", availability: "Consulting", rating: 4.9 },
    ],
    activeNursesList: [{ id: "nur_vc01", name: "Kiran More", station: "Station Vaccine-1", role: "Immunization Specialist Nurse", shift: "Morning", status: "On-Duty" }],
    supportStaffList: [{ id: "sup_vc01", name: "Vikram P.", role: "Cold Chain Handler", taskScope: "Temp log verification", shift: "Morning", status: "Active" }],
  },
  {
    id: "dep_anc_03",
    name: "Dental Clinic",
    type: "Dental",
    categoryId: "cat_ancillary",
    categoryName: "Ancillary & Preventive Services",
    description: "Routine cleanings, fillings, root canals, and minor oral surgeries that do not require hospital stay.",
    location: "Qlyno Multispecialty Hospital - Main Campus",
    floor: "1st Floor · Dental Suite",
    headName: "Dr. Prateek Merchant",
    headTitle: "Chief Dental Surgeon & Maxillofacial Specialist",
    activePatients: 22,
    status: "active",
    operatingHours: "09:00 AM – 07:00 PM (Mon–Sat)",
    shiftModel: "2-Shift Operatory Roster",
    nurseStations: ["Station Dental-1"],
    scope: {
      clinicalProcedures: ["Ultrasonic Scaling & Polishing", "Endodontic Root Canal Treatments (RCT)", "Tooth Extractions & Minor Oral Surgeries", "Cosmetic Veneers & Dental Crowns"],
      bedAllocationRights: "4 High-Tech Dental Operatory Chairs",
      equipmentReady: ["A-dec 500 Dental Operatory Chair", "Digital Intraoral RVG X-ray", "Rotary Endomotor & Apex Locator", "Class B Autoclave"],
      supervisionLevel: "Senior Dental Surgeon (MDS)",
      delegationLimits: "Dental radiography performed under certified operatory protocols.",
    },
    activePatientsList: [],
    activeDoctorsList: [
      { id: "doc_dt01", name: "Dr. Prateek Merchant", specialty: "Dental & Maxillofacial", qualification: "BDS, MDS (Conservative Dentistry)", experience: "14 yrs", availability: "Consulting", rating: 4.8 },
    ],
    activeNursesList: [{ id: "nur_dt01", name: "Aparna K.", station: "Station Dental-1", role: "Chairside Dental Assistant", shift: "Morning", status: "On-Duty" }],
    supportStaffList: [{ id: "sup_dt01", name: "Nitin B.", role: "Sterilization Attendant", taskScope: "Autoclave processing", shift: "Morning", status: "Active" }],
  },
];

export const DEPARTMENT_CATEGORIES: DepartmentCategory[] = [
  {
    id: "cat_medicine",
    name: "Medicine & Specialised Medical Clinics",
    shortName: "Medicine & Clinics",
    description: "Comprehensive adult medical care, internal medicine diagnostics, organ-specific chronic disease management, and specialized outpatient care.",
    iconName: "Stethoscope",
    themeColor: "text-blue-600 bg-blue-500/10 border-blue-500/20",
    gradient: "from-blue-600 to-indigo-600",
    departmentCount: 9,
    departments: detailedDepartments.filter((d) => d.categoryId === "cat_medicine"),
  },
  {
    id: "cat_surgical",
    name: "Surgical Specialties (Pre- & Post-Operative OPD)",
    shortName: "Surgical Specialties",
    description: "Pre-surgical clinical assessments, surgical consultations, trauma repairs, and post-operative healing reviews across general and super-specialty surgeries.",
    iconName: "Scissors",
    themeColor: "text-rose-600 bg-rose-500/10 border-rose-500/20",
    gradient: "from-rose-600 to-pink-600",
    departmentCount: 6,
    departments: detailedDepartments.filter((d) => d.categoryId === "cat_surgical"),
  },
  {
    id: "cat_women_children",
    name: "Women & Children's Health",
    shortName: "Women & Children",
    description: "Dedicated maternal, obstetric, pediatric and neonatal outpatient clinics providing comprehensive family healthcare and growth milestone tracking.",
    iconName: "Baby",
    themeColor: "text-amber-600 bg-amber-500/10 border-amber-500/20",
    gradient: "from-amber-600 to-orange-600",
    departmentCount: 3,
    departments: detailedDepartments.filter((d) => d.categoryId === "cat_women_children"),
  },
  {
    id: "cat_head_neck",
    name: "Head, Neck & Sensory Organs",
    shortName: "Head, Neck & Sensory",
    description: "Specialized diagnostics and procedures for sensory organs: Ophthalmology, Otolaryngology (ENT), and Dermatology & Venereology.",
    iconName: "Eye",
    themeColor: "text-emerald-600 bg-emerald-500/10 border-emerald-500/20",
    gradient: "from-emerald-600 to-teal-600",
    departmentCount: 3,
    departments: detailedDepartments.filter((d) => d.categoryId === "cat_head_neck"),
  },
  {
    id: "cat_mental_health",
    name: "Mental Health & Rehabilitation",
    shortName: "Mental Health & Rehab",
    description: "Comprehensive behavioral health, psychiatric medication management, evidence-based psychological therapies, and physical neuro-orthopedic rehabilitation.",
    iconName: "Brain",
    themeColor: "text-purple-600 bg-purple-500/10 border-purple-500/20",
    gradient: "from-purple-600 to-violet-600",
    departmentCount: 3,
    departments: detailedDepartments.filter((d) => d.categoryId === "cat_mental_health"),
  },
  {
    id: "cat_ancillary",
    name: "Ancillary & Preventive Services",
    shortName: "Ancillary & Preventive",
    description: "Proactive wellness evaluations, master executive screenings, universal immunization clinics, and comprehensive outpatient dental operatory suites.",
    iconName: "ShieldCheck",
    themeColor: "text-cyan-600 bg-cyan-500/10 border-cyan-500/20",
    gradient: "from-cyan-600 to-sky-600",
    departmentCount: 3,
    departments: detailedDepartments.filter((d) => d.categoryId === "cat_ancillary"),
  },
];
