import {
  HospitalDocumentItem,
  PolicyTemplateItem,
  ContractItem,
  DMSAnalyticsSummary,
} from "@/hospital-admin/lib/types/documents";

export const mockHospitalDocuments: HospitalDocumentItem[] = [
  // 1. Hospital Documents (Institutional)
  {
    id: "DOC-HOSP-001",
    documentCode: "REG-MH-HOSP-2024",
    title: "Clinical Establishment Registration Certificate (500-Bed Tertiary Facility)",
    category: "Hospital Documents",
    subCategory: "Institutional Registration",
    departmentName: "Administration",
    version: "v1.0",
    versionHistory: [
      {
        version: "v1.0",
        modifiedAt: "2024-01-15 10:00",
        modifiedBy: "Hospital Legal Counsel",
        changeSummary: "Initial establishment registration under State Clinical Establishments Act.",
        fileUrl: "/documents/clinical-establishment-reg.pdf",
        fileSize: "3.4 MB",
      },
    ],
    issuerAuthority: "Directorate of Health Services (DHS) / State Medical Council",
    issueDate: "2024-01-15",
    expiryDate: "2029-01-14",
    isExpired: false,
    securityClassification: "Confidential: Admin & Compliance",
    isPublicCertificate: true,
    redactionStatus: "PII Redacted (Rule 13.1 Verified)",
    fileUrl: "/documents/clinical-establishment-reg.pdf",
    fileSize: "3.4 MB",
    fileType: "PDF",
    uploadedBy: "Dr. Farooq Abdullah (Med Supt)",
    uploadedAt: "2024-01-16 11:30",
    tags: ["Institutional", "Establishment License", "DHS"],
  },
  {
    id: "DOC-HOSP-002",
    documentCode: "PCB-NOC-BIO-2025",
    title: "Pollution Control Board (PCB) Biomedical Waste Authorization & Water Clearance",
    category: "Hospital Documents",
    subCategory: "Statutory Environmental Clearance",
    departmentName: "Biomedical & Facility Safety",
    version: "v2.0",
    versionHistory: [
      {
        version: "v2.0",
        modifiedAt: "2025-06-10 14:00",
        modifiedBy: "Facility Safety Officer",
        changeSummary: "Annual renewal for effluent treatment plant (ETP) and red/yellow bag disposal contract.",
        fileUrl: "/documents/pcb-authorization-2025.pdf",
        fileSize: "2.8 MB",
      },
    ],
    issuerAuthority: "State Pollution Control Board (SPCB)",
    issueDate: "2025-06-10",
    expiryDate: "2027-06-09",
    isExpired: false,
    securityClassification: "Internal Staff Read-Only",
    isPublicCertificate: false,
    redactionStatus: "Not Required",
    fileUrl: "/documents/pcb-authorization-2025.pdf",
    fileSize: "2.8 MB",
    fileType: "PDF",
    uploadedBy: "Ramesh Nair (Facility Lead)",
    uploadedAt: "2025-06-11 09:15",
    tags: ["Pollution Control", "Biomedical Waste", "ETP", "Statutory"],
  },
  {
    id: "DOC-HOSP-003",
    documentCode: "FIRE-NOC-2025-99",
    title: "Fire Safety & Emergency Evacuation Clearance Certificate (High-Rise Hospital)",
    category: "Hospital Documents",
    subCategory: "Statutory Safety Clearance",
    departmentName: "Facility Infrastructure",
    version: "v1.2",
    versionHistory: [
      {
        version: "v1.2",
        modifiedAt: "2025-09-01 11:00",
        modifiedBy: "Chief Security Officer",
        changeSummary: "Addition of West Wing ICU fire suppression sprinkler testing audit.",
        fileUrl: "/documents/fire-safety-noc-2025.pdf",
        fileSize: "4.1 MB",
      },
    ],
    issuerAuthority: "Municipal Fire Department / Disaster Management Authority",
    issueDate: "2025-09-01",
    expiryDate: "2026-08-31",
    expiryAlertDays: 30,
    isExpired: false,
    securityClassification: "Internal Staff Read-Only",
    isPublicCertificate: true,
    redactionStatus: "PII Redacted (Rule 13.1 Verified)",
    fileUrl: "/documents/fire-safety-noc-2025.pdf",
    fileSize: "4.1 MB",
    fileType: "PDF",
    uploadedBy: "Chief Security Officer",
    uploadedAt: "2025-09-02 10:00",
    tags: ["Fire Safety", "Evacuation", "NOC", "Audit"],
  },

  // 2. Staff Documents (General Personnel Paperwork)
  {
    id: "DOC-STAFF-101",
    documentCode: "EMP-DOC-101-AGR",
    title: "Consultant Physician Employment Agreement & Privilege Scope: Dr. Arvind Kumar",
    category: "Staff Documents",
    subCategory: "Employment Contract",
    departmentName: "Cardiology",
    linkedEntityId: "doc-101",
    linkedEntityName: "Dr. Arvind Kumar",
    linkedEntityType: "Doctor",
    version: "v1.0",
    versionHistory: [
      {
        version: "v1.0",
        modifiedAt: "2023-04-01 10:00",
        modifiedBy: "HR Director",
        changeSummary: "Initial full-time senior consultant cardiology contract.",
        fileUrl: "/documents/staff/dr-arvind-contract.pdf",
        fileSize: "1.9 MB",
      },
    ],
    issuerAuthority: "Hospital HR & Board of Directors",
    issueDate: "2023-04-01",
    isExpired: false,
    securityClassification: "Confidential: Admin & Compliance",
    isPublicCertificate: false,
    redactionStatus: "Not Required",
    fileUrl: "/documents/staff/dr-arvind-contract.pdf",
    fileSize: "1.9 MB",
    fileType: "PDF",
    uploadedBy: "HR Director",
    uploadedAt: "2023-04-02 12:00",
    tags: ["Doctor", "Employment", "Confidential", "Cardiology"],
  },
  {
    id: "DOC-STAFF-102",
    documentCode: "BGV-NUR-204-VERIF",
    title: "Background Verification & Identity Clearance: Sister Sheela (ICU Nurse Lead)",
    category: "Staff Documents",
    subCategory: "Background Verification",
    departmentName: "Critical Care (ICU)",
    linkedEntityId: "nur-204",
    linkedEntityName: "Sister Sheela",
    linkedEntityType: "Nurse",
    version: "v1.0",
    versionHistory: [
      {
        version: "v1.0",
        modifiedAt: "2024-02-15 14:00",
        modifiedBy: "HR Compliance Officer",
        changeSummary: "Police clearance & previous hospital employment verification passed.",
        fileUrl: "/documents/staff/sheela-bgv.pdf",
        fileSize: "1.2 MB",
      },
    ],
    issuerAuthority: "AuthBridge Background Verification Services",
    issueDate: "2024-02-15",
    isExpired: false,
    securityClassification: "Restricted: Clinical Leads",
    isPublicCertificate: false,
    redactionStatus: "Not Required",
    fileUrl: "/documents/staff/sheela-bgv.pdf",
    fileSize: "1.2 MB",
    fileType: "PDF",
    uploadedBy: "HR Compliance Officer",
    uploadedAt: "2024-02-16 10:00",
    tags: ["Nursing", "BGV", "Police Verification"],
  },

  // 3. Licenses (Professional Credentials - Cross-Ref Module 13)
  {
    id: "DOC-LIC-201",
    documentCode: "MCI-REG-48912-DOC",
    title: "State Medical Council Permanent Registration: Dr. Arvind Kumar (MBBS, MD, DM)",
    category: "Licenses",
    subCategory: "Medical Council Registration",
    departmentName: "Cardiology",
    linkedEntityId: "doc-101",
    linkedEntityName: "Dr. Arvind Kumar",
    linkedEntityType: "Doctor",
    version: "v1.0",
    versionHistory: [
      {
        version: "v1.0",
        modifiedAt: "2022-07-01 10:00",
        modifiedBy: "Credentialing Officer",
        changeSummary: "Verified against State Medical Council online registry.",
        fileUrl: "/documents/licenses/dr-arvind-mci.pdf",
        fileSize: "1.5 MB",
      },
    ],
    issuerAuthority: "State Medical Council (MCI / NMC Accredited)",
    issueDate: "2022-07-01",
    expiryDate: "2027-06-30",
    isExpired: false,
    securityClassification: "Restricted: Clinical Leads",
    isPublicCertificate: true,
    redactionStatus: "PII Redacted (Rule 13.1 Verified)",
    fileUrl: "/documents/licenses/dr-arvind-mci.pdf",
    fileSize: "1.5 MB",
    fileType: "PDF",
    uploadedBy: "Credentialing Officer",
    uploadedAt: "2022-07-02 11:00",
    evidenceViewerUrl: "/verification/evidence-viewer?doc=dr-arvind-mci.pdf&cap=Cardiology",
    tags: ["License", "Doctor", "NMC", "Medical Council"],
  },
  {
    id: "DOC-LIC-202",
    documentCode: "AHA-ACLS-2025-99",
    title: "Advanced Cardiovascular Life Support (ACLS) Certification: Dr. Sunita Rao",
    category: "Licenses",
    subCategory: "Emergency Resuscitation Certification",
    departmentName: "Pediatrics & Emergency",
    linkedEntityId: "doc-104",
    linkedEntityName: "Dr. Sunita Rao",
    linkedEntityType: "Doctor",
    version: "v2.0",
    versionHistory: [
      {
        version: "v2.0",
        modifiedAt: "2025-08-10 16:00",
        modifiedBy: "Emergency Training Coordinator",
        changeSummary: "Biennial ACLS re-certification completed.",
        fileUrl: "/documents/licenses/dr-sunita-acls.pdf",
        fileSize: "1.1 MB",
      },
    ],
    issuerAuthority: "American Heart Association (AHA) / Indian Resuscitation Council",
    issueDate: "2025-08-10",
    expiryDate: "2027-08-09",
    isExpired: false,
    securityClassification: "Internal Staff Read-Only",
    isPublicCertificate: true,
    redactionStatus: "PII Redacted (Rule 13.1 Verified)",
    fileUrl: "/documents/licenses/dr-sunita-acls.pdf",
    fileSize: "1.1 MB",
    fileType: "PDF",
    uploadedBy: "Emergency Training Coordinator",
    uploadedAt: "2025-08-11 10:00",
    evidenceViewerUrl: "/verification/evidence-viewer?doc=dr-sunita-acls.pdf&cap=Emergency",
    tags: ["License", "ACLS", "Resuscitation", "Doctor"],
  },

  // 4. Certificates (Accreditations & Equipment Calibration - Cross-Ref Module 13 & F20)
  {
    id: "DOC-CERT-301",
    documentCode: "NABH-HOSP-ACC-2025",
    title: "National Accreditation Board for Hospitals & Healthcare Providers (NABH Full Accreditation)",
    category: "Certificates",
    subCategory: "Hospital Accreditation",
    departmentName: "Hospital-Wide",
    version: "v5.0",
    versionHistory: [
      {
        version: "v5.0",
        modifiedAt: "2025-01-10 10:00",
        modifiedBy: "Quality & Compliance Director",
        changeSummary: "Successful 5th Edition NABH Full Accreditation audit cycle.",
        fileUrl: "/documents/certificates/nabh-full-accreditation.pdf",
        fileSize: "3.8 MB",
      },
    ],
    issuerAuthority: "Quality Council of India / NABH Secretariat",
    issueDate: "2025-01-10",
    expiryDate: "2028-01-09",
    isExpired: false,
    securityClassification: "Public Redacted",
    isPublicCertificate: true,
    redactionStatus: "PII Redacted (Rule 13.1 Verified)",
    fileUrl: "/documents/certificates/nabh-full-accreditation.pdf",
    fileSize: "3.8 MB",
    fileType: "PDF",
    uploadedBy: "Quality Director",
    uploadedAt: "2025-01-11 11:30",
    evidenceViewerUrl: "/verification/evidence-viewer?doc=nabh-full-accreditation.pdf&cap=NABH",
    tags: ["Accreditation", "NABH", "Quality", "Hospital-Wide"],
  },
  {
    id: "DOC-CERT-302",
    documentCode: "AERB-RAD-PERMIT-2025",
    title: "Atomic Energy Regulatory Board (AERB) 128-Slice CT Scanner Radiation Safety License",
    category: "Certificates",
    subCategory: "Radiation Safety Permit",
    departmentName: "Radiology",
    linkedEntityId: "asset-ct-01",
    linkedEntityName: "GE Revolution 128-Slice CT Scanner",
    linkedEntityType: "Asset",
    version: "v3.1",
    versionHistory: [
      {
        version: "v3.1",
        modifiedAt: "2025-03-20 14:00",
        modifiedBy: "Radiation Safety Officer (RSO)",
        changeSummary: "Radiation lead shielding audit and dosimeter badge compliance clearance.",
        fileUrl: "/documents/certificates/aerb-ct-license.pdf",
        fileSize: "2.1 MB",
      },
    ],
    issuerAuthority: "Atomic Energy Regulatory Board (AERB), Govt. of India",
    issueDate: "2025-03-20",
    expiryDate: "2028-03-19",
    isExpired: false,
    securityClassification: "Internal Staff Read-Only",
    isPublicCertificate: true,
    redactionStatus: "PII Redacted (Rule 13.1 Verified)",
    fileUrl: "/documents/certificates/aerb-ct-license.pdf",
    fileSize: "2.1 MB",
    fileType: "PDF",
    uploadedBy: "RSO Officer",
    uploadedAt: "2025-03-21 09:00",
    evidenceViewerUrl: "/verification/evidence-viewer?doc=aerb-ct-license.pdf&cap=Radiology",
    tags: ["AERB", "Radiation Safety", "CT Scanner", "Asset Calibration"],
  },
  {
    id: "DOC-CERT-303",
    documentCode: "RTO-AMB-ALS-882",
    title: "Commercial Emergency Ambulance Motor Fitness & Life-Support Equipment Calibration",
    category: "Certificates",
    subCategory: "Vehicle & Medical Fleet Fitness",
    departmentName: "Ambulance & Emergency",
    linkedEntityId: "amb-01",
    linkedEntityName: "ALS Ambulance (KA-01-EA-9021)",
    linkedEntityType: "Asset",
    version: "v1.0",
    versionHistory: [
      {
        version: "v1.0",
        modifiedAt: "2025-08-15 10:00",
        modifiedBy: "Fleet Manager",
        changeSummary: "Annual RTO commercial fitness & onboard defibrillator calibration pass.",
        fileUrl: "/documents/certificates/rto-ambulance-fitness.pdf",
        fileSize: "1.8 MB",
      },
    ],
    issuerAuthority: "Regional Transport Authority (RTO) Commercial Division",
    issueDate: "2025-08-15",
    expiryDate: "2026-08-14",
    expiryAlertDays: 30,
    isExpired: false,
    securityClassification: "Internal Staff Read-Only",
    isPublicCertificate: true,
    redactionStatus: "PII Redacted (Rule 13.1 Verified)",
    fileUrl: "/documents/certificates/rto-ambulance-fitness.pdf",
    fileSize: "1.8 MB",
    fileType: "PDF",
    uploadedBy: "Fleet Manager",
    uploadedAt: "2025-08-16 11:00",
    evidenceViewerUrl: "/verification/evidence-viewer?doc=rto-ambulance-fitness.pdf&cap=Ambulance",
    tags: ["Ambulance", "RTO", "Fleet Fitness", "Defibrillator"],
  },

  // 5. Policies (Clinical SOPs & Blank Consent Form Templates)
  {
    id: "DOC-POL-401",
    documentCode: "SOP-BMW-SEG-2026",
    title: "Standard Operating Procedure: Biomedical Waste Segregation, Color Coding & Disposal",
    category: "Policies",
    subCategory: "Clinical SOP",
    departmentName: "Hospital-Wide",
    version: "v4.0",
    versionHistory: [
      {
        version: "v4.0",
        modifiedAt: "2026-01-05 10:00",
        modifiedBy: "Infection Control Committee (HICC)",
        changeSummary: "Updated sharps containment protocol and barcoded yellow bag weight tracking.",
        fileUrl: "/documents/policies/sop-biomedical-waste.pdf",
        fileSize: "1.6 MB",
      },
    ],
    issuerAuthority: "Hospital Infection Control Committee (HICC)",
    issueDate: "2026-01-05",
    expiryDate: "2027-01-04",
    isExpired: false,
    securityClassification: "Internal Staff Read-Only",
    isPublicCertificate: false,
    redactionStatus: "Not Required",
    fileUrl: "/documents/policies/sop-biomedical-waste.pdf",
    fileSize: "1.6 MB",
    fileType: "PDF",
    uploadedBy: "HICC Secretary",
    uploadedAt: "2026-01-06 09:30",
    tags: ["SOP", "Infection Control", "Biomedical Waste", "NABH"],
  },
  {
    id: "DOC-POL-402",
    documentCode: "TMPL-CONSENT-SURG-01",
    title: "Master Template: High-Risk Surgical, Anesthesia & Blood Transfusion Informed Consent",
    category: "Policies",
    subCategory: "Consent Form Template",
    departmentName: "OT & Surgery",
    version: "v3.2",
    versionHistory: [
      {
        version: "v3.2",
        modifiedAt: "2026-03-01 12:00",
        modifiedBy: "Medical Superintendent",
        changeSummary: "Added bilingual English/Hindi risk disclosure clauses per NABH 5th Ed.",
        fileUrl: "/documents/templates/surgical-consent-template.pdf",
        fileSize: "850 KB",
      },
    ],
    issuerAuthority: "Hospital Clinical Governance & Legal Committee",
    issueDate: "2026-03-01",
    isExpired: false,
    securityClassification: "Internal Staff Read-Only",
    isPublicCertificate: false,
    redactionStatus: "Not Required",
    fileUrl: "/documents/templates/surgical-consent-template.pdf",
    fileSize: "850 KB",
    fileType: "PDF",
    uploadedBy: "Dr. Farooq Abdullah",
    uploadedAt: "2026-03-02 11:00",
    tags: ["Consent Template", "Surgery", "Anesthesia", "Legal"],
  },
  {
    id: "DOC-POL-403",
    documentCode: "TMPL-LAMA-DISCH-02",
    title: "Master Template: Leave Against Medical Advice (LAMA) & High-Risk Discharge Undertaking",
    category: "Policies",
    subCategory: "Consent Form Template",
    departmentName: "Emergency & IPD",
    version: "v2.1",
    versionHistory: [
      {
        version: "v2.1",
        modifiedAt: "2025-11-15 15:00",
        modifiedBy: "Legal Advisor",
        changeSummary: "Reinforced physician indemnity waiver and emergency transfer advisory.",
        fileUrl: "/documents/templates/lama-discharge-undertaking.pdf",
        fileSize: "620 KB",
      },
    ],
    issuerAuthority: "Hospital Legal & Ethics Committee",
    issueDate: "2025-11-15",
    isExpired: false,
    securityClassification: "Internal Staff Read-Only",
    isPublicCertificate: false,
    redactionStatus: "Not Required",
    fileUrl: "/documents/templates/lama-discharge-undertaking.pdf",
    fileSize: "620 KB",
    fileType: "PDF",
    uploadedBy: "Legal Advisor",
    uploadedAt: "2025-11-16 10:00",
    tags: ["LAMA", "Discharge", "Legal Undertaking", "Emergency"],
  },

  // 6. Contracts (Vendor, AMC/CMC & Service Agreements - Cross-Ref Module 11 & F20)
  {
    id: "DOC-CTR-501",
    documentCode: "CTR-AMC-GE-CT-2025",
    title: "Comprehensive Annual Maintenance Contract (CMC): 128-Slice CT Scanner System",
    category: "Contracts",
    subCategory: "Biomedical AMC/CMC",
    departmentName: "Radiology",
    linkedEntityId: "ven-01",
    linkedEntityName: "GE Healthcare India Pvt Ltd",
    linkedEntityType: "Vendor",
    version: "v1.0",
    versionHistory: [
      {
        version: "v1.0",
        modifiedAt: "2025-04-01 10:00",
        modifiedBy: "Procurement Director",
        changeSummary: "3-Year CMC with 98.5% uptime commitment and 4-hour breakdown response SLA.",
        fileUrl: "/documents/contracts/ge-ct-amc-contract.pdf",
        fileSize: "4.5 MB",
      },
    ],
    issuerAuthority: "GE Healthcare & Hospital Procurement Dept",
    issueDate: "2025-04-01",
    expiryDate: "2028-03-31",
    isExpired: false,
    securityClassification: "Confidential: Admin & Compliance",
    isPublicCertificate: false,
    redactionStatus: "Not Required",
    fileUrl: "/documents/contracts/ge-ct-amc-contract.pdf",
    fileSize: "4.5 MB",
    fileType: "PDF",
    uploadedBy: "Procurement Lead",
    uploadedAt: "2025-04-02 14:00",
    tags: ["AMC", "CMC", "GE Healthcare", "CT Scanner", "Vendor Agreement"],
  },
  {
    id: "DOC-CTR-502",
    documentCode: "CTR-PHARM-BULK-2026",
    title: "Pharmaceutical Bulk Procurement & Emergency Drug Supply Rate Contract",
    category: "Contracts",
    subCategory: "Pharmacy Purchase Agreement",
    departmentName: "Pharmacy",
    linkedEntityId: "ven-03",
    linkedEntityName: "Cipla Healthcare Distribution Ltd",
    linkedEntityType: "Vendor",
    version: "v2.0",
    versionHistory: [
      {
        version: "v2.0",
        modifiedAt: "2026-01-01 11:00",
        modifiedBy: "Chief Pharmacist",
        changeSummary: "Annual rate contract renewal with tiered discounts for schedule H/H1 drugs.",
        fileUrl: "/documents/contracts/cipla-rate-contract-2026.pdf",
        fileSize: "3.2 MB",
      },
    ],
    issuerAuthority: "Cipla Distribution & Hospital Purchase Committee",
    issueDate: "2026-01-01",
    expiryDate: "2026-12-31",
    expiryAlertDays: 90,
    isExpired: false,
    securityClassification: "Confidential: Admin & Compliance",
    isPublicCertificate: false,
    redactionStatus: "Not Required",
    fileUrl: "/documents/contracts/cipla-rate-contract-2026.pdf",
    fileSize: "3.2 MB",
    fileType: "PDF",
    uploadedBy: "Chief Pharmacist",
    uploadedAt: "2026-01-02 12:00",
    tags: ["Pharmacy", "Drug Supply", "Cipla", "Rate Contract"],
  },
];

export const mockPolicyTemplates: PolicyTemplateItem[] = [
  {
    id: "TMPL-CONSENT-001",
    code: "TMPL-CONSENT-SURG-01",
    title: "High-Risk Surgical, Anesthesia & Blood Transfusion Informed Consent",
    type: "Consent Template",
    department: "OT & Surgery",
    applicableClinicalWorkflows: ["OT Surgery", "Pre-Anesthesia Checkup", "Blood Transfusion"],
    version: "v3.2",
    effectiveDate: "2026-03-01",
    reviewCycleMonths: 12,
    isApproved: true,
    approvedBy: "Dr. Farooq Abdullah (Medical Superintendent)",
    documentId: "DOC-POL-402",
    contentBody: `### Informed Consent for High-Risk Surgery & Anesthesia
1. **Procedural Disclosure**: The patient/next of kin has been explained the nature of the planned surgical procedure, anticipated clinical benefits, and foreseeable risks.
2. **Anesthetic Risks**: Disclosure of general, spinal, or regional anesthesia hazards including hemodynamic instability, allergic reactions, and aspiration.
3. **Blood Component Transfusion**: Consent for emergency transfusion of packed red blood cells (PRBC), fresh frozen plasma (FFP), or platelets if clinically indicated.
4. **Physician Attribution**: Authorized operating surgeon and lead anesthesiologist signatures mandatory prior to premedication.`,
  },
  {
    id: "TMPL-SOP-002",
    code: "SOP-BMW-SEG-2026",
    title: "Biomedical Waste Management, Segregation & Color Coding Protocol",
    type: "Clinical SOP",
    department: "Hospital-Wide",
    applicableClinicalWorkflows: ["Nursing Stations", "OT", "ICU", "Laboratory", "Emergency"],
    version: "v4.0",
    effectiveDate: "2026-01-05",
    reviewCycleMonths: 12,
    isApproved: true,
    approvedBy: "Hospital Infection Control Committee (HICC)",
    documentId: "DOC-POL-401",
    contentBody: `### NABH Biomedical Waste Segregation Guidelines
- **Yellow Bin**: Anatomical waste, soiled dressings, blood bags, expired cytotoxic drugs.
- **Red Bin**: Contaminated recyclable plastic waste, IV bottles, tubing, catheters, syringes (without needle).
- **White Translucent Container**: Sharps, needles, scalpels, blades (puncture-proof box).
- **Blue Cardboard Box**: Glassware, ampoules, metallic orthopedic implants.
- **Barcoding & Weighing**: Every bag must be weighed and scanned at the central temporary storage before final handover to the authorized SPCB vendor.`,
  },
  {
    id: "TMPL-LAMA-003",
    code: "TMPL-LAMA-DISCH-02",
    title: "Leave Against Medical Advice (LAMA) & High-Risk Discharge Undertaking",
    type: "Legal Undertaking",
    department: "Emergency & IPD",
    applicableClinicalWorkflows: ["Emergency Discharge", "IPD Ward Discharge", "ICU Step-Down"],
    version: "v2.1",
    effectiveDate: "2025-11-15",
    reviewCycleMonths: 24,
    isApproved: true,
    approvedBy: "Hospital Legal & Ethics Committee",
    documentId: "DOC-POL-403",
    contentBody: `### Patient Discharge Against Medical Advice (LAMA) Declaration
1. **Clinical Warning**: The attending consultant has explicitly counseled the patient/guardian that premature discharge carries severe health risks, including clinical deterioration or death.
2. **Voluntary Decision**: The patient/guardian certifies that they are leaving the hospital on their own volition contrary to medical advice.
3. **Indemnity Waiver**: Complete release of hospital and attending clinical staff from liability for adverse outcomes resulting from premature departure.`,
  },
];

export const mockContracts: ContractItem[] = [
  {
    id: "CTR-2026-0012",
    contractCode: "CTR-AMC-GE-CT-2025",
    title: "Comprehensive Annual Maintenance Contract (CMC): 128-Slice CT Scanner",
    contractType: "Biomedical AMC/CMC",
    vendorId: "ven-01",
    vendorName: "GE Healthcare India Pvt Ltd",
    assetId: "asset-ct-01",
    assetName: "GE Revolution 128-Slice CT Scanner",
    startDate: "2025-04-01",
    endDate: "2028-03-31",
    annualValue: 2450000,
    paymentTerms: "Quarterly in Advance upon Preventive Maintenance (PPM) sign-off",
    renewalStatus: "Active",
    slaUptimeCommitment: "98.5% Guaranteed Operational Uptime",
    documentId: "DOC-CTR-501",
  },
  {
    id: "CTR-2026-0018",
    contractCode: "CTR-PHARM-BULK-2026",
    title: "Pharmaceutical Bulk Purchase & Emergency Schedule Drug Supply Rate Contract",
    contractType: "Pharmacy Purchase Agreement",
    vendorId: "ven-03",
    vendorName: "Cipla Healthcare Distribution Ltd",
    startDate: "2026-01-01",
    endDate: "2026-12-31",
    annualValue: 8500000,
    paymentTerms: "30-Day Credit upon Goods Receipt Note (GRN) Verification",
    renewalStatus: "Expiring in 30 Days",
    slaUptimeCommitment: "2-Hour Emergency Delivery SLA for Critical Care",
    documentId: "DOC-CTR-502",
  },
];

export const mockDmsAnalyticsSummary: DMSAnalyticsSummary = {
  totalDocumentsCount: 1248,
  activePoliciesCount: 142,
  professionalLicensesCount: 186,
  regulatoryCertificatesCount: 38,
  activeContractsCount: 64,
  expiringIn30DaysCount: 3,
  expiringIn60DaysCount: 4,
  expiringIn90DaysCount: 7,
  publicRedactedCertsCount: 28,
};
