import { Ambulance, Department, NurseStation, SupportStaff, Surgeon } from "@/hospital-admin/lib/types";

export const hospitalDepartments: Department[] = [
  {
    id: "dep_001",
    name: "OPD",
    type: "OPD",
    location: "Andheri",
    headName: "Dr. Simran Kaur",
    activePatients: 168,
    status: "active",
  },
  {
    id: "dep_002",
    name: "ICU",
    type: "ICU",
    location: "Andheri",
    headName: "Dr. Aditya Verma",
    activePatients: 19,
    bedCapacity: 28,
    status: "warning",
  },
  {
    id: "dep_003",
    name: "Emergency",
    type: "Emergency",
    location: "Andheri",
    headName: "Dr. Farhan Sheikh",
    activePatients: 31,
    bedCapacity: 12,
    status: "critical",
  },
  {
    id: "dep_004",
    name: "OT Complex",
    type: "OT",
    location: "Andheri",
    headName: "Dr. Kavya Iyer",
    activePatients: 7,
    status: "active",
  },
  {
    id: "dep_005",
    name: "Radiology",
    type: "Radiology",
    location: "Powai",
    headName: "Dr. Aarav Sharma",
    activePatients: 22,
    status: "active",
  },
];

export const nurseStations: NurseStation[] = [
  {
    id: "ns_001",
    name: "Station A1",
    department: "General Ward",
    location: "Qlyno Multispecialty Hospital - Main Campus",
    leadName: "Anjali Bhosale",
    capacity: 18,
    occupancy: 15,
    status: "stable",
    shiftCoverage: "Morning · 6 staff",
  },
  {
    id: "ns_002",
    name: "Station ICU-1",
    department: "ICU",
    location: "Qlyno Multispecialty Hospital - Main Campus",
    leadName: "Ritu Sharma",
    capacity: 10,
    occupancy: 9,
    status: "watch",
    shiftCoverage: "Night · 4 staff",
  },
  {
    id: "ns_003",
    name: "Station ER-2",
    department: "Emergency",
    location: "Qlyno Multispecialty Hospital - Main Campus",
    leadName: "Nikita Sen",
    capacity: 12,
    occupancy: 11,
    status: "critical",
    shiftCoverage: "24x7 · 7 staff",
  },
  {
    id: "ns_004",
    name: "Station P1",
    department: "OPD",
    location: "Qlyno Multispecialty Hospital - Main Campus",
    leadName: "Zoya Ansari",
    capacity: 8,
    occupancy: 6,
    status: "stable",
    shiftCoverage: "Evening · 3 staff",
  },
];

export const surgeons: Surgeon[] = [
  {
    id: "sur_001",
    name: "Dr. Devika Nair",
    email: "devika.nair@qlyno.health",
    phone: "+91 90111 44332",
    status: "on-call",
    createdAt: "2021-02-12",
    location: "Qlyno Multispecialty Hospital - OT Complex",
    role: "Surgeon",
    specialty: "Cardiac Surgery",
    qualification: "MBBS, MS (Cardio Thoracic Surgery)",
    caseAccess: "Internal",
    nextAvailable: "Today · 18:30",
    avatarUrl: "https://i.pravatar.cc/150?img=30",
  },
  {
    id: "sur_002",
    name: "Dr. Arjun Deshpande",
    email: "arjun.deshpande@qlyno.health",
    phone: "+91 98201 55777",
    status: "assigned",
    createdAt: "2020-06-10",
    location: "Qlyno Multispecialty Hospital - OR Block",
    role: "Surgeon",
    specialty: "Orthopedic Surgery",
    qualification: "MBBS, D.Ortho, MCh",
    caseAccess: "Requested",
    nextAvailable: "Tomorrow · 09:00",
    avatarUrl: "https://i.pravatar.cc/150?img=31",
  },
  {
    id: "sur_003",
    name: "Dr. Rhea Banerjee",
    email: "rhea.banerjee@qlyno.health",
    phone: "+91 98222 90091",
    status: "available",
    createdAt: "2019-11-05",
    location: "Qlyno Multispecialty Hospital - Consultation Wing",
    role: "Surgeon",
    specialty: "General Surgery",
    qualification: "MBBS, MS (General Surgery)",
    caseAccess: "External",
    nextAvailable: "Today · 16:00",
    avatarUrl: "https://i.pravatar.cc/150?img=32",
  },
];

export const supportStaff: SupportStaff[] = [
  {
    id: "sup_001",
    name: "Amit Kale",
    email: "amit.kale@qlyno.health",
    phone: "+91 98909 92013",
    status: "active",
    createdAt: "2023-03-18",
    location: "Qlyno Multispecialty Hospital - ER",
    role: "Support Staff",
    department: "Emergency",
    taskScope: ["Triage assistance", "Wheelchair support"],
    assignment: "ER desk support",
    availability: "assigned",
    avatarUrl: "https://i.pravatar.cc/150?img=50",
  },
  {
    id: "sup_002",
    name: "Sanjana Patil",
    email: "sanjana.patil@qlyno.health",
    phone: "+91 99880 34567",
    status: "active",
    createdAt: "2022-11-02",
    location: "Qlyno Multispecialty Hospital - Housekeeping",
    role: "Housekeeping",
    department: "Facilities",
    taskScope: ["Cleaning rounds", "Sanitization logs"],
    assignment: "Ward B cleaning",
    availability: "available",
    avatarUrl: "https://i.pravatar.cc/150?img=51",
  },
  {
    id: "sup_003",
    name: "Dinesh Verma",
    email: "dinesh.verma@qlyno.health",
    phone: "+91 97662 41091",
    status: "on-leave",
    createdAt: "2021-09-09",
    location: "Qlyno Multispecialty Hospital - Admissions",
    role: "Assistant",
    department: "Admissions",
    taskScope: ["Patient escort", "File movement"],
    assignment: "Admissions desk",
    availability: "off-duty",
    avatarUrl: "https://i.pravatar.cc/150?img=52",
  },
];

export const ambulances: Ambulance[] = [
  {
    id: "amb_001",
    vehicleNo: "MH-02-AX-8101",
    baseLocation: "Qlyno Multispecialty Hospital - Main Campus",
    driverName: "Sanjay Pawar",
    status: "available",
    capacity: 2,
    lastDispatchAt: "2026-08-16T06:10:00",
  },
  {
    id: "amb_002",
    vehicleNo: "MH-04-RT-2145",
    baseLocation: "Qlyno Multispecialty Hospital - Main Campus",
    driverName: "Rafiq Khan",
    status: "en-route",
    capacity: 3,
    lastDispatchAt: "2026-08-17T08:45:00",
  },
  {
    id: "amb_003",
    vehicleNo: "MH-14-FJ-8820",
    baseLocation: "Qlyno Multispecialty Hospital - Main Campus",
    driverName: "Vikas Naik",
    status: "maintenance",
    capacity: 2,
  },
];

export const emergencyAlerts = [
  {
    id: "emg_001",
    title: "Code Blue · ICU",
    patient: "Aman Verma",
    alertTime: "2026-08-17T08:48:00",
    status: "active",
    severity: "critical",
    assignedTeam: "ICU Team A",
    eta: "3 min",
  },
  {
    id: "emg_002",
    title: "Trauma intake",
    patient: "Ritika Soni",
    alertTime: "2026-08-17T08:12:00",
    status: "active",
    severity: "warning",
    assignedTeam: "ER Resuscitation",
    eta: "8 min",
  },
  {
    id: "emg_003",
    title: "Ambulance dispatch request",
    patient: "Rajesh Yadav",
    alertTime: "2026-08-17T07:40:00",
    status: "dispatched",
    severity: "info",
    assignedTeam: "Main Campus Ambulance Unit",
    eta: "Arrived",
  },
];
