import {
  HospitalNotification,
  NotificationEventRule,
  EscalationLadder,
  EscalationRecord,
} from "@/hospital-admin/lib/types";
import { AppUserRole } from "@/hospital-admin/lib/types/nursing-module";

// ==========================================
// 16.1 NOTIFICATION CENTER LIVE FEED
// ==========================================
export const mockExtendedNotifications: HospitalNotification[] = [
  {
    id: "notif_01",
    title: "Emergency SOS: Cardiac Arrest in Emergency Bay 3",
    message: "Code Blue activated for Inpatient P-9102 (Kavita Patil). Resuscitation crash cart and attending emergency physician dispatched.",
    eventType: "Emergency SOS",
    category: "Emergency",
    severity: "critical",
    timestamp: "2026-08-24T17:40:00Z",
    status: "Unread",
    targetRoles: ["Emergency Team", "Hospital Admin", "ICU Incharge"],
    adminRecipient: true,
    linkUrl: "/hospital-admin/emergency",
    escalationLevel: "L2",
    sourceDepartment: "Emergency & Trauma",
  },
  {
    id: "notif_02",
    title: "Surgery Blocker: OT-2 Anesthesia Workstation Gas Pressure Drop",
    message: "OT 2 central oxygen manifold pressure below 3.8 bar. Laparoscopic Cholecystectomy case #SURG-8802 paused pending biomedical verification.",
    eventType: "Surgery blocker",
    category: "Operational",
    severity: "critical",
    timestamp: "2026-08-24T17:25:00Z",
    status: "Unread",
    targetRoles: ["Dr. Arvind Swaminathan (Surgeon)", "OT Coordinator", "Hospital Admin"],
    adminRecipient: true,
    linkUrl: "/hospital-admin/surgical-cases",
    escalationLevel: "L3",
    sourceDepartment: "Operation Theatre",
  },
  {
    id: "notif_03",
    title: "ICU Bed Shortage: Zero Ventilator Beds Available",
    message: "Medical ICU bed occupancy reached 100% (12/12 occupied). 2 post-op cardiac transfers awaiting step-down clearance.",
    eventType: "Bed shortage",
    category: "Operational",
    severity: "high",
    timestamp: "2026-08-24T17:10:00Z",
    status: "Unread",
    targetRoles: ["Hospital Admin", "Admissions Desk", "Emergency Triage"],
    adminRecipient: true,
    linkUrl: "/hospital-admin/wards-beds",
    escalationLevel: "L1",
    sourceDepartment: "Critical Care / ICU",
  },
  {
    id: "notif_04",
    title: "Doctor Delay: Dr. Kavita Verma delayed by 45 mins",
    message: "Cardiology OPD queue has 14 waiting patients. Reception 1 re-scheduling tokens and dispatching SMS alerts to checked-in patients.",
    eventType: "Doctor delay",
    category: "Clinical",
    severity: "medium",
    timestamp: "2026-08-24T16:50:00Z",
    status: "Acknowledged",
    targetRoles: ["Hospital Admin", "OPD Receptionist Desk", "Patient Relations"],
    adminRecipient: true,
    linkUrl: "/hospital-admin/appointments/opd-queue",
    sourceDepartment: "Cardiology OPD",
    acknowledgedBy: "Meenakshi Sundaram (Admin)",
    acknowledgedAt: "2026-08-24T17:00:00Z",
  },
  {
    id: "notif_05",
    title: "Night Shift Staffing Gap: 3 Staff Nurses Deficit in Ward 4",
    message: "Night shift roster in Ward 4 (Post-Op Surgical) is short by 3 staff nurses due to unplanned sick leaves. Nurse-to-patient ratio at 1:12.",
    eventType: "Staffing gap",
    category: "Staffing",
    severity: "high",
    timestamp: "2026-08-24T16:30:00Z",
    status: "Unread",
    targetRoles: ["Nursing Superintendent", "Hospital Admin", "Ward 4 Sister Incharge"],
    adminRecipient: true,
    linkUrl: "/hospital-admin/roster",
    escalationLevel: "L2",
    sourceDepartment: "Nursing Administration",
  },
  {
    id: "notif_06",
    title: "Security Alert: Unauthorized Narcotics Vault Access Attempt",
    message: "Biometric access failure (3 consecutive invalid attempts) detected at Central Pharmacy Schedule H1 Vault Door 2.",
    eventType: "Security alert",
    category: "Security",
    severity: "critical",
    timestamp: "2026-08-24T16:05:00Z",
    status: "Acknowledged",
    targetRoles: ["Chief Security Officer", "Hospital Admin", "Chief Pharmacist"],
    adminRecipient: true,
    linkUrl: "/hospital-admin/audit-logs",
    escalationLevel: "L1",
    sourceDepartment: "Security & Surveillance",
    acknowledgedBy: "Vikram Gaikwad (Security)",
    acknowledgedAt: "2026-08-24T16:10:00Z",
  },
  {
    id: "notif_07",
    title: "High-Value Vendor Quote Submitted: ₹18.5L Cath Lab Consumables",
    message: "Medtronic India submitted tender quotation #QT-2026-9904 for drug-eluting stents and balloon catheters awaiting Admin sign-off.",
    eventType: "Vendor quote",
    category: "Vendor",
    severity: "medium",
    timestamp: "2026-08-24T15:45:00Z",
    status: "Read",
    targetRoles: ["Procurement Officer", "Hospital Admin Reviewer"],
    adminRecipient: true,
    linkUrl: "/hospital-admin/procurement",
    sourceDepartment: "Supply Chain & Procurement",
  },
  {
    id: "notif_08",
    title: "Critical Lab Panic Alert: Serum Troponin-I @ 14.8 ng/mL",
    message: "Patient Arjun Gupta (P-8821) in Emergency Ward exhibits severe cardiac biomarker elevation. Direct critical finding alerted to attending cardiologist.",
    eventType: "Critical lab/result",
    category: "Clinical",
    severity: "critical",
    timestamp: "2026-08-24T15:15:00Z",
    status: "Acknowledged",
    targetRoles: ["Dr. Ananya Patel (Attending)", "Emergency Resident"],
    adminRecipient: false,
    linkUrl: "/hospital-admin/lab",
    sourceDepartment: "Central Clinical Biochemistry",
    acknowledgedBy: "Dr. Ananya Patel",
    acknowledgedAt: "2026-08-24T15:18:00Z",
  },
  {
    id: "notif_09",
    title: "Ambulance Dispatched: Advanced Cardiac Life Support (Unit MH-02-AL-9901)",
    message: "ACLS Ambulance #01 en route to Vile Parle East for trauma pickup. Estimated ETA to Emergency triage bay: 12 minutes.",
    eventType: "Ambulance dispatch",
    category: "Emergency",
    severity: "high",
    timestamp: "2026-08-24T15:00:00Z",
    status: "Read",
    targetRoles: ["Emergency Team", "Ambulance Driver", "Dispatch Coordinator"],
    adminRecipient: false,
    linkUrl: "/hospital-admin/ambulance/live-tracking",
    sourceDepartment: "Ambulance Fleet Control",
  },
  {
    id: "notif_10",
    title: "Surgeon Co-Opt Request: Emergency Craniotomy Assistant Required",
    message: "Dr. Arvind Swaminathan requested an on-call Senior Neurosurgeon for bilateral subdural hematoma decompression at 19:00.",
    eventType: "Surgeon request",
    category: "Clinical",
    severity: "high",
    timestamp: "2026-08-24T14:30:00Z",
    status: "Read",
    targetRoles: ["On-Call Neurosurgeons", "Case Owner (Dr. Arvind Swaminathan)"],
    adminRecipient: false,
    linkUrl: "/hospital-admin/surgical-cases/surgeon-requests",
    sourceDepartment: "Surgical Services",
  },
  {
    id: "notif_11",
    title: "Vendor Delivery Delay: Dialysis Filters Shipment Delayed by 24h",
    message: "Baxter Healthcare reported a transit delay for 150 Dialysis High-Flux dialyzers. Existing stock sufficient for 36 hours.",
    eventType: "Vendor delivery delay",
    category: "Vendor",
    severity: "medium",
    timestamp: "2026-08-24T13:45:00Z",
    status: "Read",
    targetRoles: ["Procurement Request Owner", "Dialysis Unit Head"],
    adminRecipient: false,
    linkUrl: "/hospital-admin/procurement/deliveries",
    sourceDepartment: "Dialysis & Renal Care",
  },
  {
    id: "notif_12",
    title: "New Patient Check-in: VIP Inpatient Admission (P-1004)",
    message: "Patient Vijay Varma checked in at Main Lobby Desk for elective orthopaedic total knee replacement under Dr. Ramesh Sharma.",
    eventType: "New appointment/check-in",
    category: "Appointments",
    severity: "info",
    timestamp: "2026-08-24T12:30:00Z",
    status: "Read",
    targetRoles: ["Reception Desk", "Dr. Ramesh Sharma Clinical Team"],
    adminRecipient: false,
    linkUrl: "/hospital-admin/patients",
    sourceDepartment: "Main Admissions Reception",
  },
  {
    id: "notif_13",
    title: "Fire Alarm Sensor Trigger: Kitchen Duct Heat Spike",
    message: "Sensor #F-301 in Basement Dietary Kitchen registered 68°C thermal anomaly. Engineering team and Fire Safety officer alerted.",
    eventType: "Security alert",
    category: "Security",
    severity: "critical",
    timestamp: "2026-08-24T11:15:00Z",
    status: "Acknowledged",
    targetRoles: ["Chief Security Officer", "Hospital Admin", "Facility Engineering"],
    adminRecipient: true,
    linkUrl: "/hospital-admin/audit-logs",
    sourceDepartment: "Facility Safety",
    acknowledgedBy: "Rajesh Kadam (Facilities)",
    acknowledgedAt: "2026-08-24T11:20:00Z",
  },
  {
    id: "notif_14",
    title: "Radiology Emergency: Acute Right MCA Infarction Finding",
    message: "MRI Brain of patient Kavita Patil (P-9102) revealed acute ischemic stroke. Direct alert transmitted to Stroke Intervention team.",
    eventType: "Critical lab/result",
    category: "Clinical",
    severity: "critical",
    timestamp: "2026-08-24T10:15:00Z",
    status: "Acknowledged",
    targetRoles: ["Stroke Team", "Dr. Sunita Kulkarni (Neuroradiologist)"],
    adminRecipient: false,
    linkUrl: "/hospital-admin/radiology/critical-findings",
    sourceDepartment: "Radiology & Neuroradiology",
    acknowledgedBy: "Stroke On-Duty Fellow",
    acknowledgedAt: "2026-08-24T10:18:00Z",
  },
  {
    id: "notif_15",
    title: "Staffing Gap: Emergency Night Resident Absent Without Cover",
    message: "Emergency Room Night Shift Roster (20:00 - 08:00) requires urgent locum allocation due to sudden illness of Dr. Tariq.",
    eventType: "Staffing gap",
    category: "Staffing",
    severity: "high",
    timestamp: "2026-08-24T09:30:00Z",
    status: "Acknowledged",
    targetRoles: ["Medical Superintendent", "Hospital Admin", "Emergency HOD"],
    adminRecipient: true,
    linkUrl: "/hospital-admin/roster",
    sourceDepartment: "Emergency Department",
    acknowledgedBy: "Hospital Admin",
    acknowledgedAt: "2026-08-24T09:45:00Z",
  },
];

// ==========================================
// ROLE-SCOPED NOTIFICATION FEEDS
// ==========================================

export const mockSupportStaffNotifications: HospitalNotification[] = [
  {
    id: "notif_sup_01",
    title: "Bed Sanitization: Bed GW-104 Vacated",
    message: "General Medical Ward Bed 104 is vacated and ready for terminal cleaning and fresh linen preparation.",
    eventType: "Bed shortage",
    category: "Operational",
    severity: "medium",
    timestamp: "10m ago",
    status: "Unread",
    targetRoles: ["Ward Attendant", "Housekeeping"],
    adminRecipient: false,
    linkUrl: "/hospital-admin/support-staff",
    sourceDepartment: "General Medical Ward",
  },
  {
    id: "notif_sup_02",
    title: "Patient Transport: Wheelchair Assistance",
    message: "Escort patient Vijay Varma (P-1004) from OPD Consulting Room 3 to Radiology Ultrasound Bay.",
    eventType: "Ambulance dispatch",
    category: "Operational",
    severity: "high",
    timestamp: "25m ago",
    status: "Unread",
    targetRoles: ["Ward Attendant"],
    adminRecipient: false,
    linkUrl: "/hospital-admin/support-staff",
    sourceDepartment: "OPD Services",
  },
  {
    id: "notif_sup_03",
    title: "Linen Restock: ICU Clean Utility Closet",
    message: "Clean linen delivery arrived at basement storage. Transfer 10 sets to ICU station closet.",
    eventType: "Vendor quote",
    category: "Operational",
    severity: "low",
    timestamp: "1h ago",
    status: "Read",
    targetRoles: ["Housekeeping / Cleaning Staff"],
    adminRecipient: false,
    linkUrl: "/hospital-admin/support-staff",
    sourceDepartment: "Supply & Linen",
  },
  {
    id: "notif_sup_04",
    title: "Duty Shift Confirmed: Morning Shift",
    message: "Your roster assignment for tomorrow (07:00 – 15:00) at ICU & Critical Care Station is confirmed.",
    eventType: "Staffing gap",
    category: "Staffing",
    severity: "info",
    timestamp: "2h ago",
    status: "Read",
    targetRoles: ["Support Staff"],
    adminRecipient: false,
    linkUrl: "/hospital-admin/roster",
    sourceDepartment: "Nursing Administration",
  },
];

export const mockStaffNurseNotifications: HospitalNotification[] = [
  {
    id: "notif_nurse_01",
    title: "Medication Due: Bed 06 Nebulization",
    message: "Nebulization Levosalbutamol 1.25mg for Inpatient Sunita Deshmukh is due in 15 minutes.",
    eventType: "Critical lab/result",
    category: "Clinical",
    severity: "high",
    timestamp: "5m ago",
    status: "Unread",
    targetRoles: ["Staff Nurse"],
    adminRecipient: false,
    linkUrl: "/hospital-admin/nurse",
    sourceDepartment: "ICU Station",
  },
  {
    id: "notif_nurse_02",
    title: "Doctor Order: IV Infusion Rate Change",
    message: "Dr. Ananya Patel updated Dextrose Normal Saline rate to 75 mL/hr for Bed 04 (Amit Patel).",
    eventType: "Doctor delay",
    category: "Clinical",
    severity: "medium",
    timestamp: "20m ago",
    status: "Unread",
    targetRoles: ["Staff Nurse"],
    adminRecipient: false,
    linkUrl: "/hospital-admin/nurse",
    sourceDepartment: "Cardiology",
  },
  {
    id: "notif_nurse_03",
    title: "Patient Call: Bed 02 Assistance Requested",
    message: "Patient Kavita Patil activated bedside call alert for pain medication assessment.",
    eventType: "Emergency SOS",
    category: "Clinical",
    severity: "high",
    timestamp: "45m ago",
    status: "Read",
    targetRoles: ["Staff Nurse"],
    adminRecipient: false,
    linkUrl: "/hospital-admin/nurse",
    sourceDepartment: "ICU Station",
  },
  {
    id: "notif_nurse_04",
    title: "Shift Handover Note Completed",
    message: "Night Shift Nurse Suman Das completed shift handover documentation for Bed 01 and Bed 03.",
    eventType: "Staffing gap",
    category: "Clinical",
    severity: "info",
    timestamp: "3h ago",
    status: "Read",
    targetRoles: ["Staff Nurse"],
    adminRecipient: false,
    linkUrl: "/hospital-admin/nurse",
    sourceDepartment: "ICU Station",
  },
];

export const mockNurseLeadNotifications: HospitalNotification[] = [
  {
    id: "notif_lead_01",
    title: "Task Overdue Alert: Bed 06 Nebulization",
    message: "Nebulization Levosalbutamol for Bed 06 is 30 mins overdue. Station Lead intervention required.",
    eventType: "Critical lab/result",
    category: "Clinical",
    severity: "critical",
    timestamp: "12m ago",
    status: "Unread",
    targetRoles: ["Nurse Station Lead", "Senior Nurse"],
    adminRecipient: false,
    linkUrl: "/hospital-admin/nurse-station",
    sourceDepartment: "ICU & Critical Care Station",
  },
  {
    id: "notif_lead_02",
    title: "Shift Swap Request: Nurse Meera Varma",
    message: "Nurse Meera requested shift swap with Nurse Rahul Shinde for Evening Shift on Sept 02.",
    eventType: "Staffing gap",
    category: "Staffing",
    severity: "medium",
    timestamp: "30m ago",
    status: "Unread",
    targetRoles: ["Nurse Station Lead"],
    adminRecipient: false,
    linkUrl: "/hospital-admin/nurse-station",
    sourceDepartment: "ICU Station Operations",
  },
  {
    id: "notif_lead_03",
    title: "Doctor Instruction: 2 New Orders Pending",
    message: "New cardiology care orders for Bed 02 and Bed 04 need station nurse assignment.",
    eventType: "Doctor delay",
    category: "Clinical",
    severity: "high",
    timestamp: "50m ago",
    status: "Read",
    targetRoles: ["Nurse Station Lead", "Senior Nurse"],
    adminRecipient: false,
    linkUrl: "/hospital-admin/nurse-station",
    sourceDepartment: "Critical Care / ICU",
  },
  {
    id: "notif_lead_04",
    title: "Shift Handover Ready for Sign-Off",
    message: "Morning Shift (07:00 – 15:00) handover checklist prepared for Sister Sneha Kulkarni.",
    eventType: "Surgery blocker",
    category: "Operational",
    severity: "info",
    timestamp: "2h ago",
    status: "Read",
    targetRoles: ["Nurse Station Lead", "Senior Nurse"],
    adminRecipient: false,
    linkUrl: "/hospital-admin/nurse-station",
    sourceDepartment: "ICU Station Operations",
  },
];

export function getNotificationsForRole(role?: AppUserRole): HospitalNotification[] {
  switch (role) {
    case "support_staff":
      return mockSupportStaffNotifications;
    case "nurse":
      return mockStaffNurseNotifications;
    case "nurse_lead":
    case "senior_nurse":
      return mockNurseLeadNotifications;
    case "admin":
    default:
      return mockExtendedNotifications;
  }
}

// ==========================================
// 16.2 NOTIFICATION CONFIGURATION RULES (PRD VERBATIM)
// ==========================================
export const mockNotificationRules: NotificationEventRule[] = [
  {
    id: "rule_01",
    eventType: "Doctor delay",
    category: "Clinical",
    defaultRecipients: ["Hospital Admin", "Affected Reception Desk", "Department Head", "Patient SMS/App"],
    adminDirectRecipient: true,
    enabledChannels: ["in-app", "sms", "email"],
    enabled: true,
    hasEscalationLadder: true,
    description: "Alerts when physician OPD arrival exceeds scheduled slot by >15 minutes to initiate patient queue mitigation.",
  },
  {
    id: "rule_02",
    eventType: "Emergency SOS",
    category: "Emergency",
    defaultRecipients: ["Emergency Response Team", "Hospital Admin", "ICU Coordinator", "Chief Nursing Officer"],
    adminDirectRecipient: true,
    enabledChannels: ["in-app", "sms", "whatsapp"],
    enabled: true,
    hasEscalationLadder: true,
    description: "Code Blue / Trauma activation broadcasted instantly across panic terminals and emergency pagers.",
  },
  {
    id: "rule_03",
    eventType: "Surgery blocker",
    category: "Operational",
    defaultRecipients: ["Responsible Surgeon", "OT Coordinator", "Hospital Admin", "Biomedical Engineering"],
    adminDirectRecipient: true,
    enabledChannels: ["in-app", "sms", "email"],
    enabled: true,
    hasEscalationLadder: true,
    description: "Immediate escalation for OT equipment breakdown, surgical sterility breaches, or anesthesia gas failures.",
  },
  {
    id: "rule_04",
    eventType: "Vendor quote",
    category: "Vendor",
    defaultRecipients: ["Procurement Officer", "Hospital Admin Reviewer", "Finance Manager"],
    adminDirectRecipient: true,
    enabledChannels: ["in-app", "email"],
    enabled: true,
    hasEscalationLadder: false,
    description: "Notifies designated procurement authorities when wholesale vendors submit RFQ bids exceeding ₹1,00,000 threshold.",
  },
  {
    id: "rule_05",
    eventType: "Bed shortage",
    category: "Operational",
    defaultRecipients: ["Hospital Admin", "Central Admissions Desk", "Emergency Triage Coordinator"],
    adminDirectRecipient: true,
    enabledChannels: ["in-app", "sms"],
    enabled: true,
    hasEscalationLadder: true,
    description: "Fires when ICU/HDU bed occupancy hits >95% to trigger accelerated discharge planning and step-down transfers.",
  },
  {
    id: "rule_06",
    eventType: "Staffing gap",
    category: "Staffing",
    defaultRecipients: ["Nurse Station Incharge", "Hospital Admin", "Department Head", "HR Roster Desk"],
    adminDirectRecipient: true,
    enabledChannels: ["in-app", "sms", "whatsapp"],
    enabled: true,
    hasEscalationLadder: true,
    description: "Alerts when ward nursing or medical staff ratio drops below NABH patient safety thresholds.",
  },
  {
    id: "rule_07",
    eventType: "Security alert",
    category: "Security",
    defaultRecipients: ["Chief Security Officer", "Hospital Admin", "Facility Safety Head"],
    adminDirectRecipient: true,
    enabledChannels: ["in-app", "sms", "whatsapp"],
    enabled: true,
    hasEscalationLadder: true,
    description: "Real-time panic signals from fire detection, unauthorized restricted area access, or perimeter alarms.",
  },
  {
    id: "rule_08",
    eventType: "New appointment/check-in",
    category: "Appointments",
    defaultRecipients: ["Relevant Receptionist Desk", "Attending Doctor Team"],
    adminDirectRecipient: false,
    enabledChannels: ["in-app", "sms"],
    enabled: true,
    hasEscalationLadder: false,
    description: "Notifies OPD clinic coordinators upon patient arrival and token issue (Admin receives aggregated reporting only).",
  },
  {
    id: "rule_09",
    eventType: "Critical lab/result",
    category: "Clinical",
    defaultRecipients: ["Responsible Clinician", "Relevant Clinical Care Team"],
    adminDirectRecipient: false,
    enabledChannels: ["in-app", "sms", "whatsapp"],
    enabled: true,
    hasEscalationLadder: true,
    description: "Direct panic values (e.g. Troponin, Potassium <2.5 or >6.0, Critical pH) routed directly to prescribing clinician.",
  },
  {
    id: "rule_10",
    eventType: "Ambulance dispatch",
    category: "Emergency",
    defaultRecipients: ["Emergency Team", "Ambulance Driver", "Dispatch Coordinator", "Patient / Family (where configured)"],
    adminDirectRecipient: false,
    enabledChannels: ["in-app", "sms", "whatsapp"],
    enabled: true,
    hasEscalationLadder: false,
    description: "GPS dispatch alerts and trip progress updates dispatched to paramedics and emergency coordinators.",
  },
  {
    id: "rule_11",
    eventType: "Surgeon request",
    category: "Clinical",
    defaultRecipients: ["Eligible Surgeon(s)", "Surgical Case Owner"],
    adminDirectRecipient: false,
    enabledChannels: ["in-app", "email", "sms"],
    enabled: true,
    hasEscalationLadder: false,
    description: "Surgical co-opt and cross-specialty intra-operative assistance invitations sent to eligible credentialed surgeons.",
  },
  {
    id: "rule_12",
    eventType: "Vendor delivery delay",
    category: "Vendor",
    defaultRecipients: ["Procurement Request Owner", "Department / Case Owner"],
    adminDirectRecipient: false,
    enabledChannels: ["in-app", "email"],
    enabled: true,
    hasEscalationLadder: false,
    description: "Supply chain shipment delay alerts routed directly to indenting department managers and storekeepers.",
  },
];

// ==========================================
// 16.3 ESCALATION RULES & MULTI-TIER LADDERS
// ==========================================
export const mockEscalationLadders: EscalationLadder[] = [
  {
    id: "lad_01",
    name: "Emergency Code Blue / Trauma Ladder",
    eventType: "Emergency SOS",
    department: "Emergency & Critical Care",
    enabled: true,
    steps: [
      { level: 1, name: "Immediate Emergency Team Dispatch", role: "On-Duty ER Residents & Crash Team", thresholdMinutes: 0, channel: "in-app" },
      { level: 2, name: "Critical Care Specialist Escalation", role: "Senior Intensivist & ICU Registrar", thresholdMinutes: 3, channel: "sms" },
      { level: 3, name: "Hospital Executive Command", role: "Medical Superintendent & Hospital Admin", thresholdMinutes: 7, channel: "whatsapp" },
    ],
    fallbackRecipient: "Chief Medical Officer (+91 98200 11223)",
    autoResolveOnAction: true,
  },
  {
    id: "lad_02",
    name: "OT Surgery Blocker Protocol",
    eventType: "Surgery blocker",
    department: "Operation Theatres",
    enabled: true,
    steps: [
      { level: 1, name: "OT Coordinator & Biomedical Desk", role: "On-Duty Biomedical Engineer", thresholdMinutes: 0, channel: "in-app" },
      { level: 2, name: "Senior Surgical Director Alert", role: "Head of Surgical Services", thresholdMinutes: 5, channel: "sms" },
      { level: 3, name: "Hospital Admin Operational Intervention", role: "Hospital Administrator", thresholdMinutes: 10, channel: "whatsapp" },
    ],
    fallbackRecipient: "OT Complex Director (+91 98200 44556)",
    autoResolveOnAction: true,
  },
  {
    id: "lad_03",
    name: "Critical Care Bed Crunch Escalation",
    eventType: "Bed shortage",
    department: "Inpatient Wards & ICU",
    enabled: true,
    steps: [
      { level: 1, name: "Ward Sister & Discharge Coordinator", role: "Central Admissions Lead", thresholdMinutes: 0, channel: "in-app" },
      { level: 2, name: "Department Heads Discharge Review", role: "ICU & General Ward HODs", thresholdMinutes: 15, channel: "sms" },
      { level: 3, name: "Hospital Admin Inter-Hospital Transfer", role: "Hospital Admin & Medical Director", thresholdMinutes: 30, channel: "email" },
    ],
    fallbackRecipient: "Hospital Operations Manager (+91 98200 77889)",
    autoResolveOnAction: true,
  },
  {
    id: "lad_04",
    name: "Nursing Staffing Ratio Deficit Ladder",
    eventType: "Staffing gap",
    department: "Nursing Administration",
    enabled: true,
    steps: [
      { level: 1, name: "Sister Incharge & Floor Float", role: "Floor Nurse Supervisor", thresholdMinutes: 0, channel: "in-app" },
      { level: 2, name: "Nursing Superintendent Mobilization", role: "Chief Nursing Officer", thresholdMinutes: 20, channel: "sms" },
      { level: 3, name: "Admin Emergency Locum Authorization", role: "Hospital Admin & HR Director", thresholdMinutes: 45, channel: "email" },
    ],
    fallbackRecipient: "Chief Nursing Officer (+91 98200 33445)",
    autoResolveOnAction: true,
  },
];

// ==========================================
// 16.4 ESCALATION HISTORY & INCIDENT LOG
// ==========================================
export const mockEscalationRecords: EscalationRecord[] = [
  {
    id: "esc_101",
    incidentCode: "INC-2026-0941",
    eventType: "Emergency SOS",
    title: "Code Blue in Emergency Bay 3 (P-9102)",
    department: "Emergency & Trauma",
    triggeredAt: "2026-08-24T17:40:00Z",
    currentStep: "L2",
    stepsTaken: [
      { step: "L1: Immediate ER Crash Team", notifiedAt: "2026-08-24T17:40:00Z", recipient: "Dr. Rohan (ER Resident)", channel: "in-app", status: "Acknowledged" },
      { step: "L2: Senior Intensivist Pager", notifiedAt: "2026-08-24T17:43:00Z", recipient: "Dr. Ananya Patel (ICU)", channel: "sms", status: "Delivered" },
    ],
    status: "In Progress",
    durationMinutes: 12,
  },
  {
    id: "esc_102",
    incidentCode: "INC-2026-0940",
    eventType: "Surgery blocker",
    title: "OT-2 Oxygen Line Pressure Fluctuation",
    department: "Operation Theatre Complex",
    triggeredAt: "2026-08-24T17:25:00Z",
    currentStep: "L3",
    stepsTaken: [
      { step: "L1: Biomedical Eng on-call", notifiedAt: "2026-08-24T17:25:00Z", recipient: "Biomedical Engineer Rajesh", channel: "in-app", status: "Timed Out" },
      { step: "L2: Head of OT Services", notifiedAt: "2026-08-24T17:30:00Z", recipient: "Dr. Arvind Swaminathan", channel: "sms", status: "Acknowledged" },
      { step: "L3: Hospital Admin Executive", notifiedAt: "2026-08-24T17:35:00Z", recipient: "Hospital Administrator", channel: "whatsapp", status: "Delivered" },
    ],
    status: "Escalated",
    durationMinutes: 27,
  },
  {
    id: "esc_103",
    incidentCode: "INC-2026-0939",
    eventType: "Bed shortage",
    title: "MICU 100% Occupancy with Pending ER Transfers",
    department: "Critical Care",
    triggeredAt: "2026-08-24T17:10:00Z",
    currentStep: "L1",
    stepsTaken: [
      { step: "L1: Central Admissions Desk", notifiedAt: "2026-08-24T17:10:00Z", recipient: "Admissions Desk Lead", channel: "in-app", status: "Acknowledged" },
    ],
    status: "In Progress",
    durationMinutes: 42,
  },
  {
    id: "esc_104",
    incidentCode: "INC-2026-0938",
    eventType: "Security alert",
    title: "Pharmacy Narcotics Vault Tamper Trigger",
    department: "Pharmacy & Security",
    triggeredAt: "2026-08-24T16:05:00Z",
    currentStep: "L1",
    stepsTaken: [
      { step: "L1: Chief Security Officer", notifiedAt: "2026-08-24T16:05:00Z", recipient: "Vikram Gaikwad", channel: "in-app", status: "Acknowledged" },
    ],
    status: "Resolved",
    durationMinutes: 15,
    resolvedAt: "2026-08-24T16:20:00Z",
    resolvedBy: "Vikram Gaikwad (Chief Security)",
    resolutionNotes: "Biometric sensor glitch identified. Certified by pharmacist and sensor rebooted.",
  },
  {
    id: "esc_105",
    incidentCode: "INC-2026-0937",
    eventType: "Staffing gap",
    title: "Ward 4 Night Shift Staff Shortage (3 Nurses)",
    department: "Inpatient Wards",
    triggeredAt: "2026-08-24T16:30:00Z",
    currentStep: "L2",
    stepsTaken: [
      { step: "L1: Floor Nurse Supervisor", notifiedAt: "2026-08-24T16:30:00Z", recipient: "Sister Nirmala", channel: "in-app", status: "Timed Out" },
      { step: "L2: Chief Nursing Officer", notifiedAt: "2026-08-24T16:50:00Z", recipient: "Matron Sunita", channel: "sms", status: "Acknowledged" },
    ],
    status: "Resolved",
    durationMinutes: 35,
    resolvedAt: "2026-08-24T17:05:00Z",
    resolvedBy: "Matron Sunita (Nursing Sup.)",
    resolutionNotes: "2 relievers mobilized from Day Float Pool + 1 overtime nurse assigned.",
  },
  {
    id: "esc_106",
    incidentCode: "INC-2026-0936",
    eventType: "Doctor delay",
    title: "Cardiology OPD Delay (45m Queue Block)",
    department: "Cardiology OPD",
    triggeredAt: "2026-08-24T16:50:00Z",
    currentStep: "L1",
    stepsTaken: [
      { step: "L1: OPD Reception 1", notifiedAt: "2026-08-24T16:50:00Z", recipient: "OPD Receptionist", channel: "in-app", status: "Acknowledged" },
    ],
    status: "Resolved",
    durationMinutes: 18,
    resolvedAt: "2026-08-24T17:08:00Z",
    resolvedBy: "Meenakshi Sundaram (Admin)",
    resolutionNotes: "Dr. Kavita arrived. 6 patients redirected to Junior Consultant for pre-check.",
  },
];
