import { AppNotification, AuditLogEntry, LabOrder, RoleDefinition } from "@/hospital-admin/lib/types";

export const labOrders: LabOrder[] = [
  {
    id: "lo_001",
    orderNo: "LAB-88213",
    patientName: "Ibrahim Sheikh",
    test: "HbA1c + Fasting Glucose",
    orderingDoctor: "Dr. Simran Kaur",
    source: "Doctor Order",
    status: "released",
    orderedOn: "2026-08-12",
    tat: "6 hrs",
  },
  {
    id: "lo_002",
    orderNo: "LAB-88214",
    patientName: "Aarav Shah",
    test: "Lipid Profile",
    orderingDoctor: "Dr. Ananya Rao",
    source: "Doctor Order",
    status: "processing",
    orderedOn: "2026-08-13",
    tat: "12 hrs",
  },
  {
    id: "lo_003",
    orderNo: "LAB-88215",
    patientName: "Fatima Ansari",
    test: "MRI Brain",
    orderingDoctor: "Dr. Vikram Nair",
    source: "Doctor Order",
    status: "awaiting-validation",
    orderedOn: "2026-08-01",
    tat: "24 hrs",
    critical: true,
  },
  {
    id: "lo_004",
    orderNo: "LAB-88216",
    patientName: "Devansh Pandey",
    test: "X-Ray Knee (Left)",
    orderingDoctor: "Dr. Rohan Mehta",
    source: "Doctor Order",
    status: "scheduled",
    orderedOn: "2026-08-13",
    tat: "2 hrs",
  },
  {
    id: "lo_005",
    orderNo: "LAB-88217",
    patientName: "Walk-in Patient - Rekha Joshi",
    test: "Complete Blood Count",
    orderingDoctor: "-",
    source: "Direct",
    status: "sample-pending",
    orderedOn: "2026-08-14",
    tat: "4 hrs",
  },
  {
    id: "lo_006",
    orderNo: "LAB-88190",
    patientName: "Sunita Reddy",
    test: "Allergy Panel",
    orderingDoctor: "Dr. Aditya Verma",
    source: "Clinic Referral",
    status: "rejected",
    orderedOn: "2026-08-05",
    tat: "24 hrs",
  },
];

export const notifications: AppNotification[] = [
  {
    id: "ntf_001",
    category: "emergency",
    title: "Critical lab result flagged",
    message: "MRI Brain result for Fatima Ansari flagged critical by Dr. Meera Kapoor. Awaiting clinician acknowledgement.",
    timestamp: "2026-08-14T08:12:00",
    read: false,
    severity: "critical",
  },
  {
    id: "ntf_002",
    category: "vendor",
    title: "Procurement request closing soon",
    message: "Cardiac Monitor request (PR-2026-003) closes in 4 hours with only 2 quotes received.",
    timestamp: "2026-08-14T07:40:00",
    read: false,
    severity: "warning",
  },
  {
    id: "ntf_003",
    category: "staff",
    title: "Nurse shift understaffed",
    message: "ICU night shift is short-staffed by 1 nurse for Aug 15. Roster requires attention.",
    timestamp: "2026-08-14T06:55:00",
    read: false,
    severity: "warning",
  },
  {
    id: "ntf_004",
    category: "billing",
    title: "Large outstanding balance",
    message: "Devansh Pandey has an outstanding balance of ₹5,600 pending for over 2 days.",
    timestamp: "2026-08-13T18:20:00",
    read: true,
    severity: "info",
  },
  {
    id: "ntf_005",
    category: "appointment",
    title: "Doctor marked unavailable",
    message: "Dr. Farhan Sheikh is on leave — 3 upcoming appointments require reassignment.",
    timestamp: "2026-08-13T14:05:00",
    read: true,
    severity: "info",
  },
  {
    id: "ntf_006",
    category: "system",
    title: "Weekly backup completed",
    message: "Automated data backup completed successfully with no errors.",
    timestamp: "2026-08-13T02:00:00",
    read: true,
    severity: "success",
  },
];

export const auditLogs: AuditLogEntry[] = [
  {
    id: "adt_001",
    actor: "Dr. Simran Kaur",
    actorRole: "Doctor",
    action: "Reviewed lab report",
    entity: "Lab Order",
    entityId: "LAB-88213",
    timestamp: "2026-08-14T08:02:11",
    ipAddress: "10.22.4.18",
    status: "success",
  },
  {
    id: "adt_002",
    actor: "Suresh Kamble",
    actorRole: "Billing Staff",
    action: "Applied 10% discount",
    entity: "Invoice",
    entityId: "INV-2026-08-1043",
    timestamp: "2026-08-14T07:51:44",
    ipAddress: "10.22.4.55",
    status: "success",
  },
  {
    id: "adt_003",
    actor: "Priya Deshmukh",
    actorRole: "Receptionist",
    action: "Rescheduled appointment",
    entity: "Appointment",
    entityId: "apt_007",
    timestamp: "2026-08-14T07:30:09",
    ipAddress: "10.22.4.12",
    status: "success",
  },
  {
    id: "adt_004",
    actor: "Unknown",
    actorRole: "System",
    action: "Failed login attempt (3x)",
    entity: "Auth",
    entityId: "user_9921",
    timestamp: "2026-08-14T05:14:52",
    ipAddress: "103.44.19.201",
    status: "failed",
  },
  {
    id: "adt_005",
    actor: "Hospital Admin",
    actorRole: "Admin",
    action: "Updated role permissions",
    entity: "Role",
    entityId: "role_billing_staff",
    timestamp: "2026-08-13T19:44:03",
    ipAddress: "10.22.4.2",
    status: "success",
  },
  {
    id: "adt_006",
    actor: "Ritu Sharma",
    actorRole: "Nurse",
    action: "Escalated critical patient concern",
    entity: "Patient",
    entityId: "pat_003",
    timestamp: "2026-08-13T16:12:37",
    ipAddress: "10.22.4.61",
    status: "success",
  },
  {
    id: "adt_007",
    actor: "Vendor - MedSupply Healthcare",
    actorRole: "Vendor",
    action: "Submitted quote",
    entity: "Procurement Request",
    entityId: "pr_002",
    timestamp: "2026-08-13T11:05:22",
    ipAddress: "182.71.9.44",
    status: "success",
  },
];

export const roles: RoleDefinition[] = [
  {
    id: "role_hospital_admin",
    name: "Hospital Admin",
    description: "Full operational access across doctors, staff, vendors, billing and patients.",
    userCount: 2,
    system: true,
    permissions: [
      { module: "Doctors", view: true, create: true, edit: true, delete: true, approve: true },
      { module: "Clinic Staff", view: true, create: true, edit: true, delete: true, approve: true },
      { module: "Vendors", view: true, create: true, edit: true, delete: true, approve: true },
      { module: "Billing", view: true, create: true, edit: true, delete: false, approve: true },
      { module: "Patients", view: true, create: true, edit: true, delete: false, approve: false },
    ],
  },
  {
    id: "role_doctor",
    name: "Doctor",
    description: "Clinical workspace access limited to own patients and permitted shared care.",
    userCount: 8,
    system: true,
    permissions: [
      { module: "Doctors", view: true, create: false, edit: false, delete: false, approve: false },
      { module: "Clinic Staff", view: false, create: false, edit: false, delete: false, approve: false },
      { module: "Vendors", view: false, create: false, edit: false, delete: false, approve: false },
      { module: "Billing", view: true, create: false, edit: false, delete: false, approve: false },
      { module: "Patients", view: true, create: true, edit: true, delete: false, approve: false },
    ],
  },
  {
    id: "role_receptionist",
    name: "Receptionist",
    description: "Front-desk operations: appointments, check-in and limited billing.",
    userCount: 3,
    system: true,
    permissions: [
      { module: "Doctors", view: true, create: false, edit: false, delete: false, approve: false },
      { module: "Clinic Staff", view: false, create: false, edit: false, delete: false, approve: false },
      { module: "Vendors", view: false, create: false, edit: false, delete: false, approve: false },
      { module: "Billing", view: true, create: true, edit: false, delete: false, approve: false },
      { module: "Patients", view: true, create: true, edit: true, delete: false, approve: false },
    ],
  },
  {
    id: "role_billing_staff",
    name: "Billing Staff",
    description: "Invoicing, payments, refunds and reconciliation within assigned scope.",
    userCount: 2,
    system: true,
    permissions: [
      { module: "Doctors", view: false, create: false, edit: false, delete: false, approve: false },
      { module: "Clinic Staff", view: false, create: false, edit: false, delete: false, approve: false },
      { module: "Vendors", view: false, create: false, edit: false, delete: false, approve: false },
      { module: "Billing", view: true, create: true, edit: true, delete: false, approve: false },
      { module: "Patients", view: true, create: false, edit: false, delete: false, approve: false },
    ],
  },
  {
    id: "role_nurse",
    name: "Nurse",
    description: "Assigned patient care, tasks, vitals and nursing documentation.",
    userCount: 4,
    system: true,
    permissions: [
      { module: "Doctors", view: true, create: false, edit: false, delete: false, approve: false },
      { module: "Clinic Staff", view: false, create: false, edit: false, delete: false, approve: false },
      { module: "Vendors", view: false, create: false, edit: false, delete: false, approve: false },
      { module: "Billing", view: false, create: false, edit: false, delete: false, approve: false },
      { module: "Patients", view: true, create: false, edit: true, delete: false, approve: false },
    ],
  },
  {
    id: "role_lab_staff",
    name: "Lab Staff",
    description: "Sample management, result entry and report validation.",
    userCount: 3,
    system: true,
    permissions: [
      { module: "Doctors", view: false, create: false, edit: false, delete: false, approve: false },
      { module: "Clinic Staff", view: false, create: false, edit: false, delete: false, approve: false },
      { module: "Vendors", view: false, create: false, edit: false, delete: false, approve: false },
      { module: "Billing", view: false, create: false, edit: false, delete: false, approve: false },
      { module: "Patients", view: true, create: false, edit: false, delete: false, approve: false },
    ],
  },
];
