import {
  PatientReviewItem,
  NPSSurveyResponse,
  GrievanceCase,
  DoctorScorecard,
  DepartmentScorecard,
  ReviewAnalyticsSummary,
} from "@/hospital-admin/lib/types/patient-reviews";

export const mockPatientReviews: PatientReviewItem[] = [
  {
    id: "rev-google-001",
    source: "Google",
    patientName: "Rajeshwar Iyer",
    rating: 5,
    reviewText:
      "Exceptional care by Dr. Arvind Kumar during my father's pacemaker implantation. The CCU nursing team was attentive 24/7. Highly recommended!",
    submittedAt: "2026-08-28 14:30",
    responded: true,
    responseText:
      "Dear Mr. Iyer, thank you for your kind words. We are thrilled to hear your father received exemplary care under Dr. Arvind Kumar and our cardiac nursing team.",
    respondedBy: "Hospital Admin (Dr. Farooq Abdullah)",
    respondedAt: "2026-08-28 17:15",
    linkedDoctorId: "doc-101",
    linkedDoctorName: "Dr. Arvind Kumar",
    linkedDepartmentId: "dept-cardio",
    linkedDepartmentName: "Cardiology",
    sentiment: "Positive",
    tags: ["Bedside Manner", "Nursing Care", "Cardiac Surgery"],
    googleReviewUrl: "https://maps.google.com/?cid=qlyno-hospital",
  },
  {
    id: "rev-survey-002",
    source: "Post-Discharge Survey",
    patientId: "UHID-2026-8910",
    patientName: "Meenakshi Sundaram",
    rating: 5,
    reviewText:
      "My total knee replacement surgery went smoothly. Dr. Rajesh Sharma and the physio team were very gentle and supportive. Room hygiene was spotless.",
    submittedAt: "2026-08-27 10:15",
    responded: true,
    responseText:
      "Thank you Meenakshi ji for sharing your positive recovery journey. We wish you continued mobility and good health!",
    respondedBy: "Patient Care Coordinator",
    respondedAt: "2026-08-27 11:30",
    linkedDoctorId: "doc-103",
    linkedDoctorName: "Dr. Rajesh Sharma",
    linkedDepartmentId: "dept-ortho",
    linkedDepartmentName: "Orthopaedics",
    sentiment: "Positive",
    tags: ["Joint Replacement", "Physiotherapy", "Hygiene"],
  },
  {
    id: "rev-google-003",
    source: "Google",
    patientName: "Venkatesh Rao",
    rating: 1,
    reviewText:
      "Extremely frustrating experience at the OPD Billing Counter #2. Waited over 45 minutes just to get a receipt stamped, and the billing clerk was rude when questioned.",
    submittedAt: "2026-08-29 09:40",
    responded: false,
    linkedDepartmentId: "dept-billing",
    linkedDepartmentName: "Billing & Cash Counters",
    sentiment: "Negative",
    tags: ["Billing Transparency", "Wait Time", "Staff Attitude"],
    isEscalatedToGrievance: true,
    grievanceCaseId: "GRV-2026-0041",
    googleReviewUrl: "https://maps.google.com/?cid=qlyno-hospital",
  },
  {
    id: "rev-portal-004",
    source: "Portal App",
    patientId: "UHID-2026-7732",
    patientName: "Ananya Deshmukh",
    rating: 4,
    reviewText:
      "Dr. Sunita Rao gave us very clear explanations before our daughter's pediatric consultation. The wait in the lounge was slightly long, but the doctor spent ample time with us.",
    submittedAt: "2026-08-26 16:20",
    responded: true,
    responseText:
      "Dear Ananya, we appreciate your constructive feedback regarding the lounge wait time and are glad Dr. Sunita could provide the reassuring care your child needed.",
    respondedBy: "Hospital Admin",
    respondedAt: "2026-08-26 18:00",
    linkedDoctorId: "doc-104",
    linkedDoctorName: "Dr. Sunita Rao",
    linkedDepartmentId: "dept-pediatrics",
    linkedDepartmentName: "Pediatrics",
    sentiment: "Positive",
    tags: ["Doctor Communication", "Wait Time"],
  },
  {
    id: "rev-google-005",
    source: "Google",
    patientName: "Karan Malhotra",
    rating: 2,
    reviewText:
      "Emergency triage took 25 minutes to attend to a high fever case at 2 AM. Nursing staff was overwhelmed and there was confusion regarding bed availability.",
    submittedAt: "2026-08-29 11:20",
    responded: false,
    linkedDepartmentId: "dept-emg",
    linkedDepartmentName: "Emergency & Trauma",
    sentiment: "Negative",
    tags: ["Emergency Triage", "Bed Availability", "Wait Time"],
    isEscalatedToGrievance: true,
    grievanceCaseId: "GRV-2026-0042",
    googleReviewUrl: "https://maps.google.com/?cid=qlyno-hospital",
  },
  {
    id: "rev-survey-006",
    source: "Post-Discharge Survey",
    patientId: "UHID-2026-6641",
    patientName: "Siddharth Bose",
    rating: 5,
    reviewText:
      "Superb post-op care in the surgical HDU. The discharge medication summary on WhatsApp was very clear and the pharmacy delivered medicines directly to our room.",
    submittedAt: "2026-08-25 15:45",
    responded: true,
    responseText:
      "Thank you Mr. Bose! Room-delivered discharge medication is part of our patient-first initiative.",
    respondedBy: "Quality & Inpatient Lead",
    respondedAt: "2026-08-25 17:00",
    linkedDepartmentId: "dept-surg",
    linkedDepartmentName: "General Surgery",
    sentiment: "Positive",
    tags: ["Discharge Efficiency", "Pharmacy", "Nursing Care"],
  },
  {
    id: "rev-google-007",
    source: "Google",
    patientName: "Pooja Hegde",
    rating: 4,
    reviewText:
      "Very neat and clean hospital with high-tech MRI diagnostics. The radiologist explained the imaging report nicely. Cafeteria options could be expanded.",
    submittedAt: "2026-08-28 18:10",
    responded: false,
    linkedDepartmentId: "dept-rad",
    linkedDepartmentName: "Radiology",
    sentiment: "Positive",
    tags: ["Diagnostics", "Radiology", "Hospital Amenities"],
    googleReviewUrl: "https://maps.google.com/?cid=qlyno-hospital",
  },
  {
    id: "rev-survey-008",
    source: "Post-Discharge Survey",
    patientId: "UHID-2026-5519",
    patientName: "Harish Chandra",
    rating: 1,
    reviewText:
      "Insurance TPA desk took 6 hours to clear the final cashless settlement on discharge day, forcing us to wait in the room till evening.",
    submittedAt: "2026-08-29 13:00",
    responded: false,
    linkedDepartmentId: "dept-insurance",
    linkedDepartmentName: "Insurance / TPA Desk",
    sentiment: "Negative",
    tags: ["TPA Settlement", "Discharge Delay", "Billing Transparency"],
    isEscalatedToGrievance: true,
    grievanceCaseId: "GRV-2026-0043",
  },
];

export const mockNpsSurveyResponses: NPSSurveyResponse[] = [
  {
    id: "nps-501",
    patientId: "UHID-2026-8910",
    patientName: "Meenakshi Sundaram",
    encounterId: "IPD-ENC-4401",
    score: 10,
    category: "Promoter",
    feedbackText: "Flawless joint replacement recovery, exceptional doctors.",
    submittedAt: "2026-08-27 10:15",
    triggeredByDischargeId: "DISCH-2026-104",
    dispatchedViaChannel: "WhatsApp",
    departmentName: "Orthopaedics",
    doctorName: "Dr. Rajesh Sharma",
    followupRequired: false,
  },
  {
    id: "nps-502",
    patientId: "UHID-2026-6641",
    patientName: "Siddharth Bose",
    encounterId: "IPD-ENC-4395",
    score: 9,
    category: "Promoter",
    feedbackText: "Great nursing care in HDU and seamless discharge delivery.",
    submittedAt: "2026-08-25 15:45",
    triggeredByDischargeId: "DISCH-2026-102",
    dispatchedViaChannel: "WhatsApp",
    departmentName: "General Surgery",
    doctorName: "Dr. Farooq Abdullah",
    followupRequired: false,
  },
  {
    id: "nps-503",
    patientId: "UHID-2026-7732",
    patientName: "Ananya Deshmukh",
    encounterId: "OPD-ENC-9912",
    score: 8,
    category: "Passive",
    feedbackText: "Good doctor, waiting lounge needs more seating.",
    submittedAt: "2026-08-26 16:20",
    triggeredByDischargeId: "DISCH-2026-103",
    dispatchedViaChannel: "WhatsApp",
    departmentName: "Pediatrics",
    doctorName: "Dr. Sunita Rao",
    followupRequired: false,
  },
  {
    id: "nps-504",
    patientId: "UHID-2026-5519",
    patientName: "Harish Chandra",
    encounterId: "IPD-ENC-4412",
    score: 3,
    category: "Detractor",
    feedbackText: "TPA cashless processing was excruciatingly slow.",
    submittedAt: "2026-08-29 13:00",
    triggeredByDischargeId: "DISCH-2026-108",
    dispatchedViaChannel: "SMS",
    departmentName: "Insurance / TPA Desk",
    followupRequired: true,
  },
  {
    id: "nps-505",
    patientId: "UHID-2026-3390",
    patientName: "Deepak Nambiar",
    encounterId: "IPD-ENC-4420",
    score: 10,
    category: "Promoter",
    feedbackText: "Outstanding cardiac angioplasty team.",
    submittedAt: "2026-08-28 11:30",
    triggeredByDischargeId: "DISCH-2026-105",
    dispatchedViaChannel: "WhatsApp",
    departmentName: "Cardiology",
    doctorName: "Dr. Arvind Kumar",
    followupRequired: false,
  },
  {
    id: "nps-506",
    patientId: "UHID-2026-2180",
    patientName: "Sunil Verma",
    encounterId: "IPD-ENC-4428",
    score: 4,
    category: "Detractor",
    feedbackText: "Food arrived cold twice during our inpatient stay.",
    submittedAt: "2026-08-28 17:00",
    triggeredByDischargeId: "DISCH-2026-106",
    dispatchedViaChannel: "WhatsApp",
    departmentName: "General Ward",
    followupRequired: true,
  },
];

export const mockGrievanceCases: GrievanceCase[] = [
  {
    id: "GRV-2026-0041",
    patientId: "UHID-2026-9012",
    patientName: "Venkatesh Rao",
    patientPhone: "+91 98450 12345",
    category: "Billing",
    description:
      "Patient faced 45-minute delay and impolite interaction at OPD Billing Counter #2 while requesting itemized consultation break-up.",
    sourceReviewId: "rev-google-003",
    severity: "Medium",
    escalationTier: "Tier 1 - Ward Incharge",
    assignedTo: "Ramesh Nair (Billing Lead)",
    status: "In Progress",
    createdAt: "2026-08-29 10:00",
    slaDeadline: "2026-08-30 10:00",
    isOverdue: false,
    patientCallbackConfirmed: false,
  },
  {
    id: "GRV-2026-0042",
    patientId: "UHID-2026-9155",
    patientName: "Karan Malhotra",
    patientPhone: "+91 99800 54321",
    category: "Clinical Care",
    description:
      "High-grade fever pediatric patient waited 25 mins during 2 AM emergency triage shift change; bed status coordination failure in PICU.",
    sourceReviewId: "rev-google-005",
    severity: "Critical",
    escalationTier: "Tier 2 - Medical Superintendent",
    assignedTo: "Dr. Farooq Abdullah (Med Supt)",
    status: "Escalated",
    createdAt: "2026-08-29 11:45",
    slaDeadline: "2026-08-29 17:45",
    isOverdue: true,
    patientCallbackConfirmed: true,
  },
  {
    id: "GRV-2026-0043",
    patientId: "UHID-2026-5519",
    patientName: "Harish Chandra",
    patientPhone: "+91 97411 67890",
    category: "Billing",
    description:
      "TPA cashless pre-auth settlement delay of 6 hours post doctor discharge order; room retention charges dispute.",
    sourceReviewId: "rev-survey-008",
    severity: "High",
    escalationTier: "Tier 2 - Medical Superintendent",
    assignedTo: "Priya Menon (TPA Manager)",
    status: "In Progress",
    createdAt: "2026-08-29 13:30",
    slaDeadline: "2026-08-30 13:30",
    isOverdue: false,
    patientCallbackConfirmed: false,
  },
  {
    id: "GRV-2026-0038",
    patientId: "UHID-2026-4409",
    patientName: "Geeta Kulkarni",
    patientPhone: "+91 98860 11223",
    category: "Nursing",
    description:
      "Delay in IV antibiotic administration on 4th floor west ward during nursing shift changeover.",
    severity: "Medium",
    escalationTier: "Tier 1 - Ward Incharge",
    assignedTo: "Sister Sheela (Floor Incharge)",
    status: "Resolved",
    createdAt: "2026-08-24 16:00",
    slaDeadline: "2026-08-25 16:00",
    isOverdue: false,
    resolvedAt: "2026-08-25 11:30",
    resolutionNotes:
      "Investigation conducted. Medication administration schedule aligned with electronic MAR alarms. Patient called and satisfied.",
    patientCallbackConfirmed: true,
    resolvedBy: "Sister Sheela",
  },
];

export const mockDoctorScorecards: DoctorScorecard[] = [
  {
    doctorId: "doc-101",
    doctorName: "Dr. Arvind Kumar",
    specialty: "Interventional Cardiology",
    departmentId: "dept-cardio",
    departmentName: "Cardiology",
    averageRating: 4.9,
    totalReviews: 312,
    starBreakdown: { stars5: 280, stars4: 24, stars3: 6, stars2: 1, stars1: 1 },
    dimensions: [
      { dimension: "Bedside Manner & Empathy", score: 4.9 },
      { dimension: "Clinical Clarity & Explanation", score: 4.9 },
      { dimension: "Punctuality & Chamber Wait Time", score: 4.6 },
      { dimension: "Post-Procedure Follow-up", score: 4.8 },
    ],
    operationalVolume: 1240,
    patientRecommendationPercent: 98,
  },
  {
    doctorId: "doc-103",
    doctorName: "Dr. Rajesh Sharma",
    specialty: "Orthopaedic & Joint Replacement",
    departmentId: "dept-ortho",
    departmentName: "Orthopaedics",
    averageRating: 4.8,
    totalReviews: 245,
    starBreakdown: { stars5: 210, stars4: 25, stars3: 8, stars2: 1, stars1: 1 },
    dimensions: [
      { dimension: "Bedside Manner & Empathy", score: 4.8 },
      { dimension: "Clinical Clarity & Explanation", score: 4.9 },
      { dimension: "Punctuality & Chamber Wait Time", score: 4.5 },
      { dimension: "Post-Procedure Follow-up", score: 4.7 },
    ],
    operationalVolume: 890,
    patientRecommendationPercent: 96,
  },
  {
    doctorId: "doc-104",
    doctorName: "Dr. Sunita Rao",
    specialty: "Pediatrics & Neonatology",
    departmentId: "dept-pediatrics",
    departmentName: "Pediatrics",
    averageRating: 4.7,
    totalReviews: 198,
    starBreakdown: { stars5: 160, stars4: 26, stars3: 8, stars2: 3, stars1: 1 },
    dimensions: [
      { dimension: "Bedside Manner & Empathy", score: 4.9 },
      { dimension: "Clinical Clarity & Explanation", score: 4.8 },
      { dimension: "Punctuality & Chamber Wait Time", score: 4.2 },
      { dimension: "Post-Procedure Follow-up", score: 4.6 },
    ],
    operationalVolume: 740,
    patientRecommendationPercent: 94,
  },
  {
    doctorId: "doc-107",
    doctorName: "Dr. Farooq Abdullah",
    specialty: "General & Laparoscopic Surgery",
    departmentId: "dept-surg",
    departmentName: "General Surgery",
    averageRating: 4.8,
    totalReviews: 180,
    starBreakdown: { stars5: 155, stars4: 18, stars3: 5, stars2: 1, stars1: 1 },
    dimensions: [
      { dimension: "Bedside Manner & Empathy", score: 4.8 },
      { dimension: "Clinical Clarity & Explanation", score: 4.8 },
      { dimension: "Punctuality & Chamber Wait Time", score: 4.6 },
      { dimension: "Post-Procedure Follow-up", score: 4.8 },
    ],
    operationalVolume: 620,
    patientRecommendationPercent: 97,
  },
];

export const mockDepartmentScorecards: DepartmentScorecard[] = [
  {
    departmentId: "dept-cardio",
    departmentName: "Cardiology & Cath Lab",
    averageRating: 4.9,
    totalReviews: 420,
    starBreakdown: { stars5: 380, stars4: 30, stars3: 8, stars2: 1, stars1: 1 },
    dimensions: [
      { dimension: "Clinical Care Quality", score: 4.9 },
      { dimension: "Nursing Responsiveness", score: 4.8 },
      { dimension: "Room Hygiene & Cleanliness", score: 4.9 },
      { dimension: "Discharge Turnaround", score: 4.7 },
    ],
    patientRecommendationPercent: 98,
  },
  {
    departmentId: "dept-ortho",
    departmentName: "Orthopaedics & Joint Replacement",
    averageRating: 4.8,
    totalReviews: 310,
    starBreakdown: { stars5: 270, stars4: 28, stars3: 9, stars2: 2, stars1: 1 },
    dimensions: [
      { dimension: "Clinical Care Quality", score: 4.8 },
      { dimension: "Physiotherapy Support", score: 4.9 },
      { dimension: "Nursing Responsiveness", score: 4.7 },
      { dimension: "Discharge Turnaround", score: 4.6 },
    ],
    patientRecommendationPercent: 96,
  },
  {
    departmentId: "dept-emg",
    departmentName: "Emergency & Trauma Bay",
    averageRating: 4.3,
    totalReviews: 215,
    starBreakdown: { stars5: 130, stars4: 45, stars3: 20, stars2: 12, stars1: 8 },
    dimensions: [
      { dimension: "Clinical Care Quality", score: 4.6 },
      { dimension: "Triage Speed", score: 3.9 },
      { dimension: "Nursing Responsiveness", score: 4.2 },
      { dimension: "Admission Coordination", score: 4.0 },
    ],
    patientRecommendationPercent: 86,
  },
  {
    departmentId: "dept-rad",
    departmentName: "Radiology & Diagnostic Imaging",
    averageRating: 4.7,
    totalReviews: 280,
    starBreakdown: { stars5: 220, stars4: 45, stars3: 12, stars2: 2, stars1: 1 },
    dimensions: [
      { dimension: "Equipment Modernity", score: 4.9 },
      { dimension: "Report Turnaround Speed", score: 4.6 },
      { dimension: "Staff Courtesy", score: 4.7 },
      { dimension: "Appointment Punctuality", score: 4.5 },
    ],
    patientRecommendationPercent: 95,
  },
  {
    departmentId: "dept-billing",
    departmentName: "Billing & TPA Insurance",
    averageRating: 4.1,
    totalReviews: 185,
    starBreakdown: { stars5: 90, stars4: 40, stars3: 25, stars2: 18, stars1: 12 },
    dimensions: [
      { dimension: "Bill Itemization Clarity", score: 4.3 },
      { dimension: "Counter Queue Speed", score: 3.7 },
      { dimension: "TPA Cashless Clearance", score: 3.8 },
      { dimension: "Staff Courtesy", score: 4.0 },
    ],
    patientRecommendationPercent: 78,
  },
];

export const mockReviewAnalyticsSummary: ReviewAnalyticsSummary = {
  hospitalAverageRating: 4.8,
  totalReviewsCount: 1420,
  npsScore: 68,
  npsPromotersPercent: 74,
  npsPassivesPercent: 20,
  npsDetractorsPercent: 6,
  averageResponseTimeHours: 4.2,
  responseRatePercent: 92.4,
  unansweredCount: 12,
  activeGrievancesCount: 4,
  monthlyRatingTrend: [
    { month: "Jan 2026", rating: 4.6, reviewCount: 140 },
    { month: "Feb 2026", rating: 4.7, reviewCount: 155 },
    { month: "Mar 2026", rating: 4.7, reviewCount: 168 },
    { month: "Apr 2026", rating: 4.8, reviewCount: 180 },
    { month: "May 2026", rating: 4.8, reviewCount: 195 },
    { month: "Jun 2026", rating: 4.8, reviewCount: 185 },
    { month: "Jul 2026", rating: 4.9, reviewCount: 202 },
    { month: "Aug 2026", rating: 4.8, reviewCount: 195 },
  ],
  monthlyNpsTrend: [
    { month: "Jan 2026", nps: 58 },
    { month: "Feb 2026", nps: 61 },
    { month: "Mar 2026", nps: 63 },
    { month: "Apr 2026", nps: 65 },
    { month: "May 2026", nps: 67 },
    { month: "Jun 2026", nps: 66 },
    { month: "Jul 2026", nps: 70 },
    { month: "Aug 2026", nps: 68 },
  ],
  sentimentBreakdown: [
    { sentiment: "Positive", count: 1165, percentage: 82.0 },
    { sentiment: "Neutral", count: 170, percentage: 12.0 },
    { sentiment: "Negative", count: 85, percentage: 6.0 },
  ],
  categorySentiment: [
    { category: "Doctor Care & Bedside Manner", positivePercent: 96, negativePercent: 4 },
    { category: "Nursing Attentiveness & Compassion", positivePercent: 92, negativePercent: 8 },
    { category: "Inpatient Room Hygiene & Food", positivePercent: 89, negativePercent: 11 },
    { category: "Diagnostics & Imaging Accuracy", positivePercent: 94, negativePercent: 6 },
    { category: "Billing Transparency & TPA Speed", positivePercent: 78, negativePercent: 22 },
    { category: "OPD & Emergency Waiting Times", positivePercent: 75, negativePercent: 25 },
  ],
};
