import {
  PaymentTransaction,
  CashDrawerReport,
  RefundReconciliationRecord,
} from "@/hospital-admin/lib/types";

// ==========================================
// 1. EXTENDED PAYMENT TRANSACTIONS LEDGER
// ==========================================
export const mockExtendedPaymentTransactions: PaymentTransaction[] = [
  // CASH TRANSACTIONS (COUNTER 1 & 3)
  {
    id: "pay_101",
    receiptNo: "REC-2026-8801",
    patientId: "P-1001",
    patientName: "Ramesh Sharma",
    invoiceId: "INV-2026-0891",
    amount: 1500,
    paymentMethod: "Cash",
    counterNo: "Counter 1 (Main OPD)",
    cashierName: "Rajesh Kadam",
    timestamp: "2026-08-25T09:15:00Z",
    reconciliationStatus: "Reconciled",
    department: "General Medicine",
    notes: "OPD Consultation & ECG fee",
  },
  {
    id: "pay_102",
    receiptNo: "REC-2026-8802",
    patientId: "P-1004",
    patientName: "Sunita Patel",
    invoiceId: "INV-2026-0894",
    amount: 8500,
    paymentMethod: "Cash",
    counterNo: "Counter 1 (Main OPD)",
    cashierName: "Rajesh Kadam",
    timestamp: "2026-08-25T09:45:00Z",
    reconciliationStatus: "Reconciled",
    department: "Orthopaedics",
    notes: "Knee Injection & Physiotherapy initial deposit",
  },
  {
    id: "pay_103",
    receiptNo: "REC-2026-8803",
    patientId: "P-8821",
    patientName: "Arjun Gupta",
    invoiceId: "INV-2026-IPD-409",
    amount: 25000,
    paymentMethod: "Cash",
    counterNo: "Counter 3 (IPD Admissions)",
    cashierName: "Meenakshi Sundaram",
    timestamp: "2026-08-25T10:30:00Z",
    reconciliationStatus: "Reconciled",
    department: "IPD Surgical Wing",
    notes: "IPD Advance Room & Bed allocation deposit",
  },
  {
    id: "pay_104",
    receiptNo: "REC-2026-8804",
    patientId: "P-1009",
    patientName: "Deepak Chawla",
    invoiceId: "INV-2026-0902",
    amount: 4200,
    paymentMethod: "Cash",
    counterNo: "Counter 3 (IPD Admissions)",
    cashierName: "Meenakshi Sundaram",
    timestamp: "2026-08-25T11:00:00Z",
    reconciliationStatus: "Reconciled",
    department: "Day Care Surgery",
    notes: "Day Care procedural surcharge",
  },

  // UPI / QR TRANSACTIONS
  {
    id: "pay_201",
    receiptNo: "REC-2026-8805",
    patientId: "P-1002",
    patientName: "Sita Devi",
    invoiceId: "INV-2026-0892",
    amount: 3200,
    paymentMethod: "UPI/QR",
    counterNo: "Counter 2 (Lab & Diagnostics)",
    cashierName: "Priya Nair",
    timestamp: "2026-08-25T09:30:00Z",
    reconciliationStatus: "Reconciled",
    gatewayRefId: "UPI-ICICI-994821034",
    terminalId: "QR-DESK-02",
    department: "Clinical Biochemistry",
    notes: "Dynamic Dynamic QR Pay - HDFC Instant UPI",
  },
  {
    id: "pay_202",
    receiptNo: "REC-2026-8806",
    patientId: "P-1007",
    patientName: "Vikram Malhotra",
    invoiceId: "INV-2026-PHARM-104",
    amount: 2850,
    paymentMethod: "UPI/QR",
    counterNo: "Counter 1 (Main OPD)",
    cashierName: "Rajesh Kadam",
    timestamp: "2026-08-25T10:15:00Z",
    reconciliationStatus: "Reconciled",
    gatewayRefId: "UPI-AXIS-882104928",
    terminalId: "QR-DESK-01",
    department: "Central Pharmacy",
    notes: "GPay QR scan - Patient Pharmacy Bill",
  },
  {
    id: "pay_203",
    receiptNo: "REC-2026-8807",
    patientId: "P-1015",
    patientName: "Manoj Kumar",
    invoiceId: "INV-2026-0910",
    amount: 14500,
    paymentMethod: "UPI/QR",
    counterNo: "Counter 2 (Lab & Diagnostics)",
    cashierName: "Priya Nair",
    timestamp: "2026-08-25T10:45:00Z",
    reconciliationStatus: "Reconciled",
    gatewayRefId: "UPI-HDFC-771920381",
    terminalId: "QR-DESK-02",
    department: "Radiology (MRI Brain)",
    notes: "PhonePe QR scan - 3T MRI Scan payment",
  },
  {
    id: "pay_204",
    receiptNo: "REC-2026-8808",
    patientId: "P-1022",
    patientName: "Pooja Hegde",
    invoiceId: "INV-2026-0914",
    amount: 1800,
    paymentMethod: "UPI/QR",
    counterNo: "Counter 4 (Emergency Billing)",
    cashierName: "Vikram Gaikwad",
    timestamp: "2026-08-25T11:20:00Z",
    reconciliationStatus: "Pending Settlement",
    gatewayRefId: "UPI-PAYTM-449102847",
    terminalId: "QR-DESK-04",
    department: "Emergency ER",
    notes: "Paytm Soundbox verified - Auto batching at 14:00",
  },

  // CARD / POS TRANSACTIONS
  {
    id: "pay_301",
    receiptNo: "REC-2026-8809",
    patientId: "P-9102",
    patientName: "Kavita Patil",
    invoiceId: "INV-2026-IPD-9102",
    amount: 38000,
    paymentMethod: "Credit/Debit Card",
    counterNo: "Counter 3 (IPD Admissions)",
    cashierName: "Meenakshi Sundaram",
    timestamp: "2026-08-25T09:50:00Z",
    reconciliationStatus: "Reconciled",
    gatewayRefId: "POS-TXN-884920",
    terminalId: "POS-HDFC-9912",
    cardLast4: "4921",
    cardType: "HDFC Regalia Visa",
    department: "Cardiothoracic Surgery",
    notes: "POS Chip & PIN auth - Batch #104",
  },
  {
    id: "pay_302",
    receiptNo: "REC-2026-8810",
    patientId: "P-1031",
    patientName: "Nitin Gadkari Jr.",
    invoiceId: "INV-2026-0922",
    amount: 12500,
    paymentMethod: "Credit/Debit Card",
    counterNo: "Counter 1 (Main OPD)",
    cashierName: "Rajesh Kadam",
    timestamp: "2026-08-25T10:40:00Z",
    reconciliationStatus: "Reconciled",
    gatewayRefId: "POS-TXN-884928",
    terminalId: "POS-ICICI-4410",
    cardLast4: "8812",
    cardType: "ICICI Sapphiro Mastercard",
    department: "Executive Health Checkup",
    notes: "POS Contactless Tap - Batch #104",
  },
  {
    id: "pay_303",
    receiptNo: "REC-2026-8811",
    patientId: "P-1044",
    patientName: "Anil Deshmukh",
    invoiceId: "INV-2026-0931",
    amount: 6400,
    paymentMethod: "Credit/Debit Card",
    counterNo: "Counter 2 (Lab & Diagnostics)",
    cashierName: "Priya Nair",
    timestamp: "2026-08-25T11:15:00Z",
    reconciliationStatus: "Reconciled",
    gatewayRefId: "POS-TXN-884935",
    terminalId: "POS-HDFC-9914",
    cardLast4: "1094",
    cardType: "SBI Global RuPay",
    department: "Pathology Special Tests",
    notes: "POS Chip Swipe - Batch #104",
  },

  // ONLINE BANK TRANSFERS & TPA SETTLEMENTS
  {
    id: "pay_401",
    receiptNo: "REC-2026-8812",
    patientId: "P-8821",
    patientName: "Arjun Gupta",
    invoiceId: "INV-2026-IPD-409",
    amount: 145000,
    paymentMethod: "Bank Transfer",
    counterNo: "Counter 3 (IPD Admissions)",
    cashierName: "Meenakshi Sundaram",
    timestamp: "2026-08-25T08:30:00Z",
    reconciliationStatus: "Reconciled",
    gatewayRefId: "UTR-HDFC-N8849102847",
    tpaClaimNo: "CLM-2026-STAR-9921",
    tpaProvider: "Star Health",
    department: "Inpatient Cashless Desk",
    notes: "TPA Direct Cashless Settlement via NEFT/RTGS",
  },
  {
    id: "pay_402",
    receiptNo: "REC-2026-8813",
    patientId: "P-9102",
    patientName: "Kavita Patil",
    invoiceId: "INV-2026-IPD-9102",
    amount: 185000,
    paymentMethod: "Bank Transfer",
    counterNo: "Counter 3 (IPD Admissions)",
    cashierName: "Meenakshi Sundaram",
    timestamp: "2026-08-25T09:00:00Z",
    reconciliationStatus: "Reconciled",
    gatewayRefId: "UTR-ICICI-N9910248102",
    tpaClaimNo: "CLM-2026-HDFC-8812",
    tpaProvider: "HDFC ERGO",
    department: "Inpatient Cashless Desk",
    notes: "TPA Cashless Pre-Auth Claim Final Settlement",
  },
  {
    id: "pay_403",
    receiptNo: "REC-2026-8814",
    patientId: "P-1055",
    patientName: "Sanjay Singhania",
    invoiceId: "INV-2026-0940",
    amount: 50000,
    paymentMethod: "Bank Transfer",
    counterNo: "Counter 4 (Emergency Billing)",
    cashierName: "Vikram Gaikwad",
    timestamp: "2026-08-25T10:05:00Z",
    reconciliationStatus: "Pending Settlement",
    gatewayRefId: "UTR-SBIN-N2291048109",
    department: "Emergency Trauma Bay",
    notes: "Patient Direct IMPS Deposit via Hospital Portal",
  },

  // HISTORICAL RECORDS (FOR HISTORY ARCHIVE)
  {
    id: "pay_501",
    receiptNo: "REC-2026-7780",
    patientId: "P-1011",
    patientName: "Bhavna Trivedi",
    invoiceId: "INV-2026-0810",
    amount: 14500,
    paymentMethod: "Credit/Debit Card",
    counterNo: "Counter 1 (Main OPD)",
    cashierName: "Rajesh Kadam",
    timestamp: "2026-08-24T14:30:00Z",
    reconciliationStatus: "Reconciled",
    gatewayRefId: "POS-TXN-774910",
    terminalId: "POS-HDFC-9912",
    cardLast4: "7721",
    cardType: "Axis Vibe Visa",
    department: "Cardiology",
    notes: "Echocardiography & TMT stress test",
  },
  {
    id: "pay_502",
    receiptNo: "REC-2026-7781",
    patientId: "P-1012",
    patientName: "Gaurav Sen",
    invoiceId: "INV-2026-0815",
    amount: 3200,
    paymentMethod: "UPI/QR",
    counterNo: "Counter 2 (Lab & Diagnostics)",
    cashierName: "Priya Nair",
    timestamp: "2026-08-24T15:45:00Z",
    reconciliationStatus: "Reconciled",
    gatewayRefId: "UPI-PAYTM-8829104",
    terminalId: "QR-DESK-02",
    department: "Diagnostics",
    notes: "Pathology Thyroid & Vitamin panel",
  },
  {
    id: "pay_503",
    receiptNo: "REC-2026-7782",
    patientId: "P-1018",
    patientName: "Harish Iyer",
    invoiceId: "INV-2026-0820",
    amount: 60000,
    paymentMethod: "Bank Transfer",
    counterNo: "Counter 3 (IPD Admissions)",
    cashierName: "Meenakshi Sundaram",
    timestamp: "2026-08-23T11:20:00Z",
    reconciliationStatus: "Reconciled",
    gatewayRefId: "UTR-HDFC-771029481",
    tpaClaimNo: "CLM-2026-ICICI-1102",
    tpaProvider: "ICICI Lombard",
    department: "IPD Surgical Wing",
    notes: "TPA Interim Pre-Auth Settlement",
  },
];

// ==========================================
// 2. CASH DRAWER REPORTS (FOR CASH COUNTERS)
// ==========================================
export const mockExtendedCashDrawers: CashDrawerReport[] = [
  {
    counterId: "cnt_01",
    counterName: "Counter 1 (Main OPD Lobby)",
    cashierName: "Rajesh Kadam",
    openingFloat: 5000,
    cashCollected: 38400,
    posCollected: 62500,
    upiCollected: 44100,
    refundsDeducted: 1200,
    closingBalance: 42200,
    variance: 0,
    status: "Balanced",
  },
  {
    counterId: "cnt_02",
    counterName: "Counter 2 (Lab & Diagnostics)",
    cashierName: "Priya Nair",
    openingFloat: 5000,
    cashCollected: 24500,
    posCollected: 41000,
    upiCollected: 31200,
    refundsDeducted: 0,
    closingBalance: 29500,
    variance: 0,
    status: "Balanced",
  },
  {
    counterId: "cnt_03",
    counterName: "Counter 3 (IPD Admissions & Discharge)",
    cashierName: "Meenakshi Sundaram",
    openingFloat: 10000,
    cashCollected: 85000,
    posCollected: 142000,
    upiCollected: 68500,
    refundsDeducted: 4500,
    closingBalance: 90500,
    variance: 0,
    status: "Balanced",
  },
  {
    counterId: "cnt_04",
    counterName: "Counter 4 (Emergency & Trauma 24x7)",
    cashierName: "Vikram Gaikwad",
    openingFloat: 5000,
    cashCollected: 18200,
    posCollected: 28400,
    upiCollected: 19800,
    refundsDeducted: 0,
    closingBalance: 23200,
    variance: 0,
    status: "Open",
  },
];

// ==========================================
// 3. REFUND RECONCILIATION RECORDS (LENS)
// ==========================================
export const mockRefundReconciliations: RefundReconciliationRecord[] = [
  {
    id: "ref_rec_01",
    refundReceiptNo: "REF-2026-901",
    invoiceId: "INV-2026-06-0771",
    patientId: "P-1005",
    patientName: "Meena Kumari",
    amount: 1200,
    originalMethod: "Cash",
    reversalChannel: "Cash Drawer",
    counterNo: "Counter 1 (Main OPD)",
    cashierName: "Rajesh Kadam",
    approvedBy: "Finance Head (Sunil Varma)",
    approvalReference: "F8-AUTH-0921",
    reconciliationStatus: "Reconciled",
    timestamp: "2026-08-25T10:10:00Z",
    reason: "Doctor consultation cancelled due to emergency OT summons",
  },
  {
    id: "ref_rec_02",
    refundReceiptNo: "REF-2026-902",
    invoiceId: "INV-2026-08-1043",
    patientId: "P-1002",
    patientName: "Sita Devi",
    amount: 4500,
    originalMethod: "Credit/Debit Card",
    reversalChannel: "Card Reversal",
    counterNo: "Counter 3 (IPD Admissions)",
    cashierName: "Meenakshi Sundaram",
    approvedBy: "Medical Superintendent",
    approvalReference: "F11-AUTH-4412",
    reconciliationStatus: "Reconciled",
    timestamp: "2026-08-25T11:05:00Z",
    reason: "Post-op bed tier downgrade credit refund",
  },
  {
    id: "ref_rec_03",
    refundReceiptNo: "REF-2026-903",
    invoiceId: "INV-2026-07-0988",
    patientId: "P-1014",
    patientName: "Rohit Deshmukh",
    amount: 850,
    originalMethod: "UPI/QR",
    reversalChannel: "UPI Gateway Reversal",
    counterNo: "Counter 2 (Lab & Diagnostics)",
    cashierName: "Priya Nair",
    approvedBy: "Billing Supervisor",
    approvalReference: "F8-AUTH-0925",
    reconciliationStatus: "Pending Gateway Reversal",
    timestamp: "2026-08-25T11:35:00Z",
    reason: "Duplicate sample collection billing refund",
  },
];
