import {
  PharmacyPrescription,
  PharmacyPurchaseOrder,
  PharmacySupplier,
  PharmacyStaffMember,
  PharmacyBatchExpiry,
  PharmacySalesRecord,
  PharmacyReturnRecord,
} from "@/hospital-admin/lib/types";

// ==========================================
// 1. INCOMING DOCTOR PRESCRIPTIONS QUEUE
// ==========================================
export const mockPharmacyPrescriptions: PharmacyPrescription[] = [
  {
    id: "rx_01",
    prescriptionNumber: "RX-2026-8801",
    patientId: "PAT-00918",
    patientName: "Rameshwar Patil",
    patientAge: 52,
    patientGender: "Male",
    wardBed: "Trauma Red Bay — Bed 02",
    doctorId: "DOC-004",
    doctorName: "Dr. Arvind Swaminathan",
    doctorSpecialty: "Pulmonologist & Critical Care",
    source: "Emergency",
    priority: "Stat Emergency",
    status: "New",
    prescribedAt: "2026-08-24T12:45:00Z",
    clinicalDiagnosis: "Acute Hypoxemic Respiratory Failure & Severe Bronchospasm",
    totalAmount: 1840,
    items: [
      {
        medicineId: "MED-003",
        medicineName: "Hydrocortisone 100mg Injection",
        dosage: "100mg IV Stat",
        frequency: "Stat immediate",
        duration: "1 Dose",
        quantity: 2,
        unitPrice: 85,
        scheduleH1: false,
        instructions: "Administer slow IV push over 3 minutes",
      },
      {
        medicineId: "MED-008",
        medicineName: "Meropenem 1g IV Infusion",
        dosage: "1g in 100ml NS",
        frequency: "TDS (Every 8 hours)",
        duration: "5 Days",
        quantity: 15,
        unitPrice: 110,
        scheduleH1: true,
        instructions: "Infuse over 60 minutes. Controlled Schedule H1 antibiotic.",
      },
      {
        medicineId: "MED-012",
        medicineName: "Salbutamol Respirator Solution 5mg/ml",
        dosage: "2.5mg (0.5ml) in 3ml Saline",
        frequency: "Q4H Nebulization",
        duration: "3 Days",
        quantity: 1,
        unitPrice: 40,
        scheduleH1: false,
        instructions: "Continuous nebulizer support via oxygen mask",
      },
    ],
  },
  {
    id: "rx_02",
    prescriptionNumber: "RX-2026-8802",
    patientId: "PAT-00102",
    patientName: "Harish Chandra",
    patientAge: 64,
    patientGender: "Male",
    wardBed: "ICU-A Floor 2 — Bed 04",
    doctorId: "DOC-001",
    doctorName: "Dr. Ananya Rao",
    doctorSpecialty: "Chief Interventional Cardiologist",
    source: "IPD",
    priority: "Stat Emergency",
    status: "In Progress",
    prescribedAt: "2026-08-24T11:20:00Z",
    clinicalDiagnosis: "Post-PTCA Anterior STEMI with Dual Antiplatelet Therapy",
    totalAmount: 3250,
    items: [
      {
        medicineId: "MED-002",
        medicineName: "Ticagrelor 90mg Tablets",
        dosage: "90mg Oral",
        frequency: "BD (Twice Daily)",
        duration: "30 Days",
        quantity: 60,
        unitPrice: 38,
        scheduleH1: false,
        instructions: "Take with or without food. Do not skip doses.",
      },
      {
        medicineId: "MED-004",
        medicineName: "Enoxaparin 60mg / 0.6ml Pre-filled Syringe",
        dosage: "60mg SC",
        frequency: "BD (Every 12 hours)",
        duration: "3 Days",
        quantity: 6,
        unitPrice: 160,
        scheduleH1: false,
        instructions: "Subcutaneous injection into anterior abdominal wall",
      },
    ],
  },
  {
    id: "rx_03",
    prescriptionNumber: "RX-2026-8803",
    patientId: "PAT-00441",
    patientName: "Meenakshi Sundaram",
    patientAge: 48,
    patientGender: "Female",
    doctorId: "DOC-006",
    doctorName: "Dr. Tariq Mansoor",
    doctorSpecialty: "Internal Medicine & Diabetology",
    source: "OPD",
    priority: "Routine",
    status: "Ready for Pickup",
    prescribedAt: "2026-08-24T10:30:00Z",
    clinicalDiagnosis: "Type 2 Diabetes Mellitus with Essential Hypertension",
    totalAmount: 1420,
    items: [
      {
        medicineId: "MED-001",
        medicineName: "Metformin 500mg SR Tablets",
        dosage: "500mg Oral",
        frequency: "BD with meals",
        duration: "30 Days",
        quantity: 60,
        unitPrice: 4,
        scheduleH1: false,
        instructions: "Take immediately after breakfast and dinner",
      },
      {
        medicineId: "MED-006",
        medicineName: "Telmisartan 40mg + Amlodipine 5mg",
        dosage: "1 Tab Oral",
        frequency: "OD Morning",
        duration: "30 Days",
        quantity: 30,
        unitPrice: 12,
        scheduleH1: false,
        instructions: "Take at morning after waking",
      },
    ],
  },
  {
    id: "rx_04",
    prescriptionNumber: "RX-2026-8804",
    patientId: "PAT-00331",
    patientName: "Kavita R. Nair",
    patientAge: 36,
    patientGender: "Female",
    wardBed: "Female Surgical Ward — Bed 12",
    doctorId: "DOC-008",
    doctorName: "Dr. Vikram Nair",
    doctorSpecialty: "General & Laparoscopic Surgeon",
    source: "IPD",
    priority: "Routine",
    status: "Dispensed",
    prescribedAt: "2026-08-24T09:15:00Z",
    clinicalDiagnosis: "Post-Operative Day 1 Laparoscopic Cholecystectomy",
    totalAmount: 980,
    items: [
      {
        medicineId: "MED-005",
        medicineName: "Cefuroxime Axetil 500mg Tablets",
        dosage: "500mg Oral",
        frequency: "BD (Every 12 hours)",
        duration: "5 Days",
        quantity: 10,
        unitPrice: 45,
        scheduleH1: true,
        instructions: "Take with food to avoid gastric irritation",
      },
      {
        medicineId: "MED-007",
        medicineName: "Pantoprazole 40mg Injection",
        dosage: "40mg IV",
        frequency: "OD Morning",
        duration: "2 Days",
        quantity: 2,
        unitPrice: 55,
        scheduleH1: false,
        instructions: "Slow IV push over 2 minutes",
      },
    ],
  },
];

// ==========================================
// 2. PHARMACY PROCUREMENT PURCHASE ORDERS
// ==========================================
export const mockPharmacyPurchaseOrders: PharmacyPurchaseOrder[] = [
  {
    id: "po_pharm_01",
    poNumber: "PO-PHARM-2026-081",
    supplierId: "SUP-01",
    supplierName: "Apex Pharma Distributors Ltd",
    supplierContact: "+91 98201 44552 (Mukesh Shah)",
    orderedAt: "2026-08-23T14:30:00Z",
    expectedDelivery: "2026-08-25T11:00:00Z",
    status: "Dispatched",
    totalAmount: 184500,
    items: [
      { medicineId: "MED-008", medicineName: "Meropenem 1g IV Infusion", orderedQuantity: 200, unitCost: 380, totalCost: 76000, batchNumber: "APX-M-991" },
      { medicineId: "MED-004", medicineName: "Enoxaparin 60mg Pre-filled Syringes", orderedQuantity: 300, unitCost: 280, totalCost: 84000, batchNumber: "ENOX-442" },
      { medicineId: "MED-003", medicineName: "Hydrocortisone 100mg Injections", orderedQuantity: 500, unitCost: 49, totalCost: 24500, batchNumber: "HYD-112" },
    ],
  },
  {
    id: "po_pharm_02",
    poNumber: "PO-PHARM-2026-082",
    supplierId: "SUP-02",
    supplierName: "LifeCare Generic & Critical Supplies",
    supplierContact: "+91 94481 22331 (Venkatesh Rao)",
    orderedAt: "2026-08-24T09:00:00Z",
    expectedDelivery: "2026-08-26T16:00:00Z",
    status: "Ordered",
    totalAmount: 92400,
    items: [
      { medicineId: "MED-001", medicineName: "Metformin 500mg SR Tablets", orderedQuantity: 5000, unitCost: 2.2, totalCost: 11000 },
      { medicineId: "MED-002", medicineName: "Ticagrelor 90mg Tablets", orderedQuantity: 1500, unitCost: 24, totalCost: 36000 },
      { medicineId: "MED-006", medicineName: "Telmisartan 40mg + Amlodipine 5mg", orderedQuantity: 4000, unitCost: 6.8, totalCost: 27200 },
      { medicineId: "MED-009", medicineName: "Paracetamol 650mg Tablets", orderedQuantity: 10000, unitCost: 1.82, totalCost: 18200 },
    ],
  },
  {
    id: "po_pharm_03",
    poNumber: "PO-PHARM-2026-079",
    supplierId: "SUP-03",
    supplierName: "SunMed Biologicals & Cold Chain",
    supplierContact: "+91 97654 11200 (Alok Verma)",
    orderedAt: "2026-08-21T10:00:00Z",
    expectedDelivery: "2026-08-23T18:00:00Z",
    status: "Delayed",
    totalAmount: 245000,
    items: [
      { medicineId: "MED-010", medicineName: "Human Albumin 20% 100ml Infusion", orderedQuantity: 80, unitCost: 2400, totalCost: 192000 },
      { medicineId: "MED-011", medicineName: "Rabies Immunoglobulin (Equine) 1000 IU", orderedQuantity: 50, unitCost: 1060, totalCost: 53000 },
    ],
  },
  {
    id: "po_pharm_04",
    poNumber: "PO-PHARM-2026-077",
    supplierId: "SUP-01",
    supplierName: "Apex Pharma Distributors Ltd",
    supplierContact: "+91 98201 44552",
    orderedAt: "2026-08-20T08:00:00Z",
    expectedDelivery: "2026-08-22T14:00:00Z",
    status: "Received",
    totalAmount: 115000,
    receivedAt: "2026-08-22T13:45:00Z",
    receivedBy: "Rekha Joshi (Lead Pharmacist)",
    items: [
      { medicineId: "MED-005", medicineName: "Cefuroxime Axetil 500mg", orderedQuantity: 2000, unitCost: 32, totalCost: 64000, batchNumber: "CEF-2026-X" },
      { medicineId: "MED-007", medicineName: "Pantoprazole 40mg IV", orderedQuantity: 1500, unitCost: 34, totalCost: 51000, batchNumber: "PAN-4401" },
    ],
  },
];

// ==========================================
// 3. LICENSED PHARMACY SUPPLIERS DIRECTORY
// ==========================================
export const mockPharmacySuppliers: PharmacySupplier[] = [
  {
    id: "SUP-01",
    name: "Apex Pharma Distributors Ltd",
    contactPerson: "Mukesh Shah (Director of Sales)",
    phone: "+91 98201 44552",
    email: "orders@apexpharmadist.com",
    address: "Plot 44, GIDC Industrial Estate, Kurla West, Mumbai 400070",
    categoriesSupplied: ["Schedule H1 Antibiotics", "Critical Care Injections", "Cardiovascular Drugs"],
    leadTimeDays: 2,
    reliabilityScore: 99.1,
    activePOCount: 2,
    status: "Active",
  },
  {
    id: "SUP-02",
    name: "LifeCare Generic & Critical Supplies",
    contactPerson: "Venkatesh Rao",
    phone: "+91 94481 22331",
    email: "supply@lifecaregenerics.in",
    address: "108 Metro Tower, Outer Ring Road, Bengaluru 560037",
    categoriesSupplied: ["Oral Generics", "Analgesics & Antipyretics", "Anti-Diabetic Medications"],
    leadTimeDays: 3,
    reliabilityScore: 96.5,
    activePOCount: 1,
    status: "Active",
  },
  {
    id: "SUP-03",
    name: "SunMed Biologicals & Cold Chain",
    contactPerson: "Alok Verma (Cold Chain Operations)",
    phone: "+91 97654 11200",
    email: "logistics@sunmedbio.com",
    address: "Warehouse 8, MIDC Bhosari, Pune 411026",
    categoriesSupplied: ["Blood Products (Albumin)", "Vaccines & Sera", "Insulin Analogs"],
    leadTimeDays: 1,
    reliabilityScore: 98.4,
    activePOCount: 1,
    status: "Active",
  },
  {
    id: "SUP-04",
    name: "Medisurge Chem & Diagnostics",
    contactPerson: "Deepak Sethi",
    phone: "+91 98110 55432",
    email: "sales@medisurgechem.com",
    address: "24 Nehru Place, South Extension, New Delhi 110019",
    categoriesSupplied: ["IV Fluids & Electrolytes", "Surgical Disinfectants", "Anesthesia Gases"],
    leadTimeDays: 4,
    reliabilityScore: 92.0,
    activePOCount: 0,
    status: "Active",
  },
];

// ==========================================
// 4. PHARMACY STAFF & LICENSING REGISTRY
// ==========================================
export const mockPharmacyStaff: PharmacyStaffMember[] = [
  {
    id: "STF-PHARM-01",
    name: "Rekha Joshi",
    role: "Chief Pharmacist",
    shift: "Morning (08:00 - 16:00)",
    dutyStatus: "On Duty",
    pharmacyCouncilRegNo: "PCI-MAH-1994-04412",
    scheduleH1Authorized: true,
    todayDispensedCount: 42,
    contactNumber: "+91 98200 11223",
  },
  {
    id: "STF-PHARM-02",
    name: "Anand Deshpande",
    role: "Clinical Pharmacist",
    shift: "Morning (08:00 - 16:00)",
    dutyStatus: "On Duty",
    pharmacyCouncilRegNo: "PCI-MAH-2008-09182",
    scheduleH1Authorized: true,
    todayDispensedCount: 38,
    contactNumber: "+91 98200 44556",
  },
  {
    id: "STF-PHARM-03",
    name: "Pooja Patil",
    role: "Dispensing Pharmacist",
    shift: "Evening (16:00 - 00:00)",
    dutyStatus: "Off Duty",
    pharmacyCouncilRegNo: "PCI-MAH-2015-18820",
    scheduleH1Authorized: true,
    todayDispensedCount: 0,
    contactNumber: "+91 98200 77889",
  },
  {
    id: "STF-PHARM-04",
    name: "Suresh Gaikwad",
    role: "Dispensing Pharmacist",
    shift: "Night (00:00 - 08:00)",
    dutyStatus: "Off Duty",
    pharmacyCouncilRegNo: "PCI-MAH-2018-24419",
    scheduleH1Authorized: true,
    todayDispensedCount: 0,
    contactNumber: "+91 98200 99001",
  },
  {
    id: "STF-PHARM-05",
    name: "Nikhil Shinde",
    role: "Pharmacy Technician",
    shift: "Morning (08:00 - 16:00)",
    dutyStatus: "On Duty",
    pharmacyCouncilRegNo: "PCI-TECH-2022-00412",
    scheduleH1Authorized: false,
    todayDispensedCount: 29,
    contactNumber: "+91 98200 33445",
  },
];

// ==========================================
// 5. BATCH-LEVEL EXPIRY & FEFO RECORDS
// ==========================================
export const mockPharmacyBatchExpiries: PharmacyBatchExpiry[] = [
  {
    id: "exp_01",
    medicineId: "MED-003",
    medicineName: "Hydrocortisone 100mg Injection",
    category: "Critical Emergency",
    batchNumber: "HYD-2024-B09",
    manufacturer: "Zydus Cadila Healthcare",
    expiryDate: "2026-09-15",
    daysRemaining: 22,
    currentStock: 45,
    unitPrice: 85,
    fefoPriority: "Critical (<30d)",
    quarantineStatus: "Active Stock",
  },
  {
    id: "exp_02",
    medicineId: "MED-010",
    medicineName: "Human Albumin 20% 100ml Infusion",
    category: "Critical Emergency",
    batchNumber: "ALB-2024-88A",
    manufacturer: "Baxter Biopharma",
    expiryDate: "2026-09-20",
    daysRemaining: 27,
    currentStock: 12,
    unitPrice: 2850,
    fefoPriority: "Critical (<30d)",
    quarantineStatus: "Active Stock",
  },
  {
    id: "exp_03",
    medicineId: "MED-008",
    medicineName: "Meropenem 1g IV Infusion",
    category: "Antibiotics",
    batchNumber: "MER-2024-X41",
    manufacturer: "Cipla Pharmaceuticals",
    expiryDate: "2026-10-10",
    daysRemaining: 47,
    currentStock: 80,
    unitPrice: 420,
    fefoPriority: "High (<60d)",
    quarantineStatus: "Active Stock",
  },
  {
    id: "exp_04",
    medicineId: "MED-005",
    medicineName: "Cefuroxime Axetil 500mg Tablets",
    category: "Antibiotics",
    batchNumber: "CEF-2024-550",
    manufacturer: "GlaxoSmithKline (GSK)",
    expiryDate: "2026-10-25",
    daysRemaining: 62,
    currentStock: 210,
    unitPrice: 45,
    fefoPriority: "Moderate (<90d)",
    quarantineStatus: "Active Stock",
  },
];

// ==========================================
// 6. OTC WALK-IN SALES RECORDS
// ==========================================
export const mockPharmacySalesRecords: PharmacySalesRecord[] = [
  {
    id: "sale_01",
    receiptNumber: "OTC-2026-0441",
    customerName: "Sanjay Deshmukh (Walk-in)",
    customerPhone: "+91 98210 99441",
    items: [
      { medicineId: "MED-009", medicineName: "Paracetamol 650mg Tablets", quantity: 20, unitPrice: 3.5, totalPrice: 70 },
      { medicineId: "MED-013", medicineName: "Vitamin C 500mg Chewable", quantity: 30, unitPrice: 4.0, totalPrice: 120 },
      { medicineId: "MED-014", medicineName: "Antacid Liquid Gel 200ml", quantity: 1, unitPrice: 110.0, totalPrice: 110 },
    ],
    subtotal: 300,
    taxAmount: 15,
    discountAmount: 0,
    totalPaid: 315,
    paymentMode: "UPI",
    dispensingPharmacist: "Rekha Joshi",
    timestamp: "2026-08-24T12:10:00Z",
  },
  {
    id: "sale_02",
    receiptNumber: "OTC-2026-0442",
    customerName: "Sunita Verma (Walk-in)",
    customerPhone: "+91 94220 11449",
    items: [
      { medicineId: "MED-015", medicineName: "ORS Electrolyte Sachets (Pack of 5)", quantity: 2, unitPrice: 45.0, totalPrice: 90 },
      { medicineId: "MED-016", medicineName: "Digital Clinical Thermometer", quantity: 1, unitPrice: 220.0, totalPrice: 220 },
    ],
    subtotal: 310,
    taxAmount: 20,
    discountAmount: 10,
    totalPaid: 320,
    paymentMode: "Cash",
    dispensingPharmacist: "Anand Deshpande",
    timestamp: "2026-08-24T11:40:00Z",
  },
];

// ==========================================
// 7. MEDICATION RETURNS & WRITE-OFF RECORDS
// ==========================================
export const mockPharmacyReturnRecords: PharmacyReturnRecord[] = [
  {
    id: "ret_01",
    returnNumber: "RET-2026-0881",
    returnType: "Patient Return",
    medicineId: "MED-004",
    medicineName: "Enoxaparin 60mg Pre-filled Syringe",
    batchNumber: "ENOX-442",
    quantity: 4,
    unitPrice: 160,
    totalRefundAmount: 640,
    reason: "Unused sealed post-op discharge medication returned following early recovery.",
    linkedPrescriptionId: "RX-2026-8799",
    patientName: "Kavita R. Nair (PAT-00331)",
    processedBy: "Rekha Joshi (Chief Pharmacist)",
    timestamp: "2026-08-24T10:15:00Z",
    status: "Restocked & Refunded",
  },
  {
    id: "ret_02",
    returnNumber: "RET-2026-0882",
    returnType: "Supplier Return",
    medicineId: "MED-008",
    medicineName: "Meropenem 1g IV Infusion",
    batchNumber: "MER-DEF-001",
    quantity: 20,
    unitPrice: 380,
    totalRefundAmount: 7600,
    reason: "Vial label seal broken and packaging damaged during courier transit.",
    supplierName: "Apex Pharma Distributors Ltd (SUP-01)",
    processedBy: "Anand Deshpande (Clinical Pharmacist)",
    timestamp: "2026-08-23T15:30:00Z",
    status: "Returned to Vendor",
  },
  {
    id: "ret_03",
    returnNumber: "RET-2026-0883",
    returnType: "Expired / Damaged Write-Off",
    medicineId: "MED-017",
    medicineName: "Ceftriaxone 1g Injection",
    batchNumber: "CEF-2023-EX",
    quantity: 15,
    unitPrice: 65,
    totalRefundAmount: 0,
    reason: "Batch crossed official manufacturer expiry on 15-Aug-2026. Quarantined and incinerated per biomedical waste protocol.",
    processedBy: "Rekha Joshi (Chief Pharmacist)",
    timestamp: "2026-08-22T14:00:00Z",
    status: "Written Off",
  },
];
