import {
  OperationalIncident,
  HospitalHealthScore,
  StaffCoverageCell,
  EmergencyPreArrivalPacket,
  EmergencyCapacitySignal,
} from "@/hospital-admin/lib/types/proposed-features";

export const mockOperationalIncidents: OperationalIncident[] = [
  {
    id: "inc_01",
    code: "INC-2026-0041",
    title: "ICU Central Oxygen Pressure Drop Warning",
    category: "Equipment Failure",
    severity: "P1 - Critical",
    status: "Investigating",
    department: "Critical Care / ICU",
    location: "Building B • 3rd Floor • MICU Bay",
    reporter: "Head Nurse Sarita Varma",
    assignedOwner: "Rajesh Kulkarni (Biomedical Head)",
    createdAt: "2026-08-25T13:45:00Z",
    slaDeadline: "2026-08-25T14:45:00Z",
    isBreached: false,
    description: "Telemetry manifold sensor reporting 3.8 bar instead of nominal 4.2 bar on line B2.",
    impact: "Backup manifold engaged automatically. 12 ventilator patients on secondary supply.",
    auditTrail: [
      {
        timestamp: "2026-08-25T13:45:00Z",
        actor: "Head Nurse Sarita Varma",
        action: "Incident Logged",
        note: "Triggered emergency telemetry alert",
      },
      {
        timestamp: "2026-08-25T13:50:00Z",
        actor: "Rajesh Kulkarni",
        action: "Assigned & In-Progress",
        note: "Biomedical technician dispatched to 3rd floor manifold room",
      },
    ],
  },
  {
    id: "inc_02",
    code: "INC-2026-0042",
    title: "Night Shift Trauma OT Scrub Nurse Shortage",
    category: "Staffing Shortage",
    severity: "P2 - High",
    status: "Mitigating",
    department: "Operation Theatres",
    location: "Main Surgical Complex • OT Suite 4",
    reporter: "OT Manager Priya Nair",
    assignedOwner: "Dr. Sunita Rao (Nursing Superintendent)",
    createdAt: "2026-08-25T12:15:00Z",
    slaDeadline: "2026-08-25T16:15:00Z",
    isBreached: false,
    description: "2 certified cardiothoracic scrub nurses on sudden sick leave ahead of scheduled emergency bypass backup.",
    impact: "Emergency pool standby scrub nurse summons required.",
    auditTrail: [
      {
        timestamp: "2026-08-25T12:15:00Z",
        actor: "OT Manager Priya Nair",
        action: "Incident Logged",
      },
      {
        timestamp: "2026-08-25T12:30:00Z",
        actor: "Dr. Sunita Rao",
        action: "Mitigating Action",
        note: "Called in Nurse Ananya Das from Day Shift On-Call pool",
      },
    ],
  },
  {
    id: "inc_03",
    code: "INC-2026-0039",
    title: "Cardiology OPD Triage Kiosk Network Lag",
    category: "IT / Network Downtime",
    severity: "P3 - Medium",
    status: "Resolved",
    department: "Reception & OPD",
    location: "Ground Floor • OPD Counter 2",
    reporter: "Receptionist Amit Sharma",
    assignedOwner: "Vikram Seth (IT Infrastructure)",
    createdAt: "2026-08-25T09:10:00Z",
    slaDeadline: "2026-08-25T13:10:00Z",
    isBreached: false,
    description: "Slow token generation due to DHCP pool exhaustion on VLAN 4.",
    impact: "Minor 4-minute queue delay during morning rush.",
    resolutionNotes: "Subnet scope expanded and secondary gateway restarted. Latency down to < 20ms.",
    resolvedAt: "2026-08-25T10:05:00Z",
    auditTrail: [
      {
        timestamp: "2026-08-25T09:10:00Z",
        actor: "Amit Sharma",
        action: "Incident Logged",
      },
      {
        timestamp: "2026-08-25T10:05:00Z",
        actor: "Vikram Seth",
        action: "Resolved",
        note: "VLAN 4 gateway flushed and verified",
      },
    ],
  },
  {
    id: "inc_04",
    code: "INC-2026-0038",
    title: "Elevator #3 Patient Transport Stoppage",
    category: "Facility & Utilities",
    severity: "P2 - High",
    status: "Resolved",
    department: "Emergency & Trauma",
    location: "East Wing Shaft • Between 1st & 2nd Floor",
    reporter: "Security Officer R. Yadav",
    assignedOwner: "K. Mohan (Facility Engineering)",
    createdAt: "2026-08-24T18:30:00Z",
    slaDeadline: "2026-08-24T20:30:00Z",
    isBreached: false,
    description: "Door interlock fault triggered safety braking during stretcher transit (no patients trapped).",
    impact: "Stretcher transfers rerouted to Elevator #4 for 45 minutes.",
    resolutionNotes: "Optical sensor cleaned and tested with 500kg load test. Certified operational.",
    resolvedAt: "2026-08-24T19:40:00Z",
    auditTrail: [
      {
        timestamp: "2026-08-24T18:30:00Z",
        actor: "R. Yadav",
        action: "Incident Logged",
      },
      {
        timestamp: "2026-08-24T19:40:00Z",
        actor: "K. Mohan",
        action: "Resolved & Inspected",
      },
    ],
  },
];

export const mockHospitalHealthScore: HospitalHealthScore = {
  overallScore: 91,
  grade: "A",
  status: "Operational Excellence",
  lastCalculatedAt: "2026-08-25T15:10:00Z",
  components: [
    {
      id: "comp_01",
      category: "Emergency & Trauma SLA",
      score: 96,
      weight: 0.25,
      status: "Optimal",
      keyMetric: "3.8m Mean Response",
      details: "100% of SOS alerts acknowledged within 120s threshold; 0 partner diversions today.",
    },
    {
      id: "comp_02",
      category: "Bed & ICU Pressure",
      score: 86,
      weight: 0.20,
      status: "Good",
      keyMetric: "88.4% Occupancy",
      details: "MICU at 100% capacity; 4 step-down beds available in HDU; 6 beds in turnaround.",
    },
    {
      id: "comp_03",
      category: "Workforce & Staffing Coverage",
      score: 92,
      weight: 0.20,
      status: "Optimal",
      keyMetric: "94.2% Shift Fill Rate",
      details: "1 active night shift scrub deficit being mitigated; critical care skills fully staffed.",
    },
    {
      id: "comp_04",
      category: "Surgical & OT Readiness",
      score: 89,
      weight: 0.20,
      status: "Good",
      keyMetric: "91.5% Case Readiness",
      details: "8 of 9 scheduled surgeries at 100% readiness; 1 implant delivery unblocked.",
    },
    {
      id: "comp_05",
      category: "Operational Incident & Safety",
      score: 94,
      weight: 0.15,
      status: "Optimal",
      keyMetric: "0 P1 Outages Breached",
      details: "1 active P1 under biomedical investigation; all historical MTTR under 45 minutes.",
    },
  ],
};

export const mockStaffCoverageHeatmap: StaffCoverageCell[] = [
  { department: "Emergency & Trauma", shift: "Morning (07:00-15:00)", requiredStaff: 12, assignedStaff: 12, criticalSkillCovered: true, status: "Optimal", deficit: 0 },
  { department: "Emergency & Trauma", shift: "Evening (15:00-23:00)", requiredStaff: 10, assignedStaff: 10, criticalSkillCovered: true, status: "Optimal", deficit: 0 },
  { department: "Emergency & Trauma", shift: "Night (23:00-07:00)", requiredStaff: 8, assignedStaff: 7, criticalSkillCovered: true, status: "Minor Deficit", deficit: 1 },
  { department: "Critical Care / ICU", shift: "Morning (07:00-15:00)", requiredStaff: 16, assignedStaff: 16, criticalSkillCovered: true, status: "Optimal", deficit: 0 },
  { department: "Critical Care / ICU", shift: "Evening (15:00-23:00)", requiredStaff: 14, assignedStaff: 14, criticalSkillCovered: true, status: "Optimal", deficit: 0 },
  { department: "Critical Care / ICU", shift: "Night (23:00-07:00)", requiredStaff: 12, assignedStaff: 11, criticalSkillCovered: true, status: "Minor Deficit", deficit: 1 },
  { department: "Operation Theatres", shift: "Morning (07:00-15:00)", requiredStaff: 14, assignedStaff: 14, criticalSkillCovered: true, status: "Optimal", deficit: 0 },
  { department: "Operation Theatres", shift: "Evening (15:00-23:00)", requiredStaff: 8, assignedStaff: 8, criticalSkillCovered: true, status: "Optimal", deficit: 0 },
  { department: "Operation Theatres", shift: "Night (23:00-07:00)", requiredStaff: 6, assignedStaff: 4, criticalSkillCovered: false, status: "Critical Shortage", deficit: 2 },
  { department: "Cardiology Ward", shift: "Morning (07:00-15:00)", requiredStaff: 8, assignedStaff: 8, criticalSkillCovered: true, status: "Optimal", deficit: 0 },
  { department: "Cardiology Ward", shift: "Evening (15:00-23:00)", requiredStaff: 6, assignedStaff: 6, criticalSkillCovered: true, status: "Optimal", deficit: 0 },
  { department: "Cardiology Ward", shift: "Night (23:00-07:00)", requiredStaff: 4, assignedStaff: 4, criticalSkillCovered: true, status: "Optimal", deficit: 0 },
  { department: "General Medical Ward", shift: "Morning (07:00-15:00)", requiredStaff: 10, assignedStaff: 10, criticalSkillCovered: true, status: "Optimal", deficit: 0 },
  { department: "General Medical Ward", shift: "Evening (15:00-23:00)", requiredStaff: 8, assignedStaff: 7, criticalSkillCovered: true, status: "Minor Deficit", deficit: 1 },
  { department: "General Medical Ward", shift: "Night (23:00-07:00)", requiredStaff: 6, assignedStaff: 6, criticalSkillCovered: true, status: "Optimal", deficit: 0 },
];

export const mockEmergencyPreArrivalPacket: EmergencyPreArrivalPacket = {
  caseId: "emg_01",
  patientQlynoId: "QLY-PAT-2024-00841",
  patientName: "Ramesh Sharma",
  age: 58,
  gender: "Male",
  bloodGroup: "O+",
  allergies: ["Penicillin", "NSAIDs"],
  chiefComplaint: "Acute crushing retrosternal chest pain radiating to left shoulder (Onset: 45m ago)",
  etaMinutes: 7,
  vitals: {
    heartRate: 114,
    bp: "168/102 mmHg",
    spo2: 93,
    gcs: 15,
  },
  treatingCardiologist: "Dr. Arvind Swaminathan (Lead Interventional Cardiologist)",
  activeCareCaseId: "CARE-2026-0891 (CAD Post-PTCA)",
  consentVerified: true,
  receivingTraumaBay: "Trauma Resuscitation Bay 01 (Pre-cleared & Monitored)",
  preparedBy: "Paramedic S. Roy • Ambulance ALS-04 Telemetry",
};

export const mockEmergencyCapacitySignal: EmergencyCapacitySignal = {
  facilityId: "hosp_main_01",
  facilityName: "Qlyno Multispecialty Hospital — Main Campus",
  lastPublishedAt: "2026-08-25T15:05:00Z",
  isPublishedToNetwork: true,
  erBedAvailability: 4,
  erBedTotal: 20,
  traumaBayStatus: "Fully Available",
  icuBedsAvailable: 2,
  otEmergencyReadiness: "Immediate (Ready)",
  ambulanceFleetActive: 5,
  bloodSupplyStatus: "Adequate",
};
