import {
  CareCoordinationReportReviewItem,
  PatientNotificationRecord,
  AddendumClarificationRequest,
} from "@/hospital-admin/lib/types";

export const mockCareCoordinationReportsReview: CareCoordinationReportReviewItem[] = [
  // 1. Critical + Overdue Lab Report
  {
    id: "REV-1001",
    reportId: "LAB-REP-8821",
    sourceModule: "lab",
    orderId: "LAB-ORD-9021",
    patientId: "P-1001",
    patientName: "Rahul Sharma",
    patientUhid: "UHID-2026-0811",
    patientPhone: "+91 98220 11009",
    patientAgeGender: "45 / M",
    testOrStudyName: "Cardiac Troponin I (High Sensitivity)",
    modalityOrCategory: "Biochemistry & Cardiac Biomarkers",
    department: "Emergency & Cardiology",
    attendingDoctorId: "DOC-001",
    attendingDoctorName: "Dr. Vikram Seth",
    doctorSpecialty: "Chief Interventional Cardiologist",
    releasedAt: "2026-08-27T10:30:00Z",
    waitingDuration: "2h 45m",
    waitingDurationMinutes: 165,
    isCritical: true,
    criticalDetails: "Troponin I: 4.82 ng/mL (Reference: <0.04 ng/mL). Severe acute myocardial injury.",
    slaDeadlineMinutes: 120, // 2-hour SLA for critical panic values
    isOverdue: true,
    status: "pending_review",
    keyFindings: "Serum hs-cTnI elevated over 120x baseline. CK-MB elevated at 64 U/L.",
    impression: "Laboratory evidence consistent with Acute STEMI / NSTEMI. Immediate clinical correlation and emergent coronary angiogram recommended.",
    referenceRangesOrSummary: "hs-cTnI: 4.82 ng/mL (Ref: 0.00 - 0.04 ng/mL) | CK-MB: 64 U/L (Ref: 0 - 25 U/L)",
    isPatientNotified: false,
  },

  // 2. Critical Radiology Study (Report Ready)
  {
    id: "REV-1002",
    reportId: "RAD-REP-4019",
    sourceModule: "radiology",
    orderId: "RAD-ORD-5102",
    patientId: "P-1002",
    patientName: "Priya Singh",
    patientUhid: "UHID-2026-0824",
    patientPhone: "+91 98450 22341",
    patientAgeGender: "38 / F",
    testOrStudyName: "NCCT Brain (Stroke Protocol)",
    modalityOrCategory: "CT Scan (Computed Tomography)",
    department: "Neurology & Trauma",
    attendingDoctorId: "DOC-002",
    attendingDoctorName: "Dr. Priya Sharma",
    doctorSpecialty: "Senior Neurologist",
    releasedAt: "2026-08-27T12:00:00Z",
    waitingDuration: "1h 15m",
    waitingDurationMinutes: 75,
    isCritical: true,
    criticalDetails: "Acute right middle cerebral artery (MCA) territory hyperdense vessel sign with early ischemic loss of insular ribbon.",
    slaDeadlineMinutes: 120,
    isOverdue: false,
    status: "pending_review",
    keyFindings: "Loss of gray-white differentiation in right insular cortex. No intracranial hemorrhage detected. ASPECTS score: 7.",
    impression: "Acute ischemic stroke in right MCA distribution within thrombolysis window. Emergency IV thrombolysis / endovascular thrombectomy assessment requested.",
    referenceRangesOrSummary: "No midline shift. Ventricles and basal cisterns intact.",
    isPatientNotified: false,
  },

  // 3. Routine Lab Report (Pending)
  {
    id: "REV-1003",
    reportId: "LAB-REP-8835",
    sourceModule: "lab",
    orderId: "LAB-ORD-9044",
    patientId: "P-1003",
    patientName: "Arjun Patel",
    patientUhid: "UHID-2026-0839",
    patientPhone: "+91 97110 33491",
    patientAgeGender: "52 / M",
    testOrStudyName: "Complete Blood Count (CBC) with Differential",
    modalityOrCategory: "Hematology",
    department: "General Medicine",
    attendingDoctorId: "DOC-003",
    attendingDoctorName: "Dr. Rajesh Nair",
    doctorSpecialty: "Internal Medicine Specialist",
    releasedAt: "2026-08-27T11:45:00Z",
    waitingDuration: "1h 30m",
    waitingDurationMinutes: 90,
    isCritical: false,
    slaDeadlineMinutes: 360, // 6-hour routine SLA
    isOverdue: false,
    status: "pending_review",
    keyFindings: "Hemoglobin: 13.8 g/dL, Total WBC: 8,400 /mcL, Platelets: 210,000 /mcL. Absolute neutrophil count normal.",
    impression: "Normal complete hemogram. No evidence of active cytopenia or leukocytosis.",
    referenceRangesOrSummary: "Hb: 13-17 g/dL | WBC: 4,000-11,000 /mcL | Platelets: 150,000-450,000 /mcL",
    isPatientNotified: false,
  },

  // 4. Routine Radiology Study (Overdue Routine)
  {
    id: "REV-1004",
    reportId: "RAD-REP-4033",
    sourceModule: "radiology",
    orderId: "RAD-ORD-5120",
    patientId: "P-1004",
    patientName: "Neha Verma",
    patientUhid: "UHID-2026-0850",
    patientPhone: "+91 99200 44582",
    patientAgeGender: "29 / F",
    testOrStudyName: "MRI Lumbar Spine with Whole Spine Screening",
    modalityOrCategory: "Magnetic Resonance Imaging (MRI)",
    department: "Orthopedics & Spine",
    attendingDoctorId: "DOC-004",
    attendingDoctorName: "Dr. Arvind Joshi",
    doctorSpecialty: "Senior Orthopedic Surgeon",
    releasedAt: "2026-08-27T06:00:00Z",
    waitingDuration: "7h 15m",
    waitingDurationMinutes: 435,
    isCritical: false,
    slaDeadlineMinutes: 360,
    isOverdue: true,
    status: "pending_review",
    keyFindings: "L4-L5 posterior disc extrusion causing moderate thecal sac compression and bilateral L5 traversing nerve root impingement.",
    impression: "Lumbar disc herniation at L4-L5 level with neural compromise. Correlation with radiculopathy symptoms recommended.",
    referenceRangesOrSummary: "Vertebral alignment preserved. No marrow edema or destructive osseous lesions.",
    isPatientNotified: false,
  },

  // 5. Critical Radiology Study (Pending)
  {
    id: "REV-1005",
    reportId: "RAD-REP-4045",
    sourceModule: "radiology",
    orderId: "RAD-ORD-5135",
    patientId: "P-1005",
    patientName: "Kavita Rao",
    patientUhid: "UHID-2026-0865",
    patientPhone: "+91 98330 55673",
    patientAgeGender: "64 / F",
    testOrStudyName: "Chest X-Ray (AP Erect Bedside)",
    modalityOrCategory: "Digital Radiography (X-Ray)",
    department: "Pulmonology & ICU",
    attendingDoctorId: "DOC-005",
    attendingDoctorName: "Dr. Ananya Sen",
    doctorSpecialty: "Pulmonologist & Critical Care",
    releasedAt: "2026-08-27T12:15:00Z",
    waitingDuration: "1h 00m",
    waitingDurationMinutes: 60,
    isCritical: true,
    criticalDetails: "Right-sided tension pneumothorax with significant mediastinal shift to the left.",
    slaDeadlineMinutes: 120,
    isOverdue: false,
    status: "pending_review",
    keyFindings: "Complete collapse of right lung with hyperlucent pleural space. Leftward displacement of cardiac silhouette and trachea.",
    impression: "Life-threatening right tension pneumothorax. Emergency intercostal chest tube insertion indicated immediately.",
    referenceRangesOrSummary: "Left lung fields clear. No bony fractures visualized.",
    isPatientNotified: false,
  },

  // 6. Routine Lab Report (Clarification Requested)
  {
    id: "REV-1006",
    reportId: "LAB-REP-8850",
    sourceModule: "lab",
    orderId: "LAB-ORD-9070",
    patientId: "P-1006",
    patientName: "Sanjay Kulkarni",
    patientUhid: "UHID-2026-0872",
    patientPhone: "+91 97650 66784",
    patientAgeGender: "58 / M",
    testOrStudyName: "Liver Function Test (LFT) & Coagulation Profile",
    modalityOrCategory: "Clinical Biochemistry",
    department: "Gastroenterology",
    attendingDoctorId: "DOC-003",
    attendingDoctorName: "Dr. Rajesh Nair",
    doctorSpecialty: "Internal Medicine Specialist",
    releasedAt: "2026-08-27T08:30:00Z",
    waitingDuration: "4h 45m",
    waitingDurationMinutes: 285,
    isCritical: false,
    slaDeadlineMinutes: 360,
    isOverdue: false,
    status: "clarification_requested",
    keyFindings: "Bilirubin: 3.4 mg/dL, ALT/SGPT: 180 U/L, AST/SGOT: 145 U/L. Serum sample reported mildly hemolyzed.",
    impression: "Elevated transaminases with hyperbilirubinemia. Attending requested re-draw due to in-vitro hemolysis artifact.",
    referenceRangesOrSummary: "Total Bilirubin: 0.2 - 1.2 mg/dL | SGPT: 7 - 56 U/L | SGOT: 10 - 40 U/L",
    isPatientNotified: false,
    clarificationRequestId: "CLAR-901",
  },

  // 7. Reviewed Lab Report (Signed Off & Patient Notified)
  {
    id: "REV-1007",
    reportId: "LAB-REP-8790",
    sourceModule: "lab",
    orderId: "LAB-ORD-8990",
    patientId: "P-1007",
    patientName: "Sunita Desai",
    patientUhid: "UHID-2026-0801",
    patientPhone: "+91 98190 77895",
    patientAgeGender: "42 / F",
    testOrStudyName: "HbA1c & Fasting Lipid Panel",
    modalityOrCategory: "Endocrinology",
    department: "Endocrinology",
    attendingDoctorId: "DOC-001",
    attendingDoctorName: "Dr. Vikram Seth",
    doctorSpecialty: "Chief Interventional Cardiologist",
    releasedAt: "2026-08-26T14:00:00Z",
    waitingDuration: "0m",
    waitingDurationMinutes: 0,
    isCritical: false,
    slaDeadlineMinutes: 360,
    isOverdue: false,
    status: "reviewed",
    keyFindings: "HbA1c: 6.8% (Fair Glycemic Control). Total Cholesterol: 192 mg/dL, LDL: 110 mg/dL, HDL: 48 mg/dL, Triglycerides: 165 mg/dL.",
    impression: "Adequate glycemic control on current oral hypoglycemic therapy. Mild hypertriglyceridemia.",
    referenceRangesOrSummary: "HbA1c: <5.7% Normal | Total Chol: <200 mg/dL | LDL: <100 mg/dL",
    signedOffAt: "2026-08-26T16:30:00Z",
    signedOffBy: "Dr. Vikram Seth",
    signedOffDoctorRegNo: "MCI-48201-MH",
    signOffNote: "Glycemic parameters stable. Continue Metformin 500mg BD. Re-check in 3 months.",
    auditStamp: "AUTH-SIG-VS-20260826-1630-SHA256-8F2B1C",
    isPatientNotified: true,
    patientNotificationId: "NOTIF-REC-001",
  },

  // 8. Reviewed Radiology Report (Signed Off — Awaiting Patient Notification)
  {
    id: "REV-1008",
    reportId: "RAD-REP-3990",
    sourceModule: "radiology",
    orderId: "RAD-ORD-5050",
    patientId: "P-1008",
    patientName: "Manish Gupta",
    patientUhid: "UHID-2026-0795",
    patientPhone: "+91 98200 88906",
    patientAgeGender: "50 / M",
    testOrStudyName: "Ultrasound Whole Abdomen & Pelvis",
    modalityOrCategory: "Ultrasound Sonography (USG)",
    department: "Gastroenterology",
    attendingDoctorId: "DOC-004",
    attendingDoctorName: "Dr. Arvind Joshi",
    doctorSpecialty: "Senior Orthopedic Surgeon",
    releasedAt: "2026-08-26T15:30:00Z",
    waitingDuration: "0m",
    waitingDurationMinutes: 0,
    isCritical: false,
    slaDeadlineMinutes: 360,
    isOverdue: false,
    status: "reviewed",
    keyFindings: "Grade 1 hepatic steatosis. Normal gallbladder without calculi. Kidneys, pancreas, and spleen unremarkable.",
    impression: "Mild fatty liver changes without focal hepatic lesions. No cholelithiasis or hydronephrosis.",
    referenceRangesOrSummary: "Liver span: 14.2 cm. CBD diameter: 4.1 mm (Normal).",
    signedOffAt: "2026-08-26T17:15:00Z",
    signedOffBy: "Dr. Arvind Joshi",
    signedOffDoctorRegNo: "MCI-39102-MH",
    signOffNote: "Pre-operative ultrasound clear. No abdominal contraindication for scheduled elective surgery.",
    auditStamp: "AUTH-SIG-AJ-20260826-1715-SHA256-3E4F9A",
    isPatientNotified: false, // Signed off but patient NOT yet notified (Rule F22-CAN-14)
  },

  // 9. Reviewed Critical Lab (Pre-Op Clear — Satisfies OT Guard)
  {
    id: "REV-1009",
    reportId: "LAB-REP-8805",
    sourceModule: "lab",
    orderId: "LAB-ORD-9005",
    patientId: "P-1009",
    patientName: "Deepak Choudhury",
    patientUhid: "UHID-2026-0780",
    patientPhone: "+91 98770 99017",
    patientAgeGender: "61 / M",
    testOrStudyName: "Pre-Operative Viral Serology & Blood Crossmatch",
    modalityOrCategory: "Transfusion Medicine & Serology",
    department: "General Surgery & OT",
    attendingDoctorId: "DOC-004",
    attendingDoctorName: "Dr. Arvind Joshi",
    doctorSpecialty: "Senior Orthopedic Surgeon",
    releasedAt: "2026-08-26T09:00:00Z",
    waitingDuration: "0m",
    waitingDurationMinutes: 0,
    isCritical: false,
    slaDeadlineMinutes: 180,
    isOverdue: false,
    status: "reviewed",
    keyFindings: "HIV I/II, HBsAg, HCV non-reactive. Blood Group: B Positive. 2 PRBC units crossmatched and reserved.",
    impression: "Pre-op viral serology negative. Compatible blood reserved. Cleared for elective surgical intervention.",
    referenceRangesOrSummary: "Non-Reactive on 4th Gen CMIA. Crossmatch: Compatible at 37°C AHG.",
    signedOffAt: "2026-08-26T10:45:00Z",
    signedOffBy: "Dr. Arvind Joshi",
    signedOffDoctorRegNo: "MCI-39102-MH",
    signOffNote: "Pre-op serology and blood bank clearance confirmed. OT scheduling unblocked.",
    auditStamp: "AUTH-SIG-AJ-20260826-1045-SHA256-7A1C2D",
    isPatientNotified: true,
    patientNotificationId: "NOTIF-REC-002",
  },
];

export const mockPatientNotificationRecords: PatientNotificationRecord[] = [
  {
    id: "NOTIF-REC-001",
    reviewItemId: "REV-1007",
    reportId: "LAB-REP-8790",
    patientId: "P-1007",
    patientName: "Sunita Desai",
    patientPhone: "+91 98190 77895",
    testName: "HbA1c & Fasting Lipid Panel",
    channel: "whatsapp",
    notifiedBy: "Sister Mary Varghese",
    notifiedByRole: "Care Coordinator / OPD Nurse",
    notifiedAt: "2026-08-26T17:00:00Z",
    notes: "WhatsApp digital diagnostic PDF summary dispatched with doctor review notes.",
    deliveryStatus: "Delivered",
  },
  {
    id: "NOTIF-REC-002",
    reviewItemId: "REV-1009",
    reportId: "LAB-REP-8805",
    patientId: "P-1009",
    patientName: "Deepak Choudhury",
    patientPhone: "+91 98770 99017",
    testName: "Pre-Operative Viral Serology & Blood Crossmatch",
    channel: "phone_call",
    notifiedBy: "Rajesh Shinde",
    notifiedByRole: "OT Scheduling Coordinator",
    notifiedAt: "2026-08-26T11:15:00Z",
    notes: "Telephonic briefing confirmed pre-op clearance and confirmed fasting instructions for tomorrow morning.",
    deliveryStatus: "Delivered",
  },
];

export const mockAddendumClarificationRequests: AddendumClarificationRequest[] = [
  {
    id: "CLAR-901",
    reviewItemId: "REV-1006",
    reportId: "LAB-REP-8850",
    sourceModule: "lab",
    patientName: "Sanjay Kulkarni",
    testOrStudyName: "Liver Function Test (LFT) & Coagulation Profile",
    requestedBy: "Dr. Rajesh Nair (MCI-29401-MH)",
    requestedAt: "2026-08-27T09:15:00Z",
    requestType: "re-test",
    clinicalReason: "Sample reported with mild in-vitro hemolysis. Need fresh non-hemolyzed serum redraw for accurate ALT/AST quantification.",
    status: "sent_to_lab",
    responseSummary: "Lab phlebotomy dispatch ticket #PB-4401 generated. Ward nurse notified for repeat blood collection.",
  },
];
