import {
  RBACRole,
  SecuritySession,
  MFAPolicy,
  BreakGlassSession,
  AuditLogDetailedEntry,
  DocumentSecurityPolicy,
  PrivacyConsentRecord,
  ConfigBackupSnapshot,
} from "@/hospital-admin/lib/types";

// ==========================================
// 1. 6-DIMENSIONAL RBAC ROLES MATRIX
// ==========================================
export const mockRBACRoles: RBACRole[] = [
  {
    id: "role_admin",
    name: "Hospital Administrator",
    description: "Full operational and organizational governance with mandatory audit logging.",
    userCount: 3,
    system: true,
    branchScope: "All Hospital Branches (Global)",
    departmentScope: "All Clinical & Administrative Departments",
    mfaEnforced: true,
    permissions: [
      { module: "Dashboard & Analytics", view: true, create: true, edit: true, delete: false, approve: true, export: true, emergencyOverride: false, dataScope: "Organization Wide" },
      { module: "Patient Records & EMR", view: true, create: true, edit: true, delete: false, approve: true, export: true, emergencyOverride: true, dataScope: "Organization Wide" },
      { module: "Clinical & OT Operations", view: true, create: true, edit: true, delete: false, approve: true, export: true, emergencyOverride: true, dataScope: "Organization Wide" },
      { module: "Pharmacy & Formulary", view: true, create: true, edit: true, delete: false, approve: true, export: true, emergencyOverride: false, dataScope: "Organization Wide" },
      { module: "Radiology & PACS Viewer", view: true, create: true, edit: true, delete: false, approve: true, export: true, emergencyOverride: false, dataScope: "Organization Wide" },
      { module: "Billing & Finance", view: true, create: true, edit: true, delete: false, approve: true, export: true, emergencyOverride: true, dataScope: "Organization Wide" },
      { module: "Roles & Security Controls", view: true, create: true, edit: true, delete: true, approve: true, export: true, emergencyOverride: true, dataScope: "Organization Wide" },
    ],
  },
  {
    id: "role_cmo",
    name: "Chief Medical Officer (CMO)",
    description: "Clinical lead with high-privilege emergency override and clinical credential verification.",
    userCount: 2,
    system: true,
    branchScope: "Main Campus & West Wing",
    departmentScope: "Clinical, Emergency, ICU, OT",
    mfaEnforced: true,
    permissions: [
      { module: "Dashboard & Analytics", view: true, create: false, edit: false, delete: false, approve: true, export: true, emergencyOverride: false, dataScope: "Organization Wide" },
      { module: "Patient Records & EMR", view: true, create: true, edit: true, delete: false, approve: true, export: true, emergencyOverride: true, dataScope: "Organization Wide" },
      { module: "Clinical & OT Operations", view: true, create: true, edit: true, delete: false, approve: true, export: true, emergencyOverride: true, dataScope: "Organization Wide" },
      { module: "Pharmacy & Formulary", view: true, create: true, edit: true, delete: false, approve: true, export: false, emergencyOverride: true, dataScope: "Department Wide" },
      { module: "Radiology & PACS Viewer", view: true, create: true, edit: true, delete: false, approve: true, export: true, emergencyOverride: true, dataScope: "Organization Wide" },
      { module: "Billing & Finance", view: true, create: false, edit: false, delete: false, approve: false, export: false, emergencyOverride: false, dataScope: "Department Wide" },
      { module: "Roles & Security Controls", view: true, create: false, edit: false, delete: false, approve: true, export: false, emergencyOverride: true, dataScope: "Organization Wide" },
    ],
  },
  {
    id: "role_doctor",
    name: "Consultant / Attending Doctor",
    description: "Patient diagnosis, clinical order entry, prescription dispensing authorizations.",
    userCount: 28,
    system: true,
    branchScope: "Assigned Practice Location",
    departmentScope: "Assigned Specialty Department",
    mfaEnforced: true,
    permissions: [
      { module: "Dashboard & Analytics", view: true, create: false, edit: false, delete: false, approve: false, export: false, emergencyOverride: false, dataScope: "Department Wide" },
      { module: "Patient Records & EMR", view: true, create: true, edit: true, delete: false, approve: true, export: false, emergencyOverride: false, dataScope: "Department Wide" },
      { module: "Clinical & OT Operations", view: true, create: true, edit: true, delete: false, approve: true, export: false, emergencyOverride: false, dataScope: "Self Only" },
      { module: "Pharmacy & Formulary", view: true, create: true, edit: false, delete: false, approve: false, export: false, emergencyOverride: false, dataScope: "Department Wide" },
      { module: "Radiology & PACS Viewer", view: true, create: true, edit: true, delete: false, approve: true, export: false, emergencyOverride: false, dataScope: "Department Wide" },
      { module: "Billing & Finance", view: false, create: false, edit: false, delete: false, approve: false, export: false, emergencyOverride: false, dataScope: "Self Only" },
      { module: "Roles & Security Controls", view: false, create: false, edit: false, delete: false, approve: false, export: false, emergencyOverride: false, dataScope: "Self Only" },
    ],
  },
  {
    id: "role_nurse_lead",
    name: "Ward Incharge Nurse",
    description: "Inpatient vitals, medication administration logs, bed transfers, and nursing station duty.",
    userCount: 16,
    system: true,
    branchScope: "Main Campus Ward Wings",
    departmentScope: "Nursing Stations & Inpatient Units",
    mfaEnforced: false,
    permissions: [
      { module: "Dashboard & Analytics", view: true, create: false, edit: false, delete: false, approve: false, export: false, emergencyOverride: false, dataScope: "Department Wide" },
      { module: "Patient Records & EMR", view: true, create: true, edit: true, delete: false, approve: false, export: false, emergencyOverride: false, dataScope: "Department Wide" },
      { module: "Clinical & OT Operations", view: true, create: false, edit: false, delete: false, approve: false, export: false, emergencyOverride: false, dataScope: "Department Wide" },
      { module: "Pharmacy & Formulary", view: true, create: true, edit: false, delete: false, approve: false, export: false, emergencyOverride: false, dataScope: "Department Wide" },
      { module: "Radiology & PACS Viewer", view: true, create: false, edit: false, delete: false, approve: false, export: false, emergencyOverride: false, dataScope: "Department Wide" },
      { module: "Billing & Finance", view: false, create: false, edit: false, delete: false, approve: false, export: false, emergencyOverride: false, dataScope: "Self Only" },
      { module: "Roles & Security Controls", view: false, create: false, edit: false, delete: false, approve: false, export: false, emergencyOverride: false, dataScope: "Self Only" },
    ],
  },
  {
    id: "role_pharmacist",
    name: "Lead Hospital Pharmacist",
    description: "Schedule H1 drug dispensing, stock inventory batch management, and pharmacy POS receipts.",
    userCount: 6,
    system: true,
    branchScope: "Central Pharmacy & OPD Dispensary",
    departmentScope: "Pharmacy & Medical Supplies",
    mfaEnforced: true,
    permissions: [
      { module: "Dashboard & Analytics", view: true, create: false, edit: false, delete: false, approve: false, export: false, emergencyOverride: false, dataScope: "Department Wide" },
      { module: "Patient Records & EMR", view: true, create: false, edit: false, delete: false, approve: false, export: false, emergencyOverride: false, dataScope: "Restricted Clinical" },
      { module: "Clinical & OT Operations", view: false, create: false, edit: false, delete: false, approve: false, export: false, emergencyOverride: false, dataScope: "Self Only" },
      { module: "Pharmacy & Formulary", view: true, create: true, edit: true, delete: false, approve: true, export: true, emergencyOverride: false, dataScope: "Department Wide" },
      { module: "Radiology & PACS Viewer", view: false, create: false, edit: false, delete: false, approve: false, export: false, emergencyOverride: false, dataScope: "Self Only" },
      { module: "Billing & Finance", view: true, create: true, edit: false, delete: false, approve: false, export: true, emergencyOverride: false, dataScope: "Department Wide" },
      { module: "Roles & Security Controls", view: false, create: false, edit: false, delete: false, approve: false, export: false, emergencyOverride: false, dataScope: "Self Only" },
    ],
  },
  {
    id: "role_billing_super",
    name: "Central Billing Cashier & TPA Manager",
    description: "Invoice generation, insurance pre-auth, discounts, refunds, and daily collection reconciliations.",
    userCount: 8,
    system: true,
    branchScope: "Main Campus Billing Counters",
    departmentScope: "Finance & Accounts",
    mfaEnforced: true,
    permissions: [
      { module: "Dashboard & Analytics", view: true, create: false, edit: false, delete: false, approve: false, export: true, emergencyOverride: false, dataScope: "Organization Wide" },
      { module: "Patient Records & EMR", view: true, create: false, edit: false, delete: false, approve: false, export: false, emergencyOverride: false, dataScope: "Restricted Clinical" },
      { module: "Clinical & OT Operations", view: false, create: false, edit: false, delete: false, approve: false, export: false, emergencyOverride: false, dataScope: "Self Only" },
      { module: "Pharmacy & Formulary", view: true, create: false, edit: false, delete: false, approve: false, export: false, emergencyOverride: false, dataScope: "Department Wide" },
      { module: "Radiology & PACS Viewer", view: false, create: false, edit: false, delete: false, approve: false, export: false, emergencyOverride: false, dataScope: "Self Only" },
      { module: "Billing & Finance", view: true, create: true, edit: true, delete: false, approve: true, export: true, emergencyOverride: false, dataScope: "Organization Wide" },
      { module: "Roles & Security Controls", view: false, create: false, edit: false, delete: false, approve: false, export: false, emergencyOverride: false, dataScope: "Self Only" },
    ],
  },
];

// ==========================================
// 2. ACTIVE SECURITY SESSIONS & SUSPICIOUS LOGINS
// ==========================================
export const mockSecuritySessions: SecuritySession[] = [
  {
    id: "sess_01",
    userId: "USR-ADM-01",
    userName: "Akash Sharma (Hospital Admin)",
    userRole: "Hospital Administrator",
    device: "Dell Precision Workstation (Windows 11)",
    browser: "Chrome 128.0 (Encrypted Workspace)",
    ipAddress: "192.168.10.45",
    location: "Admin Block — Floor 4, Main Campus",
    lastActive: "Just now",
    status: "Active",
  },
  {
    id: "sess_02",
    userId: "USR-DOC-01",
    userName: "Dr. Ananya Rao",
    userRole: "Consultant / Attending Doctor",
    device: "iPad Pro 12.9 (iOS 17.5)",
    browser: "Safari Mobile (Hospital MDM)",
    ipAddress: "10.0.4.112",
    location: "Cath Lab Suite 2, West Wing",
    lastActive: "4 mins ago",
    status: "Active",
  },
  {
    id: "sess_03",
    userId: "USR-NUR-04",
    userName: "Pooja Varma (Sister-in-Charge)",
    userRole: "Ward Incharge Nurse",
    device: "COW Terminal #04 (Windows 10 Enterprise)",
    browser: "Edge 126.0",
    ipAddress: "10.0.12.88",
    location: "MICU Station B, Floor 2",
    lastActive: "18 mins ago",
    status: "Idle",
  },
  {
    id: "sess_04",
    userId: "USR-PHARM-02",
    userName: "Rekha Joshi",
    userRole: "Lead Hospital Pharmacist",
    device: "HP TouchPOS Counter #1",
    browser: "Chrome Kiosk Mode",
    ipAddress: "192.168.20.15",
    location: "Central Inpatient Pharmacy",
    lastActive: "2 mins ago",
    status: "Active",
  },
  {
    id: "sess_05",
    userId: "USR-BIL-03",
    userName: "Sanjay Deshmukh",
    userRole: "Central Billing Cashier",
    device: "Lenovo ThinkCentre",
    browser: "Firefox ESR 115",
    ipAddress: "192.168.30.22",
    location: "OPD Billing Counter 3",
    lastActive: "35 mins ago",
    status: "Idle",
  },
  {
    id: "sess_06",
    userId: "USR-RAD-01",
    userName: "Dr. Vikram Seth",
    userRole: "Consultant Radiologist",
    device: "Barco Coronis GSDF Diagnostic Workstation",
    browser: "Chrome 128.0 (High-Bitdepth)",
    ipAddress: "10.0.18.99",
    location: "Radiology Reading Room A",
    lastActive: "12 mins ago",
    status: "Active",
  },
  {
    id: "sess_07",
    userId: "USR-DOC-06",
    userName: "Dr. Tariq Mansoor",
    userRole: "Consultant / Attending Doctor",
    device: "MacBook Air M2 (macOS 14.5)",
    browser: "Chrome 128.0",
    ipAddress: "103.24.88.192",
    location: "Remote VPN — Bandra West",
    lastActive: "58 mins ago",
    status: "Idle",
  },
  // Suspicious Logins
  {
    id: "sess_susp_01",
    userId: "USR-ADM-02",
    userName: "Neha Trivedi (Assistant Admin)",
    userRole: "Hospital Administrator",
    device: "Unknown Linux Device (Ubuntu 22.04)",
    browser: "Headless Chromium",
    ipAddress: "185.220.101.4",
    location: "Tor Exit Node (Frankfurt, Germany)",
    lastActive: "6 mins ago",
    status: "Active",
    isSuspicious: true,
    suspiciousReason: "Impossible Travel Anomaly: Login from Frankfurt 12 mins after local Mumbai LAN session.",
  },
  {
    id: "sess_susp_02",
    userId: "USR-BIL-09",
    userName: "Vikram Pawar (Billing Trainee)",
    userRole: "Central Billing Cashier",
    device: "Android 13 Chrome Mobile",
    browser: "Chrome 127.0",
    ipAddress: "45.118.63.12",
    location: "Unverified Public IP (Kolkata)",
    lastActive: "22 mins ago",
    status: "Active",
    isSuspicious: true,
    suspiciousReason: "4 consecutive failed MFA passcode attempts followed by unusual export request.",
  },
];

// ==========================================
// 3. ROLE-BASED MFA POLICIES
// ==========================================
export const mockMFAPolicies: MFAPolicy[] = [
  {
    roleId: "role_admin",
    roleName: "Hospital Administrator",
    status: "Enforced",
    allowedMethods: ["TOTP Authenticator", "FIDO2 Security Key"],
    complianceRate: 100,
    enforcedUserCount: 3,
  },
  {
    roleId: "role_cmo",
    roleName: "Chief Medical Officer (CMO)",
    status: "Enforced",
    allowedMethods: ["TOTP Authenticator", "FIDO2 Security Key"],
    complianceRate: 100,
    enforcedUserCount: 2,
  },
  {
    roleId: "role_doctor",
    roleName: "Consultant / Attending Doctor",
    status: "Enforced",
    allowedMethods: ["TOTP Authenticator", "FIDO2 Security Key", "SMS OTP"],
    complianceRate: 92.8,
    enforcedUserCount: 28,
  },
  {
    roleId: "role_pharmacist",
    roleName: "Lead Hospital Pharmacist",
    status: "Enforced",
    allowedMethods: ["TOTP Authenticator", "SMS OTP"],
    complianceRate: 100,
    enforcedUserCount: 6,
  },
  {
    roleId: "role_billing_super",
    roleName: "Central Billing Cashier & TPA Manager",
    status: "Enforced",
    allowedMethods: ["TOTP Authenticator", "SMS OTP"],
    complianceRate: 87.5,
    enforcedUserCount: 8,
  },
  {
    roleId: "role_nurse_lead",
    roleName: "Ward Incharge Nurse",
    status: "Grace Period",
    allowedMethods: ["TOTP Authenticator", "SMS OTP"],
    graceDaysRemaining: 9,
    complianceRate: 68.7,
    enforcedUserCount: 16,
  },
  {
    roleId: "role_receptionist",
    roleName: "Front Desk Receptionist",
    status: "Optional",
    allowedMethods: ["SMS OTP"],
    complianceRate: 41.2,
    enforcedUserCount: 12,
  },
];

// ==========================================
// 4. BREAK-GLASS EMERGENCY ACCESS SESSIONS
// ==========================================
export const mockBreakGlassSessions: BreakGlassSession[] = [
  {
    id: "bg_01",
    tokenNo: "BG-2026-8801",
    requesterId: "doc_004",
    requesterName: "Dr. Arvind Swaminathan",
    requesterRole: "Pulmonologist & Critical Care Attending",
    targetPatientId: "PAT-00918",
    targetPatientName: "Rameshwar Patil (Trauma Red Bay)",
    resourceScope: "Full Unrestricted EMR Chart & Prior Cardiac Angiogram PACS",
    reason: "Massive acute hemothorax following road traffic collision. Immediate emergency thoracotomy required without prior TPA consent delay.",
    grantedAt: "2026-08-24T12:30:00Z",
    expiresAt: "2026-08-24T16:30:00Z",
    durationMinutes: 240,
    status: "Active",
  },
  {
    id: "bg_02",
    tokenNo: "BG-2026-8802",
    requesterId: "doc_008",
    requesterName: "Dr. Vikram Nair",
    requesterRole: "Neurosurgeon On-Call",
    targetPatientId: "PAT-00441",
    targetPatientName: "Meenakshi Sundaram",
    resourceScope: "Pre-Op Anesthesia & Prior Medication Chart",
    reason: "Stat emergent craniotomy for acute extradural hematoma with uncal herniation.",
    grantedAt: "2026-08-24T08:00:00Z",
    expiresAt: "2026-08-24T12:00:00Z",
    durationMinutes: 240,
    status: "Expired",
  },
  {
    id: "bg_03",
    tokenNo: "BG-2026-8803",
    requesterId: "doc_001",
    requesterName: "Dr. Ananya Rao",
    requesterRole: "Cardiologist",
    targetPatientId: "PAT-00102",
    targetPatientName: "Harish Chandra",
    resourceScope: "Full Diagnostic History & Genetic Labs",
    reason: "Suspected cardiogenic shock refractory to inotropes. Cross-branch lab history unmasking.",
    grantedAt: "2026-08-23T14:00:00Z",
    expiresAt: "2026-08-23T18:00:00Z",
    durationMinutes: 240,
    status: "Revoked",
    revokedAt: "2026-08-23T16:15:00Z",
    revokedBy: "Akash Sharma (Hospital Admin)",
  },
];

// ==========================================
// 5. DETAILED AUDIT LOG WITH BEFORE/AFTER STATE DIFFS
// ==========================================
export const mockDetailedAuditLogs: AuditLogDetailedEntry[] = [
  {
    id: "aud_01",
    actor: "Akash Sharma",
    actorRole: "Hospital Admin",
    action: "Modified Role Permissions (RBAC)",
    module: "Roles & Security Controls",
    entity: "Role Definition",
    entityId: "role_pharmacist",
    timestamp: "2026-08-24T11:45:00Z",
    ipAddress: "192.168.10.45",
    status: "step-up-verified",
    severity: "High",
    reason: "Authorized pharmacy department lead to export controlled Schedule H1 batch reconciliation CSV reports per state auditor mandate.",
    beforeState: {
      role: "Lead Hospital Pharmacist",
      module: "Pharmacy & Formulary",
      exportPermission: false,
      dataScope: "Department Wide",
    },
    afterState: {
      role: "Lead Hospital Pharmacist",
      module: "Pharmacy & Formulary",
      exportPermission: true,
      dataScope: "Department Wide",
      stepUpVerifiedBy: "Akash Sharma",
    },
  },
  {
    id: "aud_02",
    actor: "Dr. Arvind Swaminathan",
    actorRole: "Critical Care Attending",
    action: "Emergency Break-Glass Access Granted",
    module: "Emergency & Clinical Operations",
    entity: "Patient EMR Record",
    entityId: "PAT-00918",
    timestamp: "2026-08-24T12:30:00Z",
    ipAddress: "10.0.4.112",
    status: "step-up-verified",
    severity: "Critical",
    reason: "Massive acute hemothorax following road traffic collision. Immediate emergency thoracotomy required without prior TPA consent delay.",
    beforeState: {
      patientId: "PAT-00918",
      accessRestriction: "TPA Consent Gate Active",
      visibility: "Restricted",
    },
    afterState: {
      patientId: "PAT-00918",
      breakGlassToken: "BG-2026-8801",
      duration: "4 Hours",
      visibility: "Full Unrestricted EMR Chart",
      expiresAt: "2026-08-24T16:30:00Z",
    },
  },
  {
    id: "aud_03",
    actor: "Akash Sharma",
    actorRole: "Hospital Admin",
    action: "Revoked Suspicious Session",
    module: "Session Management",
    entity: "Security Session",
    entityId: "sess_susp_01",
    timestamp: "2026-08-24T13:10:00Z",
    ipAddress: "192.168.10.45",
    status: "success",
    severity: "Critical",
    reason: "Impossible travel anomaly detected from Tor exit node IP 185.220.101.4.",
    beforeState: {
      sessionId: "sess_susp_01",
      user: "Neha Trivedi",
      status: "Active",
      ip: "185.220.101.4",
    },
    afterState: {
      sessionId: "sess_susp_01",
      status: "Revoked",
      tokenInvalidated: true,
      revocationTimestamp: "2026-08-24T13:10:00Z",
    },
  },
  {
    id: "aud_04",
    actor: "Sanjay Deshmukh",
    actorRole: "Central Billing Cashier",
    action: "Approved Emergency High-Value Refund",
    module: "Billing & Finance",
    entity: "Invoice Settlement",
    entityId: "INV-2026-08891",
    timestamp: "2026-08-24T10:15:00Z",
    ipAddress: "192.168.30.22",
    status: "step-up-verified",
    severity: "High",
    reason: "Approved ₹45,000 billing refund due to duplicate advance collection for OT cancellation.",
    beforeState: {
      invoiceId: "INV-2026-08891",
      totalPaid: 125000,
      refundStatus: "None",
    },
    afterState: {
      invoiceId: "INV-2026-08891",
      refundAmount: 45000,
      netSettled: 80000,
      refundStatus: "Processed",
    },
  },
  {
    id: "aud_05",
    actor: "Dr. Vikram Seth",
    actorRole: "Consultant Radiologist",
    action: "Published Critical Radiology Finding",
    module: "Radiology & Imaging",
    entity: "CT Angiography Report",
    entityId: "RAD-2026-004",
    timestamp: "2026-08-24T09:20:00Z",
    ipAddress: "10.0.18.99",
    status: "success",
    severity: "High",
    reason: "Acute Saddle Pulmonary Embolism identified. Critical alert escalated to Pulmonology on-call team.",
    beforeState: {
      studyId: "RAD-2026-004",
      status: "Preliminary / AI Draft",
      criticalFlag: false,
    },
    afterState: {
      studyId: "RAD-2026-004",
      status: "Final Verified",
      criticalFlag: true,
      escalationAcknowledged: true,
    },
  },
];

// ==========================================
// 6. DOCUMENT SECURITY & PRIVACY POLICIES
// ==========================================
export const mockDocumentSecurityPolicies: DocumentSecurityPolicy[] = [
  {
    id: "doc_sec_01",
    documentCategory: "Inpatient Clinical EMR & Discharge Summaries",
    viewPermission: ["Doctor", "Nurse Lead", "Hospital Admin", "CMO"],
    downloadPermission: ["Doctor", "Hospital Admin"],
    sharePermission: ["Hospital Admin"],
    watermarkingEnforced: true,
    redactionRules: ["Redact Social Security / Aadhaar #", "Mask Billing Rates from Clinical Printouts"],
  },
  {
    id: "doc_sec_02",
    documentCategory: "Radiology DICOM Studies & High-Res PACS",
    viewPermission: ["Doctor", "Radiologist", "CMO", "Hospital Admin"],
    downloadPermission: ["Radiologist", "Hospital Admin"],
    sharePermission: ["Radiologist", "Hospital Admin"],
    watermarkingEnforced: true,
    redactionRules: ["DICOM Header Anonymization for Research Exports"],
  },
  {
    id: "doc_sec_03",
    documentCategory: "Molecular Pathology & Oncology Genetic Reports",
    viewPermission: ["Doctor", "Pathologist", "CMO"],
    downloadPermission: ["Pathologist", "Hospital Admin"],
    sharePermission: ["CMO", "Hospital Admin"],
    watermarkingEnforced: true,
    redactionRules: ["Strict Genetic Privacy Masking"],
  },
  {
    id: "doc_sec_04",
    documentCategory: "Schedule H1 & Narcotic Dispensing Registers",
    viewPermission: ["Lead Pharmacist", "Hospital Admin", "State Inspector"],
    downloadPermission: ["Lead Pharmacist", "Hospital Admin"],
    sharePermission: ["Hospital Admin"],
    watermarkingEnforced: true,
    redactionRules: ["Mask Patient Personal Phone Number in State Audits"],
  },
];

// ==========================================
// 7. CROSS-ORGANIZATION PRIVACY & CONSENT RECORDS
// ==========================================
export const mockPrivacyConsentRecords: PrivacyConsentRecord[] = [
  {
    id: "cons_01",
    patientId: "PAT-00102",
    patientName: "Harish Chandra",
    externalOrgName: "Tata Memorial Cancer Research Institute",
    purpose: "Cross-Hospital Oncology Second Opinion & Targeted Chemo Protocol",
    consentStatus: "Granted",
    validUntil: "2027-08-20",
    dataMinimizationTier: "Full Medical Record",
  },
  {
    id: "cons_02",
    patientId: "PAT-00331",
    patientName: "Kavita R. Nair",
    externalOrgName: "National Health Authority (ABHA Ayushman Bharat)",
    purpose: "Ayushman Digital Health Mission Insurance Claim Reconciliation",
    consentStatus: "Granted",
    validUntil: "2026-12-31",
    dataMinimizationTier: "Anonymized Billing",
  },
  {
    id: "cons_03",
    patientId: "PAT-00441",
    patientName: "Meenakshi Sundaram",
    externalOrgName: "Apollo Hospitals ApolloGleneagles Network",
    purpose: "Organ Transplant Waiting List Verification",
    consentStatus: "Expired",
    validUntil: "2026-08-01",
    dataMinimizationTier: "Restricted Diagnosis Only",
  },
];

// ==========================================
// 8. CONFIGURATION & AUDIT BACKUP SNAPSHOTS
// ==========================================
export const mockConfigBackupSnapshots: ConfigBackupSnapshot[] = [
  {
    id: "snap_01",
    snapshotName: "Daily Automated Snapshot — Core RBAC & Hospital Config",
    type: "Full System Configuration",
    createdAt: "2026-08-24T03:00:00Z",
    createdBy: "Automated Backup Engine",
    fileSize: "14.2 MB",
    checksum: "SHA256: 8f9b201a4e12c98d7f8812a",
    status: "Encrypted & Verified",
  },
  {
    id: "snap_02",
    snapshotName: "Monthly Immutable Audit Log Archive — July 2026",
    type: "Audit Log Archive",
    createdAt: "2026-08-01T00:05:00Z",
    createdBy: "Compliance Vault Service",
    fileSize: "188.4 MB",
    checksum: "SHA256: b341a998c001f55219e4431",
    status: "Archived",
  },
  {
    id: "snap_03",
    snapshotName: "Pre-Deployment Role Definitions Backup",
    type: "RBAC & Role Definitions",
    createdAt: "2026-08-20T16:40:00Z",
    createdBy: "Akash Sharma (Hospital Admin)",
    fileSize: "2.1 MB",
    checksum: "SHA256: cc4918e900a8412fb109882",
    status: "Encrypted & Verified",
  },
];
