import {
  BillingCounter,
  BillingPermissions,
  BillingStaff,
  BillingTransaction,
  DoctorOnCall,
  LabStaff,
  LeaveRequest,
  Nurse,
  Receptionist,
  SupportStaff,
  AttendanceRecord,
} from "@/hospital-admin/lib/types";

export const receptionists: Receptionist[] = [
  {
    id: "rec_001",
    name: "Priya Deshmukh",
    email: "priya.deshmukh@qlyno.health",
    phone: "+91 98200 44112",
    status: "active",
    createdAt: "2023-03-01",
    location: "Qlyno Multispecialty Hospital - Front Desk",
    role: "Receptionist",
    assignedContext: "Clinic",
    branch: "Main Hospital",
    desk: "Front Desk A",
    department: "OPD",
    workflowScope: ["Appointments", "Check-in", "Routing"],
    scope: ["Appointments", "Check-in", "Billing (limited)"],
    appointmentsHandled: 4210,
    avatarUrl: "https://i.pravatar.cc/150?img=5",
  },
  {
    id: "rec_002",
    name: "Sana Sheikh",
    email: "sana.sheikh@qlyno.health",
    phone: "+91 98330 90211",
    status: "active",
    createdAt: "2023-08-19",
    location: "Qlyno Multispecialty Hospital - Front Desk",
    role: "Receptionist",
    assignedContext: "Clinic",
    branch: "Main Hospital",
    desk: "Front Desk B",
    department: "Emergency",
    workflowScope: ["Emergency intake", "Ward routing", "Discharge"],
    scope: ["Appointments", "Check-in", "Patient Registration"],
    appointmentsHandled: 2890,
    avatarUrl: "https://i.pravatar.cc/150?img=9",
  },
  {
    id: "rec_003",
    name: "Manoj Pillai",
    email: "manoj.pillai@qlyno.health",
    phone: "+91 90210 55871",
    status: "invited",
    createdAt: "2024-06-02",
    location: "Qlyno Multispecialty Hospital - Front Desk",
    role: "Receptionist",
    assignedContext: "Clinic",
    branch: "Main Hospital",
    desk: "Front Desk C",
    department: "Admissions",
    workflowScope: ["Appointments"],
    scope: ["Appointments"],
    appointmentsHandled: 0,
    avatarUrl: "https://i.pravatar.cc/150?img=13",
  },
];

export const nurses: Nurse[] = [
  {
    id: "nur_001",
    name: "Anjali Bhosale",
    email: "anjali.bhosale@qlyno.health",
    phone: "+91 99870 12456",
    status: "active",
    createdAt: "2022-09-14",
    location: "Qlyno Multispecialty Hospital - Ward A",
    role: "Nurse",
    level: "Senior Nurse",
    department: "General Ward",
    station: "Station A1",
    shift: "Morning",
    assignedPatients: 12,
    tasksPending: 3,
    tasksOverdue: 0,
    councilRegistrationId: "MNC-RN-2018-8842",
    qualifications: ["B.Sc. Nursing (Hons)", "Critical Care Registered Nurse (CCRN)", "BLS & ACLS Certified"],
    employmentHistory: [
      { period: "2022 – Present", role: "Senior Staff Nurse", hospital: "Qlyno Multispecialty Hospital" },
      { period: "2019 – 2022", role: "Staff Nurse", hospital: "Lilavati Hospital & Research Centre" },
    ],
    vitalsCompletionRate: 98.4,
    medicationComplianceRate: 99.6,
    avgOrderFulfillmentMins: 11,
    punctualityScore: 97.5,
    incidentCount: 0,
    avatarUrl: "https://i.pravatar.cc/150?img=20",
  },
  {
    id: "nur_002",
    name: "Ritu Sharma",
    email: "ritu.sharma@qlyno.health",
    phone: "+91 91234 65890",
    status: "active",
    createdAt: "2023-01-20",
    location: "Qlyno Multispecialty Hospital - ICU",
    role: "Nurse",
    level: "Nurse Lead",
    department: "ICU",
    station: "Station ICU-1",
    shift: "Night",
    assignedPatients: 6,
    tasksPending: 5,
    tasksOverdue: 1,
    councilRegistrationId: "MNC-RN-2016-4102",
    qualifications: ["M.Sc. Nursing (Cardiothoracic)", "Post-Basic ICU Diploma", "Infection Control Specialist"],
    employmentHistory: [
      { period: "2023 – Present", role: "ICU Nurse Lead", hospital: "Qlyno Multispecialty Hospital" },
      { period: "2017 – 2022", role: "Senior ICU Nurse", hospital: "Apollo Hospitals Mumbai" },
    ],
    vitalsCompletionRate: 99.1,
    medicationComplianceRate: 98.8,
    avgOrderFulfillmentMins: 9,
    punctualityScore: 99.0,
    incidentCount: 0,
    avatarUrl: "https://i.pravatar.cc/150?img=21",
  },
  {
    id: "nur_003",
    name: "Zoya Ansari",
    email: "zoya.ansari@qlyno.health",
    phone: "+91 90045 33211",
    status: "active",
    createdAt: "2023-05-11",
    location: "Qlyno Multispecialty Hospital - OT Complex",
    role: "Nurse",
    level: "Nurse",
    department: "OT Complex",
    station: "Station OT-Main",
    shift: "Morning",
    assignedPatients: 4,
    tasksPending: 1,
    tasksOverdue: 0,
    councilRegistrationId: "MNC-RN-2021-9921",
    qualifications: ["B.Sc. Nursing", "Certified Perioperative Nurse (CNOR)", "Laser Safety Certified"],
    employmentHistory: [
      { period: "2023 – Present", role: "Scrub & Perioperative Nurse", hospital: "Qlyno Multispecialty Hospital" },
    ],
    vitalsCompletionRate: 97.8,
    medicationComplianceRate: 100,
    avgOrderFulfillmentMins: 14,
    punctualityScore: 96.0,
    incidentCount: 0,
    avatarUrl: "https://i.pravatar.cc/150?img=22",
  },
  {
    id: "nur_004",
    name: "Pooja Hegde",
    email: "pooja.hegde@qlyno.health",
    phone: "+91 98334 11098",
    status: "active",
    createdAt: "2023-11-04",
    location: "Qlyno Multispecialty Hospital - Pediatrics",
    role: "Nurse",
    level: "Nurse",
    department: "Pediatrics",
    station: "Station Peds-1",
    shift: "Evening",
    assignedPatients: 8,
    tasksPending: 2,
    tasksOverdue: 0,
    councilRegistrationId: "MNC-RN-2022-7712",
    qualifications: ["B.Sc. Nursing", "PALS (Pediatric Advanced Life Support)"],
    employmentHistory: [
      { period: "2023 – Present", role: "Pediatric Staff Nurse", hospital: "Qlyno Multispecialty Hospital" },
    ],
    vitalsCompletionRate: 96.5,
    medicationComplianceRate: 99.0,
    avgOrderFulfillmentMins: 15,
    punctualityScore: 95.5,
    incidentCount: 0,
    avatarUrl: "https://i.pravatar.cc/150?img=23",
  },
  {
    id: "nur_005",
    name: "Kiran More",
    email: "kiran.more@qlyno.health",
    phone: "+91 97654 32109",
    status: "active",
    createdAt: "2024-02-15",
    location: "Qlyno Multispecialty Hospital - Recovery PACU",
    role: "Nurse",
    level: "Senior Nurse",
    department: "PACU Recovery",
    station: "Station PACU-1",
    shift: "Morning",
    assignedPatients: 5,
    tasksPending: 1,
    tasksOverdue: 0,
    councilRegistrationId: "MNC-RN-2019-3321",
    qualifications: ["B.Sc. Nursing", "Post-Anesthesia Care Unit Certification"],
    employmentHistory: [
      { period: "2024 – Present", role: "PACU Lead Nurse", hospital: "Qlyno Multispecialty Hospital" },
      { period: "2019 – 2024", role: "Critical Care Nurse", hospital: "Hinduja Hospital" },
    ],
    vitalsCompletionRate: 99.4,
    medicationComplianceRate: 99.8,
    avgOrderFulfillmentMins: 8,
    punctualityScore: 98.5,
    incidentCount: 0,
    avatarUrl: "https://i.pravatar.cc/150?img=24",
  },
];

export const billingCounters: BillingCounter[] = [
  {
    id: "CTR-01",
    name: "Counter 1 — OPD Central Cashier",
    type: "OPD Billing",
    status: "Open",
    assignedStaffId: "bil_001",
    assignedStaffName: "Rohit Kadam",
    location: "Ground Floor OPD Atrium",
    shift: "Morning",
  },
  {
    id: "CTR-02",
    name: "Counter 2 — IPD Admissions & Discharge",
    type: "IPD Billing",
    status: "Open",
    assignedStaffId: "bil_002",
    assignedStaffName: "Meenakshi Sundaram",
    location: "Tower A, 1st Floor Lobby",
    shift: "Morning",
  },
  {
    id: "CTR-03",
    name: "Counter 3 — Insurance / TPA Pre-Auth Desk",
    type: "Insurance/TPA Desk",
    status: "Open",
    assignedStaffId: "bil_003",
    assignedStaffName: "Vikram Jadhav",
    location: "Ground Floor Admin Wing",
    shift: "Morning",
  },
  {
    id: "CTR-04",
    name: "Counter 4 — Refund & Settlement Desk",
    type: "Refund Desk",
    status: "Open",
    assignedStaffId: "bil_004",
    assignedStaffName: "Sneha Patil",
    location: "Ground Floor Accounts Room",
    shift: "Morning",
  },
  {
    id: "CTR-05",
    name: "Counter 5 — Emergency 24x7 Triage Billing",
    type: "OPD Billing",
    status: "Open",
    assignedStaffId: "bil_001",
    assignedStaffName: "Rohit Kadam",
    location: "Emergency Department Bay",
    shift: "Night",
  },
];

export const billingTransactions: BillingTransaction[] = [
  {
    id: "TXN-8801",
    timestamp: "2026-08-21T09:14:00Z",
    patientName: "Arjun Gupta",
    patientId: "P-8821",
    type: "Payment",
    amount: 145000,
    paymentMode: "Card",
    status: "Reconciled",
    counterId: "CTR-02",
    billingOfficerName: "Meenakshi Sundaram",
    notes: "Total Knee Replacement IPD Interim Deposit",
  },
  {
    id: "TXN-8802",
    timestamp: "2026-08-21T09:45:00Z",
    patientName: "Sana Sheikh",
    patientId: "P-4412",
    type: "Payment",
    amount: 1200,
    paymentMode: "UPI",
    status: "Reconciled",
    counterId: "CTR-01",
    billingOfficerName: "Rohit Kadam",
    notes: "Cardiology Specialist OPD Consultation",
  },
  {
    id: "TXN-8803",
    timestamp: "2026-08-21T10:10:00Z",
    patientName: "Kavita Patil",
    patientId: "P-9102",
    type: "Payment",
    amount: 8500,
    paymentMode: "Cash",
    status: "Reconciled",
    counterId: "CTR-01",
    billingOfficerName: "Rohit Kadam",
    notes: "Spine MRI Scan & Contrast Investigations",
  },
  {
    id: "TXN-8804",
    timestamp: "2026-08-21T11:20:00Z",
    patientName: "Rajesh Khanna",
    patientId: "P-3319",
    type: "Refund",
    amount: 1500,
    paymentMode: "Cash",
    status: "Refunded",
    counterId: "CTR-04",
    billingOfficerName: "Sneha Patil",
    notes: "Cancelled ultrasound investigation refund (Doctor authorized)",
  },
  {
    id: "TXN-8805",
    timestamp: "2026-08-21T11:45:00Z",
    patientName: "Suresh Kulkarni",
    patientId: "P-3341",
    type: "TPA Settlement",
    amount: 280000,
    paymentMode: "Insurance",
    status: "Paid",
    counterId: "CTR-03",
    billingOfficerName: "Vikram Jadhav",
    notes: "Star Health Pre-Auth Approved for CABG Surgery",
  },
];

export const billingStaff: BillingStaff[] = [
  {
    id: "bil_001",
    name: "Rohit Kadam",
    email: "rohit.kadam@qlyno.health",
    phone: "+91 98201 33456",
    status: "active",
    createdAt: "2023-04-10",
    location: "Qlyno Multispecialty Hospital - Accounts",
    role: "Billing Staff",
    scopes: ["OPD Billing", "Pharmacy POS", "Diagnostic Collections"],
    assignedCounterId: "CTR-01",
    assignedCounterName: "Counter 1 — OPD Central Cashier",
    shift: "Morning",
    permissions: {
      maxRefundLimit: 5000,
      maxDiscountLimit: 1000,
      permittedCategories: ["OPD", "Diagnostics", "Pharmacy"],
      supervisorOverride: false,
    },
    collectionsToday: 84200,
    pendingInvoices: 4,
    collectionsByMode: {
      cash: 24500,
      card: 38200,
      upi: 21500,
      insurance: 0,
    },
    discrepancyAmount: 0,
    avatarUrl: "https://i.pravatar.cc/150?img=12",
  },
  {
    id: "bil_002",
    name: "Meenakshi Sundaram",
    email: "meenakshi.sundaram@qlyno.health",
    phone: "+91 98190 22100",
    status: "active",
    createdAt: "2022-11-01",
    location: "Qlyno Multispecialty Hospital - IPD Billing",
    role: "Billing Staff",
    scopes: ["IPD Billing", "Discharge Clearance", "Surgery Packages"],
    assignedCounterId: "CTR-02",
    assignedCounterName: "Counter 2 — IPD Admissions & Discharge",
    shift: "Morning",
    permissions: {
      maxRefundLimit: 25000,
      maxDiscountLimit: 5000,
      permittedCategories: ["IPD", "Surgery Packages", "Bed Charges"],
      supervisorOverride: true,
    },
    collectionsToday: 412000,
    pendingInvoices: 7,
    collectionsByMode: {
      cash: 45000,
      card: 265000,
      upi: 102000,
      insurance: 0,
    },
    discrepancyAmount: 0,
    avatarUrl: "https://i.pravatar.cc/150?img=32",
  },
  {
    id: "bil_003",
    name: "Vikram Jadhav",
    email: "vikram.jadhav@qlyno.health",
    phone: "+91 97690 88214",
    status: "active",
    createdAt: "2023-07-15",
    location: "Qlyno Multispecialty Hospital - TPA Desk",
    role: "Billing Staff",
    scopes: ["Insurance / TPA Desk", "Cashless Pre-Auth", "Claims Settlement"],
    assignedCounterId: "CTR-03",
    assignedCounterName: "Counter 3 — Insurance / TPA Pre-Auth Desk",
    shift: "Morning",
    permissions: {
      maxRefundLimit: 50000,
      maxDiscountLimit: 10000,
      permittedCategories: ["Insurance", "Corporate", "Ayushman Bharat"],
      supervisorOverride: true,
    },
    collectionsToday: 580000,
    pendingInvoices: 12,
    collectionsByMode: {
      cash: 0,
      card: 0,
      upi: 0,
      insurance: 580000,
    },
    discrepancyAmount: 0,
    avatarUrl: "https://i.pravatar.cc/150?img=53",
  },
  {
    id: "bil_004",
    name: "Sneha Patil",
    email: "sneha.patil@qlyno.health",
    phone: "+91 99300 44521",
    status: "active",
    createdAt: "2023-09-01",
    location: "Qlyno Multispecialty Hospital - Accounts",
    role: "Billing Staff",
    scopes: ["Refund Desk", "Audit Reconciliation", "Credit Notes"],
    assignedCounterId: "CTR-04",
    assignedCounterName: "Counter 4 — Refund & Settlement Desk",
    shift: "Morning",
    permissions: {
      maxRefundLimit: 15000,
      maxDiscountLimit: 2000,
      permittedCategories: ["Refunds", "Discounts", "Credit Settlements"],
      supervisorOverride: false,
    },
    collectionsToday: 18500,
    pendingInvoices: 2,
    collectionsByMode: {
      cash: 18500,
      card: 0,
      upi: 0,
      insurance: 0,
    },
    discrepancyAmount: 0,
    avatarUrl: "https://i.pravatar.cc/150?img=47",
  },
];

export const supportStaffList: SupportStaff[] = [
  // 1. TECHNICIANS
  {
    id: "sup_tech_01",
    name: "Anand Shinde",
    email: "anand.shinde@qlyno.health",
    phone: "+91 98210 99401",
    status: "active",
    createdAt: "2023-02-15",
    location: "Central Pathology Lab",
    role: "Technician",
    category: "Technician",
    department: "Laboratory",
    taskScope: ["Hematology Automated Analyzers", "Sample Centrifugation", "Blood Smear Preparation"],
    assignment: "Hematology & Biochemistry Lab",
    availability: "assigned",
    assignedStationId: "st-1",
    avatarUrl: "https://i.pravatar.cc/150?img=60",
  },
  {
    id: "sup_tech_02",
    name: "Sameer Sheikh",
    email: "sameer.sheikh@qlyno.health",
    phone: "+91 98110 44231",
    status: "active",
    createdAt: "2023-06-20",
    location: "Radiology Wing",
    role: "Technician",
    category: "Technician",
    department: "Radiology",
    taskScope: ["MRI 3.0T Scanner", "CT 128-Slice", "Digital X-Ray Operations"],
    assignment: "Main Imaging Complex",
    availability: "assigned",
    assignedStationId: "st-1",
    avatarUrl: "https://i.pravatar.cc/150?img=61",
  },
  {
    id: "sup_tech_03",
    name: "Prashant Sawant",
    email: "prashant.sawant@qlyno.health",
    phone: "+91 97690 11982",
    status: "active",
    createdAt: "2023-08-10",
    location: "OT Complex",
    role: "Technician",
    category: "Technician",
    department: "Operation Theatre",
    taskScope: ["C-Arm Calibration", "Laparoscopy Tower Sterility", "Anesthesia Workstation Gas Monitoring"],
    assignment: "Main OR 1 & 2",
    availability: "assigned",
    assignedStationId: "st-1",
    avatarUrl: "https://i.pravatar.cc/150?img=62",
  },

  // 2. HOUSEKEEPING & SANITATION
  {
    id: "sup_hk_01",
    name: "Sunita Reddy",
    email: "sunita.reddy@qlyno.health",
    phone: "+91 98222 33441",
    status: "active",
    createdAt: "2022-10-05",
    location: "ICU & PACU Complex",
    role: "Housekeeping",
    category: "Housekeeping",
    department: "ICU",
    taskScope: ["Bio-Medical Waste Segregation (Yellow/Red Bags)", "Terminal Disinfection", "Laminar Surface Sterilization"],
    assignment: "ICU Bay 1-10",
    availability: "assigned",
    assignedStationId: "st-1",
    avatarUrl: "https://i.pravatar.cc/150?img=44",
  },
  {
    id: "sup_hk_02",
    name: "Manohar Gaikwad",
    email: "manohar.gaikwad@qlyno.health",
    phone: "+91 91220 88123",
    status: "active",
    createdAt: "2023-03-12",
    location: "General Ward Tower A",
    role: "Housekeeping",
    category: "Housekeeping",
    department: "Inpatient Wards",
    taskScope: ["Linen Turnover", "Room Fogging & Sanitization", "Washroom Deep Clean"],
    assignment: "Floor 2 General Beds",
    availability: "assigned",
    assignedStationId: "st-1",
    avatarUrl: "https://i.pravatar.cc/150?img=63",
  },

  // 3. SECURITY
  {
    id: "sup_sec_01",
    name: "Balwant Singh",
    email: "balwant.singh@qlyno.health",
    phone: "+91 99881 22334",
    status: "active",
    createdAt: "2022-08-01",
    location: "Main Emergency Gate",
    role: "Security",
    category: "Security",
    department: "Security",
    taskScope: ["Emergency Triage Gate Entry Access", "Visitor Pass Verification", "Crowd & Queue Control"],
    assignment: "Gate 1 (Emergency Intake)",
    availability: "assigned",
    avatarUrl: "https://i.pravatar.cc/150?img=64",
  },
  {
    id: "sup_sec_02",
    name: "Govind Rajput",
    email: "govind.rajput@qlyno.health",
    phone: "+91 98770 44556",
    status: "active",
    createdAt: "2023-01-15",
    location: "OPD Atrium",
    role: "Security",
    category: "Security",
    department: "Security",
    taskScope: ["Lobby Patrol", "CCTV Monitoring Room", "Doctor Cabin Security"],
    assignment: "Main Lobby & Atrium",
    availability: "assigned",
    avatarUrl: "https://i.pravatar.cc/150?img=65",
  },

  // 4. DRIVERS (CROSS-LINKED TO AMBULANCE FLEET)
  {
    id: "sup_drv_01",
    name: "Karan Johar",
    email: "karan.johar@qlyno.health",
    phone: "+91 98200 11223",
    status: "active",
    createdAt: "2022-06-01",
    location: "Ambulance Bay (Main Campus)",
    role: "Driver",
    category: "Driver",
    department: "Emergency Fleet",
    taskScope: ["ALS Ambulance Response", "Oxygen Cylinder Inventory", "GPS Live Route Navigation"],
    assignment: "Ambulance AMB-01 (Advanced Life Support)",
    availability: "assigned",
    driverLicenseNumber: "MH-02-2018-9921",
    assignedVehicleId: "AMB-01",
    avatarUrl: "https://i.pravatar.cc/150?img=66",
  },
  {
    id: "sup_drv_02",
    name: "Sanjay Raut",
    email: "sanjay.raut@qlyno.health",
    phone: "+91 98330 44556",
    status: "active",
    createdAt: "2023-04-10",
    location: "Ambulance Bay (Main Campus)",
    role: "Driver",
    category: "Driver",
    department: "Emergency Fleet",
    taskScope: ["BLS Transport", "Neonatal Incubator Securement", "Patient Shifting"],
    assignment: "Ambulance AMB-02 (Basic Life Support)",
    availability: "available",
    driverLicenseNumber: "MH-03-2019-4412",
    assignedVehicleId: "AMB-02",
    avatarUrl: "https://i.pravatar.cc/150?img=67",
  },

  // 5. SUPPORT STAFF (ATTENDANTS / ORDERLIES / RUNNERS)
  {
    id: "sup_att_01",
    name: "Ravi Kumar",
    email: "ravi.kumar@qlyno.health",
    phone: "+91 98205 11990",
    status: "active",
    createdAt: "2022-11-10",
    location: "ICU Central Floor",
    role: "Attendant",
    category: "Support Staff",
    department: "Intensive Care",
    taskScope: ["Patient Mobilization", "Stretcher Shifting to Radiology/OT", "Bedpan & Hygiene Assistance"],
    assignment: "ICU Station 1",
    availability: "assigned",
    assignedStationId: "st-1",
    avatarUrl: "https://i.pravatar.cc/150?img=68",
  },
  {
    id: "sup_att_02",
    name: "Vikram Singh",
    email: "vikram.singh@qlyno.health",
    phone: "+91 97650 22331",
    status: "active",
    createdAt: "2023-05-18",
    location: "Pediatric Ward",
    role: "Assistant",
    category: "Support Staff",
    department: "Pediatrics",
    taskScope: ["Sample Transport to Central Lab", "Material Runner", "Wheelchair Escort"],
    assignment: "Pediatric Wing A",
    availability: "assigned",
    assignedStationId: "st-2",
    avatarUrl: "https://i.pravatar.cc/150?img=69",
  },

  // 6. OTHER HOSPITAL STAFF (ADMIN CLERKS / IT / BIOMEDICAL)
  {
    id: "sup_oth_01",
    name: "Nilesh Tawde",
    email: "nilesh.tawde@qlyno.health",
    phone: "+91 98190 77881",
    status: "active",
    createdAt: "2023-01-10",
    location: "Biomedical Engineering Dept",
    role: "Other Hospital Staff",
    category: "Other Hospital Staff",
    department: "Engineering & Maintenance",
    taskScope: ["Ventilator Calibration", "Defibrillator Testing", "Medical Gas Pipeline Pressure Monitoring"],
    assignment: "Biomedical Maintenance Lab",
    availability: "assigned",
    avatarUrl: "https://i.pravatar.cc/150?img=70",
  },
  {
    id: "sup_oth_02",
    name: "Tanmay Bhatia",
    email: "tanmay.bhatia@qlyno.health",
    phone: "+91 90040 33112",
    status: "active",
    createdAt: "2023-07-01",
    location: "Hospital Server Room",
    role: "Other Hospital Staff",
    category: "Other Hospital Staff",
    department: "IT & Telecommunications",
    taskScope: ["HIS EMR Workstation Support", "Barcode Scanner Config", "Nurse Station Tablet Setup"],
    assignment: "IT Helpdesk & Networks",
    availability: "assigned",
    avatarUrl: "https://i.pravatar.cc/150?img=71",
  },
];

export const doctorsOnCall: DoctorOnCall[] = [
  {
    id: "DOC-01",
    doctorId: "doc_001",
    doctorName: "Dr. Ananya Patel",
    specialty: "Cardiology",
    phone: "+91 98200 44991",
    date: "2026-08-21",
    shiftWindow: "24 Hours (08:00 – 08:00)",
    status: "On Call",
    activeEmergencyCases: 1,
  },
  {
    id: "DOC-02",
    doctorId: "doc_002",
    doctorName: "Dr. Vikram Seth",
    specialty: "Neurosurgery",
    phone: "+91 98110 55221",
    date: "2026-08-21",
    shiftWindow: "Night (20:00 – 08:00)",
    status: "On Call",
    activeEmergencyCases: 0,
  },
  {
    id: "DOC-03",
    doctorId: "doc_003",
    doctorName: "Dr. Ramesh Sharma",
    specialty: "Orthopedics & Trauma",
    phone: "+91 97690 33114",
    date: "2026-08-21",
    shiftWindow: "Day (08:00 – 20:00)",
    status: "Consulting",
    activeEmergencyCases: 2,
  },
  {
    id: "DOC-04",
    doctorId: "doc_004",
    doctorName: "Dr. Rohan Mehta",
    specialty: "General & Trauma Surgery",
    phone: "+91 99201 88321",
    date: "2026-08-21",
    shiftWindow: "24 Hours (08:00 – 08:00)",
    status: "On Call",
    activeEmergencyCases: 1,
  },
];

export const leaveRequests: LeaveRequest[] = [
  {
    id: "LEV-001",
    staffId: "nur_003",
    staffName: "Zoya Ansari",
    staffRole: "Nurse",
    department: "OT Complex",
    leaveType: "Casual Leave",
    startDate: "2026-08-24",
    endDate: "2026-08-25",
    reason: "Family wedding event in Pune.",
    status: "Pending",
    coverageGapDetected: true,
    assignedBackupStaffId: "nur_001",
    assignedBackupStaffName: "Anjali Bhosale",
    appliedOn: "2026-08-20",
  },
  {
    id: "LEV-002",
    staffId: "bil_001",
    staffName: "Rohit Kadam",
    staffRole: "Billing Staff",
    department: "OPD Billing",
    leaveType: "Sick Leave",
    startDate: "2026-08-22",
    endDate: "2026-08-22",
    reason: "Severe viral fever & throat infection.",
    status: "Pending",
    coverageGapDetected: true,
    assignedBackupStaffId: "bil_004",
    assignedBackupStaffName: "Sneha Patil",
    appliedOn: "2026-08-21",
  },
  {
    id: "LEV-003",
    staffId: "sup_att_01",
    staffName: "Ravi Kumar",
    staffRole: "Attendant",
    department: "Intensive Care",
    leaveType: "Earned Leave",
    startDate: "2026-08-28",
    endDate: "2026-08-31",
    reason: "Annual planned hometown vacation.",
    status: "Approved",
    coverageGapDetected: false,
    assignedBackupStaffId: "sup_att_02",
    assignedBackupStaffName: "Vikram Singh",
    appliedOn: "2026-08-15",
  },
];

export const attendanceRecords: AttendanceRecord[] = [
  {
    id: "ATT-101",
    staffId: "nur_001",
    staffName: "Anjali Bhosale",
    staffRole: "Senior Nurse",
    department: "General Ward",
    date: "2026-08-21",
    scheduledShift: "Morning (06:00 – 14:00)",
    punchIn: "05:52 AM",
    punchOut: "02:08 PM",
    status: "Present",
    overtimeMinutes: 8,
  },
  {
    id: "ATT-102",
    staffId: "nur_002",
    staffName: "Ritu Sharma",
    staffRole: "Nurse Lead",
    department: "ICU",
    date: "2026-08-21",
    scheduledShift: "Night (22:00 – 06:00)",
    punchIn: "09:50 PM",
    punchOut: "06:15 AM",
    status: "Present",
    overtimeMinutes: 15,
  },
  {
    id: "ATT-103",
    staffId: "nur_003",
    staffName: "Zoya Ansari",
    staffRole: "Scrub Nurse",
    department: "OT Complex",
    date: "2026-08-21",
    scheduledShift: "Morning (06:00 – 14:00)",
    punchIn: "06:22 AM",
    punchOut: "02:00 PM",
    status: "Late",
    lateMinutes: 22,
  },
  {
    id: "ATT-104",
    staffId: "bil_001",
    staffName: "Rohit Kadam",
    staffRole: "Billing Staff",
    department: "OPD Billing",
    date: "2026-08-21",
    scheduledShift: "Morning (08:00 – 16:00)",
    punchIn: "07:55 AM",
    punchOut: "04:30 PM",
    status: "Present",
    overtimeMinutes: 30,
  },
  {
    id: "ATT-105",
    staffId: "bil_002",
    staffName: "Meenakshi Sundaram",
    staffRole: "Billing Staff",
    department: "IPD Billing",
    date: "2026-08-21",
    scheduledShift: "Morning (08:00 – 16:00)",
    punchIn: "07:50 AM",
    punchOut: "03:15 PM",
    status: "Early Departure",
    earlyMinutes: 45,
    editedReason: "Approved half-day emergency leave by Accounts Lead",
    editedBy: "Hospital Admin",
  },
  {
    id: "ATT-106",
    staffId: "sup_drv_01",
    staffName: "Karan Johar",
    staffRole: "Ambulance Driver",
    department: "Emergency Fleet",
    date: "2026-08-21",
    scheduledShift: "Morning (06:00 – 14:00)",
    punchIn: "05:45 AM",
    punchOut: "02:40 PM",
    status: "Present",
    overtimeMinutes: 40,
  },
  {
    id: "ATT-107",
    staffId: "sup_hk_01",
    staffName: "Sunita Reddy",
    staffRole: "Housekeeping",
    department: "ICU",
    date: "2026-08-21",
    scheduledShift: "Morning (06:00 – 14:00)",
    punchIn: "06:00 AM",
    punchOut: "02:00 PM",
    status: "Present",
  },
];

export const labStaffList: LabStaff[] = [
  {
    id: "lab_001",
    name: "Dr. Arvind Swaminathan",
    email: "arvind.swaminathan@qlyno.health",
    phone: "+91 98201 11299",
    status: "active",
    createdAt: "2022-05-10",
    location: "Central Pathology Wing",
    role: "Pathologist",
    labLocation: "Main Lab Block A",
    ordersHandled: 3420,
    avatarUrl: "https://i.pravatar.cc/150?img=51",
  },
  {
    id: "lab_002",
    name: "Smita Kulkarni",
    email: "smita.kulkarni@qlyno.health",
    phone: "+91 98190 44521",
    status: "active",
    createdAt: "2023-01-15",
    location: "Central Pathology Wing",
    role: "Lab Technician",
    labLocation: "Biochemistry & Hematology Lab",
    ordersHandled: 5120,
    avatarUrl: "https://i.pravatar.cc/150?img=49",
  },
  {
    id: "lab_003",
    name: "Mahesh Jadhav",
    email: "mahesh.jadhav@qlyno.health",
    phone: "+91 97690 33812",
    status: "active",
    createdAt: "2023-08-01",
    location: "OPD Sample Collection Booth",
    role: "Collection Agent",
    labLocation: "Ground Floor OPD Phlebotomy",
    ordersHandled: 2890,
    avatarUrl: "https://i.pravatar.cc/150?img=58",
  },
];

