"use client";
import { notFound } from "next/navigation";
import { EntityHeader } from "@/components/ui/EntityHeader";
import { Card } from "@/components/ui/Card";
import { StatusBadge } from "@/components/ui/Badge";
import { Timeline } from "@/components/ui/Timeline";
import { BarcodeLabelPreview } from "@/components/domain/BarcodeLabelPreview";
import { useHospitalWorkflow } from "@/state/hospital-workflow-context";
import { useDemo } from "@/state/demo-context";
import Link from "next/link";
import { ArrowRight } from "lucide-react";

export default function SpecimenDetailPage({ params }: { params: { id: string } }) {
  const { activeSpecimens, lifecycleEvents } = useHospitalWorkflow(); const { session } = useDemo(); const specimen = activeSpecimens.find((entry) => entry.id === params.id); if (!specimen) notFound();
  const permitted = Boolean(session && specimen.tenantId === session.tenantId && specimen.siteId && session.allowedSiteIds.includes(specimen.siteId)); if (!permitted) return <div role="alert" className="rounded-card border border-red-200 bg-red-50 p-5 font-semibold text-status-critical">Access denied. This specimen is outside your permitted tenant or site.</div>;
  const events = lifecycleEvents.filter((event) => event.specimenId === specimen.id).slice().sort((a, b) => a.timestamp.localeCompare(b.timestamp));
  const receivingPending = ["collected", "in_transit"].includes(specimen.status); const accessionPending = specimen.status === "received" && !specimen.accessionId;
  const action = receivingPending ? { label: "Open in Receiving", href: `/collection/scan?orderId=${specimen.orderId}&specimenId=${specimen.id}`, permission: "specimen.receive" } : accessionPending ? { label: "Open in Accessioning", href: `/accessioning?orderId=${specimen.orderId}&specimenId=${specimen.id}`, permission: "specimen.accession" } : undefined;
  return <div className="space-y-6"><EntityHeader eyebrow="Module 4 · Collection & Specimens" title={specimen.id} subtitle={`${specimen.patientName} · ${specimen.mrn} · Order ${specimen.orderId}`} badges={<StatusBadge status={specimen.status}/>}/>{action && <Card className="flex flex-wrap items-center gap-3 border-brand-blue/30 bg-emerald-50/60 p-4"><div className="mr-auto"><p className="font-semibold">Next specimen action</p><p className="text-xs text-text-muted">Continue this exact specimen in its current workflow queue.</p></div>{session?.permissions.includes(action.permission) ? <Link href={action.href} className="inline-flex h-10 items-center gap-2 rounded-control bg-brand-blue px-4 text-sm font-semibold text-white hover:opacity-90">{action.label}<ArrowRight className="h-4 w-4"/></Link> : <span className="rounded-control border border-amber-200 bg-amber-50 px-3 py-2 text-xs font-semibold text-status-warning">Requires {action.permission} permission</span>}</Card>}<div className="grid gap-4 lg:grid-cols-3"><div className="space-y-4 lg:col-span-2"><Card className="p-5"><h3 className="mb-3 font-display text-lg font-semibold">Specimen details</h3><dl className="grid grid-cols-2 gap-4 text-sm sm:grid-cols-3"><Meta label="Type" value={specimen.type}/><Meta label="Container" value={specimen.container}/><Meta label="Collection location" value={specimen.collectionLocation}/><Meta label="Collected" value={specimen.collectedAt}/><Meta label="Collected by" value={specimen.collectedBy}/><Meta label="Received" value={specimen.receivedAt}/><Meta label="Received by" value={specimen.receivedBy}/><Meta label="Received site" value={specimen.receivedSiteId}/><Meta label="Accession" value={specimen.accessionId}/><Meta label="Condition" value={specimen.collectionCondition}/><Meta label="Seal" value={specimen.sealStatus}/><Meta label="Temperature" value={specimen.temperature}/></dl></Card><Card className="p-5"><h3 className="mb-3 font-display text-lg font-semibold">Immutable lifecycle timeline</h3><Timeline entries={events.map((event) => ({ id: event.id, label: event.type.replaceAll("_", " "), timestamp: event.timestamp, description: `${event.actorName} · ${event.reason ?? "Recorded"}`, tone: event.type === "SPECIMEN_REJECTED" ? "critical" as const : "success" as const }))}/></Card></div><BarcodeLabelPreview specimenId={specimen.id} patientName={specimen.patientName} testSummary={specimen.type} container={specimen.container}/></div></div>;
}
function Meta({ label, value }: { label: string; value?: string }) { return <div><dt className="text-xs text-text-muted">{label}</dt><dd className="font-medium">{value ?? "—"}</dd></div>; }
