import { Doctor } from "@/hospital-admin/lib/types";

export const doctors: Doctor[] = [
  {
    id: "doc_001",
    name: "Dr. Ananya Rao",
    email: "ananya.rao@qlyno.health",
    phone: "+91 98200 11234",
    status: "active",
    createdAt: "2023-02-10",
    location: "Qlyno Multispecialty Hospital - Main Campus",
    specialty: "Cardiology",
    subSpecialty: "Interventional Cardiology",
    qualification: "MBBS, MD (Cardiology), DM",
    experienceYears: 14,
    registrationNo: "MH-CARD-88231",
    availability: "available",
    clinics: ["Qlyno Multispecialty Hospital - Main Campus"],
    department: "Cardiology",
    privileges: ["ECG review", "Cardiac consults", "Emergency response"],
    languages: ["English", "Hindi", "Marathi"],
    services: ["Consultation", "Stress test", "ECG review"],
    consultationSettings: {
      visitMode: "Hybrid",
      slotsPerDay: 18,
      emergencyOnCall: true,
      maxPatientsPerDay: 22,
    },
    verification: {
      status: "verified",
      hospitalVerified: true,
      platformVerified: true,
      documents: ["Medical degree", "Registration", "Identity proof", "Experience proof"],
      pendingDocuments: [],
    },
    schedule: {
      dutyHours: "Mon–Sat · 09:00–18:00",
      emergencyOnCall: true,
      availability: "On-call for cardiology emergencies",
    },
    publicProfile: {
      published: true,
      searchable: true,
    },
    todayAppointments: 9,
    totalPatients: 1842,
    rating: 4.8,
    consultationFee: 1200,
    verified: true,
    role: "Doctor",
    avatarUrl: "https://i.pravatar.cc/150?img=47",
  },
  {
    id: "doc_002",
    name: "Dr. Rohan Mehta",
    email: "rohan.mehta@qlyno.health",
    phone: "+91 98330 55621",
    status: "active",
    createdAt: "2022-11-02",
    location: "Qlyno Multispecialty Hospital - Main Campus",
    specialty: "Orthopedics",
    subSpecialty: "Joint Replacement",
    qualification: "MBBS, MS (Ortho)",
    experienceYears: 9,
    registrationNo: "MH-ORTH-77102",
    availability: "busy",
    clinics: ["Qlyno Multispecialty Hospital - Main Campus"],
    department: "Orthopedics",
    privileges: ["Joint surgeries", "Post-op review", "Fracture management"],
    languages: ["English", "Hindi"],
    services: ["Consultation", "Joint evaluation", "Surgery follow-up"],
    consultationSettings: {
      visitMode: "In-person",
      slotsPerDay: 16,
      emergencyOnCall: true,
      maxPatientsPerDay: 18,
    },
    verification: {
      status: "verified",
      hospitalVerified: true,
      platformVerified: true,
      documents: ["Medical degree", "Registration", "ID proof"],
      pendingDocuments: [],
    },
    schedule: {
      dutyHours: "Mon–Fri · 10:00–19:00",
      emergencyOnCall: true,
      availability: "OT and orthopedic consult block",
    },
    publicProfile: {
      published: true,
      searchable: true,
    },
    todayAppointments: 12,
    totalPatients: 963,
    rating: 4.6,
    consultationFee: 900,
    verified: true,
    role: "Doctor",
    avatarUrl: "https://i.pravatar.cc/150?img=12",
  },
  {
    id: "doc_003",
    name: "Dr. Kavya Iyer",
    email: "kavya.iyer@qlyno.health",
    phone: "+91 97690 44210",
    status: "active",
    createdAt: "2023-06-19",
    location: "Qlyno Multispecialty Hospital - Main Campus",
    specialty: "Pediatrics",
    subSpecialty: "Neonatal Care",
    qualification: "MBBS, MD (Pediatrics)",
    experienceYears: 7,
    registrationNo: "MH-PED-65310",
    availability: "available",
    clinics: ["Qlyno Multispecialty Hospital - Main Campus"],
    department: "Pediatrics",
    privileges: ["Child consults", "Vaccination review", "Well-child follow-up"],
    languages: ["English", "Hindi", "Kannada"],
    services: ["Consultation", "Vaccination review", "Pediatric follow-up"],
    consultationSettings: {
      visitMode: "Hybrid",
      slotsPerDay: 12,
      emergencyOnCall: false,
      maxPatientsPerDay: 14,
    },
    verification: {
      status: "verified",
      hospitalVerified: true,
      platformVerified: true,
      documents: ["Medical degree", "Registration", "Experience proof"],
      pendingDocuments: [],
    },
    schedule: {
      dutyHours: "Tue–Sun · 09:00–17:00",
      emergencyOnCall: false,
      availability: "Pediatric OPD and follow-up clinics",
    },
    publicProfile: {
      published: true,
      searchable: true,
    },
    todayAppointments: 6,
    totalPatients: 1204,
    rating: 4.9,
    consultationFee: 700,
    verified: true,
    role: "Doctor",
    avatarUrl: "https://i.pravatar.cc/150?img=32",
  },
  {
    id: "doc_004",
    name: "Dr. Aditya Verma",
    email: "aditya.verma@qlyno.health",
    phone: "+91 90040 12987",
    status: "active",
    createdAt: "2021-08-14",
    location: "Qlyno Multispecialty Hospital - Main Campus",
    specialty: "Dermatology",
    subSpecialty: "Cosmetic Dermatology",
    qualification: "MBBS, MD (Skin & VD)",
    experienceYears: 11,
    registrationNo: "MH-DERM-51278",
    availability: "off",
    clinics: ["Qlyno Multispecialty Hospital - Main Campus"],
    department: "Dermatology",
    privileges: ["Skin consults", "Allergy treatment", "Procedural care"],
    languages: ["English", "Hindi"],
    services: ["Consultation", "Patch test", "Dermatoscopy"],
    consultationSettings: {
      visitMode: "In-person",
      slotsPerDay: 10,
      emergencyOnCall: false,
      maxPatientsPerDay: 12,
    },
    verification: {
      status: "verified",
      hospitalVerified: true,
      platformVerified: true,
      documents: ["Medical degree", "Registration", "ID proof"],
      pendingDocuments: [],
    },
    schedule: {
      dutyHours: "Mon–Thu · 11:00–18:00",
      emergencyOnCall: false,
      availability: "Dermatology outpatient clinic",
    },
    publicProfile: {
      published: true,
      searchable: true,
    },
    todayAppointments: 0,
    totalPatients: 1590,
    rating: 4.7,
    consultationFee: 1000,
    verified: true,
    role: "Doctor",
    avatarUrl: "https://i.pravatar.cc/150?img=51",
  },
  {
    id: "doc_005",
    name: "Dr. Neha Kulkarni",
    email: "neha.kulkarni@qlyno.health",
    phone: "+91 99870 33445",
    status: "active",
    createdAt: "2024-01-05",
    location: "Qlyno Multispecialty Hospital - Main Campus",
    specialty: "Gynecology",
    subSpecialty: "Maternal Care",
    qualification: "MBBS, MS (OBG)",
    experienceYears: 13,
    registrationNo: "MH-GYN-40217",
    availability: "available",
    clinics: ["Qlyno Multispecialty Hospital - Main Campus"],
    department: "Gynecology",
    privileges: ["Prenatal consults", "High-risk cases", "Delivery coordination"],
    languages: ["English", "Hindi", "Marathi"],
    services: ["Consultation", "Prenatal care", "Follow-up"],
    consultationSettings: {
      visitMode: "Hybrid",
      slotsPerDay: 15,
      emergencyOnCall: true,
      maxPatientsPerDay: 18,
    },
    verification: {
      status: "verified",
      hospitalVerified: true,
      platformVerified: true,
      documents: ["Medical degree", "Registration", "Experience proof"],
      pendingDocuments: [],
    },
    schedule: {
      dutyHours: "Mon–Sat · 08:30–17:30",
      emergencyOnCall: true,
      availability: "Maternity and OPD consultations",
    },
    publicProfile: {
      published: true,
      searchable: true,
    },
    todayAppointments: 8,
    totalPatients: 2103,
    rating: 4.9,
    consultationFee: 1100,
    verified: true,
    role: "Doctor",
    avatarUrl: "https://i.pravatar.cc/150?img=45",
  },
  {
    id: "doc_006",
    name: "Dr. Farhan Sheikh",
    email: "farhan.sheikh@qlyno.health",
    phone: "+91 91234 87651",
    status: "pending",
    createdAt: "2024-05-22",
    location: "Qlyno Multispecialty Hospital - Main Campus",
    specialty: "ENT",
    subSpecialty: "Endoscopic ENT",
    qualification: "MBBS, MS (ENT)",
    experienceYears: 5,
    registrationNo: "MH-ENT-90341",
    availability: "on-leave",
    clinics: ["Qlyno Multispecialty Hospital - Main Campus"],
    department: "ENT",
    privileges: ["ENT consults", "Audiology consults"],
    languages: ["English", "Hindi"],
    services: ["Consultation", "Ear evaluation", "ENT follow-up"],
    consultationSettings: {
      visitMode: "In-person",
      slotsPerDay: 8,
      emergencyOnCall: false,
      maxPatientsPerDay: 10,
    },
    verification: {
      status: "in-review",
      hospitalVerified: true,
      platformVerified: false,
      documents: ["Medical degree", "Registration", "Identity proof"],
      pendingDocuments: ["Platform verification documents"],
    },
    schedule: {
      dutyHours: "Thu–Sun · 09:00–15:00",
      leaveWindow: "Aug 19–Aug 28",
      emergencyOnCall: false,
      availability: "Currently on leave",
    },
    publicProfile: {
      published: false,
      searchable: false,
    },
    todayAppointments: 0,
    totalPatients: 312,
    rating: 4.4,
    consultationFee: 650,
    verified: false,
    role: "Doctor",
    avatarUrl: "https://i.pravatar.cc/150?img=15",
  },
  {
    id: "doc_007",
    name: "Dr. Simran Kaur",
    email: "simran.kaur@qlyno.health",
    phone: "+91 98765 22110",
    status: "active",
    createdAt: "2020-03-30",
    location: "Qlyno Multispecialty Hospital - Main Campus",
    specialty: "General Medicine",
    subSpecialty: "Internal Medicine",
    qualification: "MBBS, MD (Internal Medicine)",
    experienceYears: 16,
    registrationNo: "MH-GM-33208",
    availability: "available",
    clinics: ["Qlyno Multispecialty Hospital - Main Campus"],
    department: "General Medicine",
    privileges: ["Primary consults", "Chronic disease management", "Referral routing"],
    languages: ["English", "Hindi", "Punjabi"],
    services: ["Consultation", "Follow-up", "Care coordination"],
    consultationSettings: {
      visitMode: "Hybrid",
      slotsPerDay: 22,
      emergencyOnCall: true,
      maxPatientsPerDay: 25,
    },
    verification: {
      status: "verified",
      hospitalVerified: true,
      platformVerified: true,
      documents: ["Medical degree", "Registration", "ID proof", "Experience proof"],
      pendingDocuments: [],
    },
    schedule: {
      dutyHours: "Mon–Sat · 09:00–18:00",
      emergencyOnCall: true,
      availability: "General medicine OPD and emergency coverage",
    },
    publicProfile: {
      published: true,
      searchable: true,
    },
    todayAppointments: 14,
    totalPatients: 3120,
    rating: 4.8,
    consultationFee: 800,
    verified: true,
    role: "Doctor",
    avatarUrl: "https://i.pravatar.cc/150?img=25",
  },
  {
    id: "doc_008",
    name: "Dr. Vikram Nair",
    email: "vikram.nair@qlyno.health",
    phone: "+91 90876 65432",
    status: "suspended",
    createdAt: "2022-07-11",
    location: "Qlyno Multispecialty Hospital - Main Campus",
    specialty: "Neurology",
    subSpecialty: "Neurocritical Care",
    qualification: "MBBS, DM (Neurology)",
    experienceYears: 10,
    registrationNo: "MH-NEU-71098",
    availability: "off",
    clinics: ["Qlyno Multispecialty Hospital - Main Campus"],
    department: "Neurology",
    privileges: ["Neurology consults", "Referral triage"],
    languages: ["English", "Hindi"],
    services: ["Consultation", "Follow-up", "Neuro review"],
    consultationSettings: {
      visitMode: "Teleconsult",
      slotsPerDay: 6,
      emergencyOnCall: false,
      maxPatientsPerDay: 8,
    },
    verification: {
      status: "rejected",
      hospitalVerified: false,
      platformVerified: true,
      documents: ["Medical degree", "Registration"],
      pendingDocuments: ["Hospital affiliation document", "Additional licensing"] ,
    },
    schedule: {
      dutyHours: "Tue–Fri · 10:00–17:00",
      emergencyOnCall: false,
      availability: "Suspended from active clinical assignments",
    },
    publicProfile: {
      published: false,
      searchable: false,
    },
    todayAppointments: 0,
    totalPatients: 748,
    rating: 4.3,
    consultationFee: 1400,
    verified: true,
    role: "Doctor",
    avatarUrl: "https://i.pravatar.cc/150?img=60",
  },
  {
    id: "doc_rad_01",
    name: "Dr. Vikram Seth",
    email: "vikram.seth@qlyno.health",
    phone: "+91 98201 55441",
    status: "active",
    createdAt: "2023-01-15",
    location: "Qlyno Multispecialty Hospital - Main Campus",
    specialty: "Radiology",
    subSpecialty: "Body Imaging & CT Angiography",
    qualification: "MD (Radiodiagnosis), FRCR (UK)",
    experienceYears: 15,
    registrationNo: "MMC-2012-08891",
    availability: "available",
    clinics: ["Qlyno Central Diagnostic & Imaging Center"],
    department: "Radiology",
    privileges: ["CT Reporting", "MRI Sign-off", "Emergency Trauma Radiology", "PACS PACS-RIS Authorization"],
    languages: ["English", "Hindi", "Marathi"],
    services: ["Diagnostic Radiology Review", "CT Angiography Consult", "Cross-Sectional Imaging Second Opinion"],
    consultationSettings: {
      visitMode: "In-person",
      slotsPerDay: 20,
      emergencyOnCall: true,
      maxPatientsPerDay: 25,
    },
    verification: {
      status: "verified",
      hospitalVerified: true,
      platformVerified: true,
      documents: ["MD Degree Certificate", "Medical Council Registration", "AERB Compliance License"],
      pendingDocuments: [],
    },
    schedule: {
      dutyHours: "Mon–Sat · 08:00–16:00",
      emergencyOnCall: true,
      availability: "On Duty for CT/MRI and Emergency Trauma Studies",
    },
    publicProfile: {
      published: true,
      searchable: true,
    },
    todayAppointments: 14,
    totalPatients: 4210,
    rating: 4.9,
    consultationFee: 1500,
    verified: true,
    role: "Doctor",
    avatarUrl: "https://i.pravatar.cc/150?img=33",
  },
  {
    id: "doc_rad_02",
    name: "Dr. Sunita Kulkarni",
    email: "sunita.kulkarni@qlyno.health",
    phone: "+91 98202 77883",
    status: "active",
    createdAt: "2022-09-20",
    location: "Qlyno Multispecialty Hospital - Main Campus",
    specialty: "Radiology",
    subSpecialty: "Neuroradiology & Advanced MRI Diagnostics",
    qualification: "MD, DNB (Neuroradiology & MRI)",
    experienceYears: 18,
    registrationNo: "MMC-2008-03419",
    availability: "available",
    clinics: ["Qlyno 3.0T High-Field MRI Suite"],
    department: "Radiology",
    privileges: ["Neuro MRI Reporting", "Stroke Protocol Triage", "fMRI & DTI Analysis", "Critical Finding Escalation"],
    languages: ["English", "Hindi", "Marathi", "Kannada"],
    services: ["Neuroradiology Consult", "Brain MRI Second Opinion", "Spine & Neurovascular Diagnostics"],
    consultationSettings: {
      visitMode: "In-person",
      slotsPerDay: 18,
      emergencyOnCall: true,
      maxPatientsPerDay: 22,
    },
    verification: {
      status: "verified",
      hospitalVerified: true,
      platformVerified: true,
      documents: ["MD Degree Certificate", "DNB Board Certification", "MMC Registration"],
      pendingDocuments: [],
    },
    schedule: {
      dutyHours: "Mon–Fri · 09:00–17:00",
      emergencyOnCall: true,
      availability: "Lead Neuroradiologist on Duty",
    },
    publicProfile: {
      published: true,
      searchable: true,
    },
    todayAppointments: 11,
    totalPatients: 3890,
    rating: 4.9,
    consultationFee: 1800,
    verified: true,
    role: "Doctor",
    avatarUrl: "https://i.pravatar.cc/150?img=44",
  },
  {
    id: "doc_rad_03",
    name: "Dr. Arvind Rao",
    email: "arvind.rao@qlyno.health",
    phone: "+91 98203 11229",
    status: "active",
    createdAt: "2023-04-10",
    location: "Qlyno Multispecialty Hospital - Main Campus",
    specialty: "Radiology",
    subSpecialty: "Musculoskeletal & Ultrasound Diagnostics",
    qualification: "MD (Radiology), Fellowship in MSK Radiology",
    experienceYears: 11,
    registrationNo: "MMC-2015-09112",
    availability: "available",
    clinics: ["Qlyno Ultrasound & MSK Suite"],
    department: "Radiology",
    privileges: ["MSK Joint MRI", "USG Doppler Guided Procedures", "Emergency Sonography"],
    languages: ["English", "Hindi", "Telugu"],
    services: ["MSK Sports Injury MRI Review", "High-Resolution Ultrasound Diagnostics"],
    consultationSettings: {
      visitMode: "Hybrid",
      slotsPerDay: 15,
      emergencyOnCall: true,
      maxPatientsPerDay: 20,
    },
    verification: {
      status: "verified",
      hospitalVerified: true,
      platformVerified: true,
      documents: ["MD Degree Certificate", "Fellowship Certificate", "State Registration"],
      pendingDocuments: [],
    },
    schedule: {
      dutyHours: "Mon–Sat · 10:00–18:00",
      emergencyOnCall: true,
      availability: "On Call for Diagnostic Sonography & MSK Consults",
    },
    publicProfile: {
      published: true,
      searchable: true,
    },
    todayAppointments: 8,
    totalPatients: 2150,
    rating: 4.7,
    consultationFee: 1200,
    verified: true,
    role: "Doctor",
    avatarUrl: "https://i.pravatar.cc/150?img=59",
  },
];
