import {
  InsuranceClaim,
  InsurancePatientRecord,
  TpaProviderMetric,
  TpaProvider,
  ClaimStatus,
} from "@/hospital-admin/lib/types";

// ==========================================
// 1. EXTENDED CLAIMS DATASET
// ==========================================
export const mockExtendedInsuranceClaims: InsuranceClaim[] = [
  // PRE-AUTHORIZED (AWAITING DISCHARGE / FINAL CLAIM)
  {
    id: "clm_01",
    claimNo: "CLM-2026-STAR-9921",
    patientId: "P-8821",
    patientName: "Arjun Gupta",
    tpaProvider: "Star Health",
    policyNo: "STAR-COMP-9912048",
    admissionDate: "2026-08-18",
    admissionType: "IPD",
    claimAmount: 185000,
    approvedAmount: 157250, // 85%
    copayAmount: 27750,     // 15%
    status: "Pre-authorized",
    submissionDate: "2026-08-18T09:00:00Z",
    linkedInvoiceId: "INV-2026-IPD-409",
    queryNotes: "Initial cashless pre-auth approved for Total Knee Replacement package.",
  },
  {
    id: "clm_02",
    claimNo: "CLM-2026-HDFC-8812",
    patientId: "P-9102",
    patientName: "Kavita Patil",
    tpaProvider: "HDFC ERGO",
    policyNo: "HDFC-HEALTH-448102",
    admissionDate: "2026-08-20",
    admissionType: "IPD",
    claimAmount: 220000,
    approvedAmount: 187000, // 85%
    copayAmount: 33000,     // 15%
    status: "Pre-authorized",
    submissionDate: "2026-08-20T10:30:00Z",
    linkedInvoiceId: "INV-2026-IPD-9102",
    queryNotes: "Cashless pre-auth granted for CABG Open Heart Surgery.",
  },

  // SUBMITTED (INITIAL PRE-AUTH UNDER PROCESS)
  {
    id: "clm_03",
    claimNo: "CLM-2026-ICICI-4410",
    patientId: "P-1004",
    patientName: "Sunita Patel",
    tpaProvider: "ICICI Lombard",
    policyNo: "ICICI-HEALTH-9910",
    admissionDate: "2026-08-24",
    admissionType: "IPD",
    claimAmount: 95000,
    approvedAmount: 0,
    copayAmount: 0,
    status: "Submitted",
    submissionDate: "2026-08-24T14:00:00Z",
    queryNotes: "Initial cashless request submitted; awaiting Medical Scrutiny Team.",
  },
  {
    id: "clm_04",
    claimNo: "CLM-2026-MEDI-3391",
    patientId: "P-1011",
    patientName: "Bhavna Trivedi",
    tpaProvider: "Medi Assist",
    policyNo: "MEDI-CORP-491028",
    admissionDate: "2026-08-25",
    admissionType: "Day Care",
    claimAmount: 48000,
    approvedAmount: 0,
    copayAmount: 0,
    status: "Submitted",
    submissionDate: "2026-08-25T08:45:00Z",
    queryNotes: "Chemotherapy Day Care cycle cashless token lodged.",
  },

  // UNDER REVIEW (RESUBMITTED / QUERY RESPONSE SENT)
  {
    id: "clm_05",
    claimNo: "CLM-2026-VIDAL-7712",
    patientId: "P-1002",
    patientName: "Sita Devi",
    tpaProvider: "Vidal Health",
    policyNo: "VIDAL-PREM-88491",
    admissionDate: "2026-08-19",
    admissionType: "IPD",
    claimAmount: 135000,
    approvedAmount: 114750,
    copayAmount: 20250,
    status: "Under Review",
    submissionDate: "2026-08-19T11:00:00Z",
    queryNotes: "Resubmitted with attending physician certificate & surgical implant barcode breakdown.",
    rejectionReason: undefined,
  },
  {
    id: "clm_06",
    claimNo: "CLM-2026-CARE-2201",
    patientId: "P-1015",
    patientName: "Manoj Kumar",
    tpaProvider: "Care Health",
    policyNo: "CARE-SUPREME-1102",
    admissionDate: "2026-08-21",
    admissionType: "Emergency",
    claimAmount: 75000,
    approvedAmount: 63750,
    copayAmount: 11250,
    status: "Under Review",
    submissionDate: "2026-08-21T16:20:00Z",
    queryNotes: "Resubmitted with emergency admission clinical summary & toxicology screen.",
  },

  // REJECTED / DISPUTED
  {
    id: "clm_07",
    claimNo: "CLM-2026-PMJAY-1094",
    patientId: "P-1018",
    patientName: "Harish Iyer",
    tpaProvider: "PM-JAY Scheme",
    policyNo: "PMJAY-GOLD-MH-8821",
    admissionDate: "2026-08-15",
    admissionType: "IPD",
    claimAmount: 65000,
    approvedAmount: 0,
    copayAmount: 0,
    status: "Rejected",
    submissionDate: "2026-08-15T12:00:00Z",
    rejectionReason: "Pre-existing condition clause 4.2 cited; missing 2-year previous medical records history.",
    queryNotes: "Action needed: Upload historical OPD consultation cards & physician clearance statement.",
  },
  {
    id: "clm_08",
    claimNo: "CLM-2026-STAR-9944",
    patientId: "P-1022",
    patientName: "Pooja Hegde",
    tpaProvider: "Star Health",
    policyNo: "STAR-SENIOR-3301",
    admissionDate: "2026-08-17",
    admissionType: "IPD",
    claimAmount: 85000,
    approvedAmount: 0,
    copayAmount: 0,
    status: "Rejected",
    submissionDate: "2026-08-17T15:30:00Z",
    rejectionReason: "Discharge summary missing final histopathology biopsy report attachment.",
    queryNotes: "Awaiting final NABL signed lab biopsy report from Pathology.",
  },

  // SETTLED (PAYMENT RECEIVED IN BANK VIA NEFT/RTGS)
  {
    id: "clm_09",
    claimNo: "CLM-2026-HDFC-7701",
    patientId: "P-1001",
    patientName: "Ramesh Sharma",
    tpaProvider: "HDFC ERGO",
    policyNo: "HDFC-HEALTH-9912",
    admissionDate: "2026-08-10",
    admissionType: "IPD",
    claimAmount: 145000,
    approvedAmount: 145000,
    copayAmount: 0,
    status: "Settled",
    submissionDate: "2026-08-10T10:00:00Z",
    settlementDate: "2026-08-25T08:30:00Z",
    settlementUtr: "UTR-HDFC-N8849102847",
    linkedInvoiceId: "INV-2026-08-1042",
    queryNotes: "100% Cashless claim settled directly into hospital HDFC Master Account.",
  },
  {
    id: "clm_10",
    claimNo: "CLM-2026-CGHS-9910",
    patientId: "P-1031",
    patientName: "Nitin Gadkari Jr.",
    tpaProvider: "CGHS Scheme",
    policyNo: "CGHS-BENE-49210",
    admissionDate: "2026-08-08",
    admissionType: "IPD",
    claimAmount: 185000,
    approvedAmount: 185000,
    copayAmount: 0,
    status: "Settled",
    submissionDate: "2026-08-08T09:15:00Z",
    settlementDate: "2026-08-25T09:00:00Z",
    settlementUtr: "UTR-ICICI-N9910248102",
    linkedInvoiceId: "INV-2026-08-1043",
    queryNotes: "Government CGHS Super-Specialty package settled in full via RBI RTGS.",
  },
];

// ==========================================
// 2. PATIENT-CENTRIC INSURANCE REGISTRY
// ==========================================
export const mockInsurancePatients: InsurancePatientRecord[] = [
  {
    id: "insp_01",
    patientId: "P-8821",
    patientName: "Arjun Gupta",
    age: 58,
    gender: "Male",
    contactNo: "+91 98201 44921",
    tpaProvider: "Star Health",
    policyNo: "STAR-COMP-9912048",
    coverageType: "Comprehensive Cashless",
    totalSumInsured: 1000000,
    availableCoverage: 815000,
    primaryInsuredName: "Arjun Gupta (Self)",
    relationship: "Self",
    activeClaimsCount: 1,
    lastClaimDate: "2026-08-18",
  },
  {
    id: "insp_02",
    patientId: "P-9102",
    patientName: "Kavita Patil",
    age: 49,
    gender: "Female",
    contactNo: "+91 98332 11094",
    tpaProvider: "HDFC ERGO",
    policyNo: "HDFC-HEALTH-448102",
    coverageType: "Corporate Floater",
    totalSumInsured: 1500000,
    availableCoverage: 1280000,
    primaryInsuredName: "Sanjay Patil (Spouse)",
    relationship: "Spouse",
    activeClaimsCount: 1,
    lastClaimDate: "2026-08-20",
  },
  {
    id: "insp_03",
    patientId: "P-1002",
    patientName: "Sita Devi",
    age: 62,
    gender: "Female",
    contactNo: "+91 98401 22849",
    tpaProvider: "Vidal Health",
    policyNo: "VIDAL-PREM-88491",
    coverageType: "Senior Citizen Special",
    totalSumInsured: 750000,
    availableCoverage: 615000,
    primaryInsuredName: "Ramesh Sharma (Son)",
    relationship: "Mother",
    activeClaimsCount: 1,
    lastClaimDate: "2026-08-19",
  },
  {
    id: "insp_04",
    patientId: "P-1018",
    patientName: "Harish Iyer",
    age: 67,
    gender: "Male",
    contactNo: "+91 98210 99401",
    tpaProvider: "PM-JAY Scheme",
    policyNo: "PMJAY-GOLD-MH-8821",
    coverageType: "Government Scheme",
    totalSumInsured: 500000,
    availableCoverage: 435000,
    primaryInsuredName: "Harish Iyer (Head of Family)",
    relationship: "Self",
    activeClaimsCount: 1,
    lastClaimDate: "2026-08-15",
  },
  {
    id: "insp_05",
    patientId: "P-1031",
    patientName: "Nitin Gadkari Jr.",
    age: 42,
    gender: "Male",
    contactNo: "+91 98190 33812",
    tpaProvider: "CGHS Scheme",
    policyNo: "CGHS-BENE-49210",
    coverageType: "Government Scheme",
    totalSumInsured: 2000000,
    availableCoverage: 1815000,
    primaryInsuredName: "Nitin Gadkari Jr.",
    relationship: "Self",
    activeClaimsCount: 0,
    lastClaimDate: "2026-08-08",
  },
];

// ==========================================
// 3. TPA OPERATIONAL & ANALYTICS METRICS
// ==========================================
export const mockTpaProviderMetrics: TpaProviderMetric[] = [
  {
    provider: "Star Health",
    totalClaims: 142,
    approvedClaims: 128,
    rejectedClaims: 14,
    approvalRatio: 90.1,
    avgTatDays: 1.8,
    totalSettledAmount: 1840000,
    pendingClaimsCount: 6,
  },
  {
    provider: "HDFC ERGO",
    totalClaims: 118,
    approvedClaims: 110,
    rejectedClaims: 8,
    approvalRatio: 93.2,
    avgTatDays: 1.4,
    totalSettledAmount: 2150000,
    pendingClaimsCount: 4,
  },
  {
    provider: "ICICI Lombard",
    totalClaims: 96,
    approvedClaims: 88,
    rejectedClaims: 8,
    approvalRatio: 91.6,
    avgTatDays: 2.1,
    totalSettledAmount: 1420000,
    pendingClaimsCount: 5,
  },
  {
    provider: "Medi Assist",
    totalClaims: 84,
    approvedClaims: 76,
    rejectedClaims: 8,
    approvalRatio: 90.4,
    avgTatDays: 2.4,
    totalSettledAmount: 1180000,
    pendingClaimsCount: 3,
  },
  {
    provider: "PM-JAY Scheme",
    totalClaims: 64,
    approvedClaims: 58,
    rejectedClaims: 6,
    approvalRatio: 90.6,
    avgTatDays: 3.2,
    totalSettledAmount: 890000,
    pendingClaimsCount: 4,
  },
  {
    provider: "CGHS Scheme",
    totalClaims: 52,
    approvedClaims: 50,
    rejectedClaims: 2,
    approvalRatio: 96.1,
    avgTatDays: 2.8,
    totalSettledAmount: 940000,
    pendingClaimsCount: 2,
  },
];

export const mockRejectionReasonBreakdown = [
  { reason: "Missing Pre-Existing Medical History", count: 24, share: "38.0%" },
  { reason: "Missing Specific Diagnostic Biopsy/Lab Report", count: 18, share: "28.5%" },
  { reason: "Incomplete Attending Physician Certificate", count: 12, share: "19.0%" },
  { reason: "Tariff Package Room Rent Capping Dispute", count: 6, share: "9.5%" },
  { reason: "Non-Medical Item Surcharge Deduction", count: 3, share: "5.0%" },
];
