import {
  ConnectorHealthItem,
  WebhookEventLog,
  ApiKeyRecord,
  ABDMMilestoneStatus,
  IntegrationsAnalyticsSummary,
} from "@/hospital-admin/lib/types/integrations";

export const mockConnectors: ConnectorHealthItem[] = [
  // 1. WhatsApp
  {
    id: "conn-whatsapp",
    name: "Meta WhatsApp Cloud API Gateway",
    category: "WhatsApp",
    provider: "Meta Graph API (v19.0)",
    status: "Degraded",
    uptimePercentage: 98.4,
    latencyMs: 340,
    dailyQuotaUsed: 18420,
    dailyQuotaLimit: 50000,
    lastPingAt: "2026-08-30 19:42",
    endpointUrl: "https://graph.facebook.com/v19.0/9188200192/messages",
    failoverActive: true,
    failoverTarget: "Communication Hub (F23) SMS Gateway",
    securityProtocol: "TLS 1.3 • AES-256",
    signatureVerified: true,
    notes: "Meta Cloud API experiencing intermittent 5xx latency in Mumbai region. Failover to F23 SMS auto-triggered.",
  },

  // 2. Payment Gateway
  {
    id: "conn-razorpay",
    name: "Razorpay Webhook & Payment Gateway Switch",
    category: "Payment Gateway",
    provider: "Razorpay API / Webhook Daemon",
    status: "Healthy",
    uptimePercentage: 99.99,
    latencyMs: 82,
    dailyQuotaUsed: 1420,
    dailyQuotaLimit: 100000,
    lastPingAt: "2026-08-30 19:44",
    endpointUrl: "https://api.qlyno.com/webhooks/v1/razorpay",
    failoverActive: false,
    securityProtocol: "TLS 1.3 • HMAC-SHA256",
    signatureVerified: true,
    notes: "Signature validation active via X-Razorpay-Signature secret header.",
  },
  {
    id: "conn-upi-npci",
    name: "UPI Dynamic QR & Smart POS Switch",
    category: "Payment Gateway",
    provider: "NPCI / Yes Bank UPI Switch",
    status: "Healthy",
    uptimePercentage: 99.95,
    latencyMs: 65,
    dailyQuotaUsed: 3120,
    dailyQuotaLimit: 50000,
    lastPingAt: "2026-08-30 19:43",
    endpointUrl: "https://api.qlyno.com/webhooks/v1/upi-npci",
    failoverActive: false,
    securityProtocol: "mTLS • RSA-4096",
    signatureVerified: true,
  },

  // 3. Lab Integration
  {
    id: "conn-lis-sysmex",
    name: "Sysmex XN-1000 Hematology Analyzer Interfacing",
    category: "Lab Integration",
    provider: "Sysmex ASTM 1394-97 / Serial-IP",
    status: "Healthy",
    uptimePercentage: 99.98,
    latencyMs: 24,
    dailyQuotaUsed: 480,
    dailyQuotaLimit: 5000,
    lastPingAt: "2026-08-30 19:45",
    endpointUrl: "tcp://192.168.10.42:5000 (Internal LIS LAN)",
    failoverActive: false,
    securityProtocol: "Internal VLAN Isolation • IP Whitelist",
    signatureVerified: true,
    notes: "Bidirectional barcode query & auto-result upload into Lab (F13).",
  },
  {
    id: "conn-lis-cobas",
    name: "Roche Cobas 6000 Biochemistry Interfacing",
    category: "Lab Integration",
    provider: "Roche Diagnostics HL7 Interface Engine",
    status: "Healthy",
    uptimePercentage: 99.92,
    latencyMs: 38,
    dailyQuotaUsed: 620,
    dailyQuotaLimit: 5000,
    lastPingAt: "2026-08-30 19:41",
    endpointUrl: "mllp://192.168.10.45:2575 (Internal LIS MLLP)",
    failoverActive: false,
    securityProtocol: "Internal VLAN Isolation",
    signatureVerified: true,
  },
  {
    id: "conn-ext-drlal",
    name: "Dr. Lal PathLabs External Reference Network",
    category: "Lab Integration",
    provider: "Dr. Lal PathLabs B2B REST API",
    status: "Healthy",
    uptimePercentage: 99.85,
    latencyMs: 195,
    dailyQuotaUsed: 42,
    dailyQuotaLimit: 500,
    lastPingAt: "2026-08-30 19:30",
    endpointUrl: "https://b2b-api.lalpathlabs.com/v2/specimens",
    failoverActive: false,
    securityProtocol: "TLS 1.3 • OAuth 2.0 Bearer",
    signatureVerified: true,
  },

  // 4. Pharmacy
  {
    id: "conn-pharm-scanners",
    name: "Dispensing Counter Barcode & 2D Scanners (Counters 1-4)",
    category: "Pharmacy",
    provider: "Zebra DS2208 USB-HID / WebSocket Daemon",
    status: "Healthy",
    uptimePercentage: 99.99,
    latencyMs: 12,
    dailyQuotaUsed: 2150,
    dailyQuotaLimit: 20000,
    lastPingAt: "2026-08-30 19:45",
    endpointUrl: "ws://localhost:8088/scanner-hub",
    failoverActive: false,
    securityProtocol: "Local Loopback WSS",
    signatureVerified: true,
    notes: "GS1 DataMatrix batch & expiry scan verification active.",
  },
  {
    id: "conn-pharm-drugdb",
    name: "Medispan National Drug Code & Master Price Sync",
    category: "Pharmacy",
    provider: "Medispan / CIMS Healthcare API",
    status: "Healthy",
    uptimePercentage: 99.78,
    latencyMs: 210,
    dailyQuotaUsed: 140,
    dailyQuotaLimit: 1000,
    lastPingAt: "2026-08-30 18:00",
    endpointUrl: "https://api.medispan-india.com/v1/drugs",
    failoverActive: false,
    securityProtocol: "TLS 1.3 • API Key",
    signatureVerified: true,
    notes: "Schedule H1 & Narcotics compliance regulatory codes verified.",
  },

  // 5. Insurance / TPA
  {
    id: "conn-tpa-medibuddy",
    name: "MediBuddy TPA Clearinghouse Switch",
    category: "Insurance / TPA",
    provider: "MediBuddy Partner Gateway (v2.4)",
    status: "Healthy",
    uptimePercentage: 99.91,
    latencyMs: 140,
    dailyQuotaUsed: 94,
    dailyQuotaLimit: 1000,
    lastPingAt: "2026-08-30 19:35",
    endpointUrl: "https://partner-switch.medibuddy.in/v2/claims",
    failoverActive: false,
    securityProtocol: "TLS 1.3 • AES-GCM",
    signatureVerified: true,
  },
  {
    id: "conn-tpa-star",
    name: "Star Health Cashless Claims Clearinghouse",
    category: "Insurance / TPA",
    provider: "Star Health B2B Portal Gateway",
    status: "Healthy",
    uptimePercentage: 99.88,
    latencyMs: 175,
    dailyQuotaUsed: 68,
    dailyQuotaLimit: 1000,
    lastPingAt: "2026-08-30 19:28",
    endpointUrl: "https://api.starhealth.in/cashless/v1",
    failoverActive: false,
    securityProtocol: "TLS 1.3 • HMAC-SHA256",
    signatureVerified: true,
  },

  // 6. External Systems
  {
    id: "conn-abdm",
    name: "ABDM / ABHA National Health Authority Gateway",
    category: "External Systems",
    provider: "National Health Authority (NHA) NDHM Gateway",
    status: "Healthy",
    uptimePercentage: 99.94,
    latencyMs: 160,
    dailyQuotaUsed: 480,
    dailyQuotaLimit: 10000,
    lastPingAt: "2026-08-30 19:40",
    endpointUrl: "https://dev.abdm.gov.in/gateway/v0.5",
    failoverActive: false,
    securityProtocol: "mTLS • RSA-2048 • JWE Payload",
    signatureVerified: true,
    notes: "Milestones M1 (ABHA Creation), M2 (HIP Clinical Push), M3 (HIU Consent) fully certified.",
  },
  {
    id: "conn-hl7-fhir",
    name: "HL7 / FHIR R4 Interoperability Gateway",
    category: "External Systems",
    provider: "HAPI FHIR Enterprise Interoperability Engine",
    status: "Healthy",
    uptimePercentage: 99.96,
    latencyMs: 95,
    dailyQuotaUsed: 1240,
    dailyQuotaLimit: 25000,
    lastPingAt: "2026-08-30 19:43",
    endpointUrl: "https://fhir.qlyno.com/r4",
    failoverActive: false,
    securityProtocol: "TLS 1.3 • SMART on FHIR OAuth2",
    signatureVerified: true,
  },
  {
    id: "conn-pacs-dicom",
    name: "Radiology PACS DICOM C-STORE / C-FIND Router",
    category: "External Systems",
    provider: "Orthanc DICOM Server (Port 4242)",
    status: "Healthy",
    uptimePercentage: 99.99,
    latencyMs: 18,
    dailyQuotaUsed: 890,
    dailyQuotaLimit: 10000,
    lastPingAt: "2026-08-30 19:45",
    endpointUrl: "dicom://192.168.10.80:4242 (AET: QLYNO_PACS)",
    failoverActive: false,
    securityProtocol: "DICOM TLS • Internal Subnet",
    signatureVerified: true,
  },
  {
    id: "conn-gps-fleet",
    name: "Emergency Ambulance Fleet GPS & OBD-II Telemetry",
    category: "External Systems",
    provider: "Teltonika Telematics MQTT Broker",
    status: "Healthy",
    uptimePercentage: 99.92,
    latencyMs: 45,
    dailyQuotaUsed: 24500,
    dailyQuotaLimit: 100000,
    lastPingAt: "2026-08-30 19:45",
    endpointUrl: "mqtts://telemetry.qlyno.com:8883",
    failoverActive: false,
    securityProtocol: "MQTTS • TLS 1.3",
    signatureVerified: true,
  },
  {
    id: "conn-biometric-att",
    name: "Staff Biometric Attendance Terminal Gateway",
    category: "External Systems",
    provider: "eSSL SilkBio-101T Push Daemon",
    status: "Healthy",
    uptimePercentage: 99.89,
    latencyMs: 55,
    dailyQuotaUsed: 1890,
    dailyQuotaLimit: 10000,
    lastPingAt: "2026-08-30 19:40",
    endpointUrl: "http://192.168.10.95:8080/iclock/cdata",
    failoverActive: false,
    securityProtocol: "Internal Push Daemon",
    signatureVerified: true,
  },

  // 7. API
  {
    id: "conn-core-api",
    name: "Qlyno Core Hospital Enterprise API Ingress",
    category: "API",
    provider: "Kong API Gateway / Envoy Proxy",
    status: "Healthy",
    uptimePercentage: 99.99,
    latencyMs: 28,
    dailyQuotaUsed: 142800,
    dailyQuotaLimit: 1000000,
    lastPingAt: "2026-08-30 19:45",
    endpointUrl: "https://api.qlyno.com/v1",
    failoverActive: false,
    securityProtocol: "TLS 1.3 • WAF Protected",
    signatureVerified: true,
  },
];

export const mockWebhookEventLogs: WebhookEventLog[] = [
  {
    id: "LOG-EVT-901",
    idempotencyKey: "wamid_HBgMOTE4ODI4MDk5NDIVALFA99",
    source: "Meta Graph API (WhatsApp)",
    eventType: "messages.status: read",
    payloadHash: "sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    status: "Processed",
    responseCode: 200,
    processedAt: "2026-08-30 19:44:12",
    executionTimeMs: 14,
    payloadSummary: "Delivery confirmation for discharge summary reminder to +91 98200 11920",
  },
  {
    id: "LOG-EVT-902",
    idempotencyKey: "pay_N8zK19200a8F91",
    source: "Razorpay Webhook",
    eventType: "payment.captured",
    payloadHash: "sha256:4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
    status: "Processed",
    responseCode: 200,
    processedAt: "2026-08-30 19:43:08",
    executionTimeMs: 22,
    payloadSummary: "UPI payment of Rs. 4,500 captured for IPD Bill INV-2026-00412",
  },
  {
    id: "LOG-EVT-903",
    idempotencyKey: "pay_N8zK19200a8F91",
    source: "Razorpay Webhook (Retry)",
    eventType: "payment.captured",
    payloadHash: "sha256:4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
    status: "Duplicate Ignored (Idempotent)",
    responseCode: 200,
    processedAt: "2026-08-30 19:43:10",
    executionTimeMs: 4,
    payloadSummary: "Duplicate pay_id detected in redis idempotency cache. Ignored duplicate billing push.",
  },
  {
    id: "LOG-EVT-904",
    idempotencyKey: "claim_ref_MED-2026-88120",
    source: "MediBuddy TPA Switch",
    eventType: "claim.preauth_approved",
    payloadHash: "sha256:7bc12849e7b2fa10984cfb7218ac940e012fe7489a2b8e390c4217fa8290bc11",
    status: "Processed",
    responseCode: 200,
    processedAt: "2026-08-30 19:40:45",
    executionTimeMs: 38,
    payloadSummary: "Initial cashless pre-auth sanctioned for Rs. 1,50,000 (UHID: QLY-2026-0941)",
  },
  {
    id: "LOG-EVT-905",
    idempotencyKey: "astm_spec_LAL-998412",
    source: "Sysmex XN-1000 Analyzer",
    eventType: "analyzer.result_upload",
    payloadHash: "sha256:91c28f4410e4b81c20984f1837bc902e718af2901c84be7281094fa82901ba34",
    status: "Processed",
    responseCode: 200,
    processedAt: "2026-08-30 19:38:19",
    executionTimeMs: 18,
    payloadSummary: "Complete Blood Count (CBC) 18 parameters uploaded for Barcode #8841920",
  },
];

export const mockApiKeys: ApiKeyRecord[] = [
  {
    id: "KEY-LIVE-001",
    serviceName: "Hospital EMR & Core Billing Microservices",
    keyMasked: "qlyno_live_98a72b...4f91e",
    scope: "read:patients, write:billing, write:lab, webhook:receive",
    rateLimitPerMin: 2400,
    createdAt: "2026-01-10",
    lastRotatedAt: "2026-07-01",
    expiresAt: "2027-01-10",
    environment: "Production",
    isActive: true,
  },
  {
    id: "KEY-LIVE-002",
    serviceName: "Meta Cloud WhatsApp Webhook Listener",
    keyMasked: "meta_wh_sec_81bc42...9902a",
    scope: "webhook:whatsapp, read:telemetry",
    rateLimitPerMin: 1200,
    createdAt: "2026-03-15",
    lastRotatedAt: "2026-08-01",
    expiresAt: "2027-03-15",
    environment: "Production",
    isActive: true,
  },
  {
    id: "KEY-STAGING-003",
    serviceName: "ABDM Milestone Sandbox Connector",
    keyMasked: "abdm_sbx_1098fa...bc812",
    scope: "m1:create, m2:hip_push, m3:hiu_consent",
    rateLimitPerMin: 600,
    createdAt: "2026-05-20",
    lastRotatedAt: "2026-08-15",
    expiresAt: "2026-11-20",
    environment: "Staging Sandbox",
    isActive: true,
  },
];

export const mockABDMMilestones: ABDMMilestoneStatus[] = [
  {
    milestone: "M1",
    title: "ABHA Health ID Creation & Verification",
    description: "Enables patients to create and authenticate 14-digit ABHA numbers and link Aadhaar OTP verification.",
    status: "Certified & Active",
    lastAuditDate: "2026-02-14",
    registeredHipId: "IN-MH-HOSP-QLYNO-001",
    recordsPushedCount: 14820,
  },
  {
    milestone: "M2",
    title: "Health Information Provider (HIP) Clinical Push",
    description: "Pushes discharge summaries, diagnostic lab reports, and prescriptions securely to the patient's Personal Health Record (PHR) app.",
    status: "Certified & Active",
    lastAuditDate: "2026-04-10",
    registeredHipId: "IN-MH-HOSP-QLYNO-001",
    recordsPushedCount: 11250,
  },
  {
    milestone: "M3",
    title: "Health Information User (HIU) Consent Manager",
    description: "Requests digital patient consent to fetch external longitudinal medical history across previous healthcare providers.",
    status: "Certified & Active",
    lastAuditDate: "2026-06-25",
    registeredHipId: "IN-MH-HOSP-QLYNO-001",
    recordsPushedCount: 4120,
  },
];

export const mockIntegrationsAnalyticsSummary: IntegrationsAnalyticsSummary = {
  totalConnectedPipes: 16,
  healthyPipesCount: 15,
  degradedPipesCount: 1,
  dailyApiTrafficCalls: 142.8,
  averageLatencyMs: 124,
  webhookDeliveryRatePercent: 99.8,
  idempotencyCatchRatePercent: 100,
  activeFailoverCount: 1,
};
