import {
  InventoryItem,
  StockMovementRecord,
  StockAdjustmentRecord,
} from "@/hospital-admin/lib/types";

// ============================================================================
// EXTENDED INVENTORY CATALOG (Consumables & Medical Supplies)
// ============================================================================
export const mockInventoryCatalogExtended: InventoryItem[] = [
  {
    id: "inv_01",
    itemCode: "ITM-SURG-101",
    name: "Sterile Surgical Gloves (Size 7.5)",
    category: "Surgical Consumables",
    stockLevel: 1450,
    unit: "Pairs",
    reorderLevel: 500,
    leadTimeDays: 2,
    supplierName: "3M India Ltd.",
    unitCost: 45,
    status: "Adequate",
    expiryDate: "2028-04-30",
    batchNumber: "GLV-2408-A",
    isCritical: true,
    lastAuditDate: "2026-08-15",
  },
  {
    id: "inv_02",
    itemCode: "ITM-SURG-102",
    name: "Disposable Scalpel Blades No. 11",
    category: "Surgical Consumables",
    stockLevel: 180,
    unit: "Packs (100s)",
    reorderLevel: 250,
    leadTimeDays: 3,
    supplierName: "B. Braun Medical India",
    unitCost: 120,
    status: "Low Stock",
    expiryDate: "2029-01-15",
    batchNumber: "SCP-2402-X",
    isCritical: true,
    lastAuditDate: "2026-08-18",
  },
  {
    id: "inv_03",
    itemCode: "ITM-PPE-201",
    name: "N95 Surgical Respirator Masks (NIOSH)",
    category: "PPE & Hygiene",
    stockLevel: 3200,
    unit: "Pieces",
    reorderLevel: 1000,
    leadTimeDays: 2,
    supplierName: "3M India Ltd.",
    unitCost: 65,
    status: "Adequate",
    expiryDate: "2028-11-30",
    batchNumber: "N95-2407-M",
    isCritical: true,
    lastAuditDate: "2026-08-20",
  },
  {
    id: "inv_04",
    itemCode: "ITM-PPE-202",
    name: "Impervious Isolation Gowns (Fluid Resistant)",
    category: "PPE & Hygiene",
    stockLevel: 240,
    unit: "Packs (50s)",
    reorderLevel: 300,
    leadTimeDays: 4,
    supplierName: "Johnson & Johnson MedTech",
    unitCost: 350,
    status: "Low Stock",
    expiryDate: "2028-09-30",
    batchNumber: "GWN-2404-B",
    isCritical: false,
    lastAuditDate: "2026-08-12",
  },
  {
    id: "inv_05",
    itemCode: "ITM-DIAG-301",
    name: "Troponin I High-Sensitivity Test Reagent Kit",
    category: "Diagnostic Reagents",
    stockLevel: 45,
    unit: "Kits (50 Tests)",
    reorderLevel: 60,
    leadTimeDays: 5,
    supplierName: "Roche Diagnostics India",
    unitCost: 4500,
    status: "Low Stock",
    expiryDate: "2026-09-18", // < 30 Days (Critical Expiry)
    batchNumber: "TRP-24B-09",
    isCritical: true,
    lastAuditDate: "2026-08-22",
  },
  {
    id: "inv_06",
    itemCode: "ITM-DIAG-302",
    name: "ABG Cartridge Multi-Parameter Cassettes",
    category: "Diagnostic Reagents",
    stockLevel: 120,
    unit: "Cartridges",
    reorderLevel: 50,
    leadTimeDays: 3,
    supplierName: "Siemens Healthcare Pvt Ltd",
    unitCost: 850,
    status: "Adequate",
    expiryDate: "2026-10-25", // < 60 Days (Urgent Expiry)
    batchNumber: "ABG-24C-12",
    isCritical: true,
    lastAuditDate: "2026-08-21",
  },
  {
    id: "inv_07",
    itemCode: "ITM-WND-401",
    name: "Hydrocolloid Bio-Active Wound Dressing (10x10cm)",
    category: "Wound Care",
    stockLevel: 310,
    unit: "Boxes (10s)",
    reorderLevel: 120,
    leadTimeDays: 3,
    supplierName: "Smith & Nephew India",
    unitCost: 420,
    status: "Adequate",
    expiryDate: "2026-11-20", // < 90 Days (Advisory Expiry)
    batchNumber: "HYD-24D-03",
    isCritical: false,
    lastAuditDate: "2026-08-16",
  },
  {
    id: "inv_08",
    itemCode: "ITM-WND-402",
    name: "Sterile Gauze Bandage Rolls (15cm x 5m)",
    category: "Wound Care",
    stockLevel: 95,
    unit: "Packs (20s)",
    reorderLevel: 200,
    leadTimeDays: 2,
    supplierName: "Dentsply Sirona Healthcare",
    unitCost: 110,
    status: "Low Stock",
    expiryDate: "2029-06-30",
    batchNumber: "GAU-2401-K",
    isCritical: false,
    lastAuditDate: "2026-08-10",
  },
  {
    id: "inv_09",
    itemCode: "ITM-SUPP-501",
    name: "IV Cannula with Injection Port 20G (Pink)",
    category: "General Medical Supplies",
    stockLevel: 2800,
    unit: "Pieces",
    reorderLevel: 800,
    leadTimeDays: 2,
    supplierName: "B. Braun Medical India",
    unitCost: 28,
    status: "Adequate",
    expiryDate: "2028-12-31",
    batchNumber: "CAN-2406-P",
    isCritical: true,
    lastAuditDate: "2026-08-23",
  },
  {
    id: "inv_10",
    itemCode: "ITM-SUPP-502",
    name: "Endotracheal Tube Cuffed 7.5mm (Sterile)",
    category: "General Medical Supplies",
    stockLevel: 65,
    unit: "Pieces",
    reorderLevel: 150,
    leadTimeDays: 4,
    supplierName: "Medtronic India Pvt Ltd",
    unitCost: 320,
    status: "Low Stock",
    expiryDate: "2028-08-31",
    batchNumber: "ETT-2403-E",
    isCritical: true,
    lastAuditDate: "2026-08-24",
  },
];

// ============================================================================
// STOCK MOVEMENT LEDGER (Unified Append-Only Audit Trail)
// ============================================================================
export const mockStockMovements: StockMovementRecord[] = [
  {
    id: "mov_1001",
    itemId: "inv_01",
    itemCode: "ITM-SURG-101",
    itemName: "Sterile Surgical Gloves (Size 7.5)",
    category: "Surgical Consumables",
    type: "Indent Dispatch",
    direction: "OUT",
    quantity: 200,
    unit: "Pairs",
    sourceModule: "OT",
    referenceId: "IND-2026-0819",
    timestamp: "2026-08-26T09:30:00Z",
    performedBy: "Kiran Rao (Store Officer)",
    notes: "Dispatched to OT Suite 3 for morning cardiothoracic surgical schedule.",
  },
  {
    id: "mov_1002",
    itemId: "inv_05",
    itemCode: "ITM-DIAG-301",
    itemName: "Troponin I High-Sensitivity Test Reagent Kit",
    category: "Diagnostic Reagents",
    type: "Indent Dispatch",
    direction: "OUT",
    quantity: 15,
    unit: "Kits (50 Tests)",
    sourceModule: "Emergency",
    referenceId: "IND-2026-0820",
    timestamp: "2026-08-26T08:15:00Z",
    performedBy: "Kiran Rao (Store Officer)",
    notes: "Urgent replenishment for Emergency Triage Pathology Station.",
  },
  {
    id: "mov_1003",
    itemId: "inv_03",
    itemCode: "ITM-PPE-201",
    itemName: "N95 Surgical Respirator Masks (NIOSH)",
    category: "PPE & Hygiene",
    type: "Procurement Delivery",
    direction: "IN",
    quantity: 1000,
    unit: "Pieces",
    sourceModule: "Procurement",
    referenceId: "PO-2026-9912",
    timestamp: "2026-08-25T14:45:00Z",
    performedBy: "Anand Sen (Receiving Dock Manager)",
    notes: "Goods Receipt Note #GRN-4421 verified from 3M India shipment.",
  },
  {
    id: "mov_1004",
    itemId: "inv_02",
    itemCode: "ITM-SURG-102",
    itemName: "Disposable Scalpel Blades No. 11",
    category: "Surgical Consumables",
    type: "Stock Adjustment",
    direction: "OUT",
    quantity: 20,
    unit: "Packs (100s)",
    sourceModule: "Physical Audit",
    referenceId: "ADJ-2026-0041",
    timestamp: "2026-08-25T11:20:00Z",
    performedBy: "Vikram Sengupta (Audit Lead)",
    notes: "Write-off: Damage - Box dropped and packaging seal ruptured during forklift transfer.",
  },
  {
    id: "mov_1005",
    itemId: "inv_09",
    itemCode: "ITM-SUPP-501",
    itemName: "IV Cannula with Injection Port 20G (Pink)",
    category: "General Medical Supplies",
    type: "Indent Dispatch",
    direction: "OUT",
    quantity: 300,
    unit: "Pieces",
    sourceModule: "ICU",
    referenceId: "IND-2026-0814",
    timestamp: "2026-08-24T16:00:00Z",
    performedBy: "Kiran Rao (Store Officer)",
    notes: "Regular weekly ward restock for MICU/SICU.",
  },
  {
    id: "mov_1006",
    itemId: "inv_07",
    itemCode: "ITM-WND-401",
    itemName: "Hydrocolloid Bio-Active Wound Dressing (10x10cm)",
    category: "Wound Care",
    type: "Sales Return",
    direction: "IN",
    quantity: 10,
    unit: "Boxes (10s)",
    sourceModule: "Pharmacy",
    referenceId: "RET-2026-0119",
    timestamp: "2026-08-24T10:10:00Z",
    performedBy: "Sunita Deshmukh (Pharmacist)",
    notes: "Post-op ward unconsumed dressings returned to Central Store intact.",
  },
  {
    id: "mov_1007",
    itemId: "inv_10",
    itemCode: "ITM-SUPP-502",
    itemName: "Endotracheal Tube Cuffed 7.5mm (Sterile)",
    category: "General Medical Supplies",
    type: "Stock Adjustment",
    direction: "IN",
    quantity: 15,
    unit: "Pieces",
    sourceModule: "Physical Audit",
    referenceId: "ADJ-2026-0039",
    timestamp: "2026-08-23T15:30:00Z",
    performedBy: "Vikram Sengupta (Audit Lead)",
    notes: "Positive Adjustment: 15 sealed units found in Auxiliary Staging Bay B during annual inventory count.",
  },
];

// ============================================================================
// STOCK ADJUSTMENTS AUDIT TRAIL
// ============================================================================
export const mockStockAdjustments: StockAdjustmentRecord[] = [
  {
    id: "adj_01",
    adjustmentNo: "ADJ-2026-0041",
    itemId: "inv_02",
    itemCode: "ITM-SURG-102",
    itemName: "Disposable Scalpel Blades No. 11",
    category: "Surgical Consumables",
    adjustmentType: "Write-off: Damage",
    previousStock: 200,
    adjustedStock: 180,
    variance: -20,
    unit: "Packs (100s)",
    unitCost: 120,
    totalVarianceValue: 2400,
    reason: "Water damage occurred to secondary packaging carton during HVAC pipe maintenance in Store Room 2. Items discarded per infection control protocol.",
    authorizedBy: "Vikram Sengupta (Hospital Admin)",
    timestamp: "2026-08-25T11:20:00Z",
    requiresDualApproval: false,
    approvalStatus: "Approved",
    notes: "Infection Control Clearance Certificate #ICC-2026-881 attached.",
  },
  {
    id: "adj_02",
    adjustmentNo: "ADJ-2026-0039",
    itemId: "inv_10",
    itemCode: "ITM-SUPP-502",
    itemName: "Endotracheal Tube Cuffed 7.5mm (Sterile)",
    category: "General Medical Supplies",
    adjustmentType: "Positive Adjustment",
    previousStock: 50,
    adjustedStock: 65,
    variance: 15,
    unit: "Pieces",
    unitCost: 320,
    totalVarianceValue: 4800,
    reason: "15 unrecorded sealed units discovered in Auxiliary Staging Bay B during bi-annual physical reconciliation count.",
    authorizedBy: "Vikram Sengupta (Hospital Admin)",
    timestamp: "2026-08-23T15:30:00Z",
    requiresDualApproval: false,
    approvalStatus: "Approved",
    notes: "Count reconciled with procurement batch PO-2026-8802.",
  },
  {
    id: "adj_03",
    adjustmentNo: "ADJ-2026-0038",
    itemId: "inv_08",
    itemCode: "ITM-WND-402",
    itemName: "Sterile Gauze Bandage Rolls (15cm x 5m)",
    category: "Wound Care",
    adjustmentType: "Physical Count Correction",
    previousStock: 110,
    adjustedStock: 95,
    variance: -15,
    unit: "Packs (20s)",
    unitCost: 110,
    totalVarianceValue: 1650,
    reason: "Variance identified during monthly cycle count; 15 packs were issued during Emergency Mass Casualty drill without electronic barcode scan.",
    authorizedBy: "Vikram Sengupta (Hospital Admin)",
    timestamp: "2026-08-21T17:00:00Z",
    requiresDualApproval: false,
    approvalStatus: "Approved",
    notes: "Mass Casualty Incident Drill #MCI-2026-02 log reconciled.",
  },
  {
    id: "adj_04",
    adjustmentNo: "ADJ-2026-0035",
    itemId: "inv_05",
    itemCode: "ITM-DIAG-301",
    itemName: "Troponin I High-Sensitivity Test Reagent Kit",
    category: "Diagnostic Reagents",
    adjustmentType: "Write-off: Expiry",
    previousStock: 52,
    adjustedStock: 45,
    variance: -7,
    unit: "Kits (50 Tests)",
    unitCost: 4500,
    totalVarianceValue: 31500, // > ₹25,000 High Value
    reason: "7 reagent kits expired on 2026-08-15 following cold-chain temperature excursion in Pathology Refrigerator #3.",
    authorizedBy: "Dr. Meenakshi Joshi (Medical Director)",
    timestamp: "2026-08-16T14:30:00Z",
    requiresDualApproval: true,
    approvalStatus: "Approved",
    notes: "High-value write-off dual-authorized by Medical Director & Finance Head.",
  },
];
