import { Invoice, DiscountType, RefundRecord } from "@/hospital-admin/lib/types";

export const discountTypesRegistry: DiscountType[] = [
  {
    id: "DISC-01",
    name: "Senior Citizen Concession (60+ Years)",
    category: "Senior Citizen",
    defaultPercentage: 15,
    eligibilityCriteria: "Age 60+ with valid Aadhar / Senior ID proof",
    requiresSupervisorApproval: false,
    isActive: true,
  },
  {
    id: "DISC-02",
    name: "Hospital Staff & Immediate Dependent",
    category: "Staff Discount",
    defaultPercentage: 25,
    eligibilityCriteria: "Active Qlyno Hospital Employee ID & HR Verification",
    requiresSupervisorApproval: true,
    isActive: true,
  },
  {
    id: "DISC-03",
    name: "Corporate / TPA Preferred Partner Rate",
    category: "Corporate / Insurance Rate",
    defaultPercentage: 10,
    eligibilityCriteria: "Empanelled Corporate ID or Star Health / HDFC Ergo Card",
    requiresSupervisorApproval: false,
    isActive: true,
  },
  {
    id: "DISC-04",
    name: "Community Health Camp Outreach Voucher",
    category: "Promotional Camp",
    defaultPercentage: 20,
    eligibilityCriteria: "Valid physical token from Qlyno Free Screening Camp",
    requiresSupervisorApproval: false,
    isActive: true,
  },
  {
    id: "DISC-05",
    name: "Compassionate / Charity Medical Relief Waiver",
    category: "Compassionate Waiver",
    defaultPercentage: 100,
    eligibilityCriteria: "Medical Superintendent & Trust Board Approval",
    requiresSupervisorApproval: true,
    isActive: true,
  },
];

export const refundRequestsQueue: RefundRecord[] = [
  {
    id: "REF-001",
    invoiceId: "inv_005",
    invoiceNo: "INV-2026-06-0771",
    patientName: "Sunita Reddy",
    amount: 4100,
    reason: "Procedure cancelled due to sudden allergic reaction before local anesthesia",
    reasonCategory: "Clinical Cancellation",
    requestedBy: "Sneha Patil (Refund Desk)",
    approvedBy: "Hospital Admin (Supervisor)",
    status: "Processed",
    timestamp: "2026-08-20T14:30:00Z",
    paymentMode: "Original Mode",
  },
  {
    id: "REF-002",
    invoiceId: "inv_002",
    invoiceNo: "INV-2026-08-1043",
    patientName: "Meera Nambiar",
    amount: 1400,
    reason: "Duplicate lab panel payment recorded by mistake at Counter 1",
    reasonCategory: "Duplicate Payment",
    requestedBy: "Rohit Kadam (OPD Cashier)",
    approvedBy: "Hospital Admin (Supervisor)",
    status: "Approved",
    timestamp: "2026-08-21T11:15:00Z",
    paymentMode: "Bank Transfer",
  },
  {
    id: "REF-003",
    invoiceId: "inv_009",
    invoiceNo: "INV-2026-08-1070",
    patientName: "Vikram Jadhav",
    amount: 8500,
    reason: "Patient discharged early before 2nd MRI contrast scan completed",
    reasonCategory: "Clinical Cancellation",
    requestedBy: "Meenakshi Sundaram (IPD Cashier)",
    status: "Requested",
    timestamp: "2026-08-22T09:40:00Z",
    paymentMode: "Original Mode",
  },
];

export const invoices: Invoice[] = [
  // 1. IPD INPATIENT WITH SURGICAL IMPLANT PULL-THROUGH & INTERIM DEPOSITS
  {
    id: "inv_ipd_409",
    invoiceNo: "INV-2026-IPD-409",
    patientName: "Arjun Gupta",
    patientId: "P-8821",
    service: "Total Knee Replacement (TKR) — Inpatient Surgical Package",
    encounterType: "IPD",
    serviceCategory: "Surgery",
    department: "Orthopedics",
    doctorName: "Dr. Ramesh Sharma",
    subtotal: 185000,
    taxAmount: 0,
    amount: 185000,
    paid: 185000,
    outstanding: 0,
    status: "paid",
    issuedOn: "2026-08-18",
    method: "Card",
    linkedCaseId: "CASE-409",
    linkedProcurementItemIds: ["PR-1002"],
    dischargeCleared: true,
    lineItems: [
      {
        id: "li-01",
        name: "Titanium Femoral Stem (Size 12 Standard) — Pulled from Procurement PR-1002",
        category: "Surgery",
        sacCode: "999312",
        quantity: 1,
        unitPrice: 85000,
        taxRate: 0,
        total: 85000,
        procurementItemId: "PR-1002",
      },
      {
        id: "li-02",
        name: "Operation Theatre (OT) 3-Hour Suite Charges & Laminar Airflow",
        category: "Surgery",
        sacCode: "999311",
        quantity: 1,
        unitPrice: 35000,
        taxRate: 0,
        total: 35000,
      },
      {
        id: "li-03",
        name: "Lead Surgeon & Anesthetist Operating Clinical Fees",
        category: "Surgery",
        sacCode: "999311",
        quantity: 1,
        unitPrice: 45000,
        taxRate: 0,
        total: 45000,
      },
      {
        id: "li-04",
        name: "Orthopedic Post-Op Inpatient Bed Charges (4 Days @ ₹5,000/day)",
        category: "Bed Charges",
        sacCode: "999314",
        quantity: 4,
        unitPrice: 5000,
        taxRate: 0,
        total: 20000,
      },
    ],
    interimDeposits: [
      {
        id: "dep-01",
        amount: 50000,
        date: "2026-08-18",
        mode: "Card",
        receiptNo: "REC-IPD-8801",
        cashierName: "Meenakshi Sundaram",
        notes: "Initial Admission Interim Deposit",
      },
      {
        id: "dep-02",
        amount: 85000,
        date: "2026-08-20",
        mode: "UPI",
        receiptNo: "REC-IPD-8824",
        cashierName: "Meenakshi Sundaram",
        notes: "Mid-Stay Implant & OT Advance",
      },
      {
        id: "dep-03",
        amount: 50000,
        date: "2026-08-21",
        mode: "Card",
        receiptNo: "REC-IPD-8849",
        cashierName: "Meenakshi Sundaram",
        notes: "Discharge Balance Clearance",
      },
    ],
  },

  // 2. IPD ACTIVE RUNNING BILL (PARTIALLY PAID / INTERIM DEPOSITS)
  {
    id: "inv_ipd_9102",
    invoiceNo: "INV-2026-IPD-9102",
    patientName: "Kavita Patil",
    patientId: "P-9102",
    service: "Neurosurgery Cranial Decompression & ICU Care",
    encounterType: "IPD",
    serviceCategory: "Surgery",
    department: "Neurology",
    doctorName: "Dr. Kavita Verma",
    subtotal: 240000,
    taxAmount: 0,
    amount: 240000,
    paid: 100000,
    outstanding: 140000,
    status: "partially-paid",
    issuedOn: "2026-08-19",
    method: "Insurance",
    linkedCaseId: "CASE-410",
    dischargeCleared: false,
    lineItems: [
      {
        id: "li-11",
        name: "Microscope & Cranial Suite High-Acuity OT Charges",
        category: "Surgery",
        sacCode: "999311",
        quantity: 1,
        unitPrice: 65000,
        taxRate: 0,
        total: 65000,
      },
      {
        id: "li-12",
        name: "ICU Ventilator Monitoring & Bed Charges (3 Days @ ₹15,000/day)",
        category: "Bed Charges",
        sacCode: "999314",
        quantity: 3,
        unitPrice: 15000,
        taxRate: 0,
        total: 45000,
      },
      {
        id: "li-13",
        name: "Neuro Specialist Surgical & PACU Team Fees",
        category: "Surgery",
        sacCode: "999311",
        quantity: 1,
        unitPrice: 80000,
        taxRate: 0,
        total: 80000,
      },
      {
        id: "li-14",
        name: "Pharmacy Critical IV Infusions & Mannitol",
        category: "Pharmacy",
        sacCode: "999315",
        quantity: 1,
        unitPrice: 50000,
        taxRate: 0,
        total: 50000,
      },
    ],
    interimDeposits: [
      {
        id: "dep-11",
        amount: 100000,
        date: "2026-08-19",
        mode: "Insurance",
        receiptNo: "REC-IPD-8812",
        cashierName: "Vikram Jadhav",
        notes: "TPA Pre-Auth Interim Approval (Star Health)",
      },
    ],
  },

  // 3. OPD CONSULTATION WITH SENIOR CITIZEN DISCOUNT
  {
    id: "inv_001",
    invoiceNo: "INV-2026-08-1042",
    patientName: "Aarav Shah",
    patientId: "pat_001",
    service: "Senior Comprehensive Cardiology Consultation",
    encounterType: "OPD",
    serviceCategory: "Consultation",
    department: "Cardiology",
    doctorName: "Dr. Ananya Patel",
    subtotal: 1400,
    taxAmount: 0,
    amount: 1200,
    paid: 1200,
    outstanding: 0,
    status: "paid",
    issuedOn: "2026-08-06",
    method: "UPI",
    discount: {
      typeId: "DISC-01",
      typeName: "Senior Citizen Concession (60+ Years)",
      percentage: 15,
      flatAmount: 200,
      appliedBy: "Rohit Kadam (OPD Cashier)",
      status: "Applied",
      appliedAt: "2026-08-06T10:15:00Z",
    },
    lineItems: [
      {
        id: "li-21",
        name: "Specialist Senior Cardiologist Consultation",
        category: "Consultation",
        sacCode: "999311",
        quantity: 1,
        unitPrice: 1000,
        taxRate: 0,
        total: 1000,
      },
      {
        id: "li-22",
        name: "12-Lead Electrocardiogram (ECG) Tracing",
        category: "Diagnostics",
        sacCode: "999313",
        quantity: 1,
        unitPrice: 400,
        taxRate: 0,
        total: 400,
      },
    ],
  },

  // 4. OPD PRENATAL CONSULTATION & ULTRASOUND
  {
    id: "inv_002",
    invoiceNo: "INV-2026-08-1043",
    patientName: "Meera Nambiar",
    patientId: "pat_002",
    service: "Prenatal Consultation + 4D Ultrasound Scan",
    encounterType: "OPD",
    serviceCategory: "Diagnostics",
    department: "Obstetrics & Gynecology",
    doctorName: "Dr. Sunita Patel",
    subtotal: 3400,
    taxAmount: 0,
    amount: 3400,
    paid: 2000,
    outstanding: 1400,
    status: "partially-paid",
    issuedOn: "2026-08-11",
    method: "Card",
    lineItems: [
      {
        id: "li-31",
        name: "Senior Obstetrician Clinical Consultation",
        category: "Consultation",
        sacCode: "999311",
        quantity: 1,
        unitPrice: 1200,
        taxRate: 0,
        total: 1200,
      },
      {
        id: "li-32",
        name: "Fetal Doppler & 4D Obstetric Ultrasound Imaging",
        category: "Diagnostics",
        sacCode: "999313",
        quantity: 1,
        unitPrice: 2200,
        taxRate: 0,
        total: 2200,
      },
    ],
  },

  // 5. LAB DIAGNOSTIC INVOICE (PATHOLOGY PANEL)
  {
    id: "inv_003",
    invoiceNo: "INV-2026-07-0988",
    patientName: "Ibrahim Sheikh",
    patientId: "pat_003",
    service: "Complete Diabetes Panel + HbA1c + Lipid Profile",
    encounterType: "OPD",
    serviceCategory: "Diagnostics",
    department: "Laboratory",
    doctorName: "Dr. Arvind Swaminathan",
    subtotal: 3200,
    taxAmount: 0,
    amount: 3200,
    paid: 0,
    outstanding: 3200,
    status: "issued",
    issuedOn: "2026-07-28",
    lineItems: [
      {
        id: "li-41",
        name: "Glycated Hemoglobin (HbA1c Automated HPLC)",
        category: "Diagnostics",
        sacCode: "999313",
        quantity: 1,
        unitPrice: 800,
        taxRate: 0,
        total: 800,
      },
      {
        id: "li-42",
        name: "Complete Lipid Profile (Cholesterol, HDL, LDL, Triglycerides)",
        category: "Diagnostics",
        sacCode: "999313",
        quantity: 1,
        unitPrice: 1200,
        taxRate: 0,
        total: 1200,
      },
      {
        id: "li-43",
        name: "Renal & Liver Function Test Panels",
        category: "Diagnostics",
        sacCode: "999313",
        quantity: 1,
        unitPrice: 1200,
        taxRate: 0,
        total: 1200,
      },
    ],
  },

  // 6. PHARMACY DISPENSED PRESCRIPTION INVOICE
  {
    id: "inv_pharm_104",
    invoiceNo: "INV-2026-PHARM-104",
    patientName: "Rohan Verma",
    patientId: "SOS-104",
    service: "Emergency Pharmacy Dispensing — Acute Bronchodilators",
    encounterType: "Emergency",
    serviceCategory: "Pharmacy",
    department: "Pharmacy",
    doctorName: "Dr. Rohan Mehta",
    subtotal: 2150,
    taxAmount: 0,
    amount: 2150,
    paid: 2150,
    outstanding: 0,
    status: "paid",
    issuedOn: "2026-08-21",
    method: "UPI",
    lineItems: [
      {
        id: "li-51",
        name: "Nebulizer Respules Salbutamol + Ipratropium (Pack of 5)",
        category: "Pharmacy",
        sacCode: "999315",
        quantity: 2,
        unitPrice: 450,
        taxRate: 0,
        total: 900,
      },
      {
        id: "li-52",
        name: "Hydrocortisone Sodium Succinate 100mg IV Vials",
        category: "Pharmacy",
        sacCode: "999315",
        quantity: 3,
        unitPrice: 250,
        taxRate: 0,
        total: 750,
      },
      {
        id: "li-53",
        name: "Metered Dose Inhaler Budesonide 200mcg",
        category: "Pharmacy",
        sacCode: "999315",
        quantity: 1,
        unitPrice: 500,
        taxRate: 0,
        total: 500,
      },
    ],
  },

  // 7. CANCELLED / REFUNDED INVOICE
  {
    id: "inv_005",
    invoiceNo: "INV-2026-06-0771",
    patientName: "Sunita Reddy",
    patientId: "pat_005",
    service: "Dermatology Cryotherapy + Biopsy Procedure",
    encounterType: "Daycare",
    serviceCategory: "Surgery",
    department: "Dermatology",
    doctorName: "Dr. Ananya Patel",
    subtotal: 4100,
    taxAmount: 0,
    amount: 4100,
    paid: 0,
    outstanding: 0,
    status: "refunded",
    issuedOn: "2026-06-30",
    method: "Insurance",
    refunds: [
      {
        id: "REF-001",
        invoiceId: "inv_005",
        invoiceNo: "INV-2026-06-0771",
        patientName: "Sunita Reddy",
        amount: 4100,
        reason: "Procedure cancelled due to sudden allergic reaction before local anesthesia",
        reasonCategory: "Clinical Cancellation",
        requestedBy: "Sneha Patil (Refund Desk)",
        approvedBy: "Hospital Admin (Supervisor)",
        status: "Processed",
        timestamp: "2026-08-20T14:30:00Z",
        paymentMode: "Original Mode",
      },
    ],
  },
];
