import {
  LabOrder,
  SampleCollectionTask,
  ExternalLabReport,
  LabTestCatalogItem,
  AnalyzerRegistryItem,
  CriticalThresholdItem,
  RejectionReasonItem,
} from "@/hospital-admin/lib/types";

// ==========================================
// 1. MASTER EXTENDED LAB ORDERS (Single Source of Truth)
// ==========================================
export const mockExtendedLabOrders: LabOrder[] = [
  {
    id: "lab_01",
    orderNo: "LAB-2026-9001",
    patientId: "P-1001",
    patientName: "Ramesh Sharma",
    uhid: "UHID-2026-1001",
    age: 54,
    gender: "Male",
    test: "Complete Blood Count (CBC) with Automated Differential",
    department: "Hematology",
    orderingDoctor: "Dr. Arvind Swaminathan",
    source: "IPD",
    priority: "Stat",
    sampleType: "Whole Blood (EDTA - Lavender Top)",
    sampleId: "SAMP-EDTA-88210",
    patientLocation: "ICU - Bed 03",
    status: "processing",
    orderedOn: "2026-08-22T08:30:00Z",
    tat: "45 mins remaining",
    critical: false,
    assignedCollector: "Phleb. Santosh Kumar",
    collectedAt: "2026-08-22T08:45:00Z",
    assignedAnalyzer: "Sysmex XN-1000 Automated Hematology System",
    expectedCompletionTime: "2026-08-22T09:45:00Z",
    tariffId: "TAR-LAB-CBC",
    price: 450,
  },
  {
    id: "lab_02",
    orderNo: "LAB-2026-9002",
    patientId: "P-9102",
    patientName: "Kavita Patil",
    uhid: "UHID-2026-9102",
    age: 48,
    gender: "Female",
    test: "Serum Electrolytes Panel (Na, K, Cl, HCO3)",
    department: "Biochemistry",
    orderingDoctor: "Dr. Kavita Verma",
    source: "Emergency",
    priority: "Stat",
    sampleType: "Serum (SST - Gold Top)",
    sampleId: "SAMP-SST-99102",
    patientLocation: "Emergency Bay 02 (Trauma)",
    status: "awaiting-validation",
    orderedOn: "2026-08-22T07:15:00Z",
    tat: "Awaiting Pathologist Sign-Off",
    critical: true,
    criticalDetails: "Serum Potassium: 6.8 mEq/L (Critical High / Hyperkalemia). Acute cardiac arrhythmia risk.",
    assignedCollector: "Phleb. Priya Sharma",
    collectedAt: "2026-08-22T07:25:00Z",
    assignedAnalyzer: "Beckman Coulter DxC 700 AU Chemistry Analyzer",
    expectedCompletionTime: "2026-08-22T08:15:00Z",
    tariffId: "TAR-LAB-ELEC",
    price: 650,
    clinicianNotified: true,
    acknowledgedBy: "Dr. Ananya Patel (Emergency In-Charge)",
    acknowledgedAt: "2026-08-22T08:00:00Z",
  },
  {
    id: "lab_03",
    orderNo: "LAB-2026-9003",
    patientId: "P-8821",
    patientName: "Arjun Gupta",
    uhid: "UHID-2026-8821",
    age: 36,
    gender: "Male",
    test: "Coagulation Profile: PT / INR & aPTT",
    department: "Hematology & Coagulation",
    orderingDoctor: "Dr. Ramesh Sharma (Orthopedic Surgeon)",
    source: "OT",
    priority: "Routine",
    sampleType: "Citrated Plasma (Light Blue Top)",
    sampleId: "SAMP-CIT-44102",
    patientLocation: "Pre-Op Holding Bay 1",
    status: "released",
    orderedOn: "2026-08-21T16:00:00Z",
    tat: "Completed",
    critical: false,
    assignedCollector: "Phleb. Santosh Kumar",
    collectedAt: "2026-08-21T16:20:00Z",
    assignedAnalyzer: "Stago Compact Max Coagulation System",
    verifiedBy: "Dr. Sunita Kulkarni (Consultant Pathologist)",
    verifiedAt: "2026-08-21T18:00:00Z",
    tariffId: "TAR-LAB-COAG",
    price: 800,
    reportUrl: "/lab/lab_03",
  },
  {
    id: "lab_04",
    orderNo: "LAB-2026-9004",
    patientId: "P-4001",
    patientName: "Anil Kapoor",
    uhid: "UHID-2026-4001",
    age: 62,
    gender: "Male",
    test: "High-Sensitivity Cardiac Troponin-I (hs-cTnI)",
    department: "Immunoassay",
    orderingDoctor: "Dr. Ananya Patel",
    source: "Emergency",
    priority: "Stat",
    sampleType: "Heparinized Plasma (Green Top)",
    sampleId: "SAMP-HEP-10293",
    patientLocation: "Emergency Bay 01 (Resuscitation)",
    status: "sample-pending",
    orderedOn: "2026-08-22T08:50:00Z",
    tat: "Pending Collection",
    critical: true,
    criticalDetails: "Rule-out Acute Myocardial Infarction. Stat collection required.",
    tariffId: "TAR-LAB-TROP",
    price: 1200,
  },
  {
    id: "lab_05",
    orderNo: "LAB-2026-9005",
    patientId: "P-5001",
    patientName: "Tariq Mansoor",
    uhid: "UHID-2026-5001",
    age: 41,
    gender: "Male",
    test: "Glycated Hemoglobin (HbA1c) by HPLC Method",
    department: "Biochemistry",
    orderingDoctor: "Dr. Rohan Mehta",
    source: "OPD",
    priority: "Routine",
    sampleType: "Whole Blood (EDTA - Lavender Top)",
    sampleId: "SAMP-EDTA-30192",
    patientLocation: "OPD Consultation Desk 102",
    status: "sample-pending",
    orderedOn: "2026-08-22T08:40:00Z",
    tat: "Pending Collection",
    critical: false,
    tariffId: "TAR-LAB-HBA1C",
    price: 550,
  },
  {
    id: "lab_06",
    orderNo: "LAB-2026-9006",
    patientId: "P-6001",
    patientName: "Meera Nair",
    uhid: "UHID-2026-6001",
    age: 29,
    gender: "Female",
    test: "Liver Function Test (LFT) with Enzymes & Bilirubin",
    department: "Biochemistry",
    orderingDoctor: "Dr. Ananya Patel",
    source: "IPD",
    priority: "Routine",
    sampleType: "Serum (SST - Gold Top)",
    sampleId: "SAMP-SST-77102",
    patientLocation: "General Ward A - Bed 04",
    status: "rejected",
    orderedOn: "2026-08-21T14:00:00Z",
    tat: "Sample Rejected - Re-dispatch Required",
    critical: false,
    assignedCollector: "Phleb. Priya Sharma",
    collectedAt: "2026-08-21T14:30:00Z",
    tariffId: "TAR-LAB-LFT",
    price: 750,
  },
];

// ==========================================
// 2. SAMPLE COLLECTION TASKS
// ==========================================
export const mockSampleCollectionTasks: SampleCollectionTask[] = [
  {
    taskId: "TASK-COL-101",
    orderId: "lab_04",
    patientName: "Anil Kapoor",
    uhid: "UHID-2026-4001",
    patientLocation: "Emergency Bay 01 (Resuscitation)",
    testName: "High-Sensitivity Cardiac Troponin-I",
    sampleType: "Heparinized Plasma (Green Top)",
    barcodeId: "BC-HEP-10293",
    priority: "Stat",
    scheduledAt: "2026-08-22T08:50:00Z",
    status: "Pending",
  },
  {
    taskId: "TASK-COL-102",
    orderId: "lab_05",
    patientName: "Tariq Mansoor",
    uhid: "UHID-2026-5001",
    patientLocation: "OPD Consultation Desk 102",
    testName: "Glycated Hemoglobin (HbA1c)",
    sampleType: "Whole Blood (EDTA - Lavender Top)",
    barcodeId: "BC-EDTA-30192",
    priority: "Routine",
    scheduledAt: "2026-08-22T08:40:00Z",
    status: "Pending",
  },
  {
    taskId: "TASK-COL-103",
    orderId: "lab_06",
    patientName: "Meera Nair",
    uhid: "UHID-2026-6001",
    patientLocation: "General Ward A - Bed 04",
    testName: "Liver Function Test (LFT)",
    sampleType: "Serum (SST - Gold Top)",
    barcodeId: "BC-SST-77102",
    priority: "Routine",
    scheduledAt: "2026-08-21T14:00:00Z",
    status: "Rejected",
    assignedCollector: "Phleb. Priya Sharma",
    rejectionReason: "Grossly Hemolyzed Specimen (Index > 3+)",
  },
];

// ==========================================
// 3. EXTERNAL / REFERENCE LAB REPORTS
// ==========================================
export const mockExternalLabReports: ExternalLabReport[] = [
  {
    id: "ext_01",
    patientId: "P-7701",
    patientName: "Sunita Deshmukh",
    uhid: "UHID-2026-7701",
    referenceLabName: "Metropolis Healthcare Reference Laboratory",
    testName: "BRCA 1 & BRCA 2 Next-Gen Sequencing Panel",
    sampleType: "Whole Blood EDTA",
    receivedAt: "2026-08-22T10:30:00Z",
    reportFileUrl: "/reports/external/BRCA-DESHMUKH-7701.pdf",
    verificationStatus: "Pending Verification",
    verificationNotes: "Awaiting Oncopathologist review and countersignature before chart publishing.",
  },
  {
    id: "ext_02",
    patientId: "P-8812",
    patientName: "Vikram Singhania",
    uhid: "UHID-2026-8812",
    referenceLabName: "Dr. Lal PathLabs Central Reference Lab",
    testName: "Flow Cytometry: Acute Leukemia Comprehensive Panel",
    sampleType: "Bone Marrow Aspirate",
    receivedAt: "2026-08-21T17:00:00Z",
    reportFileUrl: "/reports/external/FLOW-SINGHANIA-8812.pdf",
    verifyingPathologist: "Dr. Sunita Kulkarni (Senior Hematopathologist)",
    verificationStatus: "Verified",
    verificationNotes: "Verified findings consistent with B-ALL. Published to Oncology EMR chart.",
    verifiedAt: "2026-08-22T08:15:00Z",
  },
  {
    id: "ext_03",
    patientId: "P-3309",
    patientName: "Deepak Chawla",
    uhid: "UHID-2026-3309",
    referenceLabName: "Oncquest Laboratories",
    testName: "EGFR Mutation Analysis (Exons 18-21 by Real-Time PCR)",
    sampleType: "FFPE Tissue Block",
    receivedAt: "2026-08-20T12:00:00Z",
    reportFileUrl: "/reports/external/EGFR-CHAWLA-3309.pdf",
    verifyingPathologist: "Dr. Sunita Kulkarni",
    verificationStatus: "Verified",
    verificationNotes: "Exon 19 deletion detected. Signed off for medical oncology targeted therapy.",
    verifiedAt: "2026-08-20T16:00:00Z",
  },
];

// ==========================================
// 4. LAB TEST & PANEL CATALOG (Tariff Links)
// ==========================================
export const mockLabTestCatalog: LabTestCatalogItem[] = [
  {
    id: "tst_01",
    testCode: "LAB-CBC-01",
    testName: "Complete Blood Count (CBC) with Automated Differential",
    department: "Hematology",
    sampleType: "Whole Blood (EDTA)",
    referenceRange: "Hb: 12-16 g/dL, WBC: 4000-11000 /uL, Plt: 1.5-4.5 L/uL",
    unit: "Multiple Parameters",
    turnaroundHours: 1,
    tariffId: "TAR-LAB-CBC",
    price: 450,
    criticalLow: 6.0,
    criticalHigh: 20.0,
  },
  {
    id: "tst_02",
    testCode: "LAB-ELEC-01",
    testName: "Serum Electrolytes (Sodium, Potassium, Chloride, Bicarbonate)",
    department: "Biochemistry",
    sampleType: "Serum (SST)",
    referenceRange: "Na: 135-145 mEq/L, K: 3.5-5.0 mEq/L, Cl: 98-106 mEq/L",
    unit: "mEq/L",
    turnaroundHours: 1,
    tariffId: "TAR-LAB-ELEC",
    price: 650,
    criticalLow: 2.8,
    criticalHigh: 6.2,
  },
  {
    id: "tst_03",
    testCode: "LAB-TROP-01",
    testName: "High-Sensitivity Cardiac Troponin-I (hs-cTnI)",
    department: "Immunoassay",
    sampleType: "Heparinized Plasma",
    referenceRange: "< 14 ng/L (99th Percentile URL)",
    unit: "ng/L",
    turnaroundHours: 0.75,
    tariffId: "TAR-LAB-TROP",
    price: 1200,
    criticalHigh: 50.0,
  },
  {
    id: "tst_04",
    testCode: "LAB-COAG-01",
    testName: "Coagulation Profile (PT, INR, aPTT)",
    department: "Hematology & Coagulation",
    sampleType: "Citrated Plasma (Light Blue)",
    referenceRange: "PT: 11-13.5s, INR: 0.8-1.2, aPTT: 25-35s",
    unit: "Seconds / Ratio",
    turnaroundHours: 1.5,
    tariffId: "TAR-LAB-COAG",
    price: 800,
    criticalHigh: 4.5,
  },
  {
    id: "tst_05",
    testCode: "LAB-LFT-01",
    testName: "Liver Function Test (LFT Comprehensive)",
    department: "Biochemistry",
    sampleType: "Serum (SST)",
    referenceRange: "Bilirubin: 0.2-1.2 mg/dL, SGOT: < 40 U/L, SGPT: < 40 U/L",
    unit: "mg/dL & U/L",
    turnaroundHours: 2,
    tariffId: "TAR-LAB-LFT",
    price: 750,
  },
];

// ==========================================
// 5. ANALYZER REGISTRY
// ==========================================
export const mockAnalyzerRegistry: AnalyzerRegistryItem[] = [
  {
    id: "ana_01",
    analyzerId: "SYS-XN-1000",
    name: "Sysmex XN-1000 Automated Hematology System",
    model: "Sysmex XN-1000 (Fluorescence Flow Cytometry)",
    department: "Hematology",
    status: "Operational",
    dailyTestVolume: 180,
    lastCalibrationDate: "2026-08-01",
    nextCalibrationDate: "2026-09-01",
  },
  {
    id: "ana_02",
    analyzerId: "BC-DXC-700",
    name: "Beckman Coulter DxC 700 AU Chemistry Analyzer",
    model: "Beckman Coulter DxC 700 AU",
    department: "Biochemistry",
    status: "Operational",
    dailyTestVolume: 320,
    lastCalibrationDate: "2026-08-10",
    nextCalibrationDate: "2026-09-10",
  },
  {
    id: "ana_03",
    analyzerId: "STAGO-CPT",
    name: "Stago Compact Max Coagulation System",
    model: "Stago Compact Max (Mechanical Clot Detection)",
    department: "Hematology & Coagulation",
    status: "Operational",
    dailyTestVolume: 85,
    lastCalibrationDate: "2026-07-20",
    nextCalibrationDate: "2026-08-25",
  },
  {
    id: "ana_04",
    analyzerId: "ABBOT-ALIN",
    name: "Abbott Alinity ci-series Integrated System",
    model: "Abbott Alinity ci (Chemiluminescent Immunoassay)",
    department: "Immunoassay & Serology",
    status: "Calibration Due",
    dailyTestVolume: 210,
    lastCalibrationDate: "2026-07-15",
    nextCalibrationDate: "2026-08-22",
  },
];

// ==========================================
// 6. CRITICAL VALUE THRESHOLDS (Panic Triggers)
// ==========================================
export const mockCriticalThresholds: CriticalThresholdItem[] = [
  {
    id: "crit_01",
    testCode: "LAB-ELEC-01",
    testName: "Serum Potassium (K+)",
    lowPanic: 2.8,
    highPanic: 6.2,
    unit: "mEq/L",
    appliesTo: "All",
    lastAuditedAt: "2026-08-15T10:00:00Z",
    auditedBy: "Dr. Sunita Kulkarni (Head of Pathology)",
  },
  {
    id: "crit_02",
    testCode: "LAB-CBC-01",
    testName: "Hemoglobin (Hb)",
    lowPanic: 6.0,
    highPanic: 20.0,
    unit: "g/dL",
    appliesTo: "Adults",
    lastAuditedAt: "2026-08-15T10:00:00Z",
    auditedBy: "Dr. Sunita Kulkarni",
  },
  {
    id: "crit_03",
    testCode: "LAB-CBC-01",
    testName: "Platelet Count",
    lowPanic: 20000,
    highPanic: 1000000,
    unit: "/uL",
    appliesTo: "All",
    lastAuditedAt: "2026-08-15T10:00:00Z",
    auditedBy: "Dr. Sunita Kulkarni",
  },
  {
    id: "crit_04",
    testCode: "LAB-TROP-01",
    testName: "High-Sensitivity Troponin-I",
    lowPanic: 0,
    highPanic: 50.0,
    unit: "ng/L",
    appliesTo: "Adults",
    lastAuditedAt: "2026-08-15T10:00:00Z",
    auditedBy: "Dr. Sunita Kulkarni",
  },
  {
    id: "crit_05",
    testCode: "LAB-COAG-01",
    testName: "Prothrombin Time / INR",
    lowPanic: 0,
    highPanic: 4.5,
    unit: "INR",
    appliesTo: "Adults",
    lastAuditedAt: "2026-08-15T10:00:00Z",
    auditedBy: "Dr. Sunita Kulkarni",
  },
];

// ==========================================
// 7. STANDARDIZED REJECTION REASONS
// ==========================================
export const mockRejectionReasons: RejectionReasonItem[] = [
  {
    id: "rej_01",
    code: "HEM-01",
    reason: "Grossly Hemolyzed Specimen (Index > 3+)",
    category: "Specimen Quality",
    standardAction: "Auto-trigger immediate re-collection dispatch to nurse station.",
  },
  {
    id: "rej_02",
    code: "VOL-01",
    reason: "Insufficient Volume (QNS - Quantity Not Sufficient)",
    category: "Volume",
    standardAction: "Notify phlebotomy for top-up redraw.",
  },
  {
    id: "rej_03",
    code: "CLT-01",
    reason: "Micro-Clots Detected in Anticoagulated EDTA/Citrate Tube",
    category: "Specimen Quality",
    standardAction: "Sample discarded. Fresh venipuncture required.",
  },
  {
    id: "rej_04",
    code: "ID-01",
    reason: "Mislabeled Tube / Missing 2-Point Barcode Match",
    category: "Identification",
    standardAction: "Safety stop. Zero-tolerance protocol requires fresh verified redraw.",
  },
  {
    id: "rej_05",
    code: "TRP-01",
    reason: "Temperature Excursion during Cold-Chain Transport",
    category: "Transport",
    standardAction: "Sample integrity compromised. New specimen requested.",
  },
];

// ==========================================
// 8. LAB STAFF TRACEABILITY
// ==========================================
export const mockLabStaff = [
  {
    id: "stf_01",
    name: "Dr. Sunita Kulkarni",
    role: "Senior Consultant Pathologist",
    qualification: "MD (Pathology), FRCPath",
    licenseNo: "MCI-PAT-99410",
    department: "Central Diagnostic Laboratory",
    todayAuthorizedCount: 42,
    status: "Active",
  },
  {
    id: "stf_02",
    name: "Santosh Kumar",
    role: "Senior Phlebotomist",
    qualification: "DMLT, Phlebotomy Certified",
    licenseNo: "PHL-2022-819",
    department: "Phlebotomy & Sample Collection Desk",
    todayCollectedCount: 28,
    status: "Active",
  },
  {
    id: "stf_03",
    name: "Priya Sharma",
    role: "Phlebotomist & Intake Technician",
    qualification: "B.Sc MLT",
    licenseNo: "PHL-2024-102",
    department: "Phlebotomy & Sample Collection Desk",
    todayCollectedCount: 24,
    status: "Active",
  },
  {
    id: "stf_04",
    name: "Rajeshwar Rao",
    role: "Senior Laboratory Technologist",
    qualification: "M.Sc (Medical Biochemistry)",
    licenseNo: "TECH-2020-449",
    department: "Biochemistry & Immunoassay",
    todayProcessedCount: 65,
    status: "Active",
  },
];
