import { Patient } from "@/hospital-admin/lib/types";

export const patients: Patient[] = [
  {
    id: "pat_001",
    qlynoPatientId: "QLY-PAT-2024-00841",
    uhid: "HOS-2024-00841",
    name: "Aarav Shah",
    avatarUrl: "https://i.pravatar.cc/150?img=68",
    dateOfBirth: "1990-05-15",
    gender: "Male",
    phone: "+91 98220 11009",
    email: "aarav.shah@gmail.com",
    bloodGroup: "B+",
    address: "Lokhandwala Complex, Andheri West, Mumbai",
    emergencyContact: {
      name: "Priya Shah",
      phone: "+91 98220 11010",
      relationship: "Spouse",
    },
    identifiers: {
      aadhar: "1234 5678 9012",
      pan: "AAAPA1234A",
    },
    globalStatus: "active",
    createdOn: "2024-01-12",
    lastModified: "2026-08-06",
    primaryHospitalId: "hosp_001",
    tags: ["Hypertension", "Regular Patient"],
    hospitalRelationships: [
      {
        hospitalId: "hosp_001",
        hospitalName: "Qlyno Multispecialty Hospital",
        status: "active",
        relationshipEstablishedOn: "2024-01-12",
        consent: {
          status: "granted",
          dataSharing: ["OPD", "Prescriptions", "Discharge Documents"],
          restrictions: ["Genetic Data"],
          recordedOn: "2024-01-12",
        },
        opdHistory: [
          {
            id: "opd_001",
            registrationDate: "2026-08-06",
            doctor: "Dr. Ananya Rao",
            department: "Cardiology",
            status: "completed",
            visitReason: "Routine checkup",
            consultationNotes: "BP controlled, continue current medication",
            prescriptions: ["Amlodipine 5mg", "Aspirin 75mg"],
          },
        ],
        ipdHistory: [],
        documents: [
          {
            id: "doc_001",
            type: "Discharge Summary",
            name: "Discharge_2026_08_06.pdf",
            uploadedOn: "2026-08-06",
            generatedBy: "Dr. Ananya Rao",
            url: "/documents/discharge_001.pdf",
          },
        ],
        billingStatus: {
          totalOutstanding: 0,
          totalSpent: 24600,
          lastBillingDate: "2026-08-06",
        },
      },
    ],
  },
  {
    id: "pat_002",
    qlynoPatientId: "QLY-PAT-2023-00412",
    uhid: "HOS-2023-00412",
    name: "Meera Nambiar",
    avatarUrl: "https://i.pravatar.cc/150?img=44",
    dateOfBirth: "1998-11-22",
    gender: "Female",
    phone: "+91 90040 88771",
    email: "meera.nambiar@gmail.com",
    bloodGroup: "O+",
    address: "Hiranandani Gardens, Powai, Mumbai",
    emergencyContact: {
      name: "Rajesh Nambiar",
      phone: "+91 90040 88770",
      relationship: "Father",
    },
    identifiers: {
      aadhar: "2345 6789 0123",
    },
    globalStatus: "active",
    createdOn: "2023-06-05",
    lastModified: "2026-08-11",
    primaryHospitalId: "hosp_001",
    tags: ["Prenatal Care", "OB-GYN"],
    hospitalRelationships: [
      {
        hospitalId: "hosp_001",
        hospitalName: "Qlyno Multispecialty Hospital",
        status: "active",
        relationshipEstablishedOn: "2023-06-05",
        consent: {
          status: "granted",
          dataSharing: ["OPD", "IPD", "Maternity Records", "Discharge Documents"],
          restrictions: [],
          recordedOn: "2023-06-05",
        },
        opdHistory: [
          {
            id: "opd_002",
            registrationDate: "2026-08-11",
            doctor: "Dr. Neha Kulkarni",
            department: "Obstetrics & Gynecology",
            status: "completed",
            visitReason: "Prenatal checkup - Week 28",
            consultationNotes: "All parameters normal, glucose test scheduled",
            prescriptions: ["Prenatal vitamins", "Iron supplements"],
          },
        ],
        ipdHistory: [],
        documents: [
          {
            id: "doc_002",
            type: "Maternity Record",
            name: "Prenatal_Record_2026.pdf",
            uploadedOn: "2026-08-11",
            generatedBy: "Dr. Neha Kulkarni",
            url: "/documents/maternity_001.pdf",
          },
        ],
        billingStatus: {
          totalOutstanding: 1400,
          totalSpent: 18200,
          lastBillingDate: "2026-08-11",
        },
      },
    ],
  },
  {
    id: "pat_003",
    qlynoPatientId: "QLY-PAT-2022-00187",
    uhid: "HOS-2022-00187",
    name: "Ibrahim Sheikh",
    avatarUrl: "https://i.pravatar.cc/150?img=14",
    dateOfBirth: "1965-03-10",
    gender: "Male",
    phone: "+91 98670 22341",
    email: "ibrahim.sheikh@yahoo.com",
    bloodGroup: "A-",
    address: "MIDC, Andheri East, Mumbai",
    emergencyContact: {
      name: "Fatima Sheikh",
      phone: "+91 98670 22342",
      relationship: "Spouse",
    },
    identifiers: {
      aadhar: "3456 7890 1234",
      pan: "AAAAAA1111A",
    },
    globalStatus: "active",
    createdOn: "2022-03-19",
    lastModified: "2026-07-28",
    primaryHospitalId: "hosp_001",
    tags: ["Diabetes", "Cardiac Risk", "Regular IPD"],
    hospitalRelationships: [
      {
        hospitalId: "hosp_001",
        hospitalName: "Qlyno Multispecialty Hospital",
        status: "active",
        relationshipEstablishedOn: "2022-03-19",
        consent: {
          status: "granted",
          dataSharing: ["OPD", "IPD", "Lab Reports", "Discharge Documents"],
          restrictions: ["Genetic counseling"],
          recordedOn: "2022-03-19",
        },
        opdHistory: [
          {
            id: "opd_003",
            registrationDate: "2026-07-28",
            doctor: "Dr. Simran Kaur",
            department: "Internal Medicine",
            status: "completed",
            visitReason: "Diabetes review",
            consultationNotes: "HbA1c well controlled, continue current regimen",
            prescriptions: ["Metformin 500mg", "Atorvastatin 20mg"],
          },
        ],
        ipdHistory: [
          {
            id: "ipd_001",
            admissionDate: "2026-06-15",
            dischargeDate: "2026-06-22",
            department: "Cardiology",
            bedAssignment: "Cardiac Ward - Bed 12",
            doctor: "Dr. Simran Kaur",
            diagnosis: "Unstable Angina",
            status: "discharged",
            treatmentPlan: "Conservative management with cardiac monitoring",
            dischargeSummary: "Patient discharged in stable condition with follow-up prescribed",
            transferRequests: [],
          },
        ],
        documents: [
          {
            id: "doc_003",
            type: "Discharge Summary",
            name: "Cardiac_Discharge_2026_06_22.pdf",
            uploadedOn: "2026-06-22",
            generatedBy: "Dr. Simran Kaur",
            url: "/documents/cardiac_discharge_001.pdf",
          },
          {
            id: "doc_004",
            type: "Lab Report",
            name: "HbA1c_Test_2026_07_28.pdf",
            uploadedOn: "2026-07-28",
            generatedBy: "Lab Technician",
            url: "/documents/lab_report_001.pdf",
          },
        ],
        billingStatus: {
          totalOutstanding: 3200,
          totalSpent: 96700,
          lastBillingDate: "2026-07-28",
        },
      },
    ],
  },
  {
    id: "pat_004",
    qlynoPatientId: "QLY-PAT-2024-01190",
    uhid: "HOS-2024-01190",
    name: "Kabir Malhotra",
    avatarUrl: "https://i.pravatar.cc/150?img=57",
    dateOfBirth: "2019-02-14",
    gender: "Male",
    phone: "+91 91234 55098",
    email: "reema.malhotra@gmail.com",
    bloodGroup: "AB+",
    address: "Chandivali, Powai, Mumbai",
    emergencyContact: {
      name: "Reema Malhotra",
      phone: "+91 91234 55099",
      relationship: "Mother",
    },
    identifiers: {
      aadhar: "4567 8901 2345",
    },
    globalStatus: "active",
    createdOn: "2024-04-02",
    lastModified: "2026-08-10",
    primaryHospitalId: "hosp_001",
    tags: ["Pediatric", "Regular Checkup"],
    hospitalRelationships: [
      {
        hospitalId: "hosp_001",
        hospitalName: "Qlyno Multispecialty Hospital",
        status: "active",
        relationshipEstablishedOn: "2024-04-02",
        consent: {
          status: "granted",
          dataSharing: ["OPD", "Vaccination Records", "Growth Charts"],
          restrictions: [],
          recordedOn: "2024-04-02",
        },
        opdHistory: [
          {
            id: "opd_004",
            registrationDate: "2026-08-10",
            doctor: "Dr. Kavya Iyer",
            department: "Pediatrics",
            status: "completed",
            visitReason: "Annual checkup",
            consultationNotes: "Growth and development normal for age",
            prescriptions: ["Vitamin D supplement"],
          },
        ],
        ipdHistory: [],
        documents: [
          {
            id: "doc_005",
            type: "Vaccination Record",
            name: "Vaccination_Card_2026.pdf",
            uploadedOn: "2026-08-10",
            generatedBy: "Dr. Kavya Iyer",
            url: "/documents/vaccination_001.pdf",
          },
        ],
        billingStatus: {
          totalOutstanding: 0,
          totalSpent: 6200,
          lastBillingDate: "2026-08-10",
        },
      },
    ],
  },
  {
    id: "pat_005",
    qlynoPatientId: "QLY-PAT-2021-00092",
    uhid: "HOS-2021-00092",
    name: "Sunita Reddy",
    avatarUrl: "https://i.pravatar.cc/150?img=48",
    dateOfBirth: "1981-07-20",
    gender: "Female",
    phone: "+91 98200 66712",
    email: "sunita.reddy@outlook.com",
    bloodGroup: "B-",
    address: "Marol, Andheri East, Mumbai",
    emergencyContact: {
      name: "Ramesh Reddy",
      phone: "+91 98200 66711",
      relationship: "Spouse",
    },
    identifiers: {
      pan: "AAAAA2222A",
    },
    globalStatus: "inactive",
    createdOn: "2021-11-27",
    lastModified: "2026-06-30",
    primaryHospitalId: "hosp_001",
    tags: ["Dermatology", "Inactive"],
    hospitalRelationships: [
      {
        hospitalId: "hosp_001",
        hospitalName: "Qlyno Multispecialty Hospital",
        status: "inactive",
        relationshipEstablishedOn: "2021-11-27",
        consent: {
          status: "restricted",
          dataSharing: ["OPD Only"],
          restrictions: ["Genetic Data", "Mental Health Records"],
          recordedOn: "2021-11-27",
          expiresOn: "2026-11-27",
        },
        opdHistory: [
          {
            id: "opd_005",
            registrationDate: "2026-06-30",
            doctor: "Dr. Aditya Verma",
            department: "Dermatology",
            status: "completed",
            visitReason: "Skin condition followup",
            consultationNotes: "Improving with current treatment",
            prescriptions: ["Topical cream", "Sunscreen SPF 50"],
          },
        ],
        ipdHistory: [],
        documents: [],
        billingStatus: {
          totalOutstanding: 0,
          totalSpent: 41300,
        },
      },
    ],
  },
];

export const opqueueData = [
  { token: "A-001", patient: "Aarav Shah", doctor: "Dr. Ananya Rao", status: "in-consultation", waitTime: 0, queueTime: "09:30 AM" },
  { token: "A-002", patient: "Meera Nambiar", doctor: "Dr. Neha Kulkarni", status: "waiting", waitTime: 12, queueTime: "09:45 AM" },
  { token: "A-003", patient: "Priya Desai", doctor: "Dr. Simran Kaur", status: "waiting", waitTime: 24, queueTime: "10:15 AM" },
  { token: "A-004", patient: "Rajesh Patel", doctor: "Dr. Ananya Rao", status: "waiting", waitTime: 36, queueTime: "10:45 AM" },
  { token: "A-005", patient: "Neha Sharma", doctor: "Dr. Aditya Verma", status: "called", waitTime: 5, queueTime: "11:00 AM" },
];

export const opdRegistrationData = [
  { date: "2026-08-17", time: "09:00 AM", patient: "Aarav Shah", phone: "+91 98220 11009", doctor: "Dr. Ananya Rao", dept: "Cardiology", status: "registered", reason: "Routine checkup" },
  { date: "2026-08-17", time: "09:30 AM", patient: "Meera Nambiar", phone: "+91 90040 88771", doctor: "Dr. Neha Kulkarni", dept: "OB-GYN", status: "registered", reason: "Prenatal checkup" },
  { date: "2026-08-17", time: "10:00 AM", patient: "Ibrahim Sheikh", phone: "+91 98670 22341", doctor: "Dr. Simran Kaur", dept: "Internal Medicine", status: "registered", reason: "Diabetes review" },
];

export const ipdAdmissions = [
  {
    admissionId: "IPD-001",
    patientName: "Rajesh Verma",
    qlynoId: "QLY-PAT-2023-00156",
    doctor: "Dr. Simran Kaur",
    department: "Cardiology",
    bed: "Cardiac Ward - Bed 15",
    admissionDate: "2026-08-15",
    diagnosis: "Myocardial Infarction",
    status: "under-treatment",
    treatmentStage: "Recovery",
  },
  {
    admissionId: "IPD-002",
    patientName: "Sanjay Gupta",
    qlynoId: "QLY-PAT-2024-00234",
    doctor: "Dr. Rajesh Sharma",
    department: "General Surgery",
    bed: "Surgical Ward - Bed 8",
    admissionDate: "2026-08-12",
    diagnosis: "Cholecystectomy recovery",
    status: "discharge-pending",
    treatmentStage: "Ready for discharge",
  },
  {
    admissionId: "IPD-003",
    patientName: "Anjali Kapoor",
    qlynoId: "QLY-PAT-2022-00089",
    doctor: "Dr. Neha Kulkarni",
    department: "Obstetrics & Gynecology",
    bed: "Maternity Ward - Bed 5",
    admissionDate: "2026-08-16",
    diagnosis: "Scheduled C-section",
    status: "admitted",
    treatmentStage: "Pre-operative",
  },
];
