import {
  RadiologyOrder,
  ImagingSuite,
  CriticalFindingLog,
  StudyHistoryItem,
  RadiologistProfile,
} from "@/hospital-admin/lib/types";

// ==========================================
// 1. IMAGING SUITES & MACHINE REGISTRY (F14 Equipment)
// ==========================================
export const mockImagingSuites: ImagingSuite[] = [
  {
    id: "suite_01",
    suiteId: "SUITE-CT-01",
    name: "128-Slice Multi-Detector CT Suite",
    modalityType: "CT Scan",
    location: "Diagnostic Block A, Ground Floor",
    floor: "Ground Floor",
    status: "In Use",
    pacsConnectivityStatus: "Connected",
    currentActiveOrderId: "rad_103",
    lastMaintenanceDate: "2026-08-01",
    nextMaintenanceDate: "2026-09-01",
    maintenanceNotes: "Routine calibration & tube cooling inspection completed.",
  },
  {
    id: "suite_02",
    suiteId: "SUITE-MRI-01",
    name: "3.0 Tesla High-Field MRI Suite",
    modalityType: "MRI",
    location: "Neuro-Imaging Block, Basement 1",
    floor: "Basement 1",
    status: "Available",
    pacsConnectivityStatus: "Connected",
    lastMaintenanceDate: "2026-07-20",
    nextMaintenanceDate: "2026-08-28",
    maintenanceNotes: "Cryogen helium level at 98.4%. Magnet gradient coil checked.",
  },
  {
    id: "suite_03",
    suiteId: "SUITE-XRAY-01",
    name: "Digital Radiography X-Ray Bay 1",
    modalityType: "X-Ray",
    location: "OPD Emergency Wing, Ground Floor",
    floor: "Ground Floor",
    status: "Available",
    pacsConnectivityStatus: "Connected",
    lastMaintenanceDate: "2026-08-10",
    nextMaintenanceDate: "2026-10-10",
    maintenanceNotes: "Flat panel detector calibrated for chest and skeletal imaging.",
  },
  {
    id: "suite_04",
    suiteId: "SUITE-XRAY-02",
    name: "Digital Radiography X-Ray Bay 2 (Orthopedic Focus)",
    modalityType: "X-Ray",
    location: "Trauma & Ortho Wing, 1st Floor",
    floor: "1st Floor",
    status: "Maintenance",
    pacsConnectivityStatus: "Degraded",
    lastMaintenanceDate: "2026-06-15",
    nextMaintenanceDate: "2026-08-24",
    maintenanceNotes: "Collimator lamp replacement and lead shielding inspection underway.",
  },
  {
    id: "suite_05",
    suiteId: "SUITE-ECHO-01",
    name: "Echocardiography & Non-Invasive Cardio Bay 1",
    modalityType: "Ultrasound",
    location: "Cardiology Center, 2nd Floor",
    floor: "2nd Floor",
    status: "Available",
    pacsConnectivityStatus: "Connected",
    lastMaintenanceDate: "2026-08-05",
    nextMaintenanceDate: "2026-11-05",
    maintenanceNotes: "Phased array cardiac probe transducer QA passed.",
  },
];

// ==========================================
// 2. EXTENDED RADIOLOGY ORDERS (F14 Single Source of Truth)
// ==========================================
export const mockExtendedRadiologyOrders: RadiologyOrder[] = [
  {
    id: "rad_101",
    orderNo: "RAD-2026-8801",
    patientId: "P-1001",
    patientName: "Ramesh Sharma",
    uhid: "UHID-2026-1001",
    age: 54,
    gender: "Male",
    modality: "CT Scan",
    bodyPart: "High-Resolution Chest (HRCT)",
    orderingDoctor: "Dr. Arvind Swaminathan",
    source: "IPD",
    scheduledAt: "2026-08-24T11:00:00Z",
    status: "Report Ready",
    priority: "Urgent",
    roomName: "128-Slice Multi-Detector CT Suite",
    suiteId: "suite_01",
    radiologistName: "Dr. Vikram Seth, MD (Radiology)",
    radiologistId: "doc_rad_01",
    technologistName: "Pooja Verma (Senior Radiographer)",
    scanStartTime: "2026-08-24T10:45:00Z",
    elapsedScanMins: 15,
    patientLocation: "Ward B, Bed 12",
    wardBed: "Ward B-12",
    tariffId: "TAR-RAD-CT-01",
    price: 4500,
    reportNotes: "Bilateral lower lobe patchy ground-glass opacities with subpleural sparing. Findings consistent with resolving viral pneumonitis. No evidence of pulmonary thromboembolism or pleural effusion.",
    impressionNotes: "Resolving viral pneumonitis. Follow-up imaging in 6 weeks recommended if symptoms persist.",
    dicomViewerUrl: "/radiology/viewer/rad_101",
    authorizedAt: "2026-08-24T11:30:00Z",
  },
  {
    id: "rad_102",
    orderNo: "RAD-2026-8802",
    patientId: "P-9102",
    patientName: "Kavita Patil",
    uhid: "UHID-2026-9102",
    age: 48,
    gender: "Female",
    modality: "MRI",
    bodyPart: "Brain with Contrast & MR Angiography",
    orderingDoctor: "Dr. Kavita Verma",
    source: "Emergency",
    scheduledAt: "2026-08-24T10:15:00Z",
    status: "Report Ready",
    priority: "Stat Emergency",
    criticalFinding: true,
    criticalDetails: "CRITICAL ALERT: Acute right MCA territory ischemic infarct with subtle mass effect and sulcal effacement.",
    roomName: "3.0 Tesla High-Field MRI Suite",
    suiteId: "suite_02",
    radiologistName: "Dr. Sunita Kulkarni, MD (Neuroradiology)",
    radiologistId: "doc_rad_02",
    technologistName: "Amit Shinde (Lead MRI Technologist)",
    scanStartTime: "2026-08-24T09:45:00Z",
    elapsedScanMins: 30,
    patientLocation: "Emergency Resuscitation Bay 2",
    wardBed: "ER-Resus-02",
    tariffId: "TAR-RAD-MRI-01",
    price: 8500,
    reportNotes: "Diffusion-weighted imaging (DWI) demonstrates hyperintense signal in the right frontotemporoparietal cortex with corresponding ADC hypointensity. Non-hemorrhagic right MCA territory acute stroke.",
    impressionNotes: "Acute right MCA ischemic stroke. Immediate neurology/stroke team escalation completed via critical notification protocol.",
    dicomViewerUrl: "/radiology/viewer/rad_102",
    authorizedAt: "2026-08-24T10:35:00Z",
  },
  {
    id: "rad_103",
    orderNo: "RAD-2026-8803",
    patientId: "P-8821",
    patientName: "Arjun Gupta",
    uhid: "UHID-2026-8821",
    age: 36,
    gender: "Male",
    modality: "CT Scan",
    bodyPart: "Abdomen & Pelvis with IV Contrast",
    orderingDoctor: "Dr. Ramesh Sharma",
    source: "Emergency",
    scheduledAt: "2026-08-24T10:30:00Z",
    status: "In Progress",
    priority: "Stat Emergency",
    criticalFinding: false,
    roomName: "128-Slice Multi-Detector CT Suite",
    suiteId: "suite_01",
    technologistName: "Pooja Verma (Senior Radiographer)",
    scanStartTime: "2026-08-24T10:20:00Z",
    elapsedScanMins: 12,
    patientLocation: "Emergency Bay 4",
    wardBed: "ER-04",
    tariffId: "TAR-RAD-CT-02",
    price: 5200,
    dicomViewerUrl: "/radiology/viewer/rad_103",
  },
  {
    id: "rad_104",
    orderNo: "RAD-2026-8804",
    patientId: "P-4001",
    patientName: "Anil Kapoor",
    uhid: "UHID-2026-4001",
    age: 62,
    gender: "Male",
    modality: "X-Ray",
    bodyPart: "Chest PA View (Pre-Op Clearance)",
    orderingDoctor: "Dr. Ananya Patel",
    source: "OT",
    scheduledAt: "2026-08-24T11:45:00Z",
    status: "Report Pending",
    priority: "Urgent",
    criticalFinding: false,
    roomName: "Digital Radiography X-Ray Bay 1",
    suiteId: "suite_03",
    technologistName: "Sanjay Deshmukh (Radiographer)",
    scanStartTime: "2026-08-24T11:10:00Z",
    elapsedScanMins: 6,
    patientLocation: "Pre-Op Holding Room 2",
    wardBed: "OT-Holding-02",
    tariffId: "TAR-RAD-XRAY-01",
    price: 800,
    dicomViewerUrl: "/radiology/viewer/rad_104",
  },
  {
    id: "rad_105",
    orderNo: "RAD-2026-8805",
    patientId: "P-5001",
    patientName: "Tariq Mansoor",
    uhid: "UHID-2026-5001",
    age: 41,
    gender: "Male",
    modality: "MRI",
    bodyPart: "Lumbar Spine (L1-S1) Plain",
    orderingDoctor: "Dr. Rohan Mehta",
    source: "OPD",
    scheduledAt: "2026-08-24T14:00:00Z",
    status: "Scheduled",
    priority: "Routine",
    criticalFinding: false,
    roomName: "3.0 Tesla High-Field MRI Suite",
    suiteId: "suite_02",
    patientLocation: "OPD Waiting Area 3",
    tariffId: "TAR-RAD-MRI-02",
    price: 6800,
    dicomViewerUrl: "/radiology/viewer/rad_105",
  },
  {
    id: "rad_106",
    orderNo: "RAD-2026-8806",
    patientId: "P-6001",
    patientName: "Meera Nair",
    uhid: "UHID-2026-6001",
    age: 29,
    gender: "Female",
    modality: "Ultrasound",
    bodyPart: "Abdomen & Pelvis with Doppler",
    orderingDoctor: "Dr. Kavita Verma",
    source: "OPD",
    scheduledAt: "2026-08-24T15:30:00Z",
    status: "Requested",
    priority: "Routine",
    criticalFinding: false,
    roomName: "Echocardiography & Non-Invasive Cardio Bay 1",
    suiteId: "suite_05",
    patientLocation: "OPD Gynae Clinic Room 102",
    tariffId: "TAR-RAD-USG-01",
    price: 1800,
  },
  {
    id: "rad_107",
    orderNo: "RAD-2026-8807",
    patientId: "P-7001",
    patientName: "Deepak Chawla",
    uhid: "UHID-2026-7001",
    age: 51,
    gender: "Male",
    modality: "CT Scan",
    bodyPart: "CT Pulmonary Angiography (CTPA)",
    orderingDoctor: "Dr. Arvind Swaminathan",
    source: "Emergency",
    scheduledAt: "2026-08-24T08:30:00Z",
    status: "Report Pending",
    priority: "Stat Emergency",
    criticalFinding: true,
    criticalDetails: "CRITICAL ALERT: Saddle pulmonary embolism with acute right heart strain.",
    roomName: "128-Slice Multi-Detector CT Suite",
    suiteId: "suite_01",
    technologistName: "Pooja Verma (Senior Radiographer)",
    scanStartTime: "2026-08-24T08:15:00Z",
    elapsedScanMins: 14,
    patientLocation: "ICU Bed 04",
    wardBed: "ICU-04",
    tariffId: "TAR-RAD-CT-03",
    price: 6500,
    dicomViewerUrl: "/radiology/viewer/rad_107",
  },
  {
    id: "rad_108",
    orderNo: "RAD-2026-8808",
    patientId: "P-7002",
    patientName: "Meenakshi Sundaram",
    uhid: "UHID-2026-7002",
    age: 44,
    gender: "Female",
    modality: "MRI",
    bodyPart: "Cervical Spine with Contrast",
    orderingDoctor: "Dr. Rohan Mehta",
    source: "OPD",
    scheduledAt: "2026-08-25T09:00:00Z",
    status: "Scheduled",
    priority: "Routine",
    roomName: "3.0 Tesla High-Field MRI Suite",
    suiteId: "suite_02",
    patientLocation: "OPD Spine Clinic 204",
    price: 7200,
  },
  {
    id: "rad_109",
    orderNo: "RAD-2026-8809",
    patientId: "P-7003",
    patientName: "Harish Vardhan",
    uhid: "UHID-2026-7003",
    age: 58,
    gender: "Male",
    modality: "CT Scan",
    bodyPart: "Whole Abdomen Triphasic CT",
    orderingDoctor: "Dr. Arvind Swaminathan",
    source: "IPD",
    scheduledAt: "2026-08-25T14:00:00Z",
    status: "Scheduled",
    priority: "Urgent",
    roomName: "128-Slice Multi-Detector CT Suite",
    suiteId: "suite_01",
    patientLocation: "Ward A, Bed 08",
    price: 5800,
  },
  {
    id: "rad_110",
    orderNo: "RAD-2026-8810",
    patientId: "P-7004",
    patientName: "Nisha Agarwal",
    uhid: "UHID-2026-7004",
    age: 32,
    gender: "Female",
    modality: "Ultrasound",
    bodyPart: "Pelvic & Follicular Doppler",
    orderingDoctor: "Dr. Kavita Verma",
    source: "OPD",
    scheduledAt: "2026-08-26T10:00:00Z",
    status: "Scheduled",
    priority: "Routine",
    roomName: "Echocardiography & Non-Invasive Cardio Bay 1",
    suiteId: "suite_05",
    patientLocation: "OPD Women's Health Clinic",
    price: 2200,
  },
  {
    id: "rad_111",
    orderNo: "RAD-2026-8811",
    patientId: "P-7005",
    patientName: "Rajendra Prasad",
    uhid: "UHID-2026-7005",
    age: 67,
    gender: "Male",
    modality: "X-Ray",
    bodyPart: "Bilateral Knee AP/Lateral Weight-Bearing",
    orderingDoctor: "Dr. Ramesh Sharma",
    source: "OPD",
    scheduledAt: "2026-08-23T11:00:00Z",
    status: "Report Ready",
    priority: "Routine",
    roomName: "Digital Radiography X-Ray Bay 1",
    suiteId: "suite_03",
    patientLocation: "OPD Ortho Clinic 101",
    radiologistName: "Dr. Arvind Rao",
    reportNotes: "Severe medial compartment joint space narrowing with subchondral sclerosis. Grade 3 osteoarthritis.",
    impressionNotes: "Bilateral knee Grade 3 OA.",
    price: 950,
  },
];

// ==========================================
// 3. PERSISTENT CRITICAL FINDINGS LOG (F14 Critical Findings)
// ==========================================
export const mockCriticalFindingLogs: CriticalFindingLog[] = [
  {
    id: "crit_rad_01",
    orderId: "rad_102",
    orderNo: "RAD-2026-8802",
    patientName: "Kavita Patil",
    uhid: "UHID-2026-9102",
    patientLocation: "Emergency Resuscitation Bay 2",
    modality: "MRI",
    bodyPart: "Brain with Contrast & MR Angiography",
    criticalDetails: "Acute right MCA territory ischemic infarct with subtle mass effect and sulcal effacement. High risk of malignant cerebral edema.",
    flaggedAt: "2026-08-24T10:20:00Z",
    orderingDoctor: "Dr. Kavita Verma",
    reportingRadiologist: "Dr. Sunita Kulkarni, MD (Neuroradiology)",
    acknowledged: true,
    acknowledgedBy: "Dr. Kavita Verma (Attending ER Consultant)",
    acknowledgedAt: "2026-08-24T10:24:00Z",
    clinicianNotified: true,
    notificationMethod: "Phone",
    escalationNotes: "Direct phone call with Dr. Verma. Patient transferred immediately for IV thrombolysis protocol.",
  },
  {
    id: "crit_rad_02",
    orderId: "rad_107",
    orderNo: "RAD-2026-8807",
    patientName: "Deepak Chawla",
    uhid: "UHID-2026-7001",
    patientLocation: "ICU Bed 04",
    modality: "CT Scan",
    bodyPart: "CT Pulmonary Angiography (CTPA)",
    criticalDetails: "Large saddle pulmonary embolism extending into both main pulmonary arteries with RV/LV ratio > 1.2 indicating severe acute strain.",
    flaggedAt: "2026-08-24T08:28:00Z",
    orderingDoctor: "Dr. Arvind Swaminathan",
    reportingRadiologist: "Dr. Vikram Seth, MD (Radiology)",
    acknowledged: false,
    clinicianNotified: false,
    escalationNotes: "Urgent call placed to ICU Intensivist extension 4410. Awaiting return callback.",
  },
  {
    id: "crit_rad_03",
    orderId: "rad_099",
    orderNo: "RAD-2026-8790",
    patientName: "Sunil Deshmukh",
    uhid: "UHID-2026-3391",
    patientLocation: "Trauma Resuscitation Bay 1",
    modality: "CT Scan",
    bodyPart: "Non-Contrast Head CT (Trauma)",
    criticalDetails: "Acute right epidural hematoma measuring 18mm thickness with 6mm midline shift.",
    flaggedAt: "2026-08-23T22:15:00Z",
    orderingDoctor: "Dr. Ananya Patel",
    reportingRadiologist: "Dr. Sunita Kulkarni, MD (Neuroradiology)",
    acknowledged: true,
    acknowledgedBy: "Dr. Rajiv Singhania (Consultant Neurosurgeon)",
    acknowledgedAt: "2026-08-23T22:19:00Z",
    clinicianNotified: true,
    notificationMethod: "Direct Consultation",
    escalationNotes: "Neurosurgical emergency craniotomy initiated within 30 minutes.",
  },
];

// ==========================================
// 4. RADIOLOGIST ROSTER (F14 Radiologists - Reads Doctor Management)
// ==========================================
export const mockRadiologistProfiles: RadiologistProfile[] = [
  {
    id: "rad_prof_01",
    doctorId: "doc_rad_01",
    name: "Dr. Vikram Seth",
    qualification: "MD (Radiodiagnosis), FRCR (UK)",
    registrationNo: "MMC-2012-08891",
    specialty: "Radiology (Body Imaging & CT Angiography)",
    onDutyStatus: "On Duty",
    currentQueueCount: 3,
    avgTatMins: 22,
    todayAuthorizedCount: 14,
    contactNumber: "+91 98201 55441",
  },
  {
    id: "rad_prof_02",
    doctorId: "doc_rad_02",
    name: "Dr. Sunita Kulkarni",
    qualification: "MD, DNB (Neuroradiology & MRI)",
    registrationNo: "MMC-2008-03419",
    specialty: "Neuroradiology & Advanced MRI Diagnostics",
    onDutyStatus: "On Duty",
    currentQueueCount: 2,
    avgTatMins: 18,
    todayAuthorizedCount: 11,
    contactNumber: "+91 98202 77883",
  },
  {
    id: "rad_prof_03",
    doctorId: "doc_rad_03",
    name: "Dr. Arvind Rao",
    qualification: "MD (Radiology), Fellowship in MSK Radiology",
    registrationNo: "MMC-2015-09112",
    specialty: "Musculoskeletal & Ultrasound Diagnostics",
    onDutyStatus: "On Call",
    currentQueueCount: 0,
    avgTatMins: 25,
    todayAuthorizedCount: 8,
    contactNumber: "+91 98203 11229",
  },
];

// ==========================================
// 5. STUDY HISTORY & COMPLETED ARCHIVE (F14 History)
// ==========================================
export const mockStudyHistory: StudyHistoryItem[] = [
  {
    id: "hist_rad_01",
    orderId: "rad_hist_901",
    orderNo: "RAD-2026-8701",
    patientName: "Priyanka Sen",
    uhid: "UHID-2026-2210",
    modality: "MRI",
    bodyPart: "Right Knee Joint with Cartilage Mapping",
    orderingDoctor: "Dr. Ramesh Sharma",
    radiologistName: "Dr. Arvind Rao",
    technologistName: "Amit Shinde",
    suiteName: "3.0 Tesla High-Field MRI Suite",
    outcome: "Completed",
    totalTurnaroundTimeMins: 38,
    completedAt: "2026-08-23T16:45:00Z",
    archivedAt: "2026-08-23T17:00:00Z",
    dicomViewerUrl: "/radiology/viewer/rad_102",
  },
  {
    id: "hist_rad_02",
    orderId: "rad_hist_902",
    orderNo: "RAD-2026-8702",
    patientName: "Vikram Singhania",
    uhid: "UHID-2026-8812",
    modality: "CT Scan",
    bodyPart: "CT KUB (Kidney, Ureter, Bladder)",
    orderingDoctor: "Dr. Ananya Patel",
    radiologistName: "Dr. Vikram Seth",
    technologistName: "Pooja Verma",
    suiteName: "128-Slice Multi-Detector CT Suite",
    outcome: "Completed",
    totalTurnaroundTimeMins: 24,
    completedAt: "2026-08-23T15:20:00Z",
    archivedAt: "2026-08-23T15:35:00Z",
    dicomViewerUrl: "/radiology/viewer/rad_101",
  },
  {
    id: "hist_rad_03",
    orderId: "rad_hist_903",
    orderNo: "RAD-2026-8703",
    patientName: "Gopal Krishna",
    uhid: "UHID-2026-4491",
    modality: "MRI",
    bodyPart: "Cardiac MRI with Late Gadolinium Enhancement",
    orderingDoctor: "Dr. Arvind Swaminathan",
    radiologistName: "Dr. Sunita Kulkarni",
    technologistName: "Amit Shinde",
    suiteName: "3.0 Tesla High-Field MRI Suite",
    outcome: "Cancelled",
    cancellationReason: "Patient exhibited severe claustrophobia during coil placement; rescheduled with oral anxiolytic.",
    totalTurnaroundTimeMins: 15,
    completedAt: "2026-08-23T14:10:00Z",
    archivedAt: "2026-08-23T14:15:00Z",
  },
];
