import {
  HospitalReportDefinition,
  ScheduledReportConfig,
  HospitalReportCategory,
} from "@/hospital-admin/lib/types";

// ==========================================
// 17.1 THE 12 PRE-BUILT PRD HOSPITAL REPORTS
// ==========================================
export const mockHospitalReports: HospitalReportDefinition[] = [
  // 1. Patient Flow
  {
    id: "rep_01",
    code: "REP-FLOW-01",
    title: "Hospital Patient Flow & Queue Performance",
    category: "Patient Flow",
    description: "OPD consultation volume, mean triage wait times, inpatient admission vs discharge velocity, inter-facility transfers, and emergency turnaround times.",
    sensitivity: "Standard Operational",
    requiredPermission: "reports.operational.view",
    defaultPeriod: "Current Month",
    kpis: [
      { label: "Total OPD Footfall", value: "12,480", delta: "+8.4% vs last month", trend: "up", isPositive: true },
      { label: "Avg OPD Wait Time", value: "18.5 mins", delta: "-3.2 mins", trend: "down", isPositive: true },
      { label: "Admissions / Discharges", value: "482 / 456", delta: "Net +26 Bed Inflow", trend: "neutral" },
      { label: "Emergency Response TAT", value: "4.2 mins", delta: "-0.8 mins", trend: "down", isPositive: true },
    ],
    chartType: "composed",
    chartKeys: [
      { dataKey: "opdVolume", name: "OPD Volume", color: "#0d9488", type: "bar" },
      { dataKey: "admissions", name: "IPD Admissions", color: "#0284c7", type: "bar" },
      { dataKey: "avgWaitMinutes", name: "Avg Wait (mins)", color: "#f59e0b", type: "line" },
    ],
    chartData: [
      { period: "Mon (Aug 18)", opdVolume: 480, admissions: 22, avgWaitMinutes: 24 },
      { period: "Tue (Aug 19)", opdVolume: 510, admissions: 28, avgWaitMinutes: 19 },
      { period: "Wed (Aug 20)", opdVolume: 495, admissions: 25, avgWaitMinutes: 17 },
      { period: "Thu (Aug 21)", opdVolume: 530, admissions: 30, avgWaitMinutes: 21 },
      { period: "Fri (Aug 22)", opdVolume: 560, admissions: 34, avgWaitMinutes: 18 },
      { period: "Sat (Aug 23)", opdVolume: 620, admissions: 38, avgWaitMinutes: 22 },
      { period: "Sun (Aug 24)", opdVolume: 290, admissions: 18, avgWaitMinutes: 12 },
    ],
    tableColumns: [
      { key: "department", label: "Specialty / Wing" },
      { key: "opdFootfall", label: "OPD Footfall", isNumeric: true },
      { key: "avgWaitTime", label: "Mean Wait Time" },
      { key: "ipdAdmitted", label: "Admissions", isNumeric: true },
      { key: "ipdDischarged", label: "Discharges", isNumeric: true },
      { key: "transfers", label: "Transfers", isNumeric: true },
      { key: "flowStatus", label: "Flow Velocity", isBadge: true },
    ],
    tableData: [
      { department: "General Medicine", opdFootfall: 1420, avgWaitTime: "16.4 mins", ipdAdmitted: 68, ipdDischarged: 64, transfers: 4, flowStatus: "Optimal" },
      { department: "Cardiology", opdFootfall: 1180, avgWaitTime: "22.1 mins", ipdAdmitted: 84, ipdDischarged: 79, transfers: 6, flowStatus: "Moderate" },
      { department: "Orthopaedics & Joint Care", opdFootfall: 980, avgWaitTime: "14.8 mins", ipdAdmitted: 52, ipdDischarged: 48, transfers: 2, flowStatus: "Optimal" },
      { department: "Paediatrics & Neonatology", opdFootfall: 850, avgWaitTime: "12.0 mins", ipdAdmitted: 36, ipdDischarged: 34, transfers: 1, flowStatus: "Optimal" },
      { department: "Emergency & Trauma Bay", opdFootfall: 1890, avgWaitTime: "3.8 mins", ipdAdmitted: 142, ipdDischarged: 110, transfers: 14, flowStatus: "High Volume" },
      { department: "Neurology & Neurosurgery", opdFootfall: 640, avgWaitTime: "26.5 mins", ipdAdmitted: 44, ipdDischarged: 38, transfers: 3, flowStatus: "Congested" },
      { department: "Obstetrics & Gynaecology", opdFootfall: 780, avgWaitTime: "15.2 mins", ipdAdmitted: 56, ipdDischarged: 53, transfers: 0, flowStatus: "Optimal" },
    ],
  },

  // 2. Bed / Ward
  {
    id: "rep_02",
    code: "REP-BED-02",
    title: "Bed Utilization, Turnover & ALOS Analysis",
    category: "Bed/Ward",
    description: "Ward and ICU occupancy rates, bed turnover ratio, blocked beds maintenance, and average length of stay (ALOS) across departments.",
    sensitivity: "Standard Operational",
    requiredPermission: "reports.wards.view",
    defaultPeriod: "Current Month",
    kpis: [
      { label: "Overall Bed Occupancy", value: "88.4%", delta: "+2.1% vs target", trend: "up", isPositive: true },
      { label: "Avg Length of Stay (ALOS)", value: "3.8 Days", delta: "-0.3 days", trend: "down", isPositive: true },
      { label: "Monthly Bed Turnover", value: "4.6x", delta: "Benchmark: 4.2x", trend: "up", isPositive: true },
      { label: "Blocked / Isolation Beds", value: "6 Beds", delta: "Maintenance/Sanitize", trend: "neutral" },
    ],
    chartType: "bar",
    chartKeys: [
      { dataKey: "occupied", name: "Occupied Beds", color: "#0d9488" },
      { dataKey: "available", name: "Available Beds", color: "#94a3b8" },
    ],
    chartData: [
      { period: "Medical ICU", occupied: 12, available: 0 },
      { period: "Surgical ICU", occupied: 10, available: 2 },
      { period: "CCU (Cardiac)", occupied: 8, available: 2 },
      { period: "Ward 1 (General)", occupied: 45, available: 5 },
      { period: "Ward 2 (Surgical)", occupied: 42, available: 8 },
      { period: "Ward 3 (Private)", occupied: 28, available: 4 },
      { period: "Emergency Bay", occupied: 16, available: 4 },
    ],
    tableColumns: [
      { key: "wardName", label: "Ward / Unit Name" },
      { key: "totalBeds", label: "Capacity", isNumeric: true },
      { key: "occupiedBeds", label: "Occupied", isNumeric: true },
      { key: "occupancyRate", label: "Occupancy %" },
      { key: "alosDays", label: "Avg ALOS" },
      { key: "turnoverRate", label: "Turnover (x)" },
      { key: "status", label: "Capacity Status", isBadge: true },
    ],
    tableData: [
      { wardName: "Medical Intensive Care Unit (MICU)", totalBeds: 12, occupiedBeds: 12, occupancyRate: "100.0%", alosDays: "4.8 Days", turnoverRate: "5.2x", status: "Critical Shortage" },
      { wardName: "Surgical ICU (SICU)", totalBeds: 12, occupiedBeds: 10, occupancyRate: "83.3%", alosDays: "3.2 Days", turnoverRate: "6.1x", status: "Optimal" },
      { wardName: "Coronary Care Unit (CCU)", totalBeds: 10, occupiedBeds: 8, occupancyRate: "80.0%", alosDays: "2.9 Days", turnoverRate: "7.0x", status: "Optimal" },
      { wardName: "Male Surgical Ward (Ward 2)", totalBeds: 50, occupiedBeds: 42, occupancyRate: "84.0%", alosDays: "4.1 Days", turnoverRate: "4.4x", status: "Optimal" },
      { wardName: "Female Medical Ward (Ward 1)", totalBeds: 50, occupiedBeds: 45, occupancyRate: "90.0%", alosDays: "3.6 Days", turnoverRate: "4.8x", status: "High Occupancy" },
      { wardName: "Deluxe & Private Suites", totalBeds: 32, occupiedBeds: 28, occupancyRate: "87.5%", alosDays: "3.0 Days", turnoverRate: "5.0x", status: "Optimal" },
    ],
  },

  // 3. Doctors
  {
    id: "rep_03",
    code: "REP-DOC-03",
    title: "Physician Productivity, Slots & Affiliations",
    category: "Doctors",
    description: "Doctor consultation volume, appointment slot utilization, patient waiting times, cancellation frequencies, and hospital accreditation affiliations.",
    sensitivity: "Standard Operational",
    requiredPermission: "reports.doctors.view",
    defaultPeriod: "Current Month",
    kpis: [
      { label: "Active Doctors on Duty", value: "48 Consultants", delta: "100% Affiliated", trend: "up", isPositive: true },
      { label: "Slot Utilization Rate", value: "92.4%", delta: "+4.1% vs benchmark", trend: "up", isPositive: true },
      { label: "Appointment Cancellation", value: "2.8%", delta: "Benchmark <5%", trend: "down", isPositive: true },
      { label: "Avg Consult Time", value: "14.2 mins", delta: "High Clinical Quality", trend: "neutral" },
    ],
    chartType: "bar",
    chartKeys: [
      { dataKey: "consultations", name: "Completed Consults", color: "#0d9488" },
      { dataKey: "cancellations", name: "Cancellations", color: "#f43f5e" },
    ],
    chartData: [
      { period: "Dr. Arvind Swaminathan", consultations: 340, cancellations: 8 },
      { period: "Dr. Kavita Verma", consultations: 310, cancellations: 12 },
      { period: "Dr. Ramesh Sharma", consultations: 290, cancellations: 6 },
      { period: "Dr. Ananya Patel", consultations: 275, cancellations: 5 },
      { period: "Dr. Rohan Mehta", consultations: 260, cancellations: 9 },
      { period: "Dr. Sunita Kulkarni", consultations: 240, cancellations: 4 },
    ],
    tableColumns: [
      { key: "doctorName", label: "Doctor Name" },
      { key: "specialty", label: "Specialty" },
      { key: "consultations", label: "Consults", isNumeric: true },
      { key: "slotUtilization", label: "Slot Util %" },
      { key: "avgWaitTime", label: "Avg Wait" },
      { key: "cancellationRate", label: "Cancel Rate" },
      { key: "affiliation", label: "Affiliation", isBadge: true },
    ],
    tableData: [
      { doctorName: "Dr. Arvind Swaminathan", specialty: "General & Laparoscopic Surgery", consultations: 340, slotUtilization: "96.2%", avgWaitTime: "12m", cancellationRate: "2.3%", affiliation: "Full-Time Senior Consultant" },
      { doctorName: "Dr. Kavita Verma", specialty: "Cardiology & Interventional", consultations: 310, slotUtilization: "94.0%", avgWaitTime: "24m", cancellationRate: "3.7%", affiliation: "Full-Time Senior Consultant" },
      { doctorName: "Dr. Ramesh Sharma", specialty: "Orthopaedics & Joint Replacement", consultations: 290, slotUtilization: "91.5%", avgWaitTime: "14m", cancellationRate: "2.0%", affiliation: "Full-Time Consultant" },
      { doctorName: "Dr. Ananya Patel", specialty: "Critical Care & Pulmonology", consultations: 275, slotUtilization: "89.0%", avgWaitTime: "10m", cancellationRate: "1.8%", affiliation: "Full-Time Consultant" },
      { doctorName: "Dr. Rohan Mehta", specialty: "Internal Medicine & Diabetology", consultations: 260, slotUtilization: "88.4%", avgWaitTime: "18m", cancellationRate: "3.3%", affiliation: "Visiting Specialist" },
      { doctorName: "Dr. Sunita Kulkarni", specialty: "Radiology & Neuroradiology", consultations: 240, slotUtilization: "95.0%", avgWaitTime: "8m", cancellationRate: "1.6%", affiliation: "Full-Time Senior Consultant" },
    ],
  },

  // 4. Nursing
  {
    id: "rep_04",
    code: "REP-NURSE-04",
    title: "Nursing Workforce, Workload & Shift Handovers",
    category: "Nursing",
    description: "Ward nurse-to-patient staffing ratios, attendance metrics, medication administration task completion, and formal shift handover compliance.",
    sensitivity: "Standard Operational",
    requiredPermission: "reports.nursing.view",
    defaultPeriod: "Current Month",
    kpis: [
      { label: "Active Nursing Staff", value: "142 Nurses", delta: "3 Shifts / 24x7", trend: "up", isPositive: true },
      { label: "Mean Staffing Ratio", value: "1:5.4 Patients", delta: "NABH Compliant", trend: "neutral" },
      { label: "Medication Admin Task TAT", value: "98.6%", delta: "+1.2% adherence", trend: "up", isPositive: true },
      { label: "Shift Handover Compliance", value: "100%", delta: "Zero gaps recorded", trend: "up", isPositive: true },
    ],
    chartType: "line",
    chartKeys: [
      { dataKey: "attendanceRate", name: "Attendance %", color: "#0d9488" },
      { dataKey: "taskCompletion", name: "Task Completion %", color: "#0284c7" },
    ],
    chartData: [
      { period: "Week 1", attendanceRate: 97.2, taskCompletion: 98.1 },
      { period: "Week 2", attendanceRate: 95.8, taskCompletion: 98.4 },
      { period: "Week 3", attendanceRate: 96.5, taskCompletion: 99.0 },
      { period: "Week 4", attendanceRate: 98.0, taskCompletion: 98.6 },
    ],
    tableColumns: [
      { key: "wardStation", label: "Station / Floor" },
      { key: "staffAllocated", label: "Nurses on Duty", isNumeric: true },
      { key: "patientLoad", label: "Patient Load", isNumeric: true },
      { key: "actualRatio", label: "Nurse:Patient Ratio" },
      { key: "attendance", label: "Attendance %" },
      { key: "handoverStatus", label: "Handover Status", isBadge: true },
    ],
    tableData: [
      { wardStation: "Station A — MICU", staffAllocated: 12, patientLoad: 12, actualRatio: "1:1 (Critical)", attendance: "100%", handoverStatus: "100% Verified" },
      { wardStation: "Station B — SICU", staffAllocated: 10, patientLoad: 10, actualRatio: "1:1 (Critical)", attendance: "98.2%", handoverStatus: "100% Verified" },
      { wardStation: "Station C — Ward 1 (General)", staffAllocated: 8, patientLoad: 45, actualRatio: "1:5.6", attendance: "96.0%", handoverStatus: "100% Verified" },
      { wardStation: "Station D — Ward 2 (Surgical)", staffAllocated: 7, patientLoad: 42, actualRatio: "1:6.0", attendance: "94.5%", handoverStatus: "100% Verified" },
      { wardStation: "Station E — Emergency ER", staffAllocated: 14, patientLoad: 18, actualRatio: "1:1.3", attendance: "98.8%", handoverStatus: "100% Verified" },
    ],
  },

  // 5. Reception
  {
    id: "rep_05",
    code: "REP-RECEP-05",
    title: "Reception, Registration & Queue SLA",
    category: "Reception",
    description: "Daily patient registration volume, token wait time performance, appointment no-shows, and exception token handling across counters.",
    sensitivity: "Standard Operational",
    requiredPermission: "reports.reception.view",
    defaultPeriod: "Current Month",
    kpis: [
      { label: "Total Registrations", value: "14,890", delta: "+6.8% vs last month", trend: "up", isPositive: true },
      { label: "Avg Token Wait Time", value: "6.4 mins", delta: "-1.8 mins SLA", trend: "down", isPositive: true },
      { label: "Appointment No-Shows", value: "4.8%", delta: "SLA Target <8%", trend: "down", isPositive: true },
      { label: "VIP / Priority Handled", value: "320 Tokens", delta: "100% fast-tracked", trend: "neutral" },
    ],
    chartType: "area",
    chartKeys: [
      { dataKey: "registered", name: "Registrations", color: "#0d9488" },
      { dataKey: "noShows", name: "No-Shows", color: "#f43f5e" },
    ],
    chartData: [
      { period: "08:00 - 10:00", registered: 140, noShows: 8 },
      { period: "10:00 - 12:00", registered: 220, noShows: 12 },
      { period: "12:00 - 14:00", registered: 110, noShows: 6 },
      { period: "14:00 - 16:00", registered: 180, noShows: 9 },
      { period: "16:00 - 18:00", registered: 195, noShows: 7 },
      { period: "18:00 - 20:00", registered: 90, noShows: 4 },
    ],
    tableColumns: [
      { key: "counterName", label: "Counter / Desk" },
      { key: "staffName", label: "Duty Receptionist" },
      { key: "tokensServed", label: "Tokens Served", isNumeric: true },
      { key: "avgServiceTime", label: "Avg Service Time" },
      { key: "queueWait", label: "Queue Wait" },
      { key: "exceptionsHandled", label: "Exceptions", isNumeric: true },
      { key: "slaStatus", label: "SLA Performance", isBadge: true },
    ],
    tableData: [
      { counterName: "Main Reception Desk 1", staffName: "Rajesh Kadam", tokensServed: 420, avgServiceTime: "2.1 mins", queueWait: "5.4 mins", exceptionsHandled: 8, slaStatus: "Excellent" },
      { counterName: "Main Reception Desk 2", staffName: "Priya Nair", tokensServed: 390, avgServiceTime: "2.4 mins", queueWait: "6.2 mins", exceptionsHandled: 12, slaStatus: "Optimal" },
      { counterName: "Diagnostics & Lab Desk", staffName: "Meenakshi Sundaram", tokensServed: 310, avgServiceTime: "1.8 mins", queueWait: "4.8 mins", exceptionsHandled: 4, slaStatus: "Excellent" },
      { counterName: "Emergency Triage Desk", staffName: "Vikram Gaikwad", tokensServed: 180, avgServiceTime: "1.2 mins", queueWait: "1.5 mins", exceptionsHandled: 18, slaStatus: "Fast-Tracked" },
    ],
  },

  // 6. Surgery
  {
    id: "rep_06",
    code: "REP-SURG-06",
    title: "Operation Theatre (OT) Utilization & Turnaround",
    category: "Surgery",
    description: "OT room utilization percentage, surgical case readiness, cancellation analysis, intra-op blockers, and room cleanup turnaround times.",
    sensitivity: "Clinical Governance",
    requiredPermission: "reports.surgery.view",
    defaultPeriod: "Current Month",
    kpis: [
      { label: "OT Complex Utilization", value: "84.6%", delta: "Benchmark >80%", trend: "up", isPositive: true },
      { label: "Cases Performed (MTD)", value: "312 Surgeries", delta: "+14 cases vs target", trend: "up", isPositive: true },
      { label: "Surgery Cancellation Rate", value: "1.8%", delta: "Benchmark <3%", trend: "down", isPositive: true },
      { label: "Avg Room Turnaround (TAT)", value: "24 mins", delta: "-4 mins SLA", trend: "down", isPositive: true },
    ],
    chartType: "bar",
    chartKeys: [
      { dataKey: "electiveCases", name: "Elective Cases", color: "#0d9488" },
      { dataKey: "emergencyCases", name: "Emergency Cases", color: "#f59e0b" },
    ],
    chartData: [
      { period: "OT 1 (Cardiac Suite)", electiveCases: 42, emergencyCases: 8 },
      { period: "OT 2 (Neuro & Spine)", electiveCases: 38, emergencyCases: 12 },
      { period: "OT 3 (Orthopaedic)", electiveCases: 54, emergencyCases: 6 },
      { period: "OT 4 (General & Lap)", electiveCases: 62, emergencyCases: 14 },
      { period: "OT 5 (Gynecology)", electiveCases: 48, emergencyCases: 10 },
      { period: "OT 6 (Emergency 24x7)", electiveCases: 6, emergencyCases: 32 },
    ],
    tableColumns: [
      { key: "otRoom", label: "OT Theatre" },
      { key: "specialty", label: "Dedicated Specialty" },
      { key: "totalCases", label: "Total Cases", isNumeric: true },
      { key: "utilizationRate", label: "Utilization %" },
      { key: "avgDuration", label: "Avg Duration" },
      { key: "blockersEncountered", label: "Blockers", isNumeric: true },
      { key: "readinessStatus", label: "Case Readiness", isBadge: true },
    ],
    tableData: [
      { otRoom: "OT 1 — Modular Cardiac", specialty: "Cardiothoracic & Vascular", totalCases: 50, utilizationRate: "88.2%", avgDuration: "3.4h", blockersEncountered: 0, readinessStatus: "98.5% Ready" },
      { otRoom: "OT 2 — Neuro Suite", specialty: "Neurosurgery & Cranial", totalCases: 50, utilizationRate: "86.0%", avgDuration: "4.1h", blockersEncountered: 1, readinessStatus: "96.0% Ready" },
      { otRoom: "OT 3 — Ortho Laminar", specialty: "Joint Replacement & Spine", totalCases: 60, utilizationRate: "85.4%", avgDuration: "2.2h", blockersEncountered: 0, readinessStatus: "99.0% Ready" },
      { otRoom: "OT 4 — Laparoscopic", specialty: "General & Bariatric", totalCases: 76, utilizationRate: "84.0%", avgDuration: "1.8h", blockersEncountered: 1, readinessStatus: "97.5% Ready" },
      { otRoom: "OT 5 — Maternity OT", specialty: "Obstetrics & Caesarean", totalCases: 58, utilizationRate: "78.5%", avgDuration: "1.2h", blockersEncountered: 0, readinessStatus: "99.5% Ready" },
      { otRoom: "OT 6 — Emergency Trauma", specialty: "Polytrauma & Acute", totalCases: 38, utilizationRate: "81.0%", avgDuration: "2.5h", blockersEncountered: 0, readinessStatus: "100% Ready" },
    ],
  },

  // 7. Diagnostics
  {
    id: "rep_07",
    code: "REP-DIAG-07",
    title: "Diagnostics & Laboratory Turnaround SLA",
    category: "Diagnostics",
    description: "Pathology, biochemistry, and radiology investigation volumes, routine vs STAT turnaround times (TAT), pending test backlog, and critical panic alert reports.",
    sensitivity: "Standard Operational",
    requiredPermission: "reports.diagnostics.view",
    defaultPeriod: "Current Month",
    kpis: [
      { label: "Total Tests Conducted", value: "28,450", delta: "+11.2% vs last month", trend: "up", isPositive: true },
      { label: "Routine Lab Mean TAT", value: "1.8 Hours", delta: "-0.4h vs target", trend: "down", isPositive: true },
      { label: "STAT Emergency TAT", value: "28 mins", delta: "SLA <45 mins", trend: "down", isPositive: true },
      { label: "Critical Panic Reports", value: "84 Flags", delta: "100% Alerted Clinicians", trend: "neutral" },
    ],
    chartType: "line",
    chartKeys: [
      { dataKey: "routineTatHours", name: "Routine TAT (Hours)", color: "#0d9488" },
      { dataKey: "statTatMins", name: "STAT TAT (Minutes / 10)", color: "#f59e0b" },
    ],
    chartData: [
      { period: "Biochemistry", routineTatHours: 1.6, statTatMins: 2.4 },
      { period: "Haematology", routineTatHours: 1.2, statTatMins: 2.1 },
      { period: "Microbiology", routineTatHours: 24.0, statTatMins: 4.8 },
      { period: "Histopathology", routineTatHours: 48.0, statTatMins: 8.0 },
      { period: "Radiology (CT/MRI)", routineTatHours: 2.2, statTatMins: 3.2 },
      { period: "Ultrasound & Echo", routineTatHours: 1.4, statTatMins: 1.8 },
    ],
    tableColumns: [
      { key: "modality", label: "Diagnostic Department" },
      { key: "volumeCompleted", label: "Completed Tests", isNumeric: true },
      { key: "pendingBacklog", label: "Pending Tests", isNumeric: true },
      { key: "avgTat", label: "Mean TAT" },
      { key: "criticalFindings", label: "Critical Alerts", isNumeric: true },
      { key: "slaCompliance", label: "SLA Adherence", isBadge: true },
    ],
    tableData: [
      { modality: "Clinical Biochemistry", volumeCompleted: 11200, pendingBacklog: 18, avgTat: "1.6 Hours", criticalFindings: 34, slaCompliance: "99.2% Compliant" },
      { modality: "Haematology & Coagulation", volumeCompleted: 8400, pendingBacklog: 12, avgTat: "1.2 Hours", criticalFindings: 22, slaCompliance: "99.6% Compliant" },
      { modality: "Microbiology & Cultures", volumeCompleted: 2100, pendingBacklog: 45, avgTat: "24.0 Hours", criticalFindings: 8, slaCompliance: "96.4% Compliant" },
      { modality: "Radiology (128-Slice CT)", volumeCompleted: 1850, pendingBacklog: 6, avgTat: "2.1 Hours", criticalFindings: 14, slaCompliance: "98.8% Compliant" },
      { modality: "Radiology (3.0 Tesla MRI)", volumeCompleted: 1420, pendingBacklog: 8, avgTat: "2.5 Hours", criticalFindings: 6, slaCompliance: "97.5% Compliant" },
    ],
  },

  // 8. Pharmacy
  {
    id: "rep_08",
    code: "REP-PHARM-08",
    title: "Pharmacy Stock, Dispensing & Expiry Governance",
    category: "Pharmacy",
    description: "Medication dispensing volume, FEFO batch rotation compliance, Schedule H1 narcotic logs, stockout alerts, and quarantined expiry tracking.",
    sensitivity: "Standard Operational",
    requiredPermission: "reports.pharmacy.view",
    defaultPeriod: "Current Month",
    kpis: [
      { label: "Prescriptions Dispensed", value: "8,940 Orders", delta: "+5.4% vs last month", trend: "up", isPositive: true },
      { label: "Stockout Incidents", value: "0 Items", delta: "100% Availability", trend: "up", isPositive: true },
      { label: "Schedule H1 Regulated", value: "482 Dispensed", delta: "100% Verified Log", trend: "neutral" },
      { label: "Near-Expiry Value", value: "₹42,500", delta: "FEFO Promoted", trend: "down", isPositive: true },
    ],
    chartType: "bar",
    chartKeys: [
      { dataKey: "dispensedCount", name: "Dispensed Orders", color: "#0d9488" },
      { dataKey: "lowStockAlerts", name: "Low Stock Flags", color: "#f43f5e" },
    ],
    chartData: [
      { period: "Week 1", dispensedCount: 2150, lowStockAlerts: 4 },
      { period: "Week 2", dispensedCount: 2280, lowStockAlerts: 2 },
      { period: "Week 3", dispensedCount: 2210, lowStockAlerts: 1 },
      { period: "Week 4", dispensedCount: 2300, lowStockAlerts: 3 },
    ],
    tableColumns: [
      { key: "category", label: "Drug Classification" },
      { key: "skusManaged", label: "Active SKUs", isNumeric: true },
      { key: "totalStockValue", label: "Stock Valuation" },
      { key: "monthlyDispensed", label: "Dispensed", isNumeric: true },
      { key: "nearExpirySkus", label: "Near Expiry (60d)", isNumeric: true },
      { key: "stockHealth", label: "Inventory Health", isBadge: true },
    ],
    tableData: [
      { category: "Antibiotics & Anti-Infectives", skusManaged: 180, totalStockValue: "₹18,40,000", monthlyDispensed: 2450, nearExpirySkus: 2, stockHealth: "Optimal" },
      { category: "Cardiovascular & Antihypertensive", skusManaged: 140, totalStockValue: "₹14,20,000", monthlyDispensed: 2100, nearExpirySkus: 1, stockHealth: "Optimal" },
      { category: "Critical Emergency & Resuscitation", skusManaged: 65, totalStockValue: "₹8,90,000", monthlyDispensed: 890, nearExpirySkus: 0, stockHealth: "100% Stocked" },
      { category: "Schedule H1 & Narcotic Analgesics", skusManaged: 28, totalStockValue: "₹6,40,000", monthlyDispensed: 482, nearExpirySkus: 0, stockHealth: "Regulated Safe" },
      { category: "IV Infusions & Clinical Fluids", skusManaged: 45, totalStockValue: "₹5,10,000", monthlyDispensed: 3100, nearExpirySkus: 0, stockHealth: "High Turnover" },
    ],
  },

  // 9. Finance
  {
    id: "rep_09",
    code: "REP-FIN-09",
    title: "Hospital Revenue, Collections & TPA Claims Ledger",
    category: "Finance",
    description: "Departmental gross billings, daily cash desk collections, POS/digital payment receipts, pending patient receivables, refunds, and TPA cashless settlements.",
    sensitivity: "Confidential Financial",
    requiredPermission: "reports.finance.view",
    defaultPeriod: "Current Month",
    kpis: [
      { label: "Total Gross Revenue", value: "₹1,42,80,000", delta: "+12.4% vs target", trend: "up", isPositive: true },
      { label: "Daily Collections Realized", value: "₹1,18,50,000", delta: "83.0% Cash-In", trend: "up", isPositive: true },
      { label: "TPA Claims Settled", value: "₹28,90,000", delta: "89.4% Approval Ratio", trend: "up", isPositive: true },
      { label: "Total Refunds Processed", value: "₹1,24,000", delta: "0.8% of Total", trend: "down", isPositive: true },
    ],
    chartType: "composed",
    chartKeys: [
      { dataKey: "grossRevenue", name: "Gross Revenue (₹L)", color: "#0d9488", type: "bar" },
      { dataKey: "collections", name: "Realized Collections (₹L)", color: "#0284c7", type: "bar" },
      { dataKey: "tpaSettled", name: "TPA Settled (₹L)", color: "#f59e0b", type: "line" },
    ],
    chartData: [
      { period: "OPD Clinics", grossRevenue: 34.5, collections: 33.8, tpaSettled: 0.0 },
      { period: "IPD Wards", grossRevenue: 48.2, collections: 24.1, tpaSettled: 18.5 },
      { period: "OT Complex", grossRevenue: 32.0, collections: 16.0, tpaSettled: 10.4 },
      { period: "Diagnostics & Lab", grossRevenue: 15.6, collections: 15.2, tpaSettled: 0.0 },
      { period: "Pharmacy Sales", grossRevenue: 12.5, collections: 12.5, tpaSettled: 0.0 },
    ],
    tableColumns: [
      { key: "department", label: "Billing Stream" },
      { key: "billedAmount", label: "Gross Billed" },
      { key: "cashCollected", label: "Cash Collected" },
      { key: "digitalCollected", label: "Digital / POS" },
      { key: "tpaClaimed", label: "TPA Claims" },
      { key: "outstandingDues", label: "Outstanding" },
      { key: "recoveryStatus", label: "Collection Health", isBadge: true },
    ],
    tableData: [
      { department: "Outpatient Department (OPD)", billedAmount: "₹34,50,000", cashCollected: "₹12,40,000", digitalCollected: "₹21,40,000", tpaClaimed: "₹0", outstandingDues: "₹70,000", recoveryStatus: "98.0% Realized" },
      { department: "Inpatient Admissions (IPD)", billedAmount: "₹48,20,000", cashCollected: "₹10,50,000", digitalCollected: "₹13,60,000", tpaClaimed: "₹18,50,000", outstandingDues: "₹5,60,000", recoveryStatus: "88.4% Realized" },
      { department: "Operation Theatres (OT)", billedAmount: "₹32,00,000", cashCollected: "₹6,20,000", digitalCollected: "₹9,80,000", tpaClaimed: "₹10,40,000", outstandingDues: "₹5,60,000", recoveryStatus: "82.5% Realized" },
      { department: "Diagnostics & Imaging", billedAmount: "₹15,60,000", cashCollected: "₹4,80,000", digitalCollected: "₹10,40,000", tpaClaimed: "₹0", outstandingDues: "₹40,000", recoveryStatus: "97.4% Realized" },
      { department: "Central Pharmacy Dispensary", billedAmount: "₹12,50,000", cashCollected: "₹4,50,000", digitalCollected: "₹8,00,000", tpaClaimed: "₹0", outstandingDues: "₹0", recoveryStatus: "100% Realized" },
    ],
  },

  // 10. Vendor
  {
    id: "rep_10",
    code: "REP-VEND-10",
    title: "Vendor Procurement, Quotes & Delivery SLA",
    category: "Vendor",
    description: "Purchase order lifecycle, supplier quote turnaround times, delivery timeliness SLA, transit delay analytics, and defective batch return audits.",
    sensitivity: "Standard Operational",
    requiredPermission: "reports.vendors.view",
    defaultPeriod: "Current Month",
    kpis: [
      { label: "Active Suppliers", value: "34 Vendors", delta: "100% Quality Audited", trend: "up", isPositive: true },
      { label: "Purchase Orders Value", value: "₹42,50,000", delta: "28 Active POs", trend: "neutral" },
      { label: "On-Time Delivery SLA", value: "94.2%", delta: "+2.1% compliance", trend: "up", isPositive: true },
      { label: "Mean Quote Turnaround", value: "1.4 Days", delta: "Fast-Track Sourcing", trend: "down", isPositive: true },
    ],
    chartType: "bar",
    chartKeys: [
      { dataKey: "onTimeOrders", name: "On-Time Deliveries", color: "#0d9488" },
      { dataKey: "delayedOrders", name: "Delayed Shipments", color: "#f43f5e" },
    ],
    chartData: [
      { period: "Cipla Healthcare", onTimeOrders: 14, delayedOrders: 0 },
      { period: "Sun Pharma Distributors", onTimeOrders: 12, delayedOrders: 1 },
      { period: "Medtronic India", onTimeOrders: 8, delayedOrders: 0 },
      { period: "Baxter Renal Care", onTimeOrders: 6, delayedOrders: 1 },
      { period: "Philips Healthcare", onTimeOrders: 4, delayedOrders: 0 },
    ],
    tableColumns: [
      { key: "vendorName", label: "Supplier / Distributor" },
      { key: "category", label: "Supply Category" },
      { key: "totalPoValue", label: "Total PO Value" },
      { key: "quoteTat", label: "Quote TAT" },
      { key: "onTimeRate", label: "On-Time Delivery" },
      { key: "delayedCount", label: "Delays", isNumeric: true },
      { key: "slaRating", label: "Vendor Rating", isBadge: true },
    ],
    tableData: [
      { vendorName: "Cipla Healthcare Distributors", category: "Pharmaceuticals", totalPoValue: "₹14,50,000", quoteTat: "1.2 Days", onTimeRate: "100.0%", delayedCount: 0, slaRating: "Tier-1 Gold" },
      { vendorName: "Sun Pharma Logistics", category: "Pharmaceuticals", totalPoValue: "₹11,80,000", quoteTat: "1.4 Days", onTimeRate: "92.3%", delayedCount: 1, slaRating: "Tier-1 Gold" },
      { vendorName: "Medtronic India Pvt Ltd", category: "Cath Lab Implants", totalPoValue: "₹8,40,000", quoteTat: "1.8 Days", onTimeRate: "100.0%", delayedCount: 0, slaRating: "Tier-1 Gold" },
      { vendorName: "Baxter Renal Healthcare", category: "Dialysis Consumables", totalPoValue: "₹4,60,000", quoteTat: "2.0 Days", onTimeRate: "85.7%", delayedCount: 1, slaRating: "Tier-2 Silver" },
      { vendorName: "Philips Healthcare India", category: "Biomedical Spares", totalPoValue: "₹3,20,000", quoteTat: "1.5 Days", onTimeRate: "100.0%", delayedCount: 0, slaRating: "Tier-1 Gold" },
    ],
  },

  // 11. Emergency
  {
    id: "rep_11",
    code: "REP-EMERG-11",
    title: "Emergency SOS Activations & Ambulance Response",
    category: "Emergency",
    description: "Code Blue activations, trauma alert response latencies, ambulance dispatch trip durations, and resuscitation outcome transfers.",
    sensitivity: "Clinical Governance",
    requiredPermission: "reports.emergency.view",
    defaultPeriod: "Current Month",
    kpis: [
      { label: "Emergency SOS Triggers", value: "24 Code Activations", delta: "100% Dispatched", trend: "up", isPositive: true },
      { label: "Mean Acknowledgment TAT", value: "1.8 mins", delta: "-0.4 mins vs SLA", trend: "down", isPositive: true },
      { label: "Ambulance Dispatches", value: "48 Trips", delta: "Avg ETA: 12.4 mins", trend: "neutral" },
      { label: "Successful Stabilization", value: "95.8%", delta: "Exceeds NABH Target", trend: "up", isPositive: true },
    ],
    chartType: "area",
    chartKeys: [
      { dataKey: "sosCount", name: "SOS Alerts", color: "#f43f5e" },
      { dataKey: "ambulanceTrips", name: "Ambulance Dispatches", color: "#0284c7" },
    ],
    chartData: [
      { period: "Week 1", sosCount: 6, ambulanceTrips: 12 },
      { period: "Week 2", sosCount: 8, ambulanceTrips: 14 },
      { period: "Week 3", sosCount: 5, ambulanceTrips: 10 },
      { period: "Week 4", sosCount: 5, ambulanceTrips: 12 },
    ],
    tableColumns: [
      { key: "incidentType", label: "Emergency Classification" },
      { key: "totalTriggers", label: "Activations", isNumeric: true },
      { key: "avgAckTime", label: "Mean Ack Time" },
      { key: "avgDispatchTime", label: "Dispatch TAT" },
      { key: "transferredToIcu", label: "ICU Transfers", isNumeric: true },
      { key: "dischargedStabilized", label: "Stabilized", isNumeric: true },
      { key: "outcomeStatus", label: "Outcome Quality", isBadge: true },
    ],
    tableData: [
      { incidentType: "Code Blue (Cardiac Arrest)", totalTriggers: 12, avgAckTime: "1.2 mins", avgDispatchTime: "2.4 mins", transferredToIcu: 10, dischargedStabilized: 2, outcomeStatus: "100% Resuscitated" },
      { incidentType: "Code Red (Fire / Safety Hazard)", totalTriggers: 2, avgAckTime: "0.8 mins", avgDispatchTime: "1.5 mins", transferredToIcu: 0, dischargedStabilized: 0, outcomeStatus: "Contained Zero Damage" },
      { incidentType: "Polytrauma Highway Dispatch", totalTriggers: 8, avgAckTime: "2.1 mins", avgDispatchTime: "3.8 mins", transferredToIcu: 6, dischargedStabilized: 2, outcomeStatus: "Optimal Triage" },
      { incidentType: "Acute Stroke Golden Hour", totalTriggers: 6, avgAckTime: "1.5 mins", avgDispatchTime: "2.0 mins", transferredToIcu: 5, dischargedStabilized: 1, outcomeStatus: "Thrombolysis Verified" },
    ],
  },

  // 12. Security
  {
    id: "rep_12",
    code: "REP-SEC-12",
    title: "Security Audits, Access Logs & Break-Glass Events",
    category: "Security",
    description: "User authentication anomalies, role permission changes, emergency break-glass override logs, and physical perimeter access triggers.",
    sensitivity: "Restricted Security",
    requiredPermission: "reports.security.view",
    defaultPeriod: "Current Month",
    kpis: [
      { label: "Total Login Events", value: "32,450", delta: "100% MFA Protected", trend: "up", isPositive: true },
      { label: "Failed Auth Anomalies", value: "14 Blocks", delta: "IPs Auto-Blacklisted", trend: "down", isPositive: true },
      { label: "Break-Glass Overrides", value: "4 Events", delta: "100% Medical Justified", trend: "neutral" },
      { label: "Role Permission Updates", value: "8 Changes", delta: "Admin Signed Off", trend: "neutral" },
    ],
    chartType: "bar",
    chartKeys: [
      { dataKey: "authSuccess", name: "Authenticated Logins (x100)", color: "#0d9488" },
      { dataKey: "authFailed", name: "Security Flags", color: "#f43f5e" },
    ],
    chartData: [
      { period: "Mon (Aug 18)", authSuccess: 48, authFailed: 2 },
      { period: "Tue (Aug 19)", authSuccess: 52, authFailed: 1 },
      { period: "Wed (Aug 20)", authSuccess: 49, authFailed: 3 },
      { period: "Thu (Aug 21)", authSuccess: 54, authFailed: 0 },
      { period: "Fri (Aug 22)", authSuccess: 56, authFailed: 4 },
      { period: "Sat (Aug 23)", authSuccess: 42, authFailed: 2 },
      { period: "Sun (Aug 24)", authSuccess: 24, authFailed: 2 },
    ],
    tableColumns: [
      { key: "eventType", label: "Security Event Type" },
      { key: "severity", label: "Risk Severity", isBadge: true },
      { key: "actorRole", label: "Triggered By / Role" },
      { key: "targetResource", label: "Target Resource" },
      { key: "eventCount", label: "Occurrences", isNumeric: true },
      { key: "resolutionAction", label: "Audit Action Taken" },
    ],
    tableData: [
      { eventType: "Emergency Break-Glass Access", severity: "High", actorRole: "Dr. Ananya Patel (ICU)", targetResource: "Inpatient Confidential History (P-9102)", eventCount: 2, resolutionAction: "Certified Medical Emergency Override" },
      { eventType: "Pharmacy Vault Biometric Fail", severity: "Critical", actorRole: "Unknown Tag #4921", targetResource: "Schedule H1 Cold Vault Door", eventCount: 3, resolutionAction: "Sensor Rebooted & Verified by Chief Security" },
      { eventType: "Billing Role Privilege Update", severity: "Medium", actorRole: "Hospital Admin (Delegated)", targetResource: "Staff Billing Permissions Matrix", eventCount: 4, resolutionAction: "Delegation Audit Token Logged" },
      { eventType: "MFA Authentication Lockout", severity: "Low", actorRole: "Receptionist Rajesh Kadam", targetResource: "OPD Token Station 1", eventCount: 5, resolutionAction: "MFA Token Reset & Identity Verified" },
    ],
  },
];

// ==========================================
// 17.2 PRE-CONFIGURED SCHEDULED REPORTS
// ==========================================
export const mockScheduledReports: ScheduledReportConfig[] = [
  {
    id: "sch_01",
    reportId: "rep_09",
    reportTitle: "Daily Cash Counter & Revenue Realization Summary",
    category: "Finance",
    frequency: "Daily",
    deliveryTime: "20:00",
    format: "PDF",
    recipients: ["finance.head@qlyno.health", "admin@qlyno.health"],
    enabled: true,
    lastSentAt: "2026-08-24T20:00:00Z",
    nextRunAt: "2026-08-25T20:00:00Z",
  },
  {
    id: "sch_02",
    reportId: "rep_02",
    reportTitle: "Weekly Hospital Bed Occupancy & ALOS Benchmark",
    category: "Bed/Ward",
    frequency: "Weekly",
    deliveryTime: "08:00",
    dayOfWeek: "Monday",
    format: "PDF",
    recipients: ["medical.superintendent@qlyno.health", "admin@qlyno.health"],
    enabled: true,
    lastSentAt: "2026-08-18T08:00:00Z",
    nextRunAt: "2026-08-25T08:00:00Z",
  },
  {
    id: "sch_03",
    reportId: "rep_06",
    reportTitle: "Weekly Operation Theatre (OT) Utilization & Turnaround",
    category: "Surgery",
    frequency: "Weekly",
    deliveryTime: "09:00",
    dayOfWeek: "Monday",
    format: "Excel",
    recipients: ["ot.director@qlyno.health", "admin@qlyno.health"],
    enabled: true,
    lastSentAt: "2026-08-18T09:00:00Z",
    nextRunAt: "2026-08-25T09:00:00Z",
  },
  {
    id: "sch_04",
    reportId: "rep_08",
    reportTitle: "Monthly Pharmacy Stock, FEFO & Expiry Audit",
    category: "Pharmacy",
    frequency: "Monthly",
    deliveryTime: "18:00",
    format: "PDF",
    recipients: ["chief.pharmacist@qlyno.health", "procurement@qlyno.health"],
    enabled: true,
    lastSentAt: "2026-08-01T18:00:00Z",
    nextRunAt: "2026-09-01T18:00:00Z",
  },
  {
    id: "sch_05",
    reportId: "rep_11",
    reportTitle: "Daily Emergency SOS Activations & Paramedic Log",
    category: "Emergency",
    frequency: "Daily",
    deliveryTime: "07:30",
    format: "CSV",
    recipients: ["emergency.hod@qlyno.health", "admin@qlyno.health"],
    enabled: true,
    lastSentAt: "2026-08-24T07:30:00Z",
    nextRunAt: "2026-08-25T07:30:00Z",
  },
  {
    id: "sch_06",
    reportId: "rep_12",
    reportTitle: "Weekly Security Anomalies & Break-Glass Audit Trail",
    category: "Security",
    frequency: "Weekly",
    deliveryTime: "06:00",
    dayOfWeek: "Sunday",
    format: "PDF",
    recipients: ["security.head@qlyno.health", "compliance@qlyno.health"],
    enabled: true,
    lastSentAt: "2026-08-23T06:00:00Z",
    nextRunAt: "2026-08-30T06:00:00Z",
  },
];

// ==========================================
// 17.3 EXECUTIVE GROWTH & STRATEGIC ANALYTICS
// ==========================================
export const mockExecutiveAnalytics = {
  kpis: [
    { label: "Average Length of Stay (ALOS)", value: "3.8 Days", delta: "-0.4 days vs 2025", trend: "down", isPositive: true },
    { label: "Bed Turnover Ratio", value: "4.6x", delta: "Benchmark: 4.2x", trend: "up", isPositive: true },
    { label: "Revenue per Avail Bed (RevPAB)", value: "₹18,400", delta: "+8.5% YoY", trend: "up", isPositive: true },
    { label: "Case Mix Index (CMI)", value: "1.42", delta: "Tertiary Super Specialty", trend: "up", isPositive: true },
  ],
  revenueGrowth: [
    { period: "Q1 2025", revenue: 380, target: 360 },
    { period: "Q2 2025", revenue: 410, target: 400 },
    { period: "Q3 2025", revenue: 430, target: 420 },
    { period: "Q4 2025", revenue: 460, target: 450 },
    { period: "Q1 2026", revenue: 490, target: 475 },
    { period: "Q2 2026", revenue: 520, target: 500 },
  ],
  departmentCohort: [
    { name: "Cardiac Sciences", share: 28, growth: "+14.2%" },
    { name: "Neuro & Spine", share: 22, growth: "+11.8%" },
    { name: "Orthopaedics", share: 19, growth: "+8.4%" },
    { name: "Emergency & Critical Care", share: 16, growth: "+15.0%" },
    { name: "Gastro & General Surgery", share: 15, growth: "+6.2%" },
  ],
  qualityBenchmarks: [
    { indicator: "Hospital-Acquired Infection (HAI) Rate", hospitalScore: "0.4%", nationalBenchmark: "1.5%", status: "Exemplary" },
    { indicator: "30-Day Emergency Readmission Rate", hospitalScore: "2.1%", nationalBenchmark: "4.8%", status: "Exemplary" },
    { indicator: "Door-to-Balloon Time (Cath Lab)", hospitalScore: "42 mins", nationalBenchmark: "90 mins", status: "Gold Standard" },
    { indicator: "OT First Case On-Time Starts", hospitalScore: "94.8%", nationalBenchmark: "85.0%", status: "Exemplary" },
    { indicator: "Patient Net Promoter Score (NPS)", hospitalScore: "+78", nationalBenchmark: "+60", status: "Exemplary" },
  ],
};
