import {
  RadiologyOrder,
  MedicineItem,
  DispensingRecord,
  PharmacyAlert,
  PaymentTransaction,
  CashDrawerReport,
  InsuranceClaim,
  InventoryItem,
  StockIndent,
  BiomedicalAsset,
} from "@/hospital-admin/lib/types";

// ==========================================
// 12.2 RADIOLOGY & IMAGING ORDERS
// ==========================================
export const mockRadiologyOrders: RadiologyOrder[] = [
  {
    id: "rad_101",
    orderNo: "RAD-2026-8801",
    patientId: "P-1001",
    patientName: "Ramesh Sharma",
    modality: "CT Scan",
    bodyPart: "High-Resolution Chest (HRCT)",
    orderingDoctor: "Dr. Arvind Swaminathan",
    scheduledAt: "2026-08-22T11:00:00Z",
    status: "Report Ready",
    priority: "Urgent",
    roomName: "128-Slice CT Suite (Ground Floor)",
    radiologistName: "Dr. Vikram Seth (Consultant Radiologist)",
    reportNotes: "Bilateral lower lobe ground-glass opacities consistent with acute viral/bacterial pneumonitis. No pulmonary embolism.",
    dicomViewerUrl: "https://pacs.qlyno.health/viewer/study/RAD-8801",
  },
  {
    id: "rad_102",
    orderNo: "RAD-2026-8802",
    patientId: "P-9102",
    patientName: "Kavita Patil",
    modality: "MRI",
    bodyPart: "Brain with Contrast & MR Angio",
    orderingDoctor: "Dr. Kavita Verma",
    scheduledAt: "2026-08-22T10:15:00Z",
    status: "Report Ready",
    priority: "Stat Emergency",
    criticalFinding: true,
    criticalDetails: "Acute right MCA territory ischemic infarct with subtle mass effect. Immediate neuro-intervention alert triggered.",
    roomName: "3.0 Tesla MRI Suite (Basement 1)",
    radiologistName: "Dr. Sunita Kulkarni (Senior Neuroradiologist)",
    reportNotes: "Acute right middle cerebral artery territory infarction with diffusion restriction. Critical finding alerted directly to ICU team.",
    dicomViewerUrl: "https://pacs.qlyno.health/viewer/study/RAD-8802",
  },
  {
    id: "rad_103",
    orderNo: "RAD-2026-8803",
    patientId: "P-8821",
    patientName: "Arjun Gupta",
    modality: "X-Ray",
    bodyPart: "Right Hip & Pelvis AP/Lateral",
    orderingDoctor: "Dr. Ramesh Sharma",
    scheduledAt: "2026-08-22T14:30:00Z",
    status: "Scheduled",
    priority: "Routine",
    roomName: "Digital X-Ray Bay 2",
    radiologistName: "Dr. Vikram Seth",
    reportNotes: "Post-operative prosthetic alignment review.",
  },
  {
    id: "rad_104",
    orderNo: "RAD-2026-8804",
    patientId: "P-4001",
    patientName: "Anil Kapoor",
    modality: "Ultrasound",
    bodyPart: "2D Echocardiography & Doppler",
    orderingDoctor: "Dr. Ananya Patel",
    scheduledAt: "2026-08-22T15:00:00Z",
    status: "In Progress",
    priority: "Urgent",
    roomName: "Echo & Non-Invasive Cardio Bay 1",
    radiologistName: "Dr. Arvind Rao",
  },
  {
    id: "rad_105",
    orderNo: "RAD-2026-8805",
    patientId: "P-5001",
    patientName: "Tariq Mansoor",
    modality: "CT Scan",
    bodyPart: "Abdomen & Pelvis with IV Contrast",
    orderingDoctor: "Dr. Rohan Mehta",
    scheduledAt: "2026-08-22T16:30:00Z",
    status: "Report Pending",
    priority: "Routine",
    roomName: "128-Slice CT Suite (Ground Floor)",
    radiologistName: "Dr. Vikram Seth",
  },
];

// ==========================================
// 12.3 PHARMACY MEDICINE INVENTORY & DISPENSING
// ==========================================
export const mockMedicineInventory: MedicineItem[] = [
  {
    id: "med_01",
    name: "Augmentin 625mg",
    genericName: "Amoxicillin + Clavulanic Acid",
    category: "Antibiotics",
    dosageForm: "Tablet",
    stockLevel: 450,
    unit: "Strips (10x)",
    minThreshold: 100,
    expiryDate: "2027-06-30",
    batchNumber: "AUG-24B09",
    rackLocation: "Rack A-04",
    status: "In Stock",
    unitPrice: 210,
  },
  {
    id: "med_02",
    name: "Inj. Meropenem 1g",
    genericName: "Meropenem Trihydrate",
    category: "Antibiotics",
    dosageForm: "Injection / Vial",
    stockLevel: 18,
    unit: "Vials",
    minThreshold: 50,
    expiryDate: "2026-11-15",
    batchNumber: "MRP-23K11",
    rackLocation: "Cold Vault B-01",
    status: "Low Stock",
    unitPrice: 850,
    scheduleH1: true,
  },
  {
    id: "med_03",
    name: "Inj. Noradrenaline 4mg/2ml",
    genericName: "Norepinephrine Tartrate",
    category: "Critical Emergency",
    dosageForm: "Injection / Vial",
    stockLevel: 0,
    unit: "Ampoules",
    minThreshold: 40,
    expiryDate: "2026-10-30",
    batchNumber: "NOR-24E01",
    rackLocation: "Emergency Crash Shelf 1",
    status: "Out of Stock",
    unitPrice: 140,
  },
  {
    id: "med_04",
    name: "Inj. Heparin 25,000 IU",
    genericName: "Heparin Sodium Injection",
    category: "Cardiovascular",
    dosageForm: "Injection / Vial",
    stockLevel: 35,
    unit: "Vials",
    minThreshold: 30,
    expiryDate: "2026-09-05",
    batchNumber: "HEP-22H99",
    rackLocation: "Cold Vault A-02",
    status: "Expiring Soon",
    unitPrice: 320,
  },
  {
    id: "med_05",
    name: "Tab. Pantoprazole 40mg",
    genericName: "Pantoprazole Sodium",
    category: "Gastrointestinal",
    dosageForm: "Tablet",
    stockLevel: 1200,
    unit: "Strips (15x)",
    minThreshold: 200,
    expiryDate: "2027-12-31",
    batchNumber: "PAN-24A02",
    rackLocation: "Rack C-12",
    status: "In Stock",
    unitPrice: 95,
  },
  {
    id: "med_06",
    name: "Inj. Fentanyl Citrate 100mcg/2ml",
    genericName: "Fentanyl Citrate",
    category: "Anesthetics",
    dosageForm: "Injection / Vial",
    stockLevel: 80,
    unit: "Ampoules",
    minThreshold: 50,
    expiryDate: "2027-04-15",
    batchNumber: "FNT-24D08",
    rackLocation: "Narcotics Safe Box (Key Dual Auth)",
    status: "In Stock",
    unitPrice: 180,
    scheduleH1: true,
  },
];

export const mockDispensingLogs: DispensingRecord[] = [
  {
    id: "disp_101",
    prescriptionNo: "RX-2026-9041",
    patientId: "P-1001",
    patientName: "Ramesh Sharma",
    doctorName: "Dr. Ananya Patel",
    dispensedAt: "2026-08-22T10:45:00Z",
    pharmacistName: "Sunil Verma (Head Pharmacist)",
    items: [
      { medicineName: "Augmentin 625mg", quantity: 10, dosage: "1 tab TDS x 5 days" },
      { medicineName: "Tab. Pantoprazole 40mg", quantity: 10, dosage: "1 tab OD before food" },
    ],
    totalAmount: 305,
    status: "Completed",
  },
  {
    id: "disp_102",
    prescriptionNo: "RX-2026-9042",
    patientId: "P-9102",
    patientName: "Kavita Patil (ICU)",
    doctorName: "Dr. Kavita Verma",
    dispensedAt: "2026-08-22T11:15:00Z",
    pharmacistName: "Rekha Joshi (Inpatient Pharmacy)",
    items: [
      { medicineName: "Inj. Meropenem 1g", quantity: 3, dosage: "1g IV TDS" },
      { medicineName: "Inj. Pantoprazole 40mg", quantity: 2, dosage: "40mg IV BD" },
    ],
    totalAmount: 2750,
    status: "Completed",
  },
];

export const mockPharmacyAlerts: PharmacyAlert[] = [
  {
    id: "alert_01",
    medicineName: "Inj. Noradrenaline 4mg/2ml",
    type: "Critical Zero Stock",
    severity: "Critical",
    currentStock: 0,
    thresholdOrExpiry: "Min Threshold: 40 Ampoules",
    actionRequired: "Immediate emergency procurement indent required for ICU & ER Crash Carts.",
  },
  {
    id: "alert_02",
    medicineName: "Inj. Meropenem 1g",
    type: "Low Stock",
    severity: "High",
    currentStock: 18,
    thresholdOrExpiry: "Min Threshold: 50 Vials",
    actionRequired: "Stock level below reorder point. Trigger vendor replenishment.",
  },
  {
    id: "alert_03",
    medicineName: "Inj. Heparin 25,000 IU",
    type: "Expiring Soon",
    severity: "Warning",
    currentStock: 35,
    thresholdOrExpiry: "Expires: 2026-09-05 (14 Days)",
    actionRequired: "Prioritize FEFO (First-Expired-First-Out) utilization in Cath Lab / Dialysis.",
  },
];

// ==========================================
// 12.4 PAYMENTS & DAILY COUNTER COLLECTIONS
// ==========================================
export const mockPaymentTransactions: PaymentTransaction[] = [
  {
    id: "pay_101",
    receiptNo: "REC-2026-5501",
    patientId: "P-1001",
    patientName: "Ramesh Sharma",
    invoiceId: "INV-2026-0891",
    amount: 1250,
    paymentMethod: "UPI/QR",
    counterNo: "Counter 1 (Main OPD)",
    cashierName: "Rajesh Kadam",
    timestamp: "2026-08-22T09:30:00Z",
    reconciliationStatus: "Reconciled",
  },
  {
    id: "pay_102",
    receiptNo: "REC-2026-5502",
    patientId: "P-1002",
    patientName: "Sita Devi",
    invoiceId: "INV-2026-0892",
    amount: 3500,
    paymentMethod: "Credit/Debit Card",
    counterNo: "Counter 2 (Diagnostics)",
    cashierName: "Priya Nair",
    timestamp: "2026-08-22T10:15:00Z",
    reconciliationStatus: "Reconciled",
  },
  {
    id: "pay_103",
    receiptNo: "REC-2026-5503",
    patientId: "P-8821",
    patientName: "Arjun Gupta",
    invoiceId: "INV-2026-0895",
    amount: 25000,
    paymentMethod: "Cash",
    counterNo: "Counter 3 (IPD Admissions)",
    cashierName: "Meenakshi Sundaram",
    timestamp: "2026-08-22T11:00:00Z",
    reconciliationStatus: "Reconciled",
  },
  {
    id: "pay_104",
    receiptNo: "REC-2026-5504",
    patientId: "P-9102",
    patientName: "Kavita Patil",
    invoiceId: "INV-2026-0898",
    amount: 45000,
    paymentMethod: "Bank Transfer",
    counterNo: "Counter 4 (Emergency Billing)",
    cashierName: "Vikram Gaikwad",
    timestamp: "2026-08-22T11:45:00Z",
    reconciliationStatus: "Pending Settlement",
  },
];

export const mockCashDrawerReports: CashDrawerReport[] = [
  {
    counterId: "cnt_01",
    counterName: "Counter 1 (Main OPD Lobby)",
    cashierName: "Rajesh Kadam",
    openingFloat: 5000,
    cashCollected: 38400,
    posCollected: 62500,
    upiCollected: 44100,
    refundsDeducted: 1200,
    closingBalance: 42200,
    variance: 0,
    status: "Balanced",
  },
  {
    counterId: "cnt_02",
    counterName: "Counter 2 (Lab & Diagnostics)",
    cashierName: "Priya Nair",
    openingFloat: 5000,
    cashCollected: 24500,
    posCollected: 41000,
    upiCollected: 31200,
    refundsDeducted: 0,
    closingBalance: 29500,
    variance: 0,
    status: "Balanced",
  },
  {
    counterId: "cnt_03",
    counterName: "Counter 3 (IPD & Inpatient Settlement)",
    cashierName: "Meenakshi Sundaram",
    openingFloat: 10000,
    cashCollected: 145000,
    posCollected: 380000,
    upiCollected: 120000,
    refundsDeducted: 5000,
    closingBalance: 150000,
    variance: 0,
    status: "Balanced",
  },
  {
    counterId: "cnt_04",
    counterName: "Counter 4 (Emergency & Trauma 24x7)",
    cashierName: "Vikram Gaikwad",
    openingFloat: 10000,
    cashCollected: 62000,
    posCollected: 94000,
    upiCollected: 58000,
    refundsDeducted: 0,
    closingBalance: 72000,
    variance: 0,
    status: "Balanced",
  },
];

// ==========================================
// 12.4 INSURANCE & TPA CLAIMS
// ==========================================
export const mockInsuranceClaims: InsuranceClaim[] = [
  {
    id: "clm_101",
    claimNo: "CLM-2026-7701",
    patientId: "P-8821",
    patientName: "Arjun Gupta",
    tpaProvider: "Star Health",
    policyNo: "SH-MED-9941029",
    admissionDate: "2026-08-18",
    claimAmount: 185000,
    approvedAmount: 165000,
    copayAmount: 20000,
    status: "Approved",
    submissionDate: "2026-08-19",
    settlementDate: "2026-08-22",
  },
  {
    id: "clm_102",
    claimNo: "CLM-2026-7702",
    patientId: "P-9102",
    patientName: "Kavita Patil",
    tpaProvider: "HDFC ERGO",
    policyNo: "HE-CRIT-551029",
    admissionDate: "2026-08-19",
    claimAmount: 320000,
    approvedAmount: 250000,
    copayAmount: 70000,
    status: "Under Review",
    submissionDate: "2026-08-20",
    queryNotes: "Awaiting final intra-op neuro monitoring breakdown and implant invoices.",
  },
  {
    id: "clm_103",
    claimNo: "CLM-2026-7703",
    patientId: "P-4001",
    patientName: "Anil Kapoor",
    tpaProvider: "Medi Assist",
    policyNo: "MA-CORP-10029",
    admissionDate: "2026-08-19",
    claimAmount: 140000,
    approvedAmount: 0,
    copayAmount: 0,
    status: "Rejected",
    submissionDate: "2026-08-21",
    rejectionReason: "Initial pre-auth form lacked attending physician's clinical history timeline for pre-existing hypertension.",
    queryNotes: "Rectification required: Attach 2-year OPD consultation history from Dr. Ananya Patel.",
  },
  {
    id: "clm_104",
    claimNo: "CLM-2026-7704",
    patientId: "P-1004",
    patientName: "Vijay Varma",
    tpaProvider: "PM-JAY Scheme",
    policyNo: "PMJAY-MH-881920",
    admissionDate: "2026-08-18",
    claimAmount: 45000,
    approvedAmount: 45000,
    copayAmount: 0,
    status: "Settled",
    submissionDate: "2026-08-19",
    settlementDate: "2026-08-21",
  },
];

// ==========================================
// CENTRAL STORE INVENTORY & STOCK INDENTS
// ==========================================
export const mockInventoryCatalog: InventoryItem[] = [
  {
    id: "inv_01",
    itemCode: "SURG-GLV-75",
    name: "Surgical Sterile Gloves (Size 7.5)",
    category: "Surgical Consumables",
    stockLevel: 1400,
    unit: "Pairs",
    reorderLevel: 500,
    leadTimeDays: 2,
    supplierName: "Ansell Healthcare India",
    unitCost: 35,
    status: "Adequate",
  },
  {
    id: "inv_02",
    itemCode: "PPE-N95-3M",
    name: "N95 Particulate Respirator 3M Aura",
    category: "PPE & Hygiene",
    stockLevel: 180,
    unit: "Pieces",
    reorderLevel: 300,
    leadTimeDays: 3,
    supplierName: "3M India Ltd.",
    unitCost: 65,
    status: "Low Stock",
  },
  {
    id: "inv_03",
    itemCode: "REAG-CBC-SYX",
    name: "Sysmex Cellpack DCL Reagent 20L",
    category: "Diagnostic Reagents",
    stockLevel: 4,
    unit: "Cans (20L)",
    reorderLevel: 6,
    leadTimeDays: 4,
    supplierName: "Sysmex India Diagnostics",
    unitCost: 14500,
    status: "Low Stock",
  },
  {
    id: "inv_04",
    itemCode: "WND-DRS-TEG",
    name: "Tegaderm IV Advanced Dressing 10x12cm",
    category: "Wound Care",
    stockLevel: 850,
    unit: "Packs",
    reorderLevel: 250,
    leadTimeDays: 2,
    supplierName: "3M India Ltd.",
    unitCost: 120,
    status: "Adequate",
  },
];

export const mockStockIndents: StockIndent[] = [
  {
    id: "ind_101",
    indentNo: "IND-2026-301",
    department: "Main Operation Theatre Complex",
    requestedBy: "Sister Alphonsa (OT Nurse In-Charge)",
    items: [
      { itemName: "Surgical Sterile Gloves (Size 7.5)", quantity: 200 },
      { itemName: "Tegaderm IV Advanced Dressing", quantity: 50 },
    ],
    status: "Dispatched",
    requestedAt: "2026-08-22T08:30:00Z",
  },
  {
    id: "ind_102",
    indentNo: "IND-2026-302",
    department: "Intensive Care Unit (ICU)",
    requestedBy: "Sister Preeti (ICU In-Charge)",
    items: [
      { itemName: "N95 Particulate Respirator 3M", quantity: 60 },
      { itemName: "Endotracheal Tube Suction Catheters", quantity: 100 },
    ],
    status: "Pending Approval",
    requestedAt: "2026-08-22T11:00:00Z",
  },
];

// ==========================================
// BIOMEDICAL & FACILITY ASSETS REGISTRY
// ==========================================
export const mockBiomedicalAssets: BiomedicalAsset[] = [
  {
    id: "ast_01",
    assetCode: "BIO-CT-128",
    name: "Somatom Definition AS 128-Slice CT Scanner",
    category: "Diagnostic & Imaging",
    model: "Siemens Healthineers AS 128",
    serialNo: "SN-SIEM-994102",
    department: "Radiology & Imaging",
    floor: "Ground Floor - Radiology Block",
    purchaseDate: "2024-03-15",
    purchaseCost: 28500000,
    warrantyExpiry: "2027-03-15",
    amcCmcContract: "Active",
    vendorName: "Siemens Healthcare Pvt Ltd",
    nextPPMDate: "2026-09-15",
    maintenanceStatus: "Operational",
    lastCalibrationDate: "2026-06-15",
  },
  {
    id: "ast_02",
    assetCode: "BIO-VENT-04",
    name: "Hamilton C6 Intensive Care Ventilator",
    category: "Life Support",
    model: "Hamilton Medical C6",
    serialNo: "SN-HAM-881902",
    department: "Intensive Care Unit (ICU)",
    floor: "3rd Floor - Critical Care Block",
    purchaseDate: "2023-08-20",
    purchaseCost: 2400000,
    warrantyExpiry: "2026-08-20",
    amcCmcContract: "Under Renewal",
    vendorName: "Hamilton Medical India",
    nextPPMDate: "2026-08-28",
    maintenanceStatus: "Calibration Due",
    lastCalibrationDate: "2026-02-20",
  },
  {
    id: "ast_03",
    assetCode: "BIO-ANESTH-02",
    name: "Dräger Perseus A500 Anesthesia Workstation",
    category: "OT Equipment",
    model: "Dräger Perseus A500",
    serialNo: "SN-DRAG-449102",
    department: "Main Operation Theatre (OT 2)",
    floor: "3rd Floor - Surgical Suite",
    purchaseDate: "2024-01-10",
    purchaseCost: 3800000,
    warrantyExpiry: "2027-01-10",
    amcCmcContract: "Active",
    vendorName: "Dräger India Pvt Ltd",
    nextPPMDate: "2026-10-10",
    maintenanceStatus: "Operational",
    lastCalibrationDate: "2026-04-10",
  },
  {
    id: "ast_04",
    assetCode: "BIO-MON-12",
    name: "Mindray BeneVision N17 Multi-Parameter Patient Monitor",
    category: "Monitoring",
    model: "Mindray BeneVision N17",
    serialNo: "SN-MIND-100293",
    department: "Emergency & Trauma Bay 1",
    floor: "Ground Floor - Emergency Block",
    purchaseDate: "2023-11-05",
    purchaseCost: 650000,
    warrantyExpiry: "2025-11-05",
    amcCmcContract: "Active",
    vendorName: "Mindray Medical India",
    nextPPMDate: "2026-09-05",
    maintenanceStatus: "Operational",
    lastCalibrationDate: "2026-05-05",
  },
];
