import { ProcurementRequest, Vendor } from "@/hospital-admin/lib/types";

export const vendors: Vendor[] = [
  {
    id: "ven_001",
    name: "MedSupply Healthcare Pvt. Ltd.",
    categories: ["Consumables", "PPE", "Surgical Supplies"],
    contactPerson: "Ramesh Iyer",
    email: "sales@medsupplyhc.com",
    phone: "+91 98200 90112",
    serviceAreas: ["Mumbai", "Thane", "Navi Mumbai"],
    status: "verified",
    rating: 4.6,
    activeOrders: 6,
    onTimeDeliveryRate: 96,
    outstandingPayable: 128400,
    joinedOn: "2022-04-11",
    logoUrl: "https://i.pravatar.cc/150?img=1",
  },
  {
    id: "ven_002",
    name: "Orthotech Implants & Devices",
    categories: ["Implants", "Surgical Equipment"],
    contactPerson: "Kavita Shah",
    email: "orders@orthotech.in",
    phone: "+91 90040 55671",
    serviceAreas: ["Mumbai", "Pune"],
    status: "verified",
    rating: 4.8,
    activeOrders: 3,
    onTimeDeliveryRate: 92,
    outstandingPayable: 342000,
    joinedOn: "2021-09-02",
    logoUrl: "https://i.pravatar.cc/150?img=2",
  },
  {
    id: "ven_003",
    name: "PharmaLine Distributors",
    categories: ["Medicines", "Pharmacy Supplies"],
    contactPerson: "Ajay Bhatt",
    email: "ajay@pharmaline.co.in",
    phone: "+91 91234 22908",
    serviceAreas: ["Mumbai"],
    status: "under-review",
    rating: 4.1,
    activeOrders: 1,
    onTimeDeliveryRate: 88,
    outstandingPayable: 0,
    joinedOn: "2025-05-30",
    logoUrl: "https://i.pravatar.cc/150?img=3",
  },
  {
    id: "ven_004",
    name: "CalibraMed Equipment Services",
    categories: ["Equipment Maintenance", "Calibration"],
    contactPerson: "Nisha Verma",
    email: "support@calibramed.com",
    phone: "+91 98670 11223",
    serviceAreas: ["Mumbai", "Nashik"],
    status: "pending",
    rating: 0,
    activeOrders: 0,
    onTimeDeliveryRate: 0,
    outstandingPayable: 0,
    joinedOn: "2026-08-02",
    logoUrl: "https://i.pravatar.cc/150?img=4",
  },
  {
    id: "ven_005",
    name: "SafeHands Diagnostics Consumables",
    categories: ["Lab Consumables", "Reagents"],
    contactPerson: "Deepak Kulkarni",
    email: "deepak@safehandsdx.com",
    phone: "+91 90210 87643",
    serviceAreas: ["Mumbai", "Thane"],
    status: "suspended",
    rating: 3.4,
    activeOrders: 0,
    onTimeDeliveryRate: 71,
    outstandingPayable: 18900,
    joinedOn: "2022-12-18",
    logoUrl: "https://i.pravatar.cc/150?img=6",
  },
];

export const procurementRequests: ProcurementRequest[] = [
  {
    id: "pr_001",
    title: "Titanium Knee Implant Set - 6 units",
    category: "Implants",
    quantity: 6,
    requiredBy: "2026-08-20",
    urgency: "urgent",
    status: "open",
    quotesReceived: 3,
    linkedCase: "Surgical Case #SC-2291",
  },
  {
    id: "pr_002",
    title: "N95 Masks - 5,000 units",
    category: "PPE",
    quantity: 5000,
    requiredBy: "2026-08-25",
    urgency: "normal",
    status: "open",
    quotesReceived: 5,
  },
  {
    id: "pr_003",
    title: "Cardiac Monitor - 2 units",
    category: "Medical Equipment",
    quantity: 2,
    requiredBy: "2026-08-18",
    urgency: "critical",
    status: "closing-soon",
    quotesReceived: 2,
    linkedCase: "Surgical Case #SC-2288",
  },
  {
    id: "pr_004",
    title: "Surgical Sutures - Assorted (2,000 units)",
    category: "Consumables",
    quantity: 2000,
    requiredBy: "2026-09-01",
    urgency: "normal",
    status: "awarded",
    quotesReceived: 4,
  },
  {
    id: "pr_005",
    title: "Autoclave Calibration Service",
    category: "Equipment Maintenance",
    quantity: 1,
    requiredBy: "2026-08-22",
    urgency: "normal",
    status: "draft",
    quotesReceived: 0,
  },
];
