import {
  VerificationCase,
  DoctorAffiliationVerification,
  CapabilityVerification,
  ExpiryAlertItem,
} from "@/hospital-admin/lib/types";

// ==========================================
// 1. MASTER VERIFICATION CASES (All 8 Types & 6 Statuses)
// ==========================================
export const mockVerificationCases: VerificationCase[] = [
  {
    id: "ver_case_01",
    caseNo: "VER-2026-001",
    subjectName: "Qlyno Multispecialty Hospital - Main Campus",
    subjectId: "HOSP-001",
    subjectType: "Hospital",
    type: "Hospital Identity",
    status: "Verified",
    submittedAt: "2026-08-01T09:30:00Z",
    updatedAt: "2026-08-05T14:15:00Z",
    reviewerName: "Pooja Deshmukh",
    reviewerRole: "Senior Platform Trust & Safety Auditor",
    reviewerDecision: "Approved",
    decisionReason: "All legal incorporation deeds, CIN registry, and registered lease agreement verified successfully with MCA database.",
    documents: [
      {
        id: "doc_v01",
        name: "Certificate of Incorporation & CIN Registry",
        type: "Legal Entity Proof",
        documentNumber: "U85110MH2018PTC309112",
        fileSize: "2.4 MB",
        uploadedAt: "2026-08-01T09:35:00Z",
        status: "Verified",
        expiryDate: "2030-12-31",
      },
      {
        id: "doc_v02",
        name: "Hospital Registered Lease & Title Deed",
        type: "Ownership / Land Lease",
        documentNumber: "BOM-SUB-REG-2018-882",
        fileSize: "8.1 MB",
        uploadedAt: "2026-08-01T09:40:00Z",
        status: "Verified",
        expiryDate: "2048-03-31",
      },
    ],
    timeline: [
      {
        id: "tl_01",
        status: "Pending",
        actorName: "Akash Sharma",
        actorRole: "Hospital Admin",
        timestamp: "2026-08-01T09:30:00Z",
        notes: "Hospital identity and legal incorporation evidence submitted for trust verification.",
      },
      {
        id: "tl_02",
        status: "Under Review",
        actorName: "Pooja Deshmukh",
        actorRole: "Platform Trust Auditor",
        timestamp: "2026-08-03T11:00:00Z",
        notes: "Legal entity cross-check initiated with Ministry of Corporate Affairs (MCA).",
      },
      {
        id: "tl_03",
        status: "Verified",
        actorName: "Pooja Deshmukh",
        actorRole: "Senior Platform Trust Auditor",
        timestamp: "2026-08-05T14:15:00Z",
        notes: "Hospital identity verified. Entity cleared for public hospital search indexation.",
      },
    ],
    expiryDate: "2030-12-31",
    daysUntilExpiry: 1590,
    publicSearchVisible: true,
    metadata: {
      legalName: "Qlyno Healthcare Private Limited",
      registrationNo: "U85110MH2018PTC309112",
      registeredAddress: "Plot 42, Healthcare City, Andheri East, Mumbai, Maharashtra 400069",
      contactEmail: "legal@qlyno.health",
      contactPhone: "+91 22 6100 8800",
      ownershipType: "Private Limited Healthcare Corporation",
      facilityAreaSqFt: 120000,
      operatingHours: "24 Hours / 7 Days",
    },
  },
  {
    id: "ver_case_02",
    caseNo: "VER-2026-002",
    subjectName: "State Clinical Establishment License",
    subjectId: "HOSP-001",
    subjectType: "Hospital",
    type: "Hospital Registration",
    status: "Verified",
    submittedAt: "2026-08-02T10:00:00Z",
    updatedAt: "2026-08-06T16:20:00Z",
    reviewerName: "Dr. Sandeep Kulkarni",
    reviewerRole: "State Medical Licensing Officer",
    reviewerDecision: "Approved",
    decisionReason: "Maharashtra Clinical Establishments Act license and Fire Safety NOC valid and countersigned.",
    documents: [
      {
        id: "doc_v03",
        name: "Clinical Establishments Registration Certificate (Class 3 Multi-Specialty)",
        type: "Government License",
        documentNumber: "MH-CEA-2024-00918",
        fileSize: "3.2 MB",
        uploadedAt: "2026-08-02T10:05:00Z",
        status: "Verified",
        expiryDate: "2027-08-15",
      },
      {
        id: "doc_v04",
        name: "Municipal Fire Safety & High-Rise NOC",
        type: "Safety Compliance",
        documentNumber: "MCGM-FIRE-NOC-2025-110",
        fileSize: "1.9 MB",
        uploadedAt: "2026-08-02T10:10:00Z",
        status: "Verified",
        expiryDate: "2026-09-15",
      },
    ],
    timeline: [
      {
        id: "tl_04",
        status: "Pending",
        actorName: "Akash Sharma",
        actorRole: "Hospital Admin",
        timestamp: "2026-08-02T10:00:00Z",
        notes: "Clinical registration certificate and fire compliance NOC uploaded.",
      },
      {
        id: "tl_05",
        status: "Verified",
        actorName: "Dr. Sandeep Kulkarni",
        actorRole: "State Licensing Officer",
        timestamp: "2026-08-06T16:20:00Z",
        notes: "Registration approved. NABH/AERB compliance verified.",
      },
    ],
    expiryDate: "2026-09-15",
    daysUntilExpiry: 22,
    publicSearchVisible: true,
    metadata: {
      legalName: "Qlyno Multispecialty Hospital",
      registrationNo: "MH-CEA-2024-00918",
    },
  },
  {
    id: "ver_case_03",
    caseNo: "VER-2026-003",
    subjectName: "Hospital Administrator — Identity & Board Authorization",
    subjectId: "ADMIN-041",
    subjectType: "Admin",
    type: "Admin Identity",
    status: "Verified",
    submittedAt: "2026-08-10T14:00:00Z",
    updatedAt: "2026-08-12T11:45:00Z",
    reviewerName: "Rohan Varma",
    reviewerRole: "Platform Identity Officer",
    reviewerDecision: "Approved",
    decisionReason: "Government Aadhaar/PAN and Hospital Board Resolution letter authorizing administrator rights verified.",
    documents: [
      {
        id: "doc_v05",
        name: "Government Photo ID (Passport / Aadhaar)",
        type: "Identity Proof",
        documentNumber: "XXXX-XXXX-9912",
        fileSize: "1.1 MB",
        uploadedAt: "2026-08-10T14:05:00Z",
        status: "Verified",
      },
      {
        id: "doc_v06",
        name: "Board of Directors Authorized Signatory Resolution",
        type: "Authorization Letter",
        documentNumber: "QLYNO-BR-2026-04",
        fileSize: "1.5 MB",
        uploadedAt: "2026-08-10T14:10:00Z",
        status: "Verified",
      },
    ],
    timeline: [
      {
        id: "tl_06",
        status: "Pending",
        actorName: "Akash Sharma",
        actorRole: "Hospital Admin",
        timestamp: "2026-08-10T14:00:00Z",
        notes: "Admin identity verification bundle submitted.",
      },
      {
        id: "tl_07",
        status: "Verified",
        actorName: "Rohan Varma",
        actorRole: "Platform Identity Officer",
        timestamp: "2026-08-12T11:45:00Z",
        notes: "Admin rights confirmed for hospital console.",
      },
    ],
    publicSearchVisible: false,
    metadata: {
      legalName: "Akash Sharma",
      contactEmail: "akash.sharma@qlyno.health",
      contactPhone: "+91 98200 44551",
    },
  },
  {
    id: "ver_case_04",
    caseNo: "VER-2026-004",
    subjectName: "Dr. Ananya Rao (Cardiology)",
    subjectId: "doc_001",
    subjectType: "Doctor",
    type: "Doctor Affiliation",
    status: "Verified",
    submittedAt: "2026-08-04T12:00:00Z",
    updatedAt: "2026-08-08T15:30:00Z",
    reviewerName: "Dr. Meenakshi Joshi",
    reviewerRole: "Medical Council Credentialing Reviewer",
    reviewerDecision: "Approved",
    decisionReason: "Hospital affiliation confirmed; MD & DM Cardiology degrees verified with Maharashtra Medical Council.",
    documents: [
      {
        id: "doc_v07",
        name: "MD (Cardiology) & DM Super-Specialty Degrees",
        type: "Medical Degree",
        documentNumber: "MMC-CARD-88231",
        fileSize: "3.4 MB",
        uploadedAt: "2026-08-04T12:05:00Z",
        status: "Verified",
        expiryDate: "2031-03-31",
      },
      {
        id: "doc_v08",
        name: "State Medical Council Active Practice Registration",
        type: "Medical Council License",
        documentNumber: "MMC-REG-2012-04419",
        fileSize: "2.1 MB",
        uploadedAt: "2026-08-04T12:10:00Z",
        status: "Verified",
        expiryDate: "2029-06-30",
      },
    ],
    timeline: [
      {
        id: "tl_08",
        status: "Pending",
        actorName: "Hospital Admin",
        actorRole: "Hospital Admin",
        timestamp: "2026-08-04T12:00:00Z",
        notes: "Hospital-side affiliation confirmed for Dr. Ananya Rao.",
      },
      {
        id: "tl_09",
        status: "Under Review",
        actorName: "Dr. Meenakshi Joshi",
        actorRole: "Platform Credentialing Reviewer",
        timestamp: "2026-08-06T10:00:00Z",
        notes: "Platform credential verification initiated with NMC/MMC.",
      },
      {
        id: "tl_10",
        status: "Verified",
        actorName: "Dr. Meenakshi Joshi",
        actorRole: "Platform Credentialing Reviewer",
        timestamp: "2026-08-08T15:30:00Z",
        notes: "Affiliation and qualifications verified. Doctor searchable on Qlyno public search.",
      },
    ],
    expiryDate: "2029-06-30",
    daysUntilExpiry: 1040,
    publicSearchVisible: true,
    metadata: {
      specialtyClaims: ["Cardiology", "Interventional Cardiology", "Cardiac Angiography"],
      registrationNo: "MMC-CARD-88231",
    },
  },
  {
    id: "ver_case_05",
    caseNo: "VER-2026-005",
    subjectName: "Dr. Tariq Mansoor (Orthopedic Surgery)",
    subjectId: "doc_006",
    subjectType: "Doctor",
    type: "Specialty / Qualification",
    status: "Needs More Information",
    submittedAt: "2026-08-18T11:00:00Z",
    updatedAt: "2026-08-21T16:00:00Z",
    reviewerName: "Dr. Meenakshi Joshi",
    reviewerRole: "Medical Council Credentialing Reviewer",
    reviewerDecision: "Needs More Information",
    decisionReason: "Fellowship certificate in Arthroscopy is unreadable/blurry. Please re-upload a clear high-resolution scanned copy of the fellowship certificate.",
    documents: [
      {
        id: "doc_v09",
        name: "MBBS & MS Orthopedic Surgery Degree",
        type: "Medical Degree",
        documentNumber: "MMC-MS-2016-0991",
        fileSize: "2.8 MB",
        uploadedAt: "2026-08-18T11:05:00Z",
        status: "Verified",
        expiryDate: "2032-12-31",
      },
      {
        id: "doc_v10",
        name: "Fellowship in Arthroscopy & Sports Medicine Certificate",
        type: "Specialty Fellowship",
        documentNumber: "FASM-2020-044",
        fileSize: "0.4 MB",
        uploadedAt: "2026-08-18T11:10:00Z",
        status: "Flagged / Rejected",
        rejectionReason: "Blurry low-resolution scan. Text unreadable.",
      },
    ],
    timeline: [
      {
        id: "tl_11",
        status: "Pending",
        actorName: "Hospital Admin",
        actorRole: "Hospital Admin",
        timestamp: "2026-08-18T11:00:00Z",
        notes: "Submitted MS Ortho and fellowship documents.",
      },
      {
        id: "tl_12",
        status: "Needs More Information",
        actorName: "Dr. Meenakshi Joshi",
        actorRole: "Platform Credentialing Reviewer",
        timestamp: "2026-08-21T16:00:00Z",
        notes: "Requested high-res re-upload for fellowship certificate. Doctor public listing temporarily withheld.",
      },
    ],
    publicSearchVisible: false,
    metadata: {
      specialtyClaims: ["Orthopedics", "Joint Replacement", "Sports Arthroscopy"],
      registrationNo: "MMC-ORTH-77102",
    },
  },
  {
    id: "ver_case_06",
    caseNo: "VER-2026-006",
    subjectName: "Advanced Life Support (ALS) Ambulance Fleet (5 Ambulances)",
    subjectId: "FLEET-01",
    subjectType: "Ambulance Service",
    type: "Ambulance Capability",
    status: "Verified",
    submittedAt: "2026-08-12T09:00:00Z",
    updatedAt: "2026-08-15T14:30:00Z",
    reviewerName: "Vikram Sengupta",
    reviewerRole: "Emergency Medical Transport Inspector",
    reviewerDecision: "Approved",
    decisionReason: "RTO commercial ambulance fitness certificates, defibrillator calibration, and ventilator audit verified across all 5 vehicles.",
    documents: [
      {
        id: "doc_v11",
        name: "RTO Commercial Ambulance Permits & Fitness Logs",
        type: "Fleet Registration",
        documentNumber: "MH-02-AMB-2024-8891",
        fileSize: "4.5 MB",
        uploadedAt: "2026-08-12T09:05:00Z",
        status: "Verified",
        expiryDate: "2027-04-30",
      },
      {
        id: "doc_v12",
        name: "Onboard Defibrillator & Transport Ventilator Calibration Certificates",
        type: "Equipment Calibration",
        documentNumber: "CAL-AMB-2026-011",
        fileSize: "2.1 MB",
        uploadedAt: "2026-08-12T09:10:00Z",
        status: "Verified",
        expiryDate: "2027-01-31",
      },
    ],
    timeline: [
      {
        id: "tl_13",
        status: "Pending",
        actorName: "Akash Sharma",
        actorRole: "Hospital Admin",
        timestamp: "2026-08-12T09:00:00Z",
        notes: "Ambulance fleet technical and emergency readiness evidence uploaded.",
      },
      {
        id: "tl_14",
        status: "Verified",
        actorName: "Vikram Sengupta",
        actorRole: "Transport Inspector",
        timestamp: "2026-08-15T14:30:00Z",
        notes: "ALS Fleet verified. '24/7 ALS Ambulance Available' badge activated on public profile.",
      },
    ],
    expiryDate: "2027-04-30",
    daysUntilExpiry: 615,
    publicSearchVisible: true,
    metadata: {
      ambulanceFleetCount: 5,
      operatingHours: "24/7 Emergency Dispatch",
    },
  },
  {
    id: "ver_case_07",
    caseNo: "VER-2026-007",
    subjectName: "24/7 Level-1 Emergency Trauma Center & Resuscitation Bay",
    subjectId: "EMERG-01",
    subjectType: "Emergency Dept",
    type: "Emergency Capability",
    status: "Verified",
    submittedAt: "2026-08-05T10:00:00Z",
    updatedAt: "2026-08-09T17:00:00Z",
    reviewerName: "Dr. Anirudh Sen",
    reviewerRole: "NABH Emergency Services Assessor",
    reviewerDecision: "Approved",
    decisionReason: "Certified for Level-1 24/7 Trauma with dedicated trauma surgeon on-call roster and blood bank cross-match tie-up.",
    documents: [
      {
        id: "doc_v13",
        name: "NABH Emergency & Trauma Service Accreditation",
        type: "Hospital Accreditation",
        documentNumber: "NABH-ER-2025-081",
        fileSize: "3.7 MB",
        uploadedAt: "2026-08-05T10:05:00Z",
        status: "Verified",
        expiryDate: "2028-08-31",
      },
    ],
    timeline: [
      {
        id: "tl_15",
        status: "Pending",
        actorName: "Hospital Admin",
        actorRole: "Hospital Admin",
        timestamp: "2026-08-05T10:00:00Z",
        notes: "Emergency department capability evidence submitted.",
      },
      {
        id: "tl_16",
        status: "Verified",
        actorName: "Dr. Anirudh Sen",
        actorRole: "NABH Assessor",
        timestamp: "2026-08-09T17:00:00Z",
        notes: "24/7 Emergency capability approved. Public claims verified.",
      },
    ],
    expiryDate: "2028-08-31",
    daysUntilExpiry: 737,
    publicSearchVisible: true,
    metadata: {
      operatingHours: "24/7 Unrestricted Emergency",
    },
  },
  {
    id: "ver_case_08",
    caseNo: "VER-2026-008",
    subjectName: "Dr. Vikram Nair (Neurology)",
    subjectId: "doc_008",
    subjectType: "Doctor",
    type: "Doctor Affiliation",
    status: "Suspended",
    submittedAt: "2026-07-15T09:00:00Z",
    updatedAt: "2026-08-20T10:15:00Z",
    reviewerName: "Pooja Deshmukh",
    reviewerRole: "Senior Platform Trust Auditor",
    reviewerDecision: "Rejected",
    decisionReason: "Doctor license lapsed with state medical council. Suspended immediately per Rule 13.1 from public search.",
    documents: [
      {
        id: "doc_v14",
        name: "Medical Registration Certificate (Expired)",
        type: "Medical License",
        documentNumber: "MH-NEU-71098",
        fileSize: "1.8 MB",
        uploadedAt: "2026-07-15T09:05:00Z",
        status: "Flagged / Rejected",
        expiryDate: "2026-08-01",
        rejectionReason: "License expired on 2026-08-01. Renewal not submitted.",
      },
    ],
    timeline: [
      {
        id: "tl_17",
        status: "Verified",
        actorName: "Pooja Deshmukh",
        actorRole: "Trust Auditor",
        timestamp: "2026-07-18T14:00:00Z",
        notes: "Previously verified.",
      },
      {
        id: "tl_18",
        status: "Suspended",
        actorName: "System Automation",
        actorRole: "Compliance Engine",
        timestamp: "2026-08-20T10:15:00Z",
        notes: "IMMEDIATE DOWNGRADE: License lapsed. Public search visibility revoked in real time.",
      },
    ],
    expiryDate: "2026-08-01",
    daysUntilExpiry: -23,
    publicSearchVisible: false,
    metadata: {
      specialtyClaims: ["Neurology", "Neurocritical Care"],
      registrationNo: "MH-NEU-71098",
    },
  },
  {
    id: "ver_case_09",
    caseNo: "VER-2026-009",
    subjectName: "Atomic Energy Regulatory Board (AERB) Radiation License (CT/Cath Lab)",
    subjectId: "HOSP-001",
    subjectType: "Hospital",
    type: "Facility Evidence",
    status: "Under Review",
    submittedAt: "2026-08-22T14:00:00Z",
    updatedAt: "2026-08-23T09:30:00Z",
    reviewerName: "Sunil Kadam",
    reviewerRole: "AERB Compliance Auditor",
    documents: [
      {
        id: "doc_v15",
        name: "AERB Site Layout & Lead Shielding Verification Certificate",
        type: "Radiation Safety License",
        documentNumber: "AERB-MED-2026-0091",
        fileSize: "5.2 MB",
        uploadedAt: "2026-08-22T14:05:00Z",
        status: "Pending Review",
        expiryDate: "2029-08-20",
      },
    ],
    timeline: [
      {
        id: "tl_19",
        status: "Pending",
        actorName: "Hospital Admin",
        actorRole: "Hospital Admin",
        timestamp: "2026-08-22T14:00:00Z",
        notes: "Uploaded AERB radiation inspection certificate.",
      },
      {
        id: "tl_20",
        status: "Under Review",
        actorName: "Sunil Kadam",
        actorRole: "AERB Auditor",
        timestamp: "2026-08-23T09:30:00Z",
        notes: "Lead thickness and TLD badge monitoring logs under audit.",
      },
    ],
    publicSearchVisible: false,
    metadata: {
      facilityAreaSqFt: 3500,
    },
  },
  {
    id: "ver_case_10",
    caseNo: "VER-2026-010",
    subjectName: "Blood Bank & Component Storage License",
    subjectId: "BB-01",
    subjectType: "Hospital",
    type: "Facility Evidence",
    status: "Pending",
    submittedAt: "2026-08-24T08:00:00Z",
    updatedAt: "2026-08-24T08:00:00Z",
    documents: [
      {
        id: "doc_v16",
        name: "State Food & Drug Administration (FDA) Blood Bank License",
        type: "FDA Blood Storage Permit",
        documentNumber: "MH-FDA-BB-2026-014",
        fileSize: "2.7 MB",
        uploadedAt: "2026-08-24T08:05:00Z",
        status: "Pending Review",
        expiryDate: "2028-11-30",
      },
    ],
    timeline: [
      {
        id: "tl_21",
        status: "Pending",
        actorName: "Hospital Admin",
        actorRole: "Hospital Admin",
        timestamp: "2026-08-24T08:00:00Z",
        notes: "Submitted Blood Bank component storage renewal license for verification.",
      },
    ],
    publicSearchVisible: false,
    metadata: {
      facilityAreaSqFt: 1800,
    },
  },
];

// ==========================================
// 2. DOCTOR AFFILIATIONS CONSOLE (2-Step Dependency Console)
// ==========================================
export const mockDoctorAffiliations: DoctorAffiliationVerification[] = [
  {
    id: "doc_aff_01",
    doctorId: "doc_001",
    doctorName: "Dr. Ananya Rao",
    specialty: "Cardiology",
    qualification: "MBBS, MD (Cardiology), DM",
    registrationNo: "MH-CARD-88231",
    avatarUrl: "https://i.pravatar.cc/150?img=47",
    hospitalAffiliationConfirmed: true,
    hospitalAffirmedAt: "2026-08-01T10:00:00Z",
    platformCredentialsVerified: true,
    platformVerifiedAt: "2026-08-05T14:30:00Z",
    platformReviewerName: "Dr. Meenakshi Joshi (Medical Council)",
    publicSearchStatus: "Live / Searchable",
    documentsCount: 4,
    affiliationType: "Full-Time Consultant",
  },
  {
    id: "doc_aff_02",
    doctorId: "doc_002",
    doctorName: "Dr. Rohan Mehta",
    specialty: "Orthopedics",
    qualification: "MBBS, MS (Ortho)",
    registrationNo: "MH-ORTH-77102",
    avatarUrl: "https://i.pravatar.cc/150?img=12",
    hospitalAffiliationConfirmed: true,
    hospitalAffirmedAt: "2026-08-03T11:00:00Z",
    platformCredentialsVerified: true,
    platformVerifiedAt: "2026-08-06T16:00:00Z",
    platformReviewerName: "Dr. Meenakshi Joshi (Medical Council)",
    publicSearchStatus: "Live / Searchable",
    documentsCount: 3,
    affiliationType: "Full-Time Consultant",
  },
  {
    id: "doc_aff_03",
    doctorId: "doc_003",
    doctorName: "Dr. Priya Sharma",
    specialty: "Gynecology & Obstetrics",
    qualification: "MBBS, MS (OB-GYN), DGO",
    registrationNo: "MH-GYN-66521",
    avatarUrl: "https://i.pravatar.cc/150?img=32",
    hospitalAffiliationConfirmed: true,
    hospitalAffirmedAt: "2026-08-08T09:30:00Z",
    platformCredentialsVerified: true,
    platformVerifiedAt: "2026-08-10T12:15:00Z",
    platformReviewerName: "Dr. Meenakshi Joshi",
    publicSearchStatus: "Live / Searchable",
    documentsCount: 3,
    affiliationType: "Visiting Specialist",
  },
  {
    id: "doc_aff_04",
    doctorId: "doc_004",
    doctorName: "Dr. Arvind Swaminathan",
    specialty: "Pulmonology & Critical Care",
    qualification: "MBBS, MD (Pulmonology)",
    registrationNo: "MH-PUL-55412",
    avatarUrl: "https://i.pravatar.cc/150?img=15",
    hospitalAffiliationConfirmed: true,
    hospitalAffirmedAt: "2026-08-10T14:00:00Z",
    platformCredentialsVerified: true,
    platformVerifiedAt: "2026-08-12T17:00:00Z",
    platformReviewerName: "Dr. Meenakshi Joshi",
    publicSearchStatus: "Live / Searchable",
    documentsCount: 4,
    affiliationType: "Full-Time Consultant",
  },
  {
    id: "doc_aff_05",
    doctorId: "doc_005",
    doctorName: "Dr. Kavita Verma",
    specialty: "Neurology",
    qualification: "MBBS, DM (Neurology)",
    registrationNo: "MH-NEU-44310",
    avatarUrl: "https://i.pravatar.cc/150?img=28",
    hospitalAffiliationConfirmed: true,
    hospitalAffirmedAt: "2026-08-14T10:00:00Z",
    platformCredentialsVerified: true,
    platformVerifiedAt: "2026-08-16T11:30:00Z",
    platformReviewerName: "Dr. Meenakshi Joshi",
    publicSearchStatus: "Live / Searchable",
    documentsCount: 3,
    affiliationType: "Full-Time Consultant",
  },
  {
    id: "doc_aff_06",
    doctorId: "doc_006",
    doctorName: "Dr. Tariq Mansoor",
    specialty: "Orthopedic Surgery",
    qualification: "MBBS, MS (Ortho)",
    registrationNo: "MH-ORTH-77102",
    avatarUrl: "https://i.pravatar.cc/150?img=52",
    hospitalAffiliationConfirmed: true,
    hospitalAffirmedAt: "2026-08-18T11:00:00Z",
    platformCredentialsVerified: false,
    publicSearchStatus: "Blocked (Pending Platform Review)",
    documentsCount: 2,
    affiliationType: "Visiting Specialist",
  },
  {
    id: "doc_aff_07",
    doctorId: "doc_007",
    doctorName: "Dr. Meera Nair",
    specialty: "Pediatrics",
    qualification: "MBBS, MD (Pediatrics)",
    registrationNo: "MH-PED-33219",
    avatarUrl: "https://i.pravatar.cc/150?img=25",
    hospitalAffiliationConfirmed: false,
    platformCredentialsVerified: true,
    platformVerifiedAt: "2026-08-01T15:00:00Z",
    platformReviewerName: "Dr. Meenakshi Joshi",
    publicSearchStatus: "Blocked (Unconfirmed Affiliation)",
    documentsCount: 3,
    affiliationType: "On-Call Emergency",
  },
  {
    id: "doc_aff_08",
    doctorId: "doc_008",
    doctorName: "Dr. Vikram Nair",
    specialty: "Neurology",
    qualification: "MBBS, DM (Neurology)",
    registrationNo: "MH-NEU-71098",
    avatarUrl: "https://i.pravatar.cc/150?img=60",
    hospitalAffiliationConfirmed: true,
    hospitalAffirmedAt: "2026-07-15T09:00:00Z",
    platformCredentialsVerified: false,
    publicSearchStatus: "Suspended",
    documentsCount: 2,
    affiliationType: "Visiting Specialist",
  },
  {
    id: "doc_aff_09",
    doctorId: "doc_rad_01",
    doctorName: "Dr. Vikram Seth",
    specialty: "Radiology",
    qualification: "MD (Radiodiagnosis), FRCR (UK)",
    registrationNo: "MMC-2012-08891",
    avatarUrl: "https://i.pravatar.cc/150?img=33",
    hospitalAffiliationConfirmed: true,
    hospitalAffirmedAt: "2026-08-05T09:00:00Z",
    platformCredentialsVerified: true,
    platformVerifiedAt: "2026-08-08T14:00:00Z",
    platformReviewerName: "Dr. Meenakshi Joshi",
    publicSearchStatus: "Live / Searchable",
    documentsCount: 3,
    affiliationType: "Full-Time Consultant",
  },
  {
    id: "doc_aff_10",
    doctorId: "doc_rad_02",
    doctorName: "Dr. Sunita Kulkarni",
    specialty: "Neuroradiology & MRI",
    qualification: "MD, DNB (Neuroradiology)",
    registrationNo: "MMC-2008-03419",
    avatarUrl: "https://i.pravatar.cc/150?img=44",
    hospitalAffiliationConfirmed: true,
    hospitalAffirmedAt: "2026-08-06T10:00:00Z",
    platformCredentialsVerified: true,
    platformVerifiedAt: "2026-08-09T16:00:00Z",
    platformReviewerName: "Dr. Meenakshi Joshi",
    publicSearchStatus: "Live / Searchable",
    documentsCount: 4,
    affiliationType: "Full-Time Consultant",
  },
];

// ==========================================
// 3. CAPABILITIES VERIFICATION (Ambulance & Emergency)
// ==========================================
export const mockCapabilityVerifications: CapabilityVerification[] = [
  {
    id: "cap_01",
    capabilityType: "Ambulance Fleet",
    title: "24/7 Advanced Cardiac Life Support (ALS) Ambulance Dispatch",
    serviceDetails: "Fleet of 5 GPS-tracked ALS ambulances equipped with Mindray BeneHeart defibrillators, Hamilton transport ventilators, and trained emergency paramedics.",
    operatingHours: "24 Hours / 7 Days (Continuous Emergency Roster)",
    fleetCount: 5,
    status: "Verified",
    verifiedAt: "2026-08-15T14:30:00Z",
    reviewerName: "Vikram Sengupta (Emergency Medical Transport Auditor)",
    publicBadgeActive: true,
    complianceNotes: "All vehicles pass RTO commercial safety certification and medical device annual calibration standards.",
    evidenceDocs: ["RTO Commercial Ambulance Permits.pdf", "Defibrillator Calibration Logs.pdf"],
  },
  {
    id: "cap_02",
    capabilityType: "24/7 Emergency & Trauma",
    title: "Level-1 Comprehensive Emergency & Acute Trauma Center",
    serviceDetails: "Dedicated 12-bed emergency resuscitation bay with central oxygen manifold, trauma surgeons on 15-minute call-in window, and direct OT express elevator.",
    operatingHours: "24 Hours / 7 Days (Unrestricted Level-1 Trauma)",
    traumaLevel: "Level 1 Certified",
    status: "Verified",
    verifiedAt: "2026-08-09T17:00:00Z",
    reviewerName: "Dr. Anirudh Sen (NABH Emergency Services Assessor)",
    publicBadgeActive: true,
    complianceNotes: "Operating hours and trauma specialty claims strictly match verified infrastructure configuration (Rule F13-CANNOT-10).",
    evidenceDocs: ["NABH Emergency Accreditation.pdf", "Trauma Surgeon On-Call Roster.pdf"],
  },
  {
    id: "cap_03",
    capabilityType: "ICU Critical Care",
    title: "24-Bed Multi-Disciplinary Intensive Care Unit (MICU/SICU/NICU)",
    serviceDetails: "Level-3 tertiary critical care with 1:1 nurse-to-patient ratio for ventilated patients and 24/7 in-house intensivists.",
    operatingHours: "24/7 Critical Inpatient Care",
    status: "Verified",
    verifiedAt: "2026-08-07T12:00:00Z",
    reviewerName: "Dr. Anirudh Sen",
    publicBadgeActive: true,
    complianceNotes: "Isolation negative-pressure rooms and HEPA filtration validated.",
    evidenceDocs: ["ICU Air Quality & HEPA Certificate.pdf"],
  },
  {
    id: "cap_04",
    capabilityType: "Blood Bank Storage",
    title: "State FDA Certified Blood Bank & Component Separation Unit",
    serviceDetails: "Platelet agitators, deep freezers (-80°C) for Fresh Frozen Plasma, and 24/7 cross-match testing.",
    operatingHours: "24/7 Emergency Blood Supply",
    status: "Pending",
    publicBadgeActive: false,
    complianceNotes: "Awaiting State FDA physical premise inspection sign-off before public capability claim can be activated.",
    evidenceDocs: ["FDA Blood Bank Renewal Application.pdf"],
  },
];

// ==========================================
// 4. VERIFICATION EXPIRY ALERTS PANEL
// ==========================================
export const mockExpiryAlerts: ExpiryAlertItem[] = [
  {
    id: "exp_01",
    documentName: "Municipal High-Rise Fire Safety NOC",
    subjectName: "Qlyno Multispecialty Hospital",
    subjectType: "Hospital",
    licenseNumber: "MCGM-FIRE-NOC-2025-110",
    issuingAuthority: "Municipal Corporation Fire Safety Directorate",
    expiryDate: "2026-09-15",
    daysRemaining: 22,
    urgency: "High (<30 Days)",
    publicImpact: "Hospital public verified badge will be suspended on 2026-09-16 if renewal is not uploaded.",
    status: "Action Required",
  },
  {
    id: "exp_02",
    documentName: "Pollution Control Board Biomedical Waste Authorization",
    subjectName: "Hospital Hazardous & Bio-Waste Plant",
    subjectType: "Fleet / Facility",
    licenseNumber: "MPCB-BMW-2024-88912",
    issuingAuthority: "Maharashtra Pollution Control Board",
    expiryDate: "2026-09-30",
    daysRemaining: 37,
    urgency: "Medium (<60 Days)",
    publicImpact: "Facility environmental compliance rating will drop.",
    status: "Renewal Submitted",
  },
  {
    id: "exp_03",
    documentName: "State Medical Council Registration Renewal",
    subjectName: "Dr. Vikram Nair (Neurology)",
    subjectType: "Doctor",
    licenseNumber: "MH-NEU-71098",
    issuingAuthority: "Maharashtra Medical Council",
    expiryDate: "2026-08-01",
    daysRemaining: -23,
    urgency: "Critical Expired",
    publicImpact: "Doctor was immediately removed from Qlyno Public Search on 2026-08-01 per Rule 13.1.",
    status: "Action Required",
  },
  {
    id: "exp_04",
    documentName: "Ambulance Road Tax & Commercial Fitness Certificate (AMB-04)",
    subjectName: "ALS Ambulance MH-02-AMB-4004",
    subjectType: "Fleet / Facility",
    licenseNumber: "RTO-AMB-FIT-2025-04",
    issuingAuthority: "Regional Transport Office (RTO)",
    expiryDate: "2026-10-10",
    daysRemaining: 47,
    urgency: "Medium (<60 Days)",
    publicImpact: "Vehicle will be temporarily de-listed from emergency dispatch queue.",
    status: "Action Required",
  },
  {
    id: "exp_05",
    documentName: "Hospital Clinical Establishment License (Annual Renewal)",
    subjectName: "Qlyno Multispecialty Hospital",
    subjectType: "Hospital",
    licenseNumber: "MH-CEA-2024-00918",
    issuingAuthority: "Directorate of Health Services",
    expiryDate: "2027-08-15",
    daysRemaining: 356,
    urgency: "Medium (<60 Days)",
    publicImpact: "Core hospital operating license is in healthy standing.",
    status: "Verified",
  },
];

// ==========================================
// 5. PUBLIC PROFILE PREVIEW DATA (Rule 13.1 Sanitized Public View)
// ==========================================
export const mockPublicHospitalProfile = {
  hospitalName: "Qlyno Multispecialty Hospital",
  tagline: "NABH & AERB Accredited Tertiary Care Hospital",
  address: "Plot 42, Healthcare City, Andheri East, Mumbai, Maharashtra 400069",
  contactPhone: "+91 22 6100 8800",
  emergencyHelpline: "1066 / +91 22 6100 8911",
  email: "care@qlyno.health",
  website: "https://www.qlyno.health",
  verificationBadge: "Qlyno Verified Institution",
  accreditations: [
    "NABH Accredited Tertiary Center",
    "AERB Certified Radiation Safety",
    "ISO 9001:2015 Healthcare Quality",
    "AERB 128-Slice CT & 3T MRI Clearance",
  ],
  verifiedCapabilities: [
    "24/7 Level-1 Emergency & Trauma Center",
    "Advanced Cardiac Life Support (ALS) Ambulance Fleet",
    "24-Bed Tertiary Multi-Disciplinary ICU",
    "Cath Lab & Digital Subtraction Angiography",
  ],
  specialties: [
    "Cardiology & Cardiac Surgery",
    "Orthopedics & Joint Reconstruction",
    "Neurology & Neurosurgery",
    "Pulmonology & Critical Care",
    "Radiology & Cross-Sectional Imaging",
    "General & Laparoscopic Surgery",
  ],
  verifiedDoctorsCount: 8,
  // 13.1 Data Scrubbing Verification (Guarantees Zero Leakage)
  sanitizationAudit: {
    privatePatientDataScrubbed: true,
    internalStaffingSchedulesScrubbed: true,
    bedLevelOccupancyScrubbed: true,
    internalEmergencyTriageLogsScrubbed: true,
  },
};
