"use client";

import { createContext, useContext, useEffect, useMemo, useReducer, useState, type ReactNode } from "react";
import { useDemo } from "@/state/demo-context";
import type { LaboratoryRole } from "@/lib/types/laboratory-session";
import type { Order, OrderItem, Priority, Specimen } from "@/lib/types/domain";
import type { RegisteredPatient, RegisterHospitalPatientInput } from "@/lib/types/patient-registration";
import { MOCK_CATALOG } from "@/data/mock/catalog";
import { MOCK_ORDERS, MOCK_ORDER_ITEMS } from "@/data/mock/orders";
import { MOCK_PATIENTS } from "@/data/mock/patients";
import type { CollectionTask } from "@/lib/types/collection-task";
import { deriveOrderLifecycle, type LaboratoryLifecycleEvent, type LaboratoryLifecycleEventType, type LifecycleCriticalNotification, type LifecycleDelivery, type LifecycleOrder, type LifecycleOrderItem, type LifecycleReportGroup, type LifecycleReview, type LifecycleSpecimen, type LifecycleWorkItem, type OrderLifecycleSnapshot, type OrderLifecycleStage } from "@/lib/workflow/order-lifecycle";

export type HospitalWorkflowStage = OrderLifecycleStage;
interface EngineState { patientId?: string; patientName?: string; mrn?: string; encounterId?: string; order: LifecycleOrder; orderItems: LifecycleOrderItem[]; specimens: LifecycleSpecimen[]; workItems: LifecycleWorkItem[]; reviews: LifecycleReview[]; reportGroups: LifecycleReportGroup[]; deliveries: LifecycleDelivery[]; criticalNotifications: LifecycleCriticalNotification[]; events: LaboratoryLifecycleEvent[]; }
export interface HospitalWorkflowEvent { id: string; stage: HospitalWorkflowStage; action: string; actor: string; role: string; timestamp: string; reason: string; }
export interface HospitalWorkflowState { tenantId: string; orderId: string; patientId: string; mrn: string; encounterId: string; accessionId?: string; specimenId: string; orderItemId: string; resultId?: string; reportId?: string; reportVersionId?: string; stage: HospitalWorkflowStage; specimenStatus: string; testStatus: string; reportStatus: string; hmsDeliveryStatus: string; events: HospitalWorkflowEvent[]; }
const DEMO_STATE_VERSION = 3;
const WORKFLOW_STORAGE_KEY = "qlyno-hospital-workflow-v3";
const INITIAL: EngineState = {
  patientId: "PAT-1001", patientName: "Ramesh Iyer", mrn: "MRN-88213", encounterId: "ENC-501",
  order: { id: "ORD-70011", tenantId: "TEN-SUNRISE", validated: true, collectionTasksCreated: true },
  orderItems: [
    { id: "OI-1", specimenIds: ["SPX-9001"], status: "ORDERED", reportGroupId: "RG-CHEM" },
    { id: "OI-2", specimenIds: ["SPX-9002"], status: "ORDERED", reportGroupId: "RG-HEM" },
  ],
  specimens: [
    { id: "SPX-9001", tenantId: "TEN-SUNRISE", siteId: "SITE-01", orderId: "ORD-70011", patientId: "PAT-1001", patientName: "Ramesh Iyer", mrn: "MRN-88213", type: "Serum", container: "SST (Gold top)", collectionLocation: "Ward / bedside", priority: "stat", status: "COLLECTED", collectedAt: "2026-09-02T09:18:00+05:30", collectedBy: "Nikita Bhosale", collectionCondition: "Acceptable" },
    { id: "SPX-9002", tenantId: "TEN-SUNRISE", siteId: "SITE-01", orderId: "ORD-70011", patientId: "PAT-1001", patientName: "Ramesh Iyer", mrn: "MRN-88213", type: "Whole Blood", container: "EDTA (Lavender top)", collectionLocation: "Ward / bedside", priority: "stat", status: "COLLECTED", collectedAt: "2026-09-02T09:18:00+05:30", collectedBy: "Nikita Bhosale", collectionCondition: "Acceptable" },
  ],
  workItems: [], reviews: [], reportGroups: [{ id: "RG-CHEM", orderItemIds: ["OI-1"], versionCreated: false, released: false }, { id: "RG-HEM", orderItemIds: ["OI-2"], versionCreated: false, released: false }], deliveries: [], criticalNotifications: [],
  events: [
    { id: "EVT-ORD-70011-IMPORTED", tenantId: "TEN-SUNRISE", siteId: "SITE-01", orderId: "ORD-70011", type: "ORDER_IMPORTED", actorType: "HMS", actorName: "Sunrise HMS", timestamp: "2026-09-02T09:00:00+05:30", reason: "Order imported from authenticated HMS session" },
    { id: "EVT-SPX-9001-EXPECTED", tenantId: "TEN-SUNRISE", siteId: "SITE-01", orderId: "ORD-70011", specimenId: "SPX-9001", type: "SPECIMEN_EXPECTED", actorType: "SYSTEM", actorName: "Qlyno workflow engine", timestamp: "2026-09-02T09:01:00+05:30", reason: "Expected specimen and collection task created" },
    { id: "EVT-SPX-9002-EXPECTED", tenantId: "TEN-SUNRISE", siteId: "SITE-01", orderId: "ORD-70011", specimenId: "SPX-9002", type: "SPECIMEN_EXPECTED", actorType: "SYSTEM", actorName: "Qlyno workflow engine", timestamp: "2026-09-02T09:01:00+05:30", reason: "Expected specimen and collection task created" },
    { id: "EVT-SPX-9001-COLLECTED", tenantId: "TEN-SUNRISE", siteId: "SITE-01", orderId: "ORD-70011", specimenId: "SPX-9001", type: "SPECIMEN_COLLECTED", actorType: "USER", actorId: "USR-06", actorName: "Nikita Bhosale", timestamp: "2026-09-02T09:18:00+05:30", reason: "Positive identification and container verified" },
    { id: "EVT-SPX-9002-COLLECTED", tenantId: "TEN-SUNRISE", siteId: "SITE-01", orderId: "ORD-70011", specimenId: "SPX-9002", type: "SPECIMEN_COLLECTED", actorType: "USER", actorId: "USR-06", actorName: "Nikita Bhosale", timestamp: "2026-09-02T09:18:00+05:30", reason: "Positive identification and container verified" },
  ],
};
const REQUIRED: Partial<Record<OrderLifecycleStage, LaboratoryRole[]>> = { COLLECTION_READY: ["PHLEBOTOMIST", "WARD_COLLECTOR"], RECEIVING: ["RECEIVING_STAFF", "ACCESSIONING_STAFF"], ACCESSIONING: ["ACCESSIONING_STAFF"], PROCESSING: ["TECHNICIAN", "SECTION_SUPERVISOR"], TECHNICAL_REVIEW: ["TECHNICIAN", "SECTION_SUPERVISOR"], MEDICAL_VALIDATION: ["PATHOLOGIST", "LAB_DIRECTOR"], REPORT_RELEASE: ["PATHOLOGIST", "LAB_DIRECTOR"] };
const snap = (s: EngineState) => deriveOrderLifecycle({ ...s, results: [], reportVersions: [] });
function makeEvent(s: EngineState, type: LaboratoryLifecycleEventType, actorName: string, refs: Partial<LaboratoryLifecycleEvent> = {}, reason?: string): LaboratoryLifecycleEvent { return { id: `EVT-${Date.now()}-${s.events.length}`, tenantId: s.order.tenantId, orderId: s.order.id, type, actorType: type === "ANALYZER_RESULT_RECEIVED" ? "ANALYZER" : "USER", actorName, timestamp: new Date().toISOString(), reason, ...refs }; }
export interface ReceiptInput { condition: string; sealStatus: string; temperature: string; notes: string; }
type Action = { type: "NEXT"; actor: string; reason?: string } | { type: "COLLECT"; specimenIds: string[]; actor: string; actorId: string; notes: string } | { type: "RECEIVE"; specimenId: string; actor: string; actorId: string; siteId: string; receipt: ReceiptInput } | { type: "ACCESSION"; specimenId: string; actor: string; actorId: string } | { type: "REJECT"; specimenId: string; actor: string; actorId: string; reason: string } | { type: "LOAD"; state: EngineState } | { type: "RESET" };
function reducer(s: EngineState, a: Action): EngineState {
  if (a.type === "LOAD") return a.state; if (a.type === "RESET") return INITIAL;
  if (a.type === "COLLECT") {
    if (snap(s).overallStage !== "COLLECTION_READY" || !a.specimenIds.length) return s;
    const invalid = a.specimenIds.some((id) => !s.specimens.some((specimen) => specimen.id === id && specimen.status === "EXPECTED")); if (invalid) return s;
    const collectedAt = new Date().toISOString(); const specimens = s.specimens.map((specimen) => a.specimenIds.includes(specimen.id) ? { ...specimen, status: "COLLECTED" as const } : specimen);
    const events = a.specimenIds.map((specimenId, index) => makeEvent(s, "SPECIMEN_COLLECTED", a.actor, { id: `EVT-${Date.now()}-${s.events.length + index}`, specimenId, actorId: a.actorId, metadata: { quantity: 1, containerVerified: true, notes: a.notes, collectedAt } }, "Positive identification and required container validated"));
    return { ...s, specimens, events: [...s.events, ...events] };
  }
  if (a.type === "RECEIVE") { const specimen = s.specimens.find((entry) => entry.id === a.specimenId); if (!specimen || !["COLLECTED", "IN_TRANSIT"].includes(specimen.status)) return s; const timestamp = new Date().toISOString(); return { ...s, specimens: s.specimens.map((entry) => entry.id === a.specimenId ? { ...entry, status: "RECEIVED", receivedAt: timestamp, receivedBy: a.actor, receivedSiteId: a.siteId, collectionCondition: a.receipt.condition, sealStatus: a.receipt.sealStatus, temperature: a.receipt.temperature, receiptNotes: a.receipt.notes } : entry), events: [...s.events, makeEvent(s, "SPECIMEN_RECEIVED", a.actor, { siteId: a.siteId, specimenId: a.specimenId, actorId: a.actorId, metadata: { receivedAt: timestamp, receivedSiteId: a.siteId, condition: a.receipt.condition, sealStatus: a.receipt.sealStatus, temperature: a.receipt.temperature, notes: a.receipt.notes } }, "Scanned specimen reconciled and custody transfer confirmed")] }; }
  if (a.type === "ACCESSION") { const specimen = s.specimens.find((entry) => entry.id === a.specimenId); if (!specimen || specimen.status !== "RECEIVED" || specimen.accessionId) return s; const accessionId = `ACC-${a.specimenId.replace("SPX-", "")}`; const item = s.orderItems.find((entry) => entry.specimenIds.includes(a.specimenId)); return { ...s, specimens: s.specimens.map((entry) => entry.id === a.specimenId ? { ...entry, status: "ACCEPTED", accessionId } : entry), orderItems: s.orderItems.map((entry) => entry.id === item?.id ? { ...entry, status: "READY" } : entry), workItems: item && !s.workItems.some((entry) => entry.orderItemId === item.id) ? [...s.workItems, { id: `WI-${item.id}`, orderItemId: item.id, started: false, qcPassed: false, resultsComplete: false }] : s.workItems, events: [...s.events, makeEvent(s, "ACCESSION_CREATED", a.actor, { specimenId: a.specimenId, orderItemId: item?.id, actorId: a.actorId, metadata: { accessionId } }, "Accession created"), makeEvent(s, "SPECIMEN_ACCEPTED", a.actor, { specimenId: a.specimenId, orderItemId: item?.id, actorId: a.actorId, metadata: { accessionId } }, "Specimen acceptance criteria confirmed")] }; }
  if (a.type === "REJECT") { const specimen = s.specimens.find((entry) => entry.id === a.specimenId); if (!specimen || specimen.status !== "RECEIVED" || !a.reason.trim()) return s; const timestamp = new Date().toISOString(); const recollectionId = `${a.specimenId}-R${s.events.length}`; const item = s.orderItems.find((entry) => entry.specimenIds.includes(a.specimenId)); return { ...s, specimens: [...s.specimens.map((entry) => entry.id === a.specimenId ? { ...entry, status: "REJECTED" as const, blocker: a.reason, rejectedAt: timestamp, rejectedBy: a.actor, recollectionSpecimenId: recollectionId } : entry), { ...specimen, id: recollectionId, status: "EXPECTED", collectedAt: undefined, collectedBy: undefined, receivedAt: undefined, receivedBy: undefined, receivedSiteId: undefined, accessionId: undefined, recollectionSpecimenId: undefined }], orderItems: s.orderItems.map((entry) => entry.id === item?.id ? { ...entry, status: "BLOCKED", specimenIds: [...entry.specimenIds, recollectionId] } : entry), events: [...s.events, makeEvent(s, "SPECIMEN_REJECTED", a.actor, { siteId: specimen.siteId, specimenId: a.specimenId, orderItemId: item?.id, actorId: a.actorId, metadata: { rejectionReason: a.reason, recollectionSpecimenId: recollectionId } }, a.reason)] }; }
  const stage = snap(s).overallStage; const n: EngineState = { ...s, order: { ...s.order }, orderItems: s.orderItems.map(x => ({ ...x })), specimens: s.specimens.map(x => ({ ...x })), workItems: s.workItems.map(x => ({ ...x })), reviews: s.reviews.map(x => ({ ...x })), reportGroups: s.reportGroups.map(x => ({ ...x })), deliveries: s.deliveries.map(x => ({ ...x })), criticalNotifications: s.criticalNotifications.map(x => ({ ...x })) }; let e: LaboratoryLifecycleEvent | undefined;
  if (stage === "ORDER_RECEIVED") { n.order.validated = true; n.order.collectionTasksCreated = true; e = makeEvent(s, "ORDER_VALIDATED", a.actor, {}, a.reason ?? "Order requirements validated; expected specimens, labels, TAT and collection tasks created"); }
  if (stage === "COLLECTION_READY") { const x = n.specimens.find(v => v.status === "EXPECTED"); if (x) { x.status = "COLLECTED"; e = makeEvent(s, "SPECIMEN_COLLECTED", a.actor, { specimenId: x.id }, a.reason ?? "Positive identification, container and label checks confirmed"); } }
  if (stage === "RECEIVING") return s;
  if (stage === "ACCESSIONING") { const x = n.specimens.find(v => v.status === "RECEIVED"); const item = n.orderItems.find(i => x && i.specimenIds.includes(x.id)); if (x && item) { x.status = "ACCEPTED"; item.status = "READY"; n.workItems.push({ id: `WI-${item.id}`, orderItemId: item.id, started: false, qcPassed: false, resultsComplete: false }); e = makeEvent(s, "SPECIMEN_ACCEPTED", a.actor, { specimenId: x.id, orderItemId: item.id }, a.reason ?? "Specimen accepted; accession and work item created"); } }
  if (stage === "PROCESSING") { const w = n.workItems.find(v => !v.resultsComplete); const item = n.orderItems.find(i => i.id === w?.orderItemId); if (w && item) { w.started = w.qcPassed = w.resultsComplete = true; item.status = "TECHNICAL_REVIEW"; e = makeEvent(s, "RESULTS_COMPLETED", a.actor, { orderItemId: item.id }, a.reason ?? "Mandatory results and provenance captured; QC passed"); } }
  if (stage === "TECHNICAL_REVIEW") { const item = n.orderItems.find(i => i.status === "TECHNICAL_REVIEW" && !n.reviews.find(r => r.orderItemId === i.id)?.technicalApproved); if (item) { const r = n.reviews.find(v => v.orderItemId === item.id); if (r) r.technicalApproved = true; else n.reviews.push({ orderItemId: item.id, technicalApproved: true, medicalApproved: false }); item.status = "MEDICAL_VALIDATION"; e = makeEvent(s, "TECHNICAL_REVIEW_APPROVED", a.actor, { orderItemId: item.id }, a.reason ?? "Reviewed result snapshot locked"); } }
  if (stage === "MEDICAL_VALIDATION") { const item = n.orderItems.find(i => i.status === "MEDICAL_VALIDATION" && !n.reviews.find(r => r.orderItemId === i.id)?.medicalApproved); if (item) { n.reviews.find(r => r.orderItemId === item.id)!.medicalApproved = true; item.status = "VERIFIED"; n.reportGroups.find(g => g.id === item.reportGroupId)!.versionCreated = true; e = makeEvent(s, "MEDICAL_VALIDATION_APPROVED", a.actor, { orderItemId: item.id, reportGroupId: item.reportGroupId }, a.reason ?? "Clinical review completed; draft report version created"); } }
  if (stage === "REPORT_RELEASE") { const g = n.reportGroups.find(v => v.versionCreated && !v.released); if (g) { g.released = true; n.orderItems.filter(i => i.reportGroupId === g.id).forEach(i => i.status = "RELEASED"); n.deliveries.push({ reportGroupId: g.id, delivered: false }); e = makeEvent(s, "REPORT_RELEASED", a.actor, { reportGroupId: g.id }, a.reason ?? "Authorized immutable report released"); } }
  if (stage === "DELIVERY_CLOSURE") { const d = n.deliveries.find(v => !v.delivered); if (d) { d.delivered = true; e = makeEvent(s, "REPORT_DELIVERED", a.actor, { reportGroupId: d.reportGroupId }, a.reason ?? "Successful HMS delivery recorded"); } }
  if (!e) return s; n.events = [...s.events, e]; const after = snap(n); if (after.overallStage === "CLOSED" && !n.events.some(v => v.type === "ORDER_CLOSED")) n.events.push(makeEvent(n, "ORDER_CLOSED", "Qlyno workflow engine", {}, "All clinical closure requirements satisfied")); return n;
}
export interface CreateHospitalOrderInput { backendOrderId?: string; patientId: string; patientName: string; mrn: string; encounterId: string; orderingDoctor: string; priority: Priority; testIds: string[]; departmentIds: string[]; }
interface Value { workflow: HospitalWorkflowState; lifecycle: OrderLifecycleSnapshot; lifecycleEvents: LaboratoryLifecycleEvent[]; collectionTasks: CollectionTask[]; activeOrderItems: OrderItem[]; activeSpecimens: Specimen[]; dynamicOrders: Order[]; registeredPatients: RegisteredPatient[]; canAdvance: boolean; requiredRoles: LaboratoryRole[]; actionLabel: string; advance: (reason?: string) => void; confirmCollection: (taskId: string, specimenIds: string[], notes: string) => { ok: boolean; message?: string }; confirmReceipt: (orderId: string, specimenId: string, receipt: ReceiptInput) => { ok: boolean; message?: string }; accessionSpecimen: (orderId: string, specimenId: string) => { ok: boolean; message?: string }; rejectSpecimen: (orderId: string, specimenId: string, reason: string) => { ok: boolean; message?: string }; createHospitalOrder: (i: CreateHospitalOrderInput) => Order; registerHospitalPatient: (i: RegisterHospitalPatientInput) => RegisteredPatient; reset: () => void; }
const Context = createContext<Value | null>(null);
export function HospitalWorkflowProvider({ children }: { children: ReactNode }) {
  const { session } = useDemo(); const [engine, dispatch] = useReducer(reducer, INITIAL); const [ready, setReady] = useState(false); const [dynamicOrders, setDynamicOrders] = useState<Order[]>([]); const [registeredPatients, setRegisteredPatients] = useState<RegisteredPatient[]>([]);
  useEffect(() => { try { const raw = localStorage.getItem(WORKFLOW_STORAGE_KEY); if (raw) { const persisted = JSON.parse(raw) as { version?: number; state?: EngineState }; if (persisted.version === DEMO_STATE_VERSION && persisted.state?.order?.id && Array.isArray(persisted.state.specimens)) dispatch({ type: "LOAD", state: persisted.state }); } const o = localStorage.getItem("qlyno-hospital-orders-v1"); if (o) setDynamicOrders(JSON.parse(o)); const p = localStorage.getItem("qlyno-hospital-patients-v1"); if (p) setRegisteredPatients(JSON.parse(p)); } catch {} setReady(true); }, []);
  useEffect(() => { if (ready) localStorage.setItem(WORKFLOW_STORAGE_KEY, JSON.stringify({ version: DEMO_STATE_VERSION, state: engine })); }, [engine, ready]); useEffect(() => { if (ready) localStorage.setItem("qlyno-hospital-orders-v1", JSON.stringify(dynamicOrders)); }, [dynamicOrders, ready]); useEffect(() => { if (ready) localStorage.setItem("qlyno-hospital-patients-v1", JSON.stringify(registeredPatients)); }, [registeredPatients, ready]);
  const lifecycle = useMemo(() => snap(engine), [engine]); const requiredRoles = REQUIRED[lifecycle.overallStage] ?? []; const canAdvance = Boolean(session?.tenantId === engine.order.tenantId && session.billingOwner === "HMS_CENTRAL" && (requiredRoles.some(r => session.laboratoryRoles.includes(r)) || lifecycle.overallStage === "ORDER_RECEIVED" || lifecycle.overallStage === "DELIVERY_CLOSURE")); const activeOrder = dynamicOrders.find((order) => order.id === engine.order.id) ?? MOCK_ORDERS.find((order) => order.id === engine.order.id); const activePatient = MOCK_PATIENTS.find((patient) => patient.id === (engine.patientId ?? activeOrder?.patientId)); const specimen = engine.specimens.find((entry) => entry.status === "EXPECTED") ?? engine.specimens.find((entry) => entry.status === "COLLECTED") ?? engine.specimens.find((entry) => entry.status === "RECEIVED") ?? engine.specimens[0]; const item = engine.orderItems.find((entry) => entry.specimenIds.includes(specimen.id)) ?? engine.orderItems[0];
  const workflow: HospitalWorkflowState = { tenantId: engine.order.tenantId, orderId: engine.order.id, patientId: engine.patientId ?? activeOrder?.patientId ?? "PAT-1001", mrn: engine.mrn ?? activePatient?.mrn ?? "MRN pending", encounterId: engine.encounterId ?? "ENC-501", accessionId: specimen.status === "ACCEPTED" ? `ACC-${specimen.id}` : undefined, specimenId: specimen.id, orderItemId: item.id, stage: lifecycle.overallStage, specimenStatus: specimen.status, testStatus: item.status, reportStatus: engine.reportGroups.some(g => g.released) ? engine.reportGroups.every(g => g.released) ? "FINAL" : "PRELIMINARY" : "PENDING", hmsDeliveryStatus: engine.deliveries.length ? engine.deliveries.every(d => d.delivered) ? "DELIVERED_ACKNOWLEDGED" : "DELIVERY_PENDING" : "NOT_PUBLISHED", events: engine.events.map(e => ({ id: e.id, stage: lifecycle.overallStage, action: e.type.replaceAll("_", " "), actor: e.actorName, role: e.actorType, timestamp: e.timestamp, reason: e.reason ?? "Recorded lifecycle event" })) };
  const advance = (reason?: string) => { if (session && canAdvance) dispatch({ type: "NEXT", actor: session.userName, reason }); };
  const createHospitalOrder = (input: CreateHospitalOrderInput) => {
    if (!session) throw new Error("Authentication required");
    const suffix = Date.now().toString().slice(-6); const orderId = input.backendOrderId ?? `ORD-HMS-${suffix}`;
    const itemIds = input.testIds.map((_, i) => `OI-HMS-${suffix}-${i + 1}`);
    const order: Order = { id: orderId, patientId: input.patientId, patientName: input.patientName, source: "hospital_encounter", billingAuthority: "HMS_CENTRAL", priority: input.priority, status: "placed", reportStatus: "pending", hmsPostingStatus: "post_pending", orderingDoctor: input.orderingDoctor, siteId: session.activeSiteId, departmentIds: input.departmentIds, placedAt: new Date().toISOString(), itemIds };
    const orderItems: LifecycleOrderItem[] = itemIds.map((id, index) => ({ id, testId: input.testIds[index], specimenIds: [`SPX-HMS-${suffix}-${index + 1}`], status: "ORDERED", reportGroupId: `RG-HMS-${suffix}-${index + 1}` }));
    dispatch({ type: "LOAD", state: { patientId: input.patientId, patientName: input.patientName, mrn: input.mrn, encounterId: input.encounterId, order: { id: orderId, tenantId: session.tenantId, validated: false, collectionTasksCreated: false }, orderItems, specimens: orderItems.map((entry, index) => { const test = MOCK_CATALOG.find((candidate) => candidate.id === input.testIds[index]); return { id: entry.specimenIds[0], tenantId: session.tenantId, siteId: session.activeSiteId, orderId, patientId: input.patientId, patientName: input.patientName, mrn: input.mrn, type: test?.specimen ?? "Expected specimen", container: test?.container ?? "Mapped container", collectionLocation: "Ward / bedside", priority: input.priority, status: "EXPECTED" as const }; }), workItems: [], reviews: [], reportGroups: orderItems.map((entry) => ({ id: entry.reportGroupId, orderItemIds: [entry.id], versionCreated: false, released: false })), deliveries: [], criticalNotifications: [], events: [{ id: `EVT-${Date.now()}`, tenantId: session.tenantId, siteId: session.activeSiteId, orderId, type: "ORDER_PLACED", actorType: "USER", actorId: session.userId, actorName: session.userName, timestamp: new Date().toISOString(), reason: "Hospital laboratory order placed" }] } });
    setDynamicOrders(v => [order, ...v]); return order;
  };
  const registerHospitalPatient = (input: RegisterHospitalPatientInput) => { if (!session) throw new Error("Authentication required"); const suffix = String(Date.now()).slice(-7); const timestamp = new Date().toISOString(); const displayName = [input.givenName, input.middleName, input.singleName ? undefined : input.familyName].filter(Boolean).join(" "); const patient = { id: `HMS-PAT-${suffix}`, tenantId: session.tenantId, source: "HMS" as const, hospitalMrn: `MRN-${suffix}`, title: input.title, givenName: input.givenName, middleName: input.middleName, familyName: input.familyName, singleName: input.singleName, displayName, dateOfBirth: input.dateOfBirth, sexAtBirth: input.sexAtBirth, primaryMobile: input.primaryMobile, email: input.email, preferredLanguage: input.preferredLanguage, address: input.address, guardian: input.guardian, emergencyContact: input.emergencyContact, identifiers: [], privacyConsent: input.privacyConsent, reportDeliveryConsent: input.reportDeliveryConsent, notificationConsents: [], status: "ACTIVE" as const, createdAt: timestamp, updatedAt: timestamp, encounterId: `ENC-${suffix}`, encounterNumber: `LAB-${suffix}`, registrationAudit: `Registered by ${session.userName}` }; setRegisteredPatients(v => [patient, ...v]); return patient; };
  const activeOrderItems: OrderItem[] = engine.orderItems.map((entry) => { const mockItem = MOCK_ORDER_ITEMS.find((candidate) => candidate.id === entry.id); const test = MOCK_CATALOG.find((catalogItem) => catalogItem.id === (entry.testId ?? mockItem?.testId)); return { id: entry.id, orderId: engine.order.id, testId: entry.testId ?? mockItem?.testId ?? entry.id, testName: test?.name ?? mockItem?.testName ?? "Laboratory test", status: entry.status.toLowerCase() as OrderItem["status"], specimenId: entry.specimenIds[0], departmentId: test?.department, accessionId: engine.specimens.find((s) => s.id === entry.specimenIds[0])?.status === "ACCEPTED" ? `ACC-${entry.specimenIds[0]}` : undefined, reportGroupId: entry.reportGroupId }; });
  const activeSpecimens: Specimen[] = engine.specimens.map((entry) => ({ id: entry.id, tenantId: entry.tenantId, siteId: entry.siteId, orderId: entry.orderId, patientId: entry.patientId, patientName: entry.patientName, mrn: entry.mrn, type: entry.type, container: entry.container, collectionLocation: entry.collectionLocation, priority: entry.priority, status: entry.status.toLowerCase() as Specimen["status"], collectedAt: entry.collectedAt, collectedBy: entry.collectedBy, collectionCondition: entry.collectionCondition, sealStatus: entry.sealStatus, temperature: entry.temperature, receiptNotes: entry.receiptNotes, accessionId: entry.accessionId, receivedAt: entry.receivedAt, receivedBy: entry.receivedBy, receivedSiteId: entry.receivedSiteId, rejectedReason: entry.blocker, rejectedAt: entry.rejectedAt, rejectedBy: entry.rejectedBy }));
  const expected = engine.specimens.filter((entry) => entry.status === "EXPECTED").length; const collected = engine.specimens.filter((entry) => entry.status === "COLLECTED").length;
  const lastCollection = [...engine.events].reverse().find((entry) => entry.type === "SPECIMEN_COLLECTED");
  const collectionTasks: CollectionTask[] = engine.order.cancelled ? [] : [{ id: `CT-${engine.order.id}`, tenantId: engine.order.tenantId, siteId: activeOrder?.siteId ?? session?.activeSiteId ?? "SITE-01", orderId: engine.order.id, patientId: engine.patientId ?? activeOrder?.patientId ?? "PAT-1001", encounterId: engine.encounterId ?? "ENC-501", specimenIds: engine.specimens.map((entry) => entry.id), requiredContainers: activeSpecimens.map((entry) => entry.container), testNames: activeOrderItems.map((entry) => entry.testName), collectionLocation: activeOrder?.source === "hospital_encounter" ? "Ward / bedside" : "Collection centre", priority: activeOrder?.priority ?? "stat", scheduledAt: activeOrder?.placedAt ?? engine.events[0]?.timestamp ?? new Date().toISOString(), assignedRole: "PHLEBOTOMIST", assignedUserId: undefined, status: expected === 0 ? "COMPLETED" : collected > 0 ? "PARTIAL" : "PENDING", collectedAt: lastCollection?.timestamp, collectedBy: lastCollection?.actorName }];
  const confirmCollection = (taskId: string, specimenIds: string[], notes: string) => { const task = collectionTasks.find((entry) => entry.id === taskId); if (!session || !task) return { ok: false, message: "Collection task not found" }; if (task.tenantId !== session.tenantId || !session.allowedSiteIds.includes(task.siteId)) return { ok: false, message: "Collection task is outside your permitted tenant or site" }; if (!session.permissions.includes("collection.confirm") || !session.laboratoryRoles.some((role) => role === "PHLEBOTOMIST" || role === "WARD_COLLECTOR")) return { ok: false, message: "Awaiting authorized collector" }; if (task.orderId !== engine.order.id || specimenIds.some((id) => !task.specimenIds.includes(id))) return { ok: false, message: "Requested specimen does not belong to this order" }; dispatch({ type: "COLLECT", specimenIds, actor: session.userName, actorId: session.userId, notes }); return { ok: true }; };
  const validateSpecimenRequest = (orderId: string, specimenId: string) => { if (!session) return "Authentication required"; const target = activeSpecimens.find((entry) => entry.id === specimenId); if (!target || target.orderId !== orderId || orderId !== engine.order.id) return `Specimen ${specimenId} does not belong to ${orderId}`; if (target.tenantId !== session.tenantId || !target.siteId || !session.allowedSiteIds.includes(target.siteId)) return "Specimen is outside your permitted tenant or site"; return undefined; };
  const confirmReceipt = (orderId: string, specimenId: string, receipt: ReceiptInput) => { const error = validateSpecimenRequest(orderId, specimenId); if (error) return { ok: false, message: error }; if (!session?.permissions.includes("specimen.receive")) return { ok: false, message: "You do not have specimen.receive permission" }; const target = activeSpecimens.find((entry) => entry.id === specimenId); if (!target || !["collected", "in_transit"].includes(target.status)) return { ok: false, message: "Only collected or in-transit specimens can be received" }; if (!receipt.condition || !receipt.sealStatus || !receipt.temperature) return { ok: false, message: "Condition, seal status and temperature are required" }; dispatch({ type: "RECEIVE", specimenId, actor: session.userName, actorId: session.userId, siteId: session.activeSiteId, receipt }); return { ok: true }; };
  const accessionSpecimen = (orderId: string, specimenId: string) => { const error = validateSpecimenRequest(orderId, specimenId); if (error) return { ok: false, message: error }; if (!session?.permissions.includes("specimen.accession")) return { ok: false, message: "You do not have specimen.accession permission" }; const target = activeSpecimens.find((entry) => entry.id === specimenId); if (!target || target.status !== "received" || target.accessionId) return { ok: false, message: "Specimen is not awaiting accessioning" }; dispatch({ type: "ACCESSION", specimenId, actor: session.userName, actorId: session.userId }); return { ok: true }; };
  const rejectSpecimen = (orderId: string, specimenId: string, reason: string) => { const error = validateSpecimenRequest(orderId, specimenId); if (error) return { ok: false, message: error }; if (!session?.permissions.includes("specimen.reject")) return { ok: false, message: "You do not have specimen.reject permission" }; if (!reason.trim()) return { ok: false, message: "A coded rejection reason is required" }; dispatch({ type: "REJECT", specimenId, actor: session.userName, actorId: session.userId, reason }); return { ok: true }; };
  useEffect(() => { if (process.env.NODE_ENV === "production") return; const ids = engine.specimens.map((entry) => entry.id); if (new Set(ids).size !== ids.length) console.error("[workflow integrity] duplicate specimen IDs", ids); for (const entry of engine.specimens) { const eventTypes = engine.events.filter((event) => event.specimenId === entry.id).map((event) => event.type); if (["COLLECTED", "IN_TRANSIT", "RECEIVED", "ACCEPTED"].includes(entry.status) && !eventTypes.includes("SPECIMEN_COLLECTED")) console.error(`[workflow integrity] ${entry.id} is ${entry.status} without SPECIMEN_COLLECTED`); if (["RECEIVED", "ACCEPTED"].includes(entry.status) && !eventTypes.includes("SPECIMEN_RECEIVED")) console.error(`[workflow integrity] ${entry.id} is ${entry.status} without SPECIMEN_RECEIVED`); if (entry.status === "ACCEPTED" && (!entry.accessionId || !eventTypes.includes("ACCESSION_CREATED"))) console.error(`[workflow integrity] ${entry.id} accepted without accession provenance`); } }, [engine]);
  return <Context.Provider value={{ workflow, lifecycle, lifecycleEvents: engine.events, collectionTasks, activeOrderItems, activeSpecimens, dynamicOrders, registeredPatients, canAdvance, requiredRoles, actionLabel: lifecycle.nextRequiredActions[0]?.action ?? "Order closed", advance, confirmCollection, confirmReceipt, accessionSpecimen, rejectSpecimen, createHospitalOrder, registerHospitalPatient, reset: () => { if (process.env.NODE_ENV !== "production") { localStorage.removeItem(WORKFLOW_STORAGE_KEY); dispatch({ type: "RESET" }); } } }}>{children}</Context.Provider>;
}
export function useHospitalWorkflow() { const value = useContext(Context); if (!value) throw new Error("useHospitalWorkflow must be used within HospitalWorkflowProvider"); return value; }
