import {
  ClinicQueueItem,
  DoctorShift,
  DoctorTaskItem,
  HospitalWorkItem,
  Workplace,
} from "./doctor-workflow-types";
import { CURRENT_DATE_ISO, addDaysToISO } from "./app-time";

export const doctorWorkplaces: Workplace[] = [
  {
    id: "wp-clinic-mg",
    name: "Meridian Family Clinic",
    type: "clinic",
    location: "MG Road",
    role: "Consulting Physician",
    status: "Verified",
    managedBy: "Meridian Family Clinic",
  },
  {
    id: "wp-clinic-indiranagar",
    name: "Meridian Family Clinic",
    type: "clinic",
    location: "Indiranagar",
    role: "Consulting Physician",
    status: "Verified",
    managedBy: "Meridian Family Clinic",
  },
  {
    id: "wp-hospital-aster",
    name: "Aster City Hospital",
    type: "hospital",
    location: "Indiranagar",
    department: "Internal Medicine",
    role: "Visiting Consultant",
    status: "Verified",
    managedBy: "Aster City Hospital",
  },
  {
    id: "wp-online",
    name: "Qlyno Online Practice",
    type: "online",
    location: "Online",
    role: "Teleconsultation",
    status: "Active",
  },
];

export const doctorShifts: DoctorShift[] = [
  {
    id: "shift-clinic-morning",
    workplaceId: "wp-clinic-mg",
    date: CURRENT_DATE_ISO,
    startTime: "09:00",
    endTime: "13:00",
    shiftType: "clinic_opd",
    status: "upcoming",
    bookingEnabled: true,
  },
  {
    id: "shift-online-afternoon",
    workplaceId: "wp-online",
    date: CURRENT_DATE_ISO,
    startTime: "14:00",
    endTime: "16:00",
    shiftType: "online_consultation",
    status: "upcoming",
    bookingEnabled: true,
  },
  {
    id: "shift-clinic-conflict",
    workplaceId: "wp-clinic-indiranagar",
    date: CURRENT_DATE_ISO,
    startTime: "16:00",
    endTime: "19:00",
    shiftType: "clinic_opd",
    status: "upcoming",
    bookingEnabled: true,
    note: "Mock overlap for conflict UI",
  },
  {
    id: "shift-hospital-evening",
    workplaceId: "wp-hospital-aster",
    date: CURRENT_DATE_ISO,
    startTime: "18:00",
    endTime: "21:00",
    shiftType: "hospital_duty",
    status: "upcoming",
    bookingEnabled: false,
  },
  {
    id: "shift-leave",
    workplaceId: "wp-online",
    date: addDaysToISO(CURRENT_DATE_ISO, 2),
    startTime: "00:00",
    endTime: "23:59",
    shiftType: "leave",
    status: "upcoming",
    bookingEnabled: false,
    note: "Full day leave",
  },
  {
    id: "shift-block",
    workplaceId: "wp-clinic-mg",
    date: addDaysToISO(CURRENT_DATE_ISO, 3),
    startTime: "13:00",
    endTime: "14:00",
    shiftType: "blocked",
    status: "upcoming",
    bookingEnabled: false,
    note: "Lunch / personal",
  },
];

export const clinicQueue: ClinicQueueItem[] = [
  {
    id: "queue-1",
    token: "01",
    patientId: "pat-1",
    workplaceId: "wp-clinic-mg",
    appointmentTime: "10:00 AM",
    reason: "Follow-up",
    waitingMins: 8,
    status: "waiting",
  },
  {
    id: "queue-2",
    token: "02",
    patientId: "pat-2",
    workplaceId: "wp-clinic-mg",
    appointmentTime: "10:20 AM",
    reason: "New Consultation",
    waitingMins: 3,
    status: "waiting",
  },
  {
    id: "queue-3",
    token: "03",
    patientId: "pat-4",
    workplaceId: "wp-clinic-mg",
    appointmentTime: "10:45 AM",
    reason: "Lab review",
    waitingMins: 0,
    status: "upcoming",
  },
  {
    id: "queue-4",
    token: "04",
    patientId: "pat-6",
    workplaceId: "wp-clinic-mg",
    appointmentTime: "11:15 AM",
    reason: "General checkup",
    waitingMins: 0,
    status: "completed",
  },
];

export const hospitalWorklist: HospitalWorkItem[] = [
  {
    id: "hospital-1",
    patientId: "pat-7",
    workplaceId: "wp-hospital-aster",
    bed: "302",
    diagnosis: "Post angioplasty review",
    priority: "High",
    reasonAssigned: "Primary treating doctor",
    status: "assigned",
    pending: ["Repeat SpO2", "Review chest X-ray"],
  },
  {
    id: "hospital-2",
    patientId: "pat-3",
    workplaceId: "wp-hospital-aster",
    bed: "306",
    diagnosis: "COPD exacerbation",
    priority: "Critical",
    reasonAssigned: "Emergency escalation",
    status: "critical",
    pending: ["Review ABG", "Escalate if SpO2 below 90"],
  },
  {
    id: "hospital-3",
    patientId: "pat-4",
    workplaceId: "wp-hospital-aster",
    bed: "308",
    diagnosis: "Cardiology review requested",
    priority: "Medium",
    reasonAssigned: "Consult requested by another doctor",
    status: "request",
    requestedBy: "Dr. Farhan Sheikh",
    requestDepartment: "Cardiology",
    requestReason: "Chest discomfort after abnormal ECG",
    requestedAt: "05:30 PM",
  },
  {
    id: "hospital-4",
    patientId: "pat-1",
    workplaceId: "wp-hospital-aster",
    bed: "310",
    diagnosis: "Diabetes medication reconciliation",
    priority: "Medium",
    reasonAssigned: "Discharge review assigned",
    status: "discharge",
    pending: ["Discharge medication review"],
  },
  {
    id: "hospital-5",
    patientId: "pat-7",
    workplaceId: "wp-hospital-aster",
    bed: "302",
    diagnosis: "Cardiac enzymes report",
    priority: "High",
    reasonAssigned: "Report review assigned",
    status: "reports",
    pending: ["Cardiac enzymes panel"],
  },
];

export const doctorTasks: DoctorTaskItem[] = [
  {
    id: "task-1",
    title: "Critical lab report",
    patientId: "pat-7",
    workplaceId: "wp-hospital-aster",
    source: "Lab",
    assignedBy: "Aster City Hospital",
    dueTime: "Due now",
    priority: "Critical",
    status: "urgent",
  },
  {
    id: "task-2",
    title: "Follow-up due",
    patientId: "pat-2",
    workplaceId: "wp-clinic-mg",
    source: "Follow-up",
    assignedBy: "Meridian Reception",
    dueTime: "Today 4:00 PM",
    priority: "Medium",
    status: "today",
  },
  {
    id: "task-3",
    title: "Discharge review",
    patientId: "pat-1",
    workplaceId: "wp-hospital-aster",
    source: "Hospital duty",
    assignedBy: "Internal Medicine",
    dueTime: "Before 9:00 PM",
    priority: "High",
    status: "today",
  },
  {
    id: "task-4",
    title: "Update online consultation notes",
    patientId: "pat-6",
    workplaceId: "wp-online",
    source: "Online practice",
    assignedBy: "Self",
    dueTime: "Tomorrow",
    priority: "Low",
    status: "upcoming",
  },
];
